Beberapa Referensi


https://stackoverflow.com/questions/59024220/error-in-computing-the-coherence-score-attributeerror-dict-object-has-no-at?rq=1

https://towardsdatascience.com/topic-modelling-in-python-with-nltk-and-gensim-4ef03213cd21


https://www.machinelearningplus.com/nlp/topic-modeling-gensim-python/

https://stackoverflow.com/questions/66759852/no-module-named-pyldavis

# Setting

In [ ]:
# Run cell ini untuk melihat output tabel/dataframe secara keseluruhan

import pandas as pd
pd.set_option('display.max_rows', None)

# Library

In [ ]:
!pip install pyLDAvis

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyLDAvis in /usr/local/lib/python3.7/dist-packages (3.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.1.0)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.7.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (57.4.0)
Requirement already satisfied: numexpr in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (2.8.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (2.11.3)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.21.6)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (0.0)
Requirement already satisfied: gensim in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (3.6.0)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (0.16.0)
Requirement already satisfied: funcy in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.17)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from pyLDAvis) (1.0.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyLDAvis) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.2.0->pyLDAvis) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyLDAvis) (1.15.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from gensim->pyLDAvis) (5.2.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->pyLDAvis) (2.0.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from numexpr->pyLDAvis) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->numexpr->pyLDAvis) (3.0.9)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->pyLDAvis) (3.1.0)

In [ ]:
pip install wikipedia

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wikipedia in /usr/local/lib/python3.7/dist-packages (1.4.0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from wikipedia) (2.23.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from wikipedia) (4.6.3)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.0.0->wikipedia) (2.10)

In [ ]:
pip install owlready2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: owlready2 in /usr/local/lib/python3.7/dist-packages (0.38)

In [ ]:
# !wget https://raw.githubusercontent.com/hardymanm/nusantarafood/main/aziekitchen-udang.jl

In [ ]:
import pandas as pd
import numpy as np
import json
import gensim.corpora as corpora
import pyLDAvis.gensim_models #Ini library terbaru

import requests
import warnings
warnings.filterwarnings('ignore')

/usr/local/lib/python3.7/dist-packages/past/types/oldstr.py:5: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from pydrive import auth
from google.colab import auth 
from oauth2client.client import GoogleCredentials

In [ ]:
## Ontology Module
from owlready2 import *
import types

In [ ]:
from nltk.corpus import stopwords
import string
import nltk
import re
import matplotlib.pyplot as plt
import gensim
from sklearn.feature_extraction.text import CountVectorizer

import wikipedia
from nltk.corpus import wordnet as wn

# For widget
import asyncio
%gui asyncio
import ipywidgets as widgets
from IPython.display import display
from IPython.display import clear_output 

import functools

nltk.download('stopwords')
nltk.download("punkt")
nltk.download('wordnet')
nltk.download('omw')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw to /root/nltk_data...
[nltk_data]   Package omw is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

# Subprogram untuk LDA, Cleaning, dan Probability

In [ ]:
!gdown --id "1etWM37-sxCXvfy7JFc8Mwlv8rtXupeA5"

def add_stopwords_to_txtFile(array_of_words, filename = "sorted-updated-stopwords-ms.txt"):
    with open(filename, "a") as f:
        for i in range(len(array_of_words)):
            if i == len(array_of_words) - 1:
              f.write(array_of_words[i])
            else:
              f.write(array_of_words[i])
              f.write("\n")

# test = ["sapu", "cawan"]
# add_stopwords_to_txtFile(test)
# stopwordMY = set(line.strip() for line in open('sorted-updated-stopwords-ms.txt'))

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1etWM37-sxCXvfy7JFc8Mwlv8rtXupeA5
To: /content/sorted-updated-stopwords-ms.txt
100% 8.33k/8.33k [00:00<00:00, 11.1MB/s]

In [ ]:
def delist(df, colname):
  result = []
  for i in range(len(df[colname])):
    full = []
    for j in range(len(df[colname][i])):
      teks = ""
      for k in range(len(df[colname][i][j])):
        teks += df[colname][i][j][k]
      full.append(teks)
    result.append(full)
  return result
  
def pre_cleaning_text(df, threshold = 20):
  # Pre-cleaning (ngilangin cerita), hapus jika kalimat lebih dari 20
  for teks in range(len(df['page_description'])):
    for kalimat in range(len(df['page_description'][teks])):
      temp_list = df['page_description'][teks][kalimat].split()
      if len(temp_list) > threshold:
          df['page_description'][teks][kalimat] = "-"
  return df

In [ ]:
def treat_ingredients(ing_list):
    output = []
    for ingredient in ing_list:
        ingredient_list = ingredient.split(' ')
        output.append("_".join(ingredient_list))
    return output
    
def make_LDAmodel(cleaned_description, num_topics, passes):
  # Load the list of documents
  ingredients_all = cleaned_description.apply(lambda x: ", ".join(x))

  # Use CountVectorizor to find three letter tokens, remove stop_words, 
  # remove tokens that don't appear in at least 20 documents,
  # remove tokens that appear in more than 20% of the documents
  vect = CountVectorizer(token_pattern='(?u)\\b\\w\\w\\w+\\b')

  # Fit and transform
  X = vect.fit_transform(ingredients_all)

  # Convert sparse matrix to gensim corpus.
  corpus = gensim.matutils.Sparse2Corpus(X, documents_columns=False)

  # Mapping from word IDs to words (To be used in LdaModel's id2word parameter)
  id_map = dict((v, k) for k, v in vect.vocabulary_.items())

  #fit LDA model
  #ldamodel = gensim.models.ldamodel.LdaModel(corpus,num_topics = 5,passes = 20, random_state = 0, id2word = id_map)
  ldamodel = gensim.models.ldamodel.LdaModel(corpus,num_topics = num_topics, passes = passes, random_state = 0, 
                                             id2word = id_map,chunksize=100,alpha='auto',per_word_topics=True, minimum_probability= 1E-9)
  
  # Chang idword to d
  word2id =dict((k, v) for k, v in vect.vocabulary_.items())
  d = corpora.Dictionary()
  d.id2token = id_map
  d.token2id = word2id

  # visualization
  pyLDAvis.enable_notebook()
  vis = pyLDAvis.gensim_models.prepare(ldamodel, corpus, d)

  return ldamodel, vis, corpus, id_map, d

def modelToText(modelLDA, numWords):
  # Output topic modeling dalam bentuk tulisan
  all_wordList = []
  for idx, topic in modelLDA.show_topics(formatted=False, num_words= numWords):
    word_list = [w[0] for w in topic]
    all_wordList.append(word_list)
    print('Topic:', idx+1)
    print(*word_list, sep=", ")
    print()
  return all_wordList

In [ ]:
# Stopword Malaysian
!gdown --id "1etWM37-sxCXvfy7JFc8Mwlv8rtXupeA5"
stopwordMY = set(line.strip() for line in open('sorted-updated-stopwords-ms.txt'))

# stopwords bahasa indonesia
stopwordID =  set(stopwords.words('indonesian'))
# stopwords english
stopwordEN = set(stopwords.words('english'))

# Dictionary malay (without food related)
# !gdown --id "1j0YZsdWWMs7Kfo1ROLykG6AKcCzG1SWg"
# malayDict = set(line.strip() for line in open('ms-dict.txt', encoding = "ISO-8859-1"))

# gabungkan stopwords malaysia, indonesia dan english
listStopword = stopwordID | stopwordMY
listStopword = listStopword | stopwordEN

# listStopword = listStopword | malayDict

# Tambah kata
listTambahan = {'potong', 'bahan', 'resepi', 'sudu', 'kacau', 'minit', 'buang', 'cawan', 'dicelur', 'dicelup', 'dihidangkan', 'kitchen', 
                'masak', 'best', 'ever', 'yang', 'sedap', 'delicious', 'aduhaaiii', 'nyer', 'resipi', 'sdt', 'sdm'}
listStopword = listStopword | listTambahan

def cleaning_text(ing_list, listStopword):
  removed = []
  for i in range(ing_list.shape[0]):
    tokens = " ".join(ing_list[i])
    # menghilangkan angka
    tokens = re.sub(r"\d+", "", tokens)
    
    # mengubah semua karakter menjadi lower case dan menghilangkan tanda baca dalam text
    tokens = tokens.lower()
    tokens = tokens.translate(str.maketrans("","",string.punctuation)).split()
    temp = []
    
    # penghapusan stopwords
    for t in tokens:
      if t not in listStopword:
        temp.append(t)
    kata = " ".join(temp)
    hasil = [kata]
    removed.append(hasil)

  return removed

def pre_cleaning_text(df, threshold = 20):
  # Pre-cleaning (ngilangin cerita), hapus jika kalimat lebih dari threshold
  for teks in range(len(df['page_description'])):
    for kalimat in range(len(df['page_description'][teks])):
      temp_list = df['page_description'][teks][kalimat].split()
      if len(temp_list) > threshold:
          df['page_description'][teks][kalimat] = "-"
  return df

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1etWM37-sxCXvfy7JFc8Mwlv8rtXupeA5
To: /content/sorted-updated-stopwords-ms.txt
100% 8.33k/8.33k [00:00<00:00, 8.85MB/s]

In [ ]:
def cleaning_title(ing_list, listStopword):
  removed = []
  for i in range(ing_list.shape[0]):
    tokens = ing_list[i]
    # menghilangkan angka
    tokens = re.sub(r"\d+", "", tokens)
    
    # mengubah semua karakter menjadi lower case dan menghilangkan tanda baca dalam text
    tokens = tokens.lower()
    tokens = tokens.translate(str.maketrans("","",string.punctuation)).split()
    temp = []
    
    # penghapusan stopwords
    for t in tokens:
      if t not in listStopword:
        temp.append(t)
    kata = " ".join(temp)
    hasil = [kata]
    removed.append(hasil)

  return removed

In [ ]:
# Untuk mencari probability per kata di topic dataset
def term_probability(ldamodel, d, term):
  res = ldamodel[d.doc2bow([term])][0]
  for i in range(1, len(res)+1):
    print(f"Topic {i} = {res[i-1][1]}")

def return_term_probability(ldamodel, d, term):
  res = ldamodel[d.doc2bow([term])][0]
  return res

def make_dictionary_terms_prob(ldamodel, id_map, d):
  prob_allTerms = {}
  word = id_map.values()
  for key in word:
    prob_allTerms[key] = return_term_probability(ldamodel, d, key)
  return prob_allTerms

In [ ]:
def concat_bahan_langkah(df):
  ''' Concat Kolom Bahan2 dan Langkah2 '''
  df["page_bahan_langkah"] = df["page_bahan"]
  for i in range(df.shape[0]):
    df["page_bahan_langkah"][i] = [*df["page_bahan"][i], *df["page_langkah"][i]] 
  return df

# Subprogram untuk Counter

In [ ]:
def wait_for_change(widget, value):
  future = asyncio.Future()
  def getvalue(change):
    # make the new value available
    future.set_result(change.new)
    widget.unobserve(getvalue, value)
  widget.observe(getvalue, value)
  return future

In [ ]:
# Tabel 1981
async def f():
  global tabel_1981, benar, salah, all_cat, all_suggestion

  for i in range(tabel_1981.shape[0]):
    clear_output()
    display(button)
    print()
    print(f"Row: {i+1}/{tabel_1981.shape[0]}")
    print(tabel_1981["Title"][i])
    temp = str(tabel_1981["Category"][i])
    temp = temp.translate(str.maketrans("","",string.punctuation))
    category_1981 = temp.split()

    suggestion = widgets.Text(
      value="",
      description='Usulan Class',
      placeholder = "input class disini dipisahkan dengan spasi",
      disabled=False,
      layout = widgets.Layout(width='600px', height='40px')
    )

    cat = widgets.SelectMultiple(
      options= category_1981,
      value=[],
      #rows=10,
      description='category',
      disabled=False
    )
    display(cat)
    display(suggestion)
    x = await wait_for_change(button, "value")

    temp = str(cat.value)
    temp = temp.translate(str.maketrans("","",string.punctuation))

    all_cat.append(temp.split())
    all_suggestion.append(suggestion.value.split())
    benar+= len(cat.value)
    salah+= len(cat.options) - len(cat.value)
  button.layout.display = 'none'
  print()
  print("=== END ===")
  print()
  print(f"benar: {benar}\nsalah: {salah}")

In [ ]:
# Wiki
async def f_wiki():
  global wiki_df, idx, all_cat
  for i in range(wiki_df.shape[0]):
    clear_output()
    display(button)
    print()
    print(f"Row: {i+1}/{wiki_df.shape[0]}")
    print(wiki_df["Title"][i])
    
    print("\n======Definition========\n")
    print(f"Indonesia: {wiki_df.Def_IND[i]}")
    print(f"Malaysia: {wiki_df.Def_MS[i]}")
    print(f"English: {wiki_df.Def_ENG[i]}")

    print("\n")
    class_suggest = widgets.Text(
      value="",
      description='Usulan Class',
      placeholder = "input class disini dipisahkan dengan spasi",
      disabled=False,
      layout = widgets.Layout(width='600px', height='40px')
    )
    display(class_suggest)
    x = await wait_for_change(button, "value")
    
    all_cat.append(class_suggest.value.split())
    idx.append(i)
    # if len(cat.value) > 0:
    #   benar+=1
    # else:
    #   salah+=1
    # benar+= len(cat.value)
    # salah+= len(cat.options) - len(cat.value)
  button.layout.display = 'none'
  print()
  print("=== END ===")
  print()
  print("hasil dari juri telah tersimpan di variabel all_cat")
  # print(f"benar: {benar}\nsalah: {salah}")

In [ ]:
# Wordnet
def submitRadioClicked(b):
  global catStatus, changesList, benarWordnet, salahWordnet, wnIdx, textBox
  print("Success")
  print()
  if catStatus.value == 'False':
    textBox = widgets.Text(
      placeholder='Masukkan Hypernym',
      description='Masukkan Hypernym:',
      disabled=False
    )
    display(textBox)
    salahWordnet += 1

    submitBtn = widgets.Button(description = "Submit")
    display(submitBtn)
    
    submitBtn.on_click(submitBtnClicked)
  else:
    changesList.append([wnIdx, "None"])
    benarWordnet += 1

def submitBtnClicked(b):
  global changesList, wnIdx, textBox
  print("Success")
  print()
  changesList.append([wnIdx, textBox.value])

async def fWordnet():
  global changesList, catStatus, tableWordnet, benarWordnet, salahWordnet, wnIdx
  changesList = []
  for wnIdx in range(tableWordnet.shape[0]):
    clear_output()
    display(button)
    print()
    print(f"Row: {wnIdx+1}/{tableWordnet.shape[0]}")
    print()
    print("Word:", tableWordnet["Word"][wnIdx])
    print("Synonym:", tableWordnet["Synonym_clean"][wnIdx])
    print("Hypernim:", tableWordnet["Hypernim_clean"][wnIdx])
    print("Hyponim:", tableWordnet["Hyponim_clean"][wnIdx])
    print()
    catStatus = widgets.RadioButtons (
      options=['True', 'False'],
      description='Hypernym (True/False?)',
      disabled=False
    )
    display(catStatus)

    submitBtnRadio = widgets.Button(description = "Submit")
    display(submitBtnRadio)

    submitBtnRadio.on_click(submitRadioClicked)
    x = await wait_for_change(button, "value")
  button.layout.display = 'none'
  print()
  print("=== END ===")

  # List = [[idx, hypernym], [idx, hypernym], ...]
  print("Changes:")
  print(changesList)

  print()
  print(f"Status Benar: {benarWordnet}\nStatus salah: {salahWordnet}")

def listToDataframe(resultList, dfWN):
  dfResult = pd.DataFrame(resultList, columns =['Index', 'Suggestion'])
  dfResult = dfResult.drop(columns=['Index'])
  concatDf = pd.concat([dfWN, dfResult], axis=1, join='inner')
  return concatDf

# Subprogram untuk GUI

In [ ]:
def on_button_clicked(b):
  '''
  Button add word and clean
  untuk menghapus kata sesuai dengan inputan user
  '''
  global listSW # nama stopwords baru
  global data #nama dataset
  # Display the message within the output widget.
  addition = set(teks.value.split())
  listSW = listSW | addition

  data["cleaned_description"] = cleaning_text(data["page_description"], listSW)
  with output:
    print("Success")

def run_button_clicked(b, lang="zsm"):
  '''button run model'''
  clear_output()
  display(teks)
  display(n_topics)
  display(iteration)

  # run_button.on_click(run_button_clicked)
  # button.on_click(on_button_clicked)

  display(button, output)
  display(run_button, output_run)
  global dfWordnet
  global ldamodel, vis, corpus, id_map, d
  print("Running..")
  ldamodel, vis, corpus, id_map, d = make_LDAmodel(data["cleaned_description"], n_topics.value, passes = iteration.value)
  
  display(vis)
  listTerms = modelToText(ldamodel, 30)
  dfWordnet = make_dataframe_wordnet(listTerms, lang)

  # Probabilitas Topic
  display(ldamodel.print_topics(num_topics = n_topics.value, num_words = 10))

# Subprogram untuk Wordnet

In [ ]:
def termsToWordnet(wordList, lang):
  ''' Mengambil hypo, syno, hyper terms/kata2 topiclda dari wordnet '''
  topicAll = []
  synonymAll = []
  hypernimAll = []
  hyponymAll = []
  definitionAll = []
  wordAll = []
  for topic in range(len(wordList)):
    for word in wordList[topic]:
      wordSyn = wn.synsets(word, lang=lang)
      topicAll.append(topic+1)
      wordAll.append(word)
      if len(wordSyn) > 0:
        synonymAll.append(wordSyn[0])
        hypernimAll.append(wordSyn[0].hypernyms())
        hyponymAll.append(wordSyn[0].hyponyms())
        definitionAll.append(wordSyn[0].definition())
      else:
        synonymAll.append("None")
        hypernimAll.append("None")
        hyponymAll.append("None")
        definitionAll.append("None")
  return topicAll, wordAll, synonymAll, hypernimAll, hyponymAll, definitionAll

def make_dataframe_wordnet(wordList, lang="zsm"):
  ''' membuat dataframe utk wordnet '''
  topic, wrd, syno, hype, hypo, definition = termsToWordnet(wordList, lang)

  finalList = zip(topic, wrd, syno, hype, hypo, definition)
  return pd.DataFrame(finalList, columns = ["No. Topic", "Word", "Synonym", "Hypernim", "Hyponim", "Definition"])

In [ ]:
def cleanWN(nym):
  '''mengembalikan -nym yang udah engga ada .n yang gitu gitu'''
  pattern_wn = r"('.+?\.)"
  result = []
  for i in nym:
    temp = []
    if i != "None" and len(i) > 0:
      for kata in i:
        temp.append(re.findall(pattern_wn, str(kata))[0][1:-1])
      result.append(temp)
    else:
      result.append("None")
  
  return result

def cleanWN_Synonym(syno):
  '''mengembalikan synonym yang udah engga ada .n yang gitu gitu'''
  pattern_wn = r"('.+?\.)"
  result = []
  for i in syno:
    strSyn = str(i)
    if strSyn != "None":
      result.append(re.findall(pattern_wn, str(strSyn))[0][1:-1])
    else:
      result.append("None")
  
  return result

# Subprogram untuk Ontology

In [ ]:
def translate(categories):
  res = []
  for i in range(len(categories)):
    categories[i] = convertStringListToList(categories[i])
    for j in range(len(categories[i])):
      if categories[i][j] == "buah": categories[i][j] = "Fruit"
      if categories[i][j] == "bumbu": categories[i][j] = "Spice"
      if categories[i][j] == "daging": categories[i][j] = "MeatAndPoultry"
      if categories[i][j] == "gula": categories[i][j] = "SugarAndSyrup"
      if categories[i][j] == "ikan": categories[i][j] = "Fish"
      if categories[i][j] == "kacang": categories[i][j] = "Nut"
      if categories[i][j] == "lemak": categories[i][j] = "FatAndOil"
      if categories[i][j] == "sayur": categories[i][j] = "Vegetable"
      if categories[i][j] == "serealia": categories[i][j] = "Cereal"
      if categories[i][j] == "susu": categories[i][j] = "Milk"
      if categories[i][j] == "telur": categories[i][j] = "Egg"
      if categories[i][j] == "umbi": categories[i][j] = "Tuber"
  return categories

def convertStringListToList(string):
  string = string.translate({ ord(c): None for c in "'[]," })
  li = list(string.split(" "))
  return li

def concatListInColumn(df):
  df["Category_New"] = df["Category"]
  for i in range(df.shape[0]):
    listRow = df["correct_category"][i] + df["suggestion"][i]
    df["Category_New"][i] = listRow
  return df

In [ ]:
def remove_space(sentence):
  return sentence.title().replace(" ", "")

In [ ]:
## Make Ontology for wordnet dataset
def makeOntology(onto, dfWordnet):
  with onto:
    for i in range(dfWordnet.shape[0]):
      word = dfWordnet["Word"][i]
      hyp = dfWordnet["Hypernim_clean"][i][0].capitalize()
      if dfWordnet["Hypernim_clean"][i] == "None":
        NewClass = types.new_class("Nothing", (Thing,))
        NewInstance = NewClass(word) # make an instance
      else:
        NewClass = types.new_class(hyp, (Thing,))
        NewInstance = NewClass(word)

In [ ]:
## Make Ontology for wikipedia dataset
def makeOntology_wiki(onto, df):
  with onto:
    for i in range(df.shape[0]):
      title = remove_space(df["Title"][i])
      for j in range(len(df["suggest"][i])):
        clas = df["suggest"][i][j].capitalize()
        if df["suggest"][i] == "None":
          NewClass = types.new_class("Nothing", (Thing,))
          NewInstance = NewClass(title) # make an instance
        else:
          NewClass = types.new_class(clas, (Thing,))
          NewInstance = NewClass(title)

In [ ]:
## Make Ontology for Table 1981 dataset
def makeOntologyTable1981(onto, dfTable):
  with onto:
    BaseClass = types.new_class("Recipe", (Thing,))
    for i in range(dfTable.shape[0]):
      title = remove_space(dfTable["Title"][i])
      for j in range(len(dfTable["Category_New"][i])):
        SubClass = types.new_class(dfTable["Category_New"][i][j], (BaseClass,))
        SubClassInstance = SubClass(title)

# Subprogram untuk Wikipedia

In [ ]:
# Subprogram untuk scraping wikipedia 
def wiki_indo(judul):
  try:
    wikipedia.set_lang("id")
    resultID = wikipedia.summary(judul, sentences=4)
    return resultID
  except:
    return 'Not Found'

def wiki_ms(judul):
  try:
    wikipedia.set_lang("ms")
    resultMS = wikipedia.summary(judul, sentences=4)
    return resultMS
  except:
    return 'Not Found'

def wiki_en(judul):
  try:
    wikipedia.set_lang("en")
    resultEN = wikipedia.summary(judul, sentences=4)
    return resultEN
  except:
    return 'Not Found'

def patRegex(pattern, definisi):
  isi = re.findall(pattern, definisi)
  if len(isi) > 0:
    final_isi = sambung_definisi(isi)
    return final_isi
  return 'Not Found'

In [ ]:
def sambung_definisi(arr_definition):
  '''mengembalikan definisi yang disambung ada di indeks 1'''
  hasil = ""
  for i in arr_definition:
    hasil = hasil + i[1].strip() + " "
  return hasil.strip()

In [ ]:
# Pattern Regex untuk definisi
pattern = r"(ialah|adalah|merupakan|merangkumi|kepada|makanan|consist |is a |consisting |made|is an )(.+?)[+,.;]"

# Subprogram untuk membuat definisi berdasarkan pattern regex
def generate_definition(array_title, pattern):
  cleaned = cleaning_title(array_title, listStopword)
  ind = []
  ms = []
  eng = []
  clean_title = []

  for judul in cleaned:
    splitted_judul = judul[0].split()
    if len(splitted_judul) > 1:
      juduls = splitted_judul[0] + " " + splitted_judul[1]
    elif len(splitted_judul) == 1:
      juduls = splitted_judul[0]
    else:
      juduls = 'None'
    
    if juduls != 'None':
      hasil_ind = wiki_indo(juduls)
      hasil_ms = wiki_ms(juduls)
      hasil_eng = wiki_en(juduls)

      isi_ind = patRegex(pattern, hasil_ind)
      isi_ms = patRegex(pattern, hasil_ms)
      isi_eng = patRegex(pattern, hasil_eng)

      ind.append(isi_ind)
      ms.append(isi_ms)
      eng.append(isi_eng)
      clean_title.append(judul[0])
    else:
      ind.append('Unknown')
      ms.append('Unknown')
      eng.append('Unknown')
      clean_title.append(judul[0])

  return ind, ms, eng, clean_title

# Subprogram untuk membuat dataframe definisi
def make_definition_dataframe(df_title, pattern):
  title = df_title
  ind, ms, eng, cleaned = generate_definition(df_title, pattern)

  final = zip(title, cleaned,ind, ms, eng)
  return pd.DataFrame(final, columns = ["Title", "Cleaned", "Def_IND", "Def_MS", "Def_ENG"])

# Subprogram untuk Tabel 1981

In [ ]:
# Tabel Makanan 1981 versi .txt diubah menjadi set
!gdown --id "1GaXKbBdvrSt52MezMV8nSvIHy5x-fvh2" #buah
!gdown --id "1CpdhUD_DEizVOMCJJbc6dGFOh9xeE_E0" #bumbu
!gdown --id "1Gn2vCNF5kRXYJU2GU7DGIlXiLA81UTtQ" #daging
!gdown --id "1U-O_-OFBEZHR0NTqZ43rQHvW_Pqqoc_R" #gula
!gdown --id "1HctjzZRqOrqTxfGd-cWcqYEoIDS6x0fh" #ikan
!gdown --id "1jZ_ngKTPvL-8DiKQ9YG0UPRTn6S9jZMC" #kacang
!gdown --id "1BE9IIFqIcDrgLJWKOA-vPplNwwe2jZZF" #lemak
!gdown --id "14ETHj-OUpL7QidjiI3pIMfMoOy9hCwd7" #sayur
!gdown --id "1760qlylrkaFX2HfMptJDgyPGEpN1m4Ux" #serealia
!gdown --id "1dFkhjqIuTT3MAWz_ZzCkEL5Zvnn0yxHR" #susu
!gdown --id "1iV756YrD7wJ_yGlwq0CenBZLHnSFn3-2" #telur
!gdown --id "1OtQ1Ij7S_GC-ROdoVzQn4i6cLMELUYAQ" #umbi

buah = set(line.strip() for line in open('buah.txt'))
daging = set(line.strip() for line in open('daging.txt'))
kacang = set(line.strip() for line in open('kacang.txt'))
sayur = set(line.strip() for line in open('sayur.txt'))
serealia = set(line.strip() for line in open('serealia.txt'))
umbi = set(line.strip() for line in open('umbi.txt'))

bumbu = set(line.strip() for line in open('bumbu.txt'))
gula = set(line.strip() for line in open('gula.txt'))
ikan = set(line.strip() for line in open('ikan.txt'))
lemak = set(line.strip() for line in open('lemak.txt'))
susu = set(line.strip() for line in open('susu.txt'))
telur = set(line.strip() for line in open('telur.txt'))

bumbu = set(map(lambda x: x.lower(), bumbu))
gula = set(map(lambda x: x.lower(), gula))
ikan = set(map(lambda x: x.lower(), ikan))
lemak = set(map(lambda x: x.lower(), lemak))
susu = set(map(lambda x: x.lower(), susu))
telur = set(map(lambda x: x.lower(), telur))

dict_cat = {"buah": buah, "bumbu": bumbu, "daging": daging, "gula": gula, "ikan": ikan,
            "kacang": kacang, "lemak": lemak, "sayur": sayur, "serealia": serealia, "susu": susu,
            "telur": telur, "umbi": umbi}

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1GaXKbBdvrSt52MezMV8nSvIHy5x-fvh2
To: /content/buah.txt
100% 590/590 [00:00<00:00, 867kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1CpdhUD_DEizVOMCJJbc6dGFOh9xeE_E0
To: /content/bumbu.txt
100% 657/657 [00:00<00:00, 941kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Gn2vCNF5kRXYJU2GU7DGIlXiLA81UTtQ
To: /content/daging.txt
100% 702/702 [00:00<00:00, 977kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1U-O_-OFBEZHR0NTqZ43rQHvW_Pqqoc_R
To: /content/gula.txt
100% 530/530 [00:00<00:00, 686kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1HctjzZRqOrqTxfGd-cWcqYEoIDS6x0fh
To: /content/ikan.txt
100% 2.11k/2.11k [00:00<00:00, 2.93MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1jZ_ngKTPvL-8DiKQ9YG0UPRTn6S9jZMC
To: /content/kacang.txt
100% 380/380 [00:00<00:00, 434kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1BE9IIFqIcDrgLJWKOA-vPplNwwe2jZZF
To: /content/lemak.txt
100% 249/249 [00:00<00:00, 290kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=14ETHj-OUpL7QidjiI3pIMfMoOy9hCwd7
To: /content/sayur.txt
100% 1.13k/1.13k [00:00<00:00, 1.29MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1760qlylrkaFX2HfMptJDgyPGEpN1m4Ux
To: /content/serealia.txt
100% 1.06k/1.06k [00:00<00:00, 1.17MB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1dFkhjqIuTT3MAWz_ZzCkEL5Zvnn0yxHR
To: /content/susu.txt
100% 317/317 [00:00<00:00, 347kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1iV756YrD7wJ_yGlwq0CenBZLHnSFn3-2
To: /content/telur.txt
100% 259/259 [00:00<00:00, 299kB/s]
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1OtQ1Ij7S_GC-ROdoVzQn4i6cLMELUYAQ
To: /content/umbi.txt
100% 578/578 [00:00<00:00, 719kB/s]

In [ ]:
# Subprogram untuk meng-kategorikan semua title pada kolom dataframe
def generate_category(array_title):
  cleaned = cleaning_title(array_title, listStopword)
  ctg = []
  ctg_all = []

  for judul in cleaned:
    splitted_judul = judul[0].split()
    ctg = []
    for jdl in splitted_judul:
      for key, value in dict_cat.items():
        if jdl in dict_cat[key]:
          ctg.append(key)
    ctg = set(ctg)
    ctg = list(ctg)
    ctg_all.append(ctg)

  return ctg_all

# Subprogram untuk meng-append kolom category ke dataframe definisi
def make_append_category_df(df_title, df_definition):
  category = generate_category(df_title)
  df2 = df_definition.assign(Category=category)
  return df2

# Kodingan Scraping & Category (Tabel 1981)

## Scrape Wikipedia & Categorization dari Tabel 1981

Azie Udang - Sapi  
https://colab.research.google.com/drive/1Dj9b42R3czpQZrMvMh6dk-xIeOfx7ED2?usp=sharing

Fiza - Tiffin Biru, cookpad tahu - udang, dan scraping malaysian Cooking Pdf  
https://colab.research.google.com/drive/1XZ08L9TtsJPvS7lo63_SdOQUonx1Z23g?usp=sharing

Cookpad (Ayam - Sapi + Malay Cooking PDF)  
https://colab.research.google.com/drive/13efKsxutJyuV5thDDpvN_qNo5L_OHIOK?authuser=1#scrollTo=3ncLd_YZiHc3

## Scrape Website (Fiza-Tiffinbiru)

https://drive.google.com/drive/folders/1QVjafdJy7rBgi5pHE3aEJ9HVWPIrdSG9?usp=sharing

# Udang

In [ ]:
!gdown --id "1hg9S6bSgHS3yc6q3xgBDP1e6WxUV8JBw"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hg9S6bSgHS3yc6q3xgBDP1e6WxUV8JBw
To: /content/aziekitchen-udang.jl
100% 1.39M/1.39M [00:00<00:00, 94.1MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
udang=pd.read_json(r'/content/aziekitchen-udang.jl', lines = True)

#save dalam acar biar ngebut loading ntar.
udang.to_pickle(r'/content/raw_df.pkl')

udang = pre_cleaning_text(udang, threshold=20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
udang.head()

,list_scraping_time,url_search,list_item_url,list_item_title,list_item_author_name,list_item_author_url,list_item_post_date,list_item_post_comment_count,list_item_category,list_item_category_link,...,page_item_category,page_item_category_link,page_description,page_description_image_url,page_ulasan_count,page_comment,page_comment_time,page_comment_user,page_comment_user_url,page_comment_user_image_url
0,2021-12-31 06:01:24,https://www.aziekitchen.com/search?q=udang,https://www.aziekitchen.com/2020/02/rendang-pe...,Rendang Pedas Udang Galah Dengan Kacang Buncis,Azie,https://www.blogger.com/profile/00119325245731...,2/18/2020,\n1 Comment\n,\nfeatured\n,https://www.aziekitchen.com/search/label/featu...,...,"[featured, Lauk Pauk, Udang]",[https://www.aziekitchen.com/search/label/feat...,"[-, -, -, -, -, -, -, -, -, -, -, Jom layan re...",[https://1.bp.blogspot.com/-SGT7IwM3w88/XkotWQ...,1 ulasan,"[tengok saja pun dah tau sedap, kak., Ialah, k...","[23 Februari, 2020 14:53]",[Seri Kandi Di Tanah Jauhar],[https://www.blogger.com/profile/0485581192521...,[//2.bp.blogspot.com/-7IpnMVzXwzg/XY2woYDx1UI/...
1,2021-12-31 06:01:24,https://www.aziekitchen.com/search?q=udang,https://www.aziekitchen.com/2013/05/udang-gore...,Udang Goreng Butter Yang Paling Sedap,Azie,https://www.blogger.com/profile/02058252209863...,5/13/2013,\n117\n Comments\...,\nLauk Pauk\n,https://www.aziekitchen.com/search/label/Lauk%...,...,"[Lauk Pauk, Seafood, Udang]",[https://www.aziekitchen.com/search/label/Lauk...,"[-, Saya pernah menyediakan Udang Goreng Butte...",[https://3.bp.blogspot.com/-t1QVzkRla9g/UY8qkn...,117 ulasan,"[Salam Azie, mudah dan menyelerakan, mungkin s...","[13 Mei, 2013 08:52, 13 Mei, 2013 18:18, 09 Ja...","[Engineers Love Cooking, Azie, Unknown, Unknow...",[https://www.blogger.com/profile/1394017965595...,[//2.bp.blogspot.com/-CyoZGHKCgLk/T81X70uH1RI/...
2,2021-12-31 06:01:24,https://www.aziekitchen.com/search?q=udang,https://www.aziekitchen.com/2019/10/masak-loma...,Masak Lomak Cili Api Udang,Azie,https://www.blogger.com/profile/00119325245731...,10/30/2019,\n1 Comment\n,\nfeatured\n,https://www.aziekitchen.com/search/label/featu...,...,"[featured, Lauk Pauk, Masakan Tradisional, Sea...",[https://www.aziekitchen.com/search/label/feat...,"[-, -, -, -, -, -, -, Jom layan resepi masak l...",[https://1.bp.blogspot.com/-3ECL9_raEu8/Xbg33Y...,1 ulasan,[Sodapnyo],"[30 Oktober, 2019 21:33]",[Warisan Petani],[https://www.blogger.com/profile/1515705677504...,[//4.bp.blogspot.com/-I1pNzgenHDw/XO6UCe9q3UI/...
3,2021-12-31 06:01:24,https://www.aziekitchen.com/search?q=udang,https://www.aziekitchen.com/2018/06/sambal-tum...,Sambal Tumis Udang dengan Petai Buat Juita,Azie,https://www.blogger.com/profile/00119325245731...,6/08/2018,\n1 Comment\n,\nLauk Pauk\n,https://www.aziekitchen.com/search/label/Lauk%...,...,"[Lauk Pauk, Seafood, Udang]",[https://www.aziekitchen.com/search/label/Lauk...,"[-, -, Hmm terasa sangat cepat masa berlalu, R...",[https://4.bp.blogspot.com/-o3YDsu_j3rA/WxqXFd...,1 ulasan,[Wah....syoknya dengar Juita dapat beraya lama...,"[09 Jun, 2018 12:40]",[Norma Shah],[https://www.blogger.com/profile/1297446680819...,[//www.blogger.com/img/blogger_logo_round_35.png]
4,2021-12-31 06:01:24,https://www.aziekitchen.com/search?q=udang,https://www.aziekitchen.com/2011/09/mee-udang-...,Mee Udang Istimewa,Azie,https://www.blogger.com/profile/02058252209863...,9/18/2011,\n2\n Comments\n ...,\nKuih Muih\n,https://www.aziekitchen.com/search/label/Kuih%...,...,"[Kuih Muih, Mee/Mee Hoon]",[https://www.aziekitchen.com/search/label/Kuih...,"[\n, -, -, \n, -, \n, OK jom kita layan gambar...",[https://2.bp.blogspot.com/-ispM0mhrQRE/TnV2z6...,2 ulasan,[Assalamualaikum kak azie.. sy selalu jenguk b...,"[21 September, 2015 16:39, 23 Julai, 2017 13:37]","[Unknown, Unknown]",[https://www.blogger.com/profile/0363961842120...,[//www.blogger.com/img/blogger_logo_round_35.p...

In [ ]:
#boleh run sekiranya ingin masukkan column lain dari dataset, kalo ga ya jangan run donk
# convert_to_list = ['page_description']

# for c in convert_to_list:
#     print(data[c])
#     data[c] = data[c].apply(lambda x: eval(x))

## GUI Udang

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = udang.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5     -0.221905 -0.048307       1        1  55.774387
1     -0.156442  0.035967       2        1  20.617019
2      0.045597 -0.289746       3        1   6.325500
3     -0.070228  0.111930       4        1   5.998331
6      0.000154  0.114006       5        1   5.156608
0      0.244939  0.045244       6        1   3.691350
4      0.157885  0.030907       7        1   2.436806, topic_info=               Term        Freq       Total Category  logprob  loglift
23             gula  176.000000  176.000000  Default  30.0000  30.0000
28           bawang  462.000000  462.000000  Default  29.0000  29.0000
6             udang  439.000000  439.000000  Default  28.0000  28.0000
11           santan  111.000000  111.000000  Default  27.0000  27.0000
143             mee   97.000000   97.000000  Default  26.0000  26.0000
24            garam  291.000000  291.000000  Default  25.0000  25.0000
51           goreng  148.000000  148.000000  Default  24.0000  24.0000
136             air  148.000000  148.000000  Default  23.0000  23.0000
31            putih  191.000000  191.000000  Default  22.0000  22.0000
199           kicap   49.000000   49.000000  Default  21.0000  21.0000
16             daun  146.000000  146.000000  Default  20.0000  20.0000
35            hidup   58.000000   58.000000  Default  19.0000  19.0000
55            telur   85.000000   85.000000  Default  18.0000  18.0000
9            kacang   72.000000   72.000000  Default  17.0000  17.0000
29            merah  222.000000  222.000000  Default  16.0000  16.0000
131             sos   94.000000   94.000000  Default  15.0000  15.0000
20           batang  100.000000  100.000000  Default  14.0000  14.0000
96             kuah   57.000000   57.000000  Default  13.0000  13.0000
166            gram   65.000000   65.000000  Default  12.0000  12.0000
198           karot   40.000000   40.000000  Default  11.0000  11.0000
167           nenas   29.000000   29.000000  Default  10.0000  10.0000
27             biji  231.000000  231.000000  Default   9.0000   9.0000
37             cili  334.000000  334.000000  Default   8.0000   8.0000
221           panas   40.000000   40.000000  Default   7.0000   7.0000
206           sayur   55.000000   55.000000  Default   6.0000   6.0000
429          rendam   30.000000   30.000000  Default   5.0000   5.0000
208            ikan   83.000000   83.000000  Default   4.0000   4.0000
190            nasi   48.000000   48.000000  Default   3.0000   3.0000
87           keping  119.000000  119.000000  Default   2.0000   2.0000
72             kari   48.000000   48.000000  Default   1.0000   1.0000
88             asam  101.335533  101.961995   Topic1  -4.1633   0.5777
108          sambal   63.793925   64.420960   Topic1  -4.6260   0.5741
184            jawa   47.405843   48.032023   Topic1  -4.9229   0.5707
122           petai   35.014788   35.640580   Topic1  -5.2259   0.5661
207           lemak   26.657558   27.285940   Topic1  -5.4986   0.5606
226         belacan   24.971958   25.598273   Topic1  -5.5639   0.5591
502           kubis   24.859154   25.535807   Topic1  -5.5685   0.5570
608          terung   22.302356   22.930066   Topic1  -5.6770   0.5561
227           wangi   19.816392   20.444982   Topic1  -5.7952   0.5526
250             pes   17.508539   18.135962   Topic1  -5.9190   0.5486
161           gulai   17.088412   17.732642   Topic1  -5.9433   0.5468
10           buncis   16.268109   16.894024   Topic1  -5.9925   0.5461
299          tengok   16.131431   16.758306   Topic1  -6.0009   0.5457
97           cantik   15.199088   15.826258   Topic1  -6.0605   0.5434
117            saiz   15.052386   15.687663   Topic1  -6.0702   0.5425
703           bayam   13.065630   13.692239   Topic1  -6.2117   0.5370
254        ketumbar   13.061360   13.691431   Topic1  -6.2120   0.5367
169           halba   12.270400   12.896274   Topic1  -6.2745   0.5341
495         hirisan   12.516439   13.156574   Topic1  -6.2546   0.5340
87           keping  113.941498  119.852331   Topic1  -4.0460   0.5333
348            layu   11.289685   11.916575   Topic1  -6.3578   0.5298
416           ketam   10.669116   11.295447   Topic1  -6.4143   0.5268
240            lauk   10.356515   10.984329   Topic1  -6.4441   0.5250
241       kepekatan   10.352178   10.983386   Topic1  -6.4445   0.5247
111            klik   23.854157   25.396033   Topic1  -5.6097   0.5212
312           keras    9.599247   10.227615   Topic1  -6.5200   0.5204
32             inci   73.689187   79.161007   Topic1  -4.4818   0.5122
3           youtube   32.904635   35.422855   Topic1  -5.2881   0.5101
115         dimasak    8.049400    8.675495   Topic1  -6.6961   0.5090
40         caracara    8.046453    8.674995   Topic1  -6.6965   0.5086
17           kunyit   95.705717  104.241754   Topic1  -4.2204   0.4984
23             gula  158.229073  176.386396   Topic1  -3.7176   0.4752
1              lupa   26.959378   29.624986   Topic1  -5.4874   0.4896
26            kisar  174.374582  204.613057   Topic1  -3.6205   0.4239
29            merah  180.959562  222.970314   Topic1  -3.5834   0.3751
24            garam  229.481164  291.778077   Topic1  -3.3459   0.3437
6             udang  337.088268  439.383370   Topic1  -2.9613   0.3188
11           santan   92.205497  111.206254   Topic1  -4.2577   0.3965
30             ulas  144.471632  181.032864   Topic1  -3.8086   0.3583
45            tumis   95.052570  116.608972   Topic1  -4.2273   0.3795
4           selamat   59.417382   70.649147   Topic1  -4.6971   0.4107
37             cili  245.234180  334.662287   Topic1  -3.2795   0.2729
28           bawang  320.935637  462.411180   Topic1  -3.0105   0.2186
5           mencuba   56.839518   68.350675   Topic1  -4.7415   0.3994
99             nota   46.096885   54.505215   Topic1  -4.9509   0.4163
39           kering   95.394953  125.512129   Topic1  -4.2237   0.3095
27             biji  161.281777  231.602008   Topic1  -3.6985   0.2220
31            putih  135.925718  191.289313   Topic1  -3.8696   0.2422
18            hiris   85.468557  114.690588   Topic1  -4.3335   0.2898
0             layan   66.072193   85.792606   Topic1  -4.5909   0.3227
20           batang   74.613854  100.927992   Topic1  -4.4694   0.2818
9            kacang   56.827458   72.838154   Topic1  -4.7417   0.3356
77           serbuk   65.885654   90.432205   Topic1  -4.5938   0.2672
208            ikan   61.515802   83.947720   Topic1  -4.6624   0.2730
136             air   93.821652  148.678820   Topic1  -4.2403   0.1235
36          tangkai   53.660527   80.005809   Topic1  -4.7990   0.1844
16             daun   55.816051  146.541333   Topic1  -4.7596  -0.3814
51           goreng   49.892403  148.840213   Topic1  -4.8718  -0.5091
140          sotong   25.623128   26.266936   Topic2  -4.5430   1.5542
143             mee   94.811767   97.951794   Topic2  -3.2346   1.5465
916             bok   17.311850   17.971362   Topic2  -4.9351   1.5417
148            fish   15.425107   16.068591   Topic2  -5.0505   1.5382
917            choy   13.248257   13.919831   Topic2  -5.2026   1.5296
68            sulah   12.186811   12.835594   Topic2  -5.2861   1.5272
149            ball   10.168965   10.812411   Topic2  -5.4672   1.5177
54           kuning   30.524031   32.909612   Topic2  -4.3680   1.5038
757           basah    8.221527    8.864916   Topic2  -5.6797   1.5037
636         rebusan    6.935932    7.580193   Topic2  -5.8498   1.4902
133            sawi   19.839989   21.898489   Topic2  -4.7988   1.4803
256           ambil    5.649602    6.295394   Topic2  -6.0549   1.4708
359           limau   34.302715   38.303826   Topic2  -4.2513   1.4687
487            cake    5.380194    6.023787   Topic2  -6.1038   1.4661
127            buah   18.622999   20.856986   Topic2  -4.8621   1.4658
772        mengeras    5.184976    5.828445   Topic2  -6.1407   1.4621
952        direndam    5.184929    5.828450   Topic2  -6.1407   1.4621
756         bungkus    5.184022    5.828224   Topic2  -6.1409   1.4619
642       hidangkan    4.912426    5.556107   Topic2  -6.1947   1.4559
633         kasturi    4.639862    5.283755   Topic2  -6.2518   1.4491
878        pecahkan    4.172923    4.816297   Topic2  -6.3579   1.4357
1193           choi    4.172744    4.816273   Topic2  -6.3579   1.4356
1071           laut    4.172733    4.816299   Topic2  -6.3579   1.4356
1156            tom    4.172672    4.816288   Topic2  -6.3579   1.4356
1157            yam    4.172672    4.816288   Topic2  -6.3579   1.4356
134           celur    4.096274    4.739512   Topic2  -6.3764   1.4332
126          tomato   28.144043   32.640530   Topic2  -4.4492   1.4308
915           adabi    4.136662    4.810964   Topic2  -6.3666   1.4280
62           toskan    9.419807   10.961125   Topic2  -5.5437   1.4275
645         perahan    3.899518    4.543762   Topic2  -6.4256   1.4262
337            hoon   26.811301   33.260096   Topic2  -4.4977   1.3635
131             sos   66.823108   94.959640   Topic2  -3.5844   1.2277
501           bunga    7.757891    9.870683   Topic2  -5.7378   1.3382
301           manis   18.159621   26.422259   Topic2  -4.8873   1.2040
160          daging   16.699919   24.933558   Topic2  -4.9711   1.1782
69       menggoreng    7.741483    9.997718   Topic2  -5.7399   1.3233
16             daun   68.077184  146.541333   Topic2  -3.5659   0.8124
360           nipis   17.844482   29.230152   Topic2  -4.9048   1.0855
55            telur   42.008676   85.613866   Topic2  -4.0486   0.8671
199           kicap   26.653755   49.166155   Topic2  -4.5036   0.9668
51           goreng   58.256770  148.840213   Topic2  -3.7216   0.6410
417           tiram   15.404446   25.213266   Topic2  -5.0518   1.0863
191            ayam   22.090578   43.202491   Topic2  -4.6913   0.9083
28           bawang  104.543607  462.411180   Topic2  -3.1369   0.0922
37             cili   78.936484  334.662287   Topic2  -3.4179   0.1346
156         disukai   10.540613   16.365371   Topic2  -5.4313   1.1391
27             biji   52.701681  231.602008   Topic2  -3.8218   0.0987
206           sayur   21.180618   55.225596   Topic2  -4.7334   0.6207
136             air   37.037659  148.678820   Topic2  -4.1746   0.1892
6             udang   66.353247  439.383370   Topic2  -3.5915  -0.3113
39           kering   29.609129  125.512129   Topic2  -4.3984   0.1347
24            garam   40.760242  291.778077   Topic2  -4.0788  -0.3892
26            kisar   29.722693  204.613057   Topic2  -4.3946  -0.3502
66             ekor   19.320665   56.203625   Topic2  -4.8253   0.5112
31            putih   26.647837  191.289313   Topic2  -4.5038  -0.3920
30             ulas   25.480070  181.032864   Topic2  -4.5486  -0.3817
18            hiris   22.568598  114.690588   Topic2  -4.6699  -0.0466
29            merah   21.706679  222.970314   Topic2  -4.7089  -0.7504
45            tumis   20.423323  116.608972   Topic2  -4.7698  -0.1631
311          tumbuk   18.756501   67.062183   Topic2  -4.8550   0.3050
167           nenas   28.405415   29.066767   Topic3  -3.2584   2.7376
434           maggi   16.450818   17.112087   Topic3  -3.8046   2.7212
789           tempe   11.615909   12.276666   Topic3  -4.1526   2.7053
342        perencah   10.490640   11.153204   Topic3  -4.2545   2.6993
171          periuk    8.651525    9.314761   Topic3  -4.4472   2.6867
815          pajeri    7.190906    7.850031   Topic3  -4.6321   2.6729
869       sengkuang    6.305353    6.964756   Topic3  -4.7636   2.6611
791           fucuk    6.304937    6.964821   Topic3  -4.7636   2.6610
335           impit    6.067655    6.726610   Topic3  -4.8020   2.6575
870             soo    5.420310    6.079428   Topic3  -4.9148   2.6458
480           timun    6.442456    7.240145   Topic3  -4.7421   2.6438
788       semalaman    3.649052    4.308953   Topic3  -5.3105   2.5944
334           lodeh    3.411017    4.070821   Topic3  -5.3780   2.5837
89          diketuk    3.410849    4.070782   Topic3  -5.3780   2.5837
670            hati    3.405896    4.069946   Topic3  -5.3795   2.5825
817       tenggelam    2.764606    3.423580   Topic3  -5.5881   2.5468
872            basi    2.764569    3.423606   Topic3  -5.5881   2.5468
848         seriaji    2.764392    3.423593   Topic3  -5.5881   2.5467
333         lontong    2.526525    3.185468   Topic3  -5.6781   2.5288
785         belajar    4.532937    5.941083   Topic3  -5.0936   2.4901
1000   kacangsambal    1.879356    2.538308   Topic3  -5.9740   2.4600
871      sepenuhnya    1.879314    2.538310   Topic3  -5.9741   2.4600
873           didih    1.879314    2.538310   Topic3  -5.9741   2.4600
874           reneh    1.879314    2.538310   Topic3  -5.9741   2.4600
1065           olah    1.879282    2.538295   Topic3  -5.9741   2.4600
966           perap    1.879186    2.538320   Topic3  -5.9741   2.4599
1023          solok    1.879183    2.538361   Topic3  -5.9741   2.4599
822        berempah    1.877669    2.538261   Topic3  -5.9749   2.4591
828        pengukus    1.877615    2.538296   Topic3  -5.9750   2.4591
797           penuh    2.897132    4.139723   Topic3  -5.5412   2.4037
429          rendam   17.160811   30.744812   Topic3  -3.7623   2.1775
129         kentang    6.776364   10.876425   Topic3  -4.6915   2.2874
260           rebus   17.266711   36.357551   Topic3  -3.7562   2.0160
632           tauhu   14.035191   31.548594   Topic3  -3.9634   1.9506
35            hidup   20.854890   58.951050   Topic3  -3.5674   1.7215
96             kuah   19.106418   57.399380   Topic3  -3.6549   1.6606
438         masakan    4.756254    9.683600   Topic3  -5.0455   2.0496
72             kari   12.488401   48.388968   Topic3  -4.0802   1.4061
9            kacang   15.467977   72.838154   Topic3  -3.8662   1.2111
11           santan   18.480029  111.206254   Topic3  -3.6883   0.9659
25          secukup    9.744769   36.788743   Topic3  -4.3282   1.4321
20           batang   15.839324  100.927992   Topic3  -3.8425   0.9087
154           kotak    8.581229   30.617034   Topic3  -4.4554   1.4886
42              tos    7.398904   23.610456   Topic3  -4.6036   1.6002
22            ketuk    9.741380   42.943564   Topic3  -4.3286   1.2771
190            nasi    9.704794   48.838077   Topic3  -4.3323   1.1447
21            serai    9.047264   45.837087   Topic3  -4.4025   1.1380
51           goreng   14.138946  148.840213   Topic3  -3.9560   0.4066
93         mendidih    9.636348   60.909976   Topic3  -4.3394   0.9167
27             biji   14.012451  231.602008   Topic3  -3.9650  -0.0445
90            letak    7.763716   34.856382   Topic3  -4.5555   1.2588
174          rempah    7.730111   35.493793   Topic3  -4.5598   1.2363
94          biarkan    6.609175   31.799880   Topic3  -4.7165   1.1896
441           purut   16.164375   16.951228   Topic4  -3.7690   2.7662
400           lobak    5.055670    5.718151   Topic4  -4.9313   2.6906
600             utk    5.048902    5.717286   Topic4  -4.9327   2.6894
589     dibersihkan    3.959731    4.621976   Topic4  -5.1757   2.6590
913           sejuk    3.559733    4.222729   Topic4  -5.2822   2.6429
604            soto    3.322259    3.990939   Topic4  -5.3512   2.6303
195         sayuran   11.950148   14.438769   Topic4  -4.0711   2.6245
1039          paket    2.697279    3.359080   Topic4  -5.5596   2.5943
765            peti    2.696707    3.359089   Topic4  -5.5598   2.5941
885         keropok    2.693005    3.359377   Topic4  -5.5612   2.5926
197       memanjang    2.226275    2.894877   Topic4  -5.7515   2.5511
598             bwg    2.000584    2.662069   Topic4  -5.8584   2.5280
1040         minyak    1.833471    2.495299   Topic4  -5.9456   2.5055
1046          besar    1.833471    2.495299   Topic4  -5.9456   2.5055
766             ais    1.833291    2.495264   Topic4  -5.9457   2.5054
767         dikukus    1.833291    2.495264   Topic4  -5.9457   2.5054
889           sikit    1.833270    2.495372   Topic4  -5.9458   2.5054
902         paprika    1.832740    2.495248   Topic4  -5.9460   2.5051
908            chef    1.826667    2.493992   Topic4  -5.9494   2.5023
448          sayang    1.601115    2.262972   Topic4  -6.0812   2.4677
443            leek    1.600648    2.263104   Topic4  -6.0815   2.4674
442           carik    1.600604    2.263133   Topic4  -6.0815   2.4673
586           semak    1.599463    2.262649   Topic4  -6.0822   2.4668
401         supdaun    1.597771    2.263194   Topic4  -6.0832   2.4655
686      berkhasiat    1.580983    2.260599   Topic4  -6.0938   2.4561
262         pinggan    1.584143    2.265627   Topic4  -6.0918   2.4559
596        tempoyak    1.369129    2.030619   Topic4  -6.2377   2.4195
202            gaul    7.713137   12.603240   Topic4  -4.5089   2.3227
786           liter    3.611977    5.992141   Topic4  -5.2676   2.3075
468          perisa    3.328765    5.531397   Topic4  -5.3493   2.3059
762            sapi    2.619049    4.384421   Topic4  -5.5890   2.2984
632           tauhu   13.524679   31.548594   Topic4  -3.9473   1.9667
896        cendawan    4.376346    8.131381   Topic4  -5.0756   2.1942
198           karot   15.162448   40.242208   Topic4  -3.8330   1.8376
601        dipotong    3.821527    7.095941   Topic4  -5.2112   2.1948
245             sup    7.363035   17.118628   Topic4  -4.5554   1.9700
43        ketepikan   11.155445   37.472004   Topic4  -4.1399   1.6020
191            ayam   11.564227   43.202491   Topic4  -4.1039   1.4957
166            gram   15.251421   65.306342   Topic4  -3.8272   1.3593
206           sayur   13.562881   55.225596   Topic4  -3.9445   1.4096
51           goreng   23.320780  148.840213   Topic4  -3.4025   0.9602
67             lada    8.362598   28.583590   Topic4  -4.4281   1.5846
50            tabur    7.434076   26.451176   Topic4  -4.5458   1.5445
55            telur   14.046954   85.613866   Topic4  -3.9095   1.0062
193          tepung    6.443837   23.695443   Topic4  -4.6887   1.5115
16             daun   16.238337  146.541333   Topic4  -3.7645   0.6138
247         cincang    6.423189   25.439972   Topic4  -4.6919   1.4373
28           bawang   27.279731  462.411180   Topic4  -3.2457  -0.0166
31            putih   15.584463  191.289313   Topic4  -3.8056   0.3062
36          tangkai   10.626949   80.005809   Topic4  -4.1885   0.7950
204        digoreng    7.560027   37.853369   Topic4  -4.5290   1.2028
29            merah   15.368990  222.970314   Topic4  -3.8195   0.1390
71          dihiris    5.574419   27.412077   Topic4  -4.8337   1.2209
6             udang   11.416133  439.383370   Topic4  -4.1168  -0.8367
77           serbuk    7.286557   90.432205   Topic4  -4.5658   0.2951
44         panaskan    6.343874   68.831811   Topic4  -4.7044   0.4295
37             cili    8.502521  334.662287   Topic4  -4.4115  -0.8591
30             ulas    7.449490  181.032864   Topic4  -4.5437  -0.3768
18            hiris    5.741204  114.690588   Topic4  -4.8042  -0.1809
716           pasta   11.198605   11.857283   Topic5  -3.9849   2.9077
721          pepper   10.548088   11.206844   Topic5  -4.0447   2.9043
903         parsley    8.985855    9.661384   Topic5  -4.2050   2.8924
720           black    5.208673    5.867600   Topic5  -4.7503   2.8458
711           olive    4.970051    5.628255   Topic5  -4.7972   2.8405
647           enjoy    4.964598    5.628936   Topic5  -4.7983   2.8393
466           fresh    4.251983    4.910203   Topic5  -4.9533   2.8210
712             oil    4.080175    4.738378   Topic5  -4.9945   2.8153
708        scallops    4.080174    4.738378   Topic5  -4.9945   2.8153
460             teh    3.838848    4.499369   Topic5  -5.0555   2.8061
1182            red    3.668881    4.327183   Topic5  -5.1008   2.7999
472         thermos    3.601284    4.259658   Topic5  -5.1194   2.7970
217        kelainan    3.426661    4.088121   Topic5  -5.1691   2.7884

Topic: 1
kicap, teow, kue, taugeh, kucai, sos, kangkung, talam, ikan, manis, prego, isi, kerang, bilis, telur, cap, kuey, peket, ikat, bihun, kukus, tiram, mee, baby, mas, berlauk, gaul, beras, salam, hancur

Topic: 2
bawang, mee, cili, daun, sos, udang, goreng, biji, telur, garam, air, limau, kuning, kisar, kering, tomato, hoon, kicap, putih, sotong, ulas, hiris, ayam, merah, sayur, tumis, sawi, ekor, tumbuk, buah

Topic: 3
nenas, hidup, kuah, santan, rebus, rendam, maggi, batang, kacang, goreng, tauhu, biji, kari, tempe, perencah, secukup, ketuk, nasi, mendidih, serai, periuk, kotak, letak, rempah, tos, pajeri, kentang, biarkan, timun, sengkuang

Topic: 4
bawang, goreng, daun, purut, putih, merah, gram, karot, telur, sayur, tauhu, sayuran, ayam, udang, ketepikan, tangkai, cili, lada, gaul, digoreng, ulas, tabur, sup, serbuk, tepung, cincang, panaskan, hiris, dihiris, lobak

Topic: 5
tepung, gula, mentega, air, susu, telur, masin, cucur, butter, dikacau, tuang, direbus, gandum, pencicah, jagung, dicicah, tos, mushroom, macaroni, jgn, sebati, segar, cheese, ditumbuk, tuangkan, dibuang, youtube, karamel, straw, lecek

Topic: 6
udang, bawang, cili, garam, merah, kisar, biji, gula, ulas, putih, keping, asam, kunyit, kering, tumis, air, santan, hiris, batang, inci, layan, serbuk, sambal, ikan, selamat, mencuba, kacang, daun, tangkai, goreng

Topic: 7
udang, garam, panas, cincang, putih, pasta, pepper, air, gram, bawang, parsley, hitam, kuali, tepung, hidangan, lada, gandum, daun, kulit, black, cucur, olive, enjoy, merah, serbuk, jagung, kucai, fresh, oil, scallops

[(0,
  '0.043*"kicap" + 0.031*"teow" + 0.025*"kue" + 0.024*"taugeh" + 0.021*"kucai" + 0.017*"sos" + 0.014*"kangkung" + 0.012*"talam" + 0.012*"ikan" + 0.011*"manis"'),
 (1,
  '0.043*"bawang" + 0.039*"mee" + 0.033*"cili" + 0.028*"daun" + 0.028*"sos" + 0.028*"udang" + 0.024*"goreng" + 0.022*"biji" + 0.017*"telur" + 0.017*"garam"'),
 (2,
  '0.038*"nenas" + 0.028*"hidup" + 0.026*"kuah" + 0.025*"santan" + 0.023*"rebus" + 0.023*"rendam" + 0.022*"maggi" + 0.021*"batang" + 0.021*"kacang" + 0.019*"goreng"'),
 (3,
  '0.039*"bawang" + 0.033*"goreng" + 0.023*"daun" + 0.023*"purut" + 0.022*"putih" + 0.022*"merah" + 0.022*"gram" + 0.022*"karot" + 0.020*"telur" + 0.019*"sayur"'),
 (4,
  '0.034*"tepung" + 0.026*"gula" + 0.023*"mentega" + 0.021*"air" + 0.020*"susu" + 0.019*"telur" + 0.017*"masin" + 0.015*"cucur" + 0.013*"butter" + 0.011*"dikacau"'),
 (5,
  '0.052*"udang" + 0.049*"bawang" + 0.038*"cili" + 0.035*"garam" + 0.028*"merah" + 0.027*"kisar" + 0.025*"biji" + 0.024*"gula" + 0.022*"ulas" + 0.021*"putih"'),
 (6,
  '0.039*"udang" + 0.029*"garam" + 0.024*"panas" + 0.021*"cincang" + 0.020*"putih" + 0.019*"pasta" + 0.018*"pepper" + 0.016*"air" + 0.016*"gram" + 0.016*"bawang"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
udangProb = make_dictionary_terms_prob(ldamodel, id_map, d)
udangProb["mee"] #probabilitas kata mee pada setiap topik

[(0, 0.017503638),
 (1, 0.5931365),
 (2, 0.029725397),
 (3, 0.032974172),
 (4, 0.013196567),
 (5, 0.28782016),
 (6, 0.02564358)]

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
udangWN = dfWordnet.copy()

udangWN["Synonym_clean"] = cleanWN_Synonym(udangWN["Synonym"])
udangWN["Hypernim_clean"] = cleanWN(udangWN["Hypernim"])
udangWN["Hyponim_clean"] = cleanWN(udangWN["Hyponim"])
udangWN

### Make Ontology

In [ ]:
# Make Ontology
azieUdangOnto = get_ontology("http://test.org/azieUdang.owl")
makeOntology(azieUdangOnto, udangWN)
azieUdangOnto.save(file = "azieUdang.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "16ApevKhMErVji7vBeTB2cSZnWW46Scwa"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=16ApevKhMErVji7vBeTB2cSZnWW46Scwa
To: /content/AzieUdangFinal.xlsx
100% 22.8k/22.8k [00:00<00:00, 28.7MB/s]

In [ ]:
wiki_udang = pd.read_excel("AzieUdangFinal.xlsx").iloc[:, 1:]

# Translate
wiki_udang["Category"] = translate(wiki_udang["Category"])
wiki_udang

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_udang[["Title", "Category"]].iloc[:].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

ToggleButton(value=False, button_style='success', description='Next row', icon='check', tooltip='Description')

Row: 1/194
Rendang Pedas Udang Galah Dengan Kacang Buncis

SelectMultiple(description='category', options=('Vegetable', 'Nut', 'Fish', 'MeatAndPoultry'), value=())

Text(value='', description='Usulan Class', layout=Layout(height='40px', width='600px'), placeholder='input cla…

In [ ]:
udangTabel_new = tabel_1981.copy()
udangTabel_new["correct_category"] = all_cat
udangTabel_new["suggestion"] = all_suggestion

# Export Result to File
udangTabel_new.to_excel("udangTabel_Result.xlsx")
udangTabel_new

,Title,Category,correct_category,suggestion
0,Rendang Pedas Udang Galah Dengan Kacang Buncis,"[Vegetable, Nut, Fish, MeatAndPoultry]","[Vegetable, Fish]",[CuisineMeatAndPoultry]
1,Udang Goreng Butter Yang Paling Sedap,[Fish],[Fish],[]
2,Masak Lomak Cili Api Udang,"[Vegetable, Fish]",[Vegetable],[]

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "udangTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    "file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth"
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth

### Update Ontology NFO

In [ ]:
# NFO Ontology
!gdown "1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru"
table1981_Onto = get_ontology(r'/content/NFOversion2April22.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
udangTabel_new = concatListInColumn(udangTabel_new)
udangTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, udangTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

## Counter Wikipedia

In [ ]:
wiki_df = wiki_udang.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
udangWiki_new = wiki_df.copy()
udangWiki_new["suggest"] = all_cat

# Export Result to file
udangWiki_new.to_excel("udangWiki_Result.xlsx")
udangWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "udangWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieUdangOntoWiki = get_ontology("http://test.org/azieUdang_onto_wiki.owl")
makeOntology_wiki(azieUdangOntoWiki, udangWiki_new)
azieUdangOntoWiki.save(file = "azieUdang_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = udangWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

ToggleButton(value=False, button_style='success', description='Next row', icon='check', tooltip='Description')

Row: 1/210

Word: kicap
Synonym: soy_sauce
Hypernim: ['condiment']
Hyponim: None

RadioButtons(description='Hypernym (True/False?)', options=('True', 'False'), value='True')

Button(description='Submit', style=ButtonStyle())

In [ ]:
# Export Result to File
udangWN_new = listToDataframe(changesList, tableWordnet)
udangWN_new.to_excel("udangWN_Result.xlsx")
udangWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "udangWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Ayam

In [ ]:
!gdown --id "1hDDpuyUsZ9HyuG5tDM7LGzTMVifNhkrK"

In [ ]:
ayam=pd.read_json(r'/content/aziekitchen-ayam.jl', lines = True)

ayam.to_pickle(r'/content/raw_df.pkl')
ayam = pre_cleaning_text(ayam, threshold=20)
# ayam["cleaned_description"] = cleaning_text(ayam["page_description"])

# ingredients_all = ayam["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Ayam

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = ayam.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
ayamProb = make_dictionary_terms_prob(ldamodel, id_map, d)
ayamProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
ayamWN = dfWordnet.copy()

ayamWN["Synonym_clean"] = cleanWN_Synonym(ayamWN["Synonym"])
ayamWN["Hypernim_clean"] = cleanWN(ayamWN["Hypernim"])
ayamWN["Hyponim_clean"] = cleanWN(ayamWN["Hyponim"])
ayamWN

### Make Ontology

In [ ]:
# Make Ontology
azieAyamOnto = get_ontology("http://test.org/azieAyam.owl")
makeOntology(azieAyamOnto, ayamWN)
azieAyamOnto.save(file = "azieAyam.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1GdNFDSXOMR9C4TRWfGn7N8Zr_IaH0-Ur"

In [ ]:
wiki_ayam = pd.read_excel("AzieAyamFinal.xlsx").iloc[:, 1:]

# Translate
wiki_ayam["Category"] = translate(wiki_ayam["Category"])
wiki_ayam.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_ayam[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
ayamTabel_new = tabel_1981.copy()
ayamTabel_new["correct_category"] = all_cat
ayamTabel_new["suggestion"] = all_suggestion

# Export Result to File
ayamTabel_new.to_excel("ayamTabel_Result.xlsx")
ayamTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
ayamTabel_new = concatListInColumn(ayamTabel_new)
ayamTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, ayamTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

## Counter Wikipedia

In [ ]:
wiki_df = wiki_ayam.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
ayamWiki_new = wiki_df.copy()
ayamWiki_new["suggest"] = all_cat

# Export Result to file
ayamWiki_new.to_excel("ayamWiki_Result.xlsx")
ayamWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieAyamOntoWiki = get_ontology("http://test.org/azieAyam_onto_wiki.owl")
makeOntology_wiki(azieAyamOntoWiki, ayamWiki_new)
azieAyamOntoWiki.save(file = "azieAyam_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = ayamWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
ayamWN_new = listToDataframe(changesList, tableWordnet)
ayamWN_new.to_excel("ayamWN_Result.xlsx")
ayamWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Ikan

In [ ]:
!gdown --id "1h_hNQO3qLqUyvQ5v3GwPGk8YGbTpBrmd"

In [ ]:
ikan=pd.read_json(r'/content/aziekitchen-ikan.jl', lines = True)

#save dalam acar biar ngebut loading ntar.
ikan.to_pickle(r'/content/raw_df.pkl')

ikan = pre_cleaning_text(ikan, threshold=20)
# ikan["cleaned_description"] = cleaning_text(ikan["page_description"])
# ingredients_all = ikan["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Ikan

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = ikan.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
ikanProb = make_dictionary_terms_prob(ldamodel, id_map, d)
ikanProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
ikanWN = dfWordnet.copy()

ikanWN["Synonym_clean"] = cleanWN_Synonym(ikanWN["Synonym"])
ikanWN["Hypernim_clean"] = cleanWN(ikanWN["Hypernim"])
ikanWN["Hyponim_clean"] = cleanWN(ikanWN["Hyponim"])
ikanWN

### Make Ontology

In [ ]:
# Make Ontology
azieIkanOnto = get_ontology("http://test.org/azieIkan.owl")
makeOntology(azieIkanOnto, ikanWN)
azieIkanOnto.save(file = "azieIkan.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "12lE3RokN12jUUuDyAbl0_QNmKIv1IUrd"

In [ ]:
wiki_ikan = pd.read_excel("AzieIkanFinal.xlsx").iloc[:, 1:]

# Translate
wiki_ikan["Category"] = translate(wiki_ikan["Category"])
wiki_ikan.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_ikan[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
ikanTabel_new = tabel_1981.copy()
ikanTabel_new["correct_category"] = all_cat
ikanTabel_new["suggestion"] = all_suggestion

# Export Result to File
ikanTabel_new.to_excel("ikanTabel_Result.xlsx")
ikanTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
ikanTabel_new = concatListInColumn(ikanTabel_new)
ikanTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, ikanTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

## Counter Wikipedia

In [ ]:
wiki_df = wiki_ikan.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
ikanWiki_new = wiki_df.copy()
ikanWiki_new["suggest"] = all_cat

# Export Result to file
ikanWiki_new.to_excel("ikanWiki_Result.xlsx")
ikanWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieIkanOntoWiki = get_ontology("http://test.org/azieIkan_onto_wiki.owl")
makeOntology_wiki(azieIkanOntoWiki, ikanWiki_new)
azieIkanOntoWiki.save(file = "azieIkan_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = ikanWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
ikanWN_new = listToDataframe(changesList, tableWordnet)
ikanWN_new.to_excel("ikanWN_Result.xlsx")
ikanWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Kambing

In [ ]:
!gdown --id "1hPTtLXu7jgsmWegZwxU6M-Swbb_zvhgM"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hPTtLXu7jgsmWegZwxU6M-Swbb_zvhgM
To: /content/aziekitchen-kambing.jl
100% 916k/916k [00:00<00:00, 142MB/s]

In [ ]:
kambing=pd.read_json(r'/content/aziekitchen-kambing.jl', lines = True)

#save dalam acar biar ngebut loading ntar.
kambing.to_pickle(r'/content/raw_df.pkl')

kambing = pre_cleaning_text(kambing)

# kambing["cleaned_description"] = cleaning_text(kambing["page_description"])
# ingredients_all = kambing["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Kambing

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = kambing.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4      0.143016  0.048356       1        1  42.802709
5      0.173085 -0.083628       2        1  23.400268
2      0.023307  0.069393       3        1   8.776384
3     -0.091653  0.101684       4        1   7.537965
6     -0.154680 -0.101018       5        1   7.291537
0     -0.002055 -0.039683       6        1   6.657953
1     -0.091020  0.004898       7        1   3.533184, topic_info=                Term        Freq       Total Category  logprob  loglift
63               air   51.000000   51.000000  Default  30.0000  30.0000
28            bawang  135.000000  135.000000  Default  29.0000  29.0000
65            daging   55.000000   55.000000  Default  28.0000  28.0000
117           rempah   35.000000   35.000000  Default  27.0000  27.0000
27            kunyit   29.000000   29.000000  Default  26.0000  26.0000
50             garam   78.000000   78.000000  Default  25.0000  25.0000
53            goreng   25.000000   25.000000  Default  24.0000  24.0000
126              sup   13.000000   13.000000  Default  23.0000  23.0000
146             asam   33.000000   33.000000  Default  22.0000  22.0000
55             hiris   54.000000   54.000000  Default  21.0000  21.0000
145          kerisik   17.000000   17.000000  Default  20.0000  20.0000
56              cili   55.000000   55.000000  Default  19.0000  19.0000
51              gula   63.000000   63.000000  Default  18.0000  18.0000
139              mee    8.000000    8.000000  Default  17.0000  17.0000
9             keping   32.000000   32.000000  Default  16.0000  16.0000
123             ulas   43.000000   43.000000  Default  15.0000  15.0000
313             ayam   44.000000   44.000000  Default  14.0000  14.0000
54              daun   57.000000   57.000000  Default  13.0000  13.0000
34             halia   39.000000   39.000000  Default  12.0000  12.0000
23            serbuk   42.000000   42.000000  Default  11.0000  11.0000
26             putih   52.000000   52.000000  Default  10.0000  10.0000
74            kering   26.000000   26.000000  Default   9.0000   9.0000
30            tomato   33.000000   33.000000  Default   8.0000   8.0000
33            tumbuk   16.000000   16.000000  Default   7.0000   7.0000
122            merah   52.000000   52.000000  Default   6.0000   6.0000
17             manis   29.000000   29.000000  Default   5.0000   5.0000
82             tabur   11.000000   11.000000  Default   4.0000   4.0000
144           santan   28.000000   28.000000  Default   3.0000   3.0000
18              biji   82.000000   82.000000  Default   2.0000   2.0000
40             telur   14.000000   14.000000  Default   1.0000   1.0000
482              sos   17.964280   18.572085   Topic1  -4.6203   0.8153
76           lapisan   17.039831   17.636349   Topic1  -4.6731   0.8142
29              dadu   14.158284   14.799927   Topic1  -4.8584   0.8042
45              susu   12.343233   12.938914   Topic1  -4.9956   0.8014
48           pewarna   11.406404   11.999922   Topic1  -5.0745   0.7978
36             helai   10.465937   11.060100   Topic1  -5.1606   0.7934
35           yoghurt   10.465690   11.060159   Topic1  -5.1606   0.7933
97             halus    9.526472   10.120629   Topic1  -5.2546   0.7881
12            kuntum    8.585812    9.180713   Topic1  -5.3586   0.7816
96             bulat    7.646523    8.241199   Topic1  -5.4744   0.7737
30            tomato   31.127446   33.723992   Topic1  -4.0706   0.7684
488             cair    6.707657    7.302113   Topic1  -5.6054   0.7637
313             ayam   40.520666   44.398706   Topic1  -3.8069   0.7572
151             lauk    5.770212    6.362956   Topic1  -5.7560   0.7508
155          beriani    5.770012    6.362911   Topic1  -5.7560   0.7508
93        kesemuanya    5.769673    6.362847   Topic1  -5.7561   0.7507
78          menutupi    5.769630    6.362864   Topic1  -5.7561   0.7507
24          ketumbar   22.655769   25.045017   Topic1  -4.3883   0.7483
6           basmathi    4.830759    5.423468   Topic1  -5.9337   0.7328
43             kelar    4.830652    5.423426   Topic1  -5.9337   0.7328
37               bay    4.830572    5.423424   Topic1  -5.9337   0.7328
38             leave    4.830571    5.423425   Topic1  -5.9337   0.7328
98              gaul    4.830579    5.423438   Topic1  -5.9337   0.7328
83             salad    4.830115    5.423312   Topic1  -5.9338   0.7327
644            purut    4.826550    5.422183   Topic1  -5.9346   0.7322
504       bahanbahan    4.827271    5.423040   Topic1  -5.9344   0.7322
165            belah    7.605587    8.751885   Topic1  -5.4798   0.7082
493           zaitun    3.891791    4.484048   Topic1  -6.1498   0.7069
47           saffron    3.891399    4.483965   Topic1  -6.1499   0.7068
61            kismis    3.891384    4.483964   Topic1  -6.1499   0.7068
379            lidah    7.630329    8.890312   Topic1  -5.4766   0.6957
5              beras   10.466139   12.297717   Topic1  -5.1605   0.6873
75             letak    7.648414    8.959073   Topic1  -5.4742   0.6904
56              cili   44.440132   55.128870   Topic1  -3.7145   0.6330
54              daun   44.979876   57.479561   Topic1  -3.7025   0.6034
58             hijau   13.862794   16.821737   Topic1  -4.8795   0.6551
18              biji   60.658816   82.422873   Topic1  -3.4034   0.5420
71              nasi   27.350514   35.521902   Topic1  -4.2000   0.5872
49            kuning   12.324535   15.225921   Topic1  -4.9971   0.6372
23            serbuk   31.133215   42.687430   Topic1  -4.0704   0.5329
68             kuali    8.281828    9.826254   Topic1  -5.3946   0.6776
21           tangkai   17.147317   22.239989   Topic1  -4.6668   0.5885
27            kunyit   21.649735   29.254589   Topic1  -4.4337   0.5475
74            kering   19.485710   26.172616   Topic1  -4.5390   0.5535
420          secukup   10.380271   12.991045   Topic1  -5.1688   0.6242
19              buah   16.934007   24.315560   Topic1  -4.6794   0.4868
28            bawang   64.473589  135.366005   Topic1  -3.3424   0.1068
50             garam   38.021343   78.658797   Topic1  -3.8705   0.1216
25            jintan    9.511424   11.896333   Topic1  -5.2562   0.6248
53            goreng   15.638188   25.807015   Topic1  -4.7590   0.3476
63               air   23.704028   51.122780   Topic1  -4.3430   0.0800
26             putih   23.300238   52.061056   Topic1  -4.3602   0.0446
121            kisar   16.725369   30.023261   Topic1  -4.6918   0.2635
122            merah   22.669122   52.230170   Topic1  -4.3877   0.0139
15              inci   16.653796   32.428044   Topic1  -4.6961   0.1822
55             hiris   20.028896   54.069595   Topic1  -4.5115  -0.1445
51              gula   19.229428   63.781785   Topic1  -4.5522  -0.3505
13             bunga   13.450568   25.641472   Topic1  -4.9097   0.2034
34             halia   14.659096   39.294090   Topic1  -4.8236  -0.1374
17             manis   13.278641   29.595323   Topic1  -4.9225   0.0471
65            daging   13.934477   55.776802   Topic1  -4.8743  -0.5384
244          penumis    5.457222    6.058049   Topic2  -5.2079   1.3480
237            nyior    5.449586    6.054790   Topic2  -5.2093   1.3471
229            kawah   10.788337   12.107112   Topic2  -4.5264   1.3371
253           mumban    4.551020    5.162021   Topic2  -5.3895   1.3264
192            kotak    9.814800   11.153798   Topic2  -4.6209   1.3245
145          kerisik   15.768619   17.937107   Topic2  -4.1468   1.3236
118          sekawan    3.679714    4.280539   Topic2  -5.6020   1.3012
195       dimasukkan    3.643568    4.272403   Topic2  -5.6119   1.2932
142            gulai   12.563802   14.823336   Topic2  -4.3740   1.2870
117           rempah   30.062918   35.597586   Topic2  -3.5015   1.2834
169             kari   12.505710   14.828501   Topic2  -4.3787   1.2821
948            chops    2.792667    3.392159   Topic2  -5.8778   1.2580
200       disediakan    2.681747    3.362770   Topic2  -5.9184   1.2261
197          masakan    1.904309    2.503506   Topic2  -6.2607   1.1789
194          diikuti    1.904202    2.503481   Topic2  -6.2608   1.1788
951            fresh    1.904140    2.503469   Topic2  -6.2608   1.1788
227          belajar    1.904104    2.503458   Topic2  -6.2608   1.1788
682            maggi    1.903902    2.503567   Topic2  -6.2609   1.1786
260       kekuningan    1.903540    2.503452   Topic2  -6.2611   1.1785
120           saderi    1.902853    2.503214   Topic2  -6.2615   1.1782
111          kawalan    1.902683    2.503179   Topic2  -6.2616   1.1781
110         perintah    1.902556    2.503157   Topic2  -6.2616   1.1781
112       pergerakan    1.901724    2.502990   Topic2  -6.2621   1.1777
232          saudara    1.900929    2.502134   Topic2  -6.2625   1.1776
243              ubi    5.364708    7.080486   Topic2  -5.2250   1.1749
202          kerutuk    6.574628    8.967414   Topic2  -5.0216   1.1420
9             keping   23.083817   32.835436   Topic2  -3.7657   1.1000
144           santan   18.474930   28.414775   Topic2  -3.9884   1.0219
146             asam   21.658217   33.962955   Topic2  -3.8295   1.0025
66             empuk    5.291991    8.342393   Topic2  -5.2386   0.9973
65            daging   34.764927   55.776802   Topic2  -3.3562   0.9797
34             halia   22.766578   39.294090   Topic2  -3.7795   0.9066
16              kayu   12.883342   21.410262   Topic2  -4.3489   0.9445
51              gula   32.121135   63.781785   Topic2  -3.4353   0.7665
10           kambing   18.487414   34.851070   Topic2  -3.9877   0.8184
222             jawa    7.105162   11.589470   Topic2  -4.9440   0.9631
123             ulas   21.079345   43.458642   Topic2  -3.8565   0.7289
14            lawang   10.354323   18.765652   Topic2  -4.5674   0.8578
55             hiris   23.451963   54.069595   Topic2  -3.7499   0.6171
28            bawang   49.185989  135.366005   Topic2  -3.0092   0.4400
17             manis   13.388912   29.595323   Topic2  -4.3104   0.6592
26             putih   20.208023   52.061056   Topic2  -3.8988   0.5061
50             garam   26.556915   78.658797   Topic2  -3.6255   0.3666
122            merah   17.736742   52.230170   Topic2  -4.0292   0.3724
131            tumis   11.051101   26.745292   Topic2  -4.5023   0.5686
13             bunga   10.231386   25.641472   Topic2  -4.5794   0.5337
15              inci   11.593527   32.428044   Topic2  -4.4544   0.4238
63               air   13.554984   51.122780   Topic2  -4.2981   0.1249
2              layan    9.027579   22.333179   Topic2  -4.7046   0.5466
130         panaskan    7.770642   18.287026   Topic2  -4.8545   0.5966
18              biji   10.991264   82.422873   Topic2  -4.5077  -0.5623
23            serbuk    7.923649   42.687430   Topic2  -4.8350  -0.2316
598            pucuk    3.687652    4.312329   Topic3  -4.6192   2.2766
687           bunjut    2.253562    2.877721   Topic3  -5.1116   2.1886
126              sup   10.116172   13.995562   Topic3  -3.6100   2.1085
406          lempeng    1.536879    2.160483   Topic3  -5.4944   2.0925
562             step    1.536703    2.160521   Topic3  -5.4945   2.0924
424        dinikmati    1.536557    2.160563   Topic3  -5.4946   2.0923
603           airnya    1.536548    2.160566   Topic3  -5.4946   2.0923
339       menyambung    1.536879    2.680580   Topic3  -5.4944   1.8768
675         danialla    0.819669    1.443273   Topic3  -6.1230   1.8673
676          menukar    0.819669    1.443273   Topic3  -6.1230   1.8673
680         petronas    0.819669    1.443273   Topic3  -6.1230   1.8673
681             rusa    0.819669    1.443273   Topic3  -6.1230   1.8673
678        rombongan    0.819669    1.443273   Topic3  -6.1230   1.8673
674          sempena    0.819669    1.443273   Topic3  -6.1230   1.8673
341          setakat    0.819669    1.443273   Topic3  -6.1230   1.8673
677       pernikahan    0.819669    1.443273   Topic3  -6.1230   1.8673
407          dicicah    0.819669    1.443272   Topic3  -6.1230   1.8673
679          stesyen    0.819669    1.443272   Topic3  -6.1230   1.8673
405            order    0.819669    1.443273   Topic3  -6.1230   1.8673
340       terengganu    0.819669    1.443273   Topic3  -6.1230   1.8673
898         melontar    0.819669    1.443273   Topic3  -6.1230   1.8673
899         bercukur    0.819669    1.443273   Topic3  -6.1230   1.8673
900         mencukur    0.819669    1.443273   Topic3  -6.1230   1.8673
901            botak    0.819669    1.443273   Topic3  -6.1230   1.8673
902        kepalanya    0.819669    1.443273   Topic3  -6.1230   1.8673
810        tengahari    0.819668    1.443273   Topic3  -6.1230   1.8673
811          sarapan    0.819668    1.443273   Topic3  -6.1230   1.8673
563          layannn    0.819599    1.443286   Topic3  -6.1231   1.8672
558         anakanda    0.819587    1.443288   Topic3  -6.1231   1.8672
559         mengupas    0.819585    1.443290   Topic3  -6.1231   1.8672
128           periuk    2.969728    5.591812   Topic3  -4.8357   1.8003
443            tauhu    2.254703    4.227539   Topic3  -5.1111   1.8045
239           kelapa    2.970870    6.260851   Topic3  -4.8353   1.6876
378            nipis    2.253176    4.726157   Topic3  -5.1118   1.6923
600            parut    1.536564    3.049254   Topic3  -5.4946   1.7478
364            bilis    2.253702    4.873384   Topic3  -5.1116   1.6619
216            entri    3.689078    8.892328   Topic3  -4.6188   1.5533
541          diperah    1.536574    3.100068   Topic3  -5.4946   1.7312
53            goreng    8.135299   25.807015   Topic3  -3.8279   1.2787
82             tabur    4.256619   11.904728   Topic3  -4.4757   1.4046
218            kicap    2.253273    5.618604   Topic3  -5.1118   1.5194
250            rujuk    1.536796    3.369224   Topic3  -5.4945   1.6481
136            sedia    3.686598   11.109589   Topic3  -4.6194   1.3300
40             telur    4.405505   14.408274   Topic3  -4.4413   1.2482
449        ketepikan    2.814683    8.088302   Topic3  -4.8893   1.3775
262          mangkuk    2.253763    5.997377   Topic3  -5.1116   1.4544
124             lada    3.558138   11.755881   Topic3  -4.6549   1.2380
33            tumbuk    4.468637   16.627441   Topic3  -4.4271   1.1191
141            lembu    2.695479    8.213559   Topic3  -4.9326   1.3189
188             hati    2.672479    8.195765   Topic3  -4.9411   1.3125
417             kiub    1.536672    3.774870   Topic3  -5.4945   1.5344
28            bawang   15.307724  135.366005   Topic3  -3.1958   0.2535
122            merah    6.955479   52.230170   Topic3  -3.9846   0.4170
55             hiris    6.521290   54.069595   Topic3  -4.0491   0.3179
123             ulas    5.356782   43.458642   Topic3  -4.2458   0.3397
11            tulang    2.880039   13.344223   Topic3  -4.8663   0.8998
54              daun    5.014184   57.479561   Topic3  -4.3119  -0.0061
50             garam    4.998355   78.658797   Topic3  -4.3150  -0.3229
26             putih    4.329927   52.061056   Topic3  -4.4586  -0.0538
125            hitam    2.558304   10.943031   Topic3  -4.9848   0.9797
56              cili    4.146413   55.128870   Topic3  -4.5019  -0.1543
18              biji    3.939558   82.422873   Topic3  -4.5531  -0.6077
51              gula    2.937375   63.781785   Topic3  -4.8466  -0.6448
130         panaskan    2.357940   18.287026   Topic3  -5.0664   0.3847
2              layan    2.347197   22.333179   Topic3  -5.0709   0.1803
131            tumis    2.275772   26.745292   Topic3  -5.1018  -0.0309
139              mee    6.983912    8.330347   Topic4  -3.8284   2.4089
714            talam    1.475512    2.103311   Topic4  -5.3830   2.2307
698          tinggal    1.475499    2.103303   Topic4  -5.3830   2.2307
586           sardin    1.475475    2.103327   Topic4  -5.3831   2.2307
387           baking    1.475458    2.103372   Topic4  -5.3831   2.2306
751         jemputan    1.475427    2.103329   Topic4  -5.3831   2.2306
594             bone    1.475418    2.103329   Topic4  -5.3831   2.2306
597              sum    1.475413    2.103329   Topic4  -5.3831   2.2306
750              kad    1.475342    2.103333   Topic4  -5.3832   2.2306
286              teh    1.475247    2.103420   Topic4  -5.3832   2.2305
303             kuih    1.475235    2.103412   Topic4  -5.3832   2.2305
292           bingka    1.475231    2.103425   Topic4  -5.3832   2.2305
327            datin    1.475204    2.103411   Topic4  -5.3832   2.2305
724        persiapan    1.470483    2.103534   Topic4  -5.3865   2.2272
584            stick    2.164029    3.680761   Topic4  -5.0001   2.0541
191          kampung    3.541191    6.224617   Topic4  -4.5076   2.0212
391           pisang    1.475417    2.623486   Topic4  -5.3831   2.0097
941           dituju    0.787005    1.414691   Topic4  -6.0116   1.9988
942       tersenarai    0.787005    1.414691   Topic4  -6.0116   1.9988
943             list    0.787005    1.414691   Topic4  -6.0116   1.9988
944         perjalan    0.787004    1.414691   Topic4  -6.0116   1.9988
689       dijanjikan    0.787004    1.414691   Topic4  -6.0116   1.9988
696         dibangku    0.786965    1.414687   Topic4  -6.0116   1.9987
695      menyukarkan    0.786962    1.414685   Topic4  -6.0116   1.9987
697          sekolah    0.786955    1.414686   Topic4  -6.0116   1.9987
694        melambung    0.786955    1.414686   Topic4  -6.0116   1.9987
718             boko    0.786955    1.414686   Topic4  -6.0116   1.9987
717              aka    0.786954    1.414686   Topic4  -6.0116   1.9987
709          mengaku    0.786953    1.414686   Topic4  -6.0116   1.9987
711       mengkagumi    0.786953    1.414685   Topic4  -6.0116   1.9987
314             arab    1.475253    2.778262   Topic4  -5.3832   1.9522
283         panggang    1.475286    2.992133   Topic4  -5.3832   1.8781
32              labu    4.120332   11.281673   Topic4  -4.3561   1.5780
218            kicap    2.164172    5.618604   Topic4  -5.0000   1.6312
361         kangkung    1.475569    3.410187   Topic4  -5.3830   1.7475
157             acar    1.475278    3.982390   Topic4  -5.3832   1.5922
426            udang    1.475439    4.170317   Topic4  -5.3831   1.5462
2              layan    3.540957   22.333179   Topic4  -4.5076   0.7435
3             gambar    2.163918    9.367934   Topic4  -5.0001   1.1198
396            tuang    1.475414    4.582250   Topic4  -5.3831   1.4520
393             gram    1.475388    4.597943   Topic4  -5.3831   1.4485
335         berjumpa    1.475466    4.657253   Topic4  -5.3831   1.4358
246          dihiris    2.191253   10.004104   Topic4  -4.9876   1.0667
51              gula    3.541684   63.781785   Topic4  -4.5074  -0.3056
41             rebus    2.164515   16.835246   Topic4  -4.9998   0.5339
122            merah    2.866136   52.230170   Topic4  -4.7191  -0.3175
56              cili    2.578687   55.128870   Topic4  -4.8248  -0.4772
121            kisar    2.164403   30.023261   Topic4  -4.9999  -0.0446
144           santan    2.010169   28.414775   Topic4  -5.0738  -0.0635
33            tumbuk    1.733484   16.627441   Topic4  -5.2219   0.3243
50             garam    1.575752   78.658797   Topic4  -5.3173  -1.3252
18              biji    1.536148   82.422873   Topic4  -5.3428  -1.3974
28            bawang    1.541019  135.366005   Topic4  -5.3396  -1.8903
123             ulas    1.476524   43.458642   Topic4  -5.3824  -0.7969
131            tumis    1.476102   26.745292   Topic4  -5.3826  -0.3117
19              buah    1.475789   24.315560   Topic4  -5.3828  -0.2167
10           kambing    1.475784   34.851070   Topic4  -5.3829  -0.5767
116          mencuba    1.475605    9.786245   Topic4  -5.3830   0.6933
71              nasi    1.475603   35.521902   Topic4  -5.3830  -0.5959
100          selamat    1.475600   11.781075   Topic4  -5.3830   0.5078
280             kuah    1.475596   11.397423   Topic4  -5.3830   0.5409

Topic: 1
daging, kunyit, garam, bawang, separuh, kering, putih, hiris, panas, rendang, hati, air, ulas, cili, serbuk, klik, sambal, itik, paru, lupa, kisar, kerutuk, batang, tabur, kerisik, nasi, serai, dihiris, nak, hidup

Topic: 2
air, garam, abang, asam, manis, biji, lembu, lupa, serbuk, arwah, ingatan, arahan, perbanyakkan, kunyit, ubi, keledek, ditumis, penyediaan, tuang, kampung, kelantan, gula, daging, bunga, cili, limau, rebus, padi, kambing, rebusan

Topic: 3
bawang, sup, goreng, merah, hiris, ulas, daun, garam, tumbuk, telur, putih, tabur, cili, biji, entri, pucuk, sedia, lada, kelapa, periuk, gula, tulang, ketepikan, lembu, hati, hitam, panaskan, layan, tumis, tauhu

Topic: 4
mee, labu, gula, kampung, layan, merah, cili, dihiris, rebus, kisar, kicap, stick, gambar, santan, tumbuk, garam, bawang, biji, ulas, tumis, buah, kambing, mencuba, nasi, selamat, kuah, kangkung, entri, talam, tinggal

Topic: 5
bawang, biji, daun, cili, ayam, garam, serbuk, tomato, nasi, air, putih, merah, ketumbar, kunyit, hiris, kering, gula, sos, tangkai, lapisan, buah, kisar, inci, goreng, halia, dadu, daging, hijau, bunga, manis

Topic: 6
bawang, daging, gula, rempah, garam, hiris, keping, halia, asam, ulas, putih, kambing, santan, merah, kerisik, air, manis, kayu, gulai, kari, inci, tumis, biji, kawah, lawang, bunga, kotak, layan, serbuk, panaskan

Topic: 7
gula, biji, klik, epal, perbanyakkan, batang, inci, oven, cream, membaca, berkorban, keperangan, kulit, telur, kisar, air, keping, kacang, rendam, ayam, hirisan, keluarkan, bakar, tepung, nenas, jus, ais, kekacang, putar, tart

[(0,
  '0.021*"daging" + 0.020*"kunyit" + 0.018*"garam" + 0.016*"bawang" + 0.012*"separuh" + 0.012*"kering" + 0.011*"putih" + 0.010*"hiris" + 0.010*"panas" + 0.009*"rendang"'),
 (1,
  '0.046*"air" + 0.015*"garam" + 0.011*"abang" + 0.008*"asam" + 0.008*"manis" + 0.007*"biji" + 0.007*"lembu" + 0.007*"lupa" + 0.007*"serbuk" + 0.007*"arwah"'),
 (2,
  '0.041*"bawang" + 0.027*"sup" + 0.022*"goreng" + 0.019*"merah" + 0.017*"hiris" + 0.014*"ulas" + 0.013*"daun" + 0.013*"garam" + 0.012*"tumbuk" + 0.012*"telur"'),
 (3,
  '0.022*"mee" + 0.013*"labu" + 0.011*"gula" + 0.011*"kampung" + 0.011*"layan" + 0.009*"merah" + 0.008*"cili" + 0.007*"dihiris" + 0.007*"rebus" + 0.007*"kisar"'),
 (4,
  '0.035*"bawang" + 0.033*"biji" + 0.025*"daun" + 0.024*"cili" + 0.022*"ayam" + 0.021*"garam" + 0.017*"serbuk" + 0.017*"tomato" + 0.015*"nasi" + 0.013*"air"'),
 (5,
  '0.049*"bawang" + 0.035*"daging" + 0.032*"gula" + 0.030*"rempah" + 0.027*"garam" + 0.024*"hiris" + 0.023*"keping" + 0.023*"halia" + 0.022*"asam" + 0.021*"ulas"'),
 (6,
  '0.015*"gula" + 0.013*"biji" + 0.010*"klik" + 0.009*"epal" + 0.009*"perbanyakkan" + 0.008*"batang" + 0.007*"inci" + 0.007*"oven" + 0.007*"cream" + 0.007*"membaca"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
kambingProb = make_dictionary_terms_prob(ldamodel, id_map, d)
kambingProb["bawang"] #probabilitas kata bawang pada setiap topik

[(0, 0.020178424),
 (1, 0.054989588),
 (2, 0.031142846),
 (3, 0.03367496),
 (4, 0.01622466),
 (5, 0.812446),
 (6, 0.03134356)]

## Wordnet

In [ ]:
kambingWN = dfWordnet.copy()

kambingWN["Synonym_clean"] = cleanWN_Synonym(kambingWN["Synonym"])
kambingWN["Hypernim_clean"] = cleanWN(kambingWN["Hypernim"])
kambingWN["Hyponim_clean"] = cleanWN(kambingWN["Hyponim"])
kambingWN

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,daging,Synset('fiber.n.05'),[Synset('fabric.n.01')],[],a leatherlike material made by compressing lay...,fiber,[fabric],None
1,1,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
2,1,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
3,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
4,1,separuh,Synset('partially.r.01'),[],[],in part; in some degree; not wholly,partially,None,None
5,1,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
6,1,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
7,1,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
8,1,panas,Synset('warm.v.02'),[Synset('change.v.01')],[Synset('chafe.v.06')],make warm or warmer,warm,[change],[chafe]
9,1,rendang,Synset('shady.s.04'),[],[],filled with shade,shady,None,None
10,1,hati,Synset('heart.n.06'),[Synset('disposition.n.01')],[],an inclination or tendency of a certain kind,heart,[disposition],None
11,1,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
12,1,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
13,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
14,1,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
15,1,klik,Synset('snap.v.10'),[Synset('move.v.03')],[],cause to make a snapping sound,snap,[move],None
16,1,sambal,None,None,None,None,None,None,None
17,1,itik,Synset('duck.n.01'),[Synset('anseriform_bird.n.01')],"[Synset('black_duck.n.01'), Synset('bufflehead...",small wild or domesticated web-footed broad-bi...,duck,[anseriform_bird],"[black_duck, bufflehead, canvasback, dabbling_..."
18,1,paru,None,None,None,None,None,None,None
19,1,lupa,Synset('forget.v.02'),[],[Synset('slip.v.10')],be unable to remember,forget,None,[slip]
20,1,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
21,1,kerutuk,None,None,None,None,None,None,None
22,1,batang,Synset('bar.n.03'),[Synset('implement.n.01')],"[Synset('belaying_pin.n.01'), Synset('bolt.n.0...",a rigid piece of metal or wood; usually used a...,bar,[implement],"[belaying_pin, bolt, bolt, carpenter's_level, ..."
23,1,tabur,None,None,None,None,None,None,None
24,1,kerisik,Synset('gravel.n.01'),[Synset('rock.n.02')],"[Synset('ballast.n.02'), Synset('bank_gravel.n...",rock fragments and pebbles,gravel,[rock],"[ballast, bank_gravel, shingle]"
25,1,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
26,1,serai,Synset('lemongrass.n.02'),[Synset('grass.n.01')],[],a tropical grass native to India and Sri Lanka,lemongrass,[grass],None
27,1,dihiris,None,None,None,None,None,None,None
28,1,nak,Synset('cub.n.02'),[Synset('male_child.n.01')],[],a male child (a familiar term of address to a ...,cub,[male_child],None
29,1,hidup,Synset('life.n.10'),[Synset('living_thing.n.01')],[Synset('wildlife.n.01')],living things collectively,life,[living_thing],[wildlife]
30,2,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
31,2,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
32,2,abang,Synset('beloved.n.01'),[Synset('lover.n.01')],[],a beloved person; used as terms of endearment,beloved,[lover],None
33,2,asam,Synset('sourly.r.01'),[],[],in a sour manner,sourly,None,None
34,2,manis,Synset('attractive.a.01'),[],[],pleasing to the eye or mind especially through...,attractive,None,None
35,2,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
36,2,lembu,Synset('cow.n.02'),[Synset('placental.n.01')],[],mature female of mammals of which the male is ...,cow,[placental],None
37,2,lupa,Synset('forget.v.02'),[],[Synset('slip.v.10')],be unable to remember,forget,None,[slip]
38,2,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
39,2,arwah,Synset('die.v.01'),[Synset('change_state.v.01')],"[Synset('abort.v.02'), Synset('buy_it.v.01'), ...",pass from physical life and lose all bodily at...,die,[change_state],"[abort, buy_it, drown, fall, predecease, starv..."
40,2,ingatan,Synset('memory.n.04'),"[Synset('hardware.n.03'), Synset('memory_devic...","[Synset('non-volatile_storage.n.01'), Synset('...",an electronic memory device,memory,"[hardware, memory_device]","[non-volatile_storage, read-only_memory, real_..."
41,2,arahan,Synset('directing.s.01'),[],[],showing the way by conducting or leading; impo...,directing,None,None
42,2,perbanyakkan,None,None,None,None,None,None,None
43,2,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
44,2,ubi,Synset('beet.n.02'),[Synset('root_vegetable.n.01')],"[Synset('mangel-wurzel.n.02'), Synset('sugar_b...",round red root vegetable,beet,[root_vegetable],"[mangel-wurzel, sugar_beet]"
45,2,keledek,Synset('sweet_potato.n.01'),[Synset('morning_glory.n.01')],[],pantropical vine widely cultivated in several ...,sweet_potato,[morning_glory],None
46,2,ditumis,None,None,None,None,None,None,None
47,2,penyediaan,None,None,None,None,None,None,None
48,2,tuang,Synset('pour.v.01'),[Synset('move.v.02')],"[Synset('decant.v.01'), Synset('dribble.v.02')...",cause to run,pour,[move],"[decant, dribble, effuse, spill, transfuse]"
49,2,kampung,Synset('rural.a.01'),[],[],living in or characteristic of farming or coun...,rural,None,None
50,2,kelantan,None,None,None,None,None,None,None
51,2,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
52,2,daging,Synset('fiber.n.05'),[Synset('fabric.n.01')],[],a leatherlike material made by compressing lay...,fiber,[fabric],None
53,2,bunga,Synset('bloom.v.01'),[Synset('develop.v.10')],[Synset('effloresce.v.01')],produce or yield flowers,bloom,[develop],[effloresce]
54,2,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
55,2,limau,Synset('orange.n.01'),[Synset('citrus.n.01')],"[Synset('bitter_orange.n.02'), Synset('sweet_o...",round yellow to orange fruit of any of several...,orange,[citrus],"[bitter_orange, sweet_orange, temple_orange]"
56,2,rebus,Synset('boil.v.01'),[Synset('change_state.v.01')],[Synset('boil_over.v.01')],come to the boiling point and change from a li...,boil,[change_state],[boil_over]
57,2,padi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
58,2,kambing,Synset('sheep.n.01'),[Synset('bovid.n.01')],"[Synset('black_sheep.n.02'), Synset('domestic_...",woolly usually horned ruminant mammal related ...,sheep,[bovid],"[black_sheep, domestic_sheep, ewe, ram, wether]"
59,2,rebusan,Synset('thyme.n.02'),[Synset('herb.n.02')],[],leaves can be used as seasoning for almost any...,thyme,[herb],None
60,3,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
61,3,sup,Synset('soup.n.01'),[Synset('dish.n.02')],"[Synset('alphabet_soup.n.02'), Synset('bisque....",liquid food especially of meat or fish or vege...,soup,[dish],"[alphabet_soup, bisque, borsch, broth, broth, ..."
62,3,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
63,3,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
64,3,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
65,3,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
66,3,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
67,3,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
68,3,tumbuk,Synset('crushed.s.01'),[],[],treated so as to have a permanently wrinkled a...,crushed,None,None
69,3,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
70,3,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
71,3,tabur,None,None,None,None,None,None,None
72,3,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
73,3,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
74,3,entri,None,None,None,None,None,None,None
75,3,pucuk,Synset('shoot.v.19'),[Synset('grow.v.03')],[],"produce buds, branches, or germinate",shoot,[grow],None
76,3,sedia,Synset('fix.v.12'),[Synset('change.v.01')],"[Synset('brace.v.01'), Synset('cram.v.04'), Sy...",make ready or suitable or equip in advance for...,fix,[change],"[brace, cram, cultivate, fix, mount, precondit..."
77,3,lada,Synset('ratatouille.n.01'),[Synset('stew.n.02')],[],"a vegetable stew; usually made with tomatoes, ...",ratatouille,[stew],None
78,3,kelapa,Synset('coconut.n.02'),[Synset('edible_nut.n.01')],[],large hard-shelled oval nut with a fibrous hus...,coconut,[edible_nut],None
79,3,periuk,Synset('pan.n.01'),[Synset('cooking_utensil.n.01')],"[Synset('dripping_pan.n.01'), Synset('frying_p...",cooking utensil consisting of a wide metal vessel,pan,[cooking_utensil],"[dripping_pan, frying_pan, omelet_pan, patty-p..."
80,3,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
81,3,tulang,Synset('quill.n.04'),[Synset('rib.n.05')],[],the hollow spine of a feather,quill,[rib],None
82,3,ketepikan,None,None,None,None,None,None,None
83,3,lembu,Synset('cow.n.02'),[Synset('placental.n.01')],[],mature female of mammals of which the male is ...,cow,[placental],None
84,3,hati,Synset('heart.n.06'),[Synset('disposition.n.01')],[],an inclination or tendency of a certain kind,heart,[disposition],None
85,3,hitam,Synset('dark.s.03'),[],[],brunet (used of hair or skin or eyes),dark,None,None
86,3,panaskan,None,None,None,None,None,None,None
87,3,layan,Synset('listen.v.01'),[Synset('perceive.v.01')],"[Synset('attend.v.05'), Synset('hark.v.01'), S...",hear with intention,listen,[perceive],"[attend, hark, hear_out, listen_in, listen_in]"
88,3,tumis,None,None,None,None,None,None,None
89,3,tauhu,Synset('bean_curd.n.01'),[Synset('curd.n.01')],[],cheeselike food made of curdled soybean milk,bean_curd,[curd],None
90,4,mee,None,None,None,None,None,None,None
91,4,labu,Synset('gourd.n.01'),[Synset('bottle.n.01')],[],bottle made from the dried shell of a bottle g...,gourd,[bottle],None
92,4,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
93,4,kampung,Synset('rural.a.01'),[],[],living in or characteristic of farming or coun...,rural,None,None
94,4,layan,Synset('listen.v.01'),[Synset('perceive.v.01')],"[Synset('attend.v.05'), Synset('hark.v.01'), S...",hear with intention,listen,[perceive],"[attend, hark, hear_out, listen_in, listen_in]"
95,4,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
96,4,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
97,4,dihiris,None,None,None,None,None,None,None
98,4,rebus,Synset('boil.v.01'),[Synset('change_state.v.01')],[Synset('boil_over.v.01')],come to the boiling point and change from a li...,boil,[change_state],[boil_over]
99,4,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
100,4,kicap,Synset('soy_sauce.n.01'),[Synset('condiment.n.01')],[],thin sauce made of fermented soy beans,soy_sauce,[condiment],None
101,4,stick,None,None,None,None,None,None,None
102,4,gambar,Synset('frame.n.02'),[Synset('photograph.n.01')],[],a single one of a series of still transparent ...,frame,[photograph],None
103,4,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
104,4,tumbuk,Synset('crushed.s.01'),[],[],treated so as to have a permanently wrinkled a...,crushed,None,None
105,4,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
106,4,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
107,4,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
108,4,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
109,4,tumis,None,None,None,None,None,None,None
110,4,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
111,4,kambing,Synset('sheep.n.01'),[Synset('bovid.n.01')],"[Synset('black_sheep.n.02'), Synset('domestic_...",woolly usually horned ruminant mammal related ...,sheep,[bovid],"[black_sheep, domestic_sheep, ewe, ram, wether]"
112,4,mencuba,Synset('try_on.v.01'),[Synset('wear.v.09')],[],put on a garment in order to see whether it fi...,try_on,[wear],None
113,4,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
114,4,selamat,Synset('redemption.n.01'),[Synset('rescue.n.01')],"[Synset('absolution.n.02'), Synset('conversion...",(theology) the act of delivering from sin or s...,redemption,[rescue],"[absolution, conversion, expiation]"
115,4,kuah,Synset('dressing.n.04'),[Synset('cloth_covering.n.01')],"[Synset('bandage.n.01'), Synset('compress.n.01...",a cloth covering for a wound or sore,dressing,[cloth_covering],"[bandage, compress, poultice, surgical_dressing]"
116,4,kangkung,None,None,None,None,None,None,None
117,4,entri,None,None,None,None,None,None,None
118,4,talam,Synset('tray.n.01'),[Synset('receptacle.n.01')],"[Synset('alms_dish.n.01'), Synset('cafeteria_t...",an open receptacle for holding or displaying o...,tray,[receptacle],"[alms_dish, cafeteria_tray, cheeseboard, icetr..."
119,4,tinggal,Synset('departure.n.01'),[Synset('act.n.02')],"[Synset('boarding.n.01'), Synset('breaking_awa...",the act of departing,departure,[act],"[boarding, breaking_away, disappearance, dispa..."
120,5,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
121,5,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
122,5,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
123,5,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
124,5,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
125,5,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
126,5,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
127,5,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
128,5,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
129,5,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
130,5,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
131,5,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
132,5,ketumbar,Synset('coriander.n.02'),[Synset('flavorer.n.01')],[],dried coriander seeds used whole or ground,coriander,[flavorer],None
133,5,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
134,5,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
135,5,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
136,5,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None

### Make Ontology

In [ ]:
# Make Ontology
azieKambingOnto = get_ontology("http://test.org/azieKambing.owl")
makeOntology(azieKambingOnto, kambingWN)
azieKambingOnto.save(file = "azieKambing.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1i4ibWRh3bkxlOW72pJfF1g9rLER-4gbt"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1i4ibWRh3bkxlOW72pJfF1g9rLER-4gbt
To: /content/AzieKambingFinal.xlsx
100% 16.3k/16.3k [00:00<00:00, 23.3MB/s]

In [ ]:
wiki_kambing = pd.read_excel("AzieKambingFinal.xlsx").iloc[:, 1:]

# Translate
wiki_kambing["Category"] = translate(wiki_kambing["Category"])
wiki_kambing.head()

,Title,Cleaned,Def_IND,Def_MS,Def_ENG,Category
0,Nasi Beriani Kambing Pakistan Yang Memang Supe...,nasi beriani kambing pakistan super duper,Not Found,hidangan nasi campur dari Benua Kecil India sa...,Not Found,"['serealia', 'daging']"
1,Sup Kambing Berempah Yang Sangat Sedap,sup kambing berempah,hidangan sup daging kambing yang lazim ditemuk...,sup kambing yang biasa ditemui dalam masakan I...,Southeast Asian mutton soup,['daging']
2,Gulai Kambing Kelantan,gulai kambing kelantan,masakan berbahan baku daging ayam bumbunya yan...,masakan mengandungi daging,type of food containing rich common name to re...,['daging']
3,Beriani Daging Kambing,beriani daging kambing,Not Found,Not Found,Not Found,['daging']
4,Gulai Kampung Daging Kambing,gulai kampung daging kambing,Not Found,gulai itik khas dari Aceh gulai itik yang dibu...,type of food containing rich common name to re...,['daging']

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_kambing[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
kambingTabel_new = tabel_1981.copy()
kambingTabel_new["correct_category"] = all_cat
kambingTabel_new["suggestion"] = all_suggestion

# Export Result to File
kambingTabel_new.to_excel("kambingTabel_Result.xlsx")
kambingTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
kambingTabel_new = concatListInColumn(kambingTabel_new)
kambingTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, kambingTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_kambing.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
kambingWiki_new = wiki_df.copy()
kambingWiki_new["suggest"] = all_cat

# Export Result to file
kambingWiki_new.to_excel("kambingWiki_Result.xlsx")
kambingWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieKambingOntoWiki = get_ontology("http://test.org/azieKambing_onto_wiki.owl")
makeOntology_wiki(azieKambingOntoWiki, kambingWiki_new)
azieKambingOntoWiki.save(file = "azieKambing_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = kambingWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
kambingWN_new = listToDataframe(changesList, tableWordnet)
kambingWN_new.to_excel("kambingWN_Result.xlsx")
kambingWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Tempe

In [ ]:
!gdown --id "1hXhZXEAiqEeWn5_0SiC3JLTnQiMSDYb3"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hXhZXEAiqEeWn5_0SiC3JLTnQiMSDYb3
To: /content/aziekitchen-tempe.jl
100% 195k/195k [00:00<00:00, 89.7MB/s]

In [ ]:
tempe=pd.read_json(r'/content/aziekitchen-tempe.jl', lines = True)
tempe.to_pickle(r'/content/raw_df.pkl')
tempe = pre_cleaning_text(tempe, threshold=20)
# tempe["cleaned_description"] = cleaning_text(tempe["page_description"])
# ingredients_all = tempe["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Tempe

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = tempe.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
1      0.199445 -0.050918       1        1  40.551482
2     -0.082372 -0.162198       2        1  26.668087
6     -0.099134 -0.004899       3        1   9.610349
3      0.003299  0.044380       4        1   9.437549
0      0.037760  0.009881       5        1   7.900587
4     -0.018298  0.109559       6        1   5.804739
5     -0.040700  0.054195       7        1   0.027207, topic_info=              Term       Freq      Total Category  logprob  loglift
66           bilis  27.000000  27.000000  Default  30.0000  30.0000
65            ikan  28.000000  28.000000  Default  29.0000  29.0000
41          bawang  34.000000  34.000000  Default  28.0000  28.0000
132         batang  30.000000  30.000000  Default  27.0000  27.0000
126         kacang  22.000000  22.000000  Default  26.0000  26.0000
144          udang  20.000000  20.000000  Default  25.0000  25.0000
136         rendam  21.000000  21.000000  Default  24.0000  24.0000
76            gula  20.000000  20.000000  Default  23.0000  23.0000
145          hidup  17.000000  17.000000  Default  22.0000  22.0000
12           tempe  29.000000  29.000000  Default  21.0000  21.0000
83          garing  11.000000  11.000000  Default  20.0000  20.0000
141          tauhu  15.000000  15.000000  Default  19.0000  19.0000
71           kisar  34.000000  34.000000  Default  18.0000  18.0000
146         santan  21.000000  21.000000  Default  17.0000  17.0000
139           hoon   8.000000   8.000000  Default  16.0000  16.0000
138            soo   8.000000   8.000000  Default  15.0000  15.0000
46          kunyit  15.000000  15.000000  Default  14.0000  14.0000
156          sayur  11.000000  11.000000  Default  13.0000  13.0000
68          keping  26.000000  26.000000  Default  12.0000  12.0000
13          goreng  35.000000  35.000000  Default  11.0000  11.0000
72           merah  36.000000  36.000000  Default  10.0000  10.0000
134         terung  10.000000  10.000000  Default   9.0000   9.0000
45          serbuk   8.000000   8.000000  Default   8.0000   8.0000
142          serai  11.000000  11.000000  Default   7.0000   7.0000
69            cili  36.000000  36.000000  Default   6.0000   6.0000
42           putih  13.000000  13.000000  Default   5.0000   5.0000
60          sambal  14.000000  14.000000  Default   4.0000   4.0000
149           inci  12.000000  12.000000  Default   3.0000   3.0000
133          karot   9.000000   9.000000  Default   2.0000   2.0000
143          ketuk  10.000000  10.000000  Default   1.0000   1.0000
166           kuah   9.275083   9.959489   Topic1  -4.2447   0.8314
136         rendam  19.661497  21.211749   Topic1  -3.4934   0.8267
137           ikat   6.682819   7.222620   Topic1  -4.5725   0.8249
130      sengkuang   6.681123   7.222252   Topic1  -4.5727   0.8247
148          kotak   5.749108   6.285786   Topic1  -4.7230   0.8134
129          kubis   7.276487   8.042498   Topic1  -4.4874   0.8025
173          impit   4.803465   5.346866   Topic1  -4.9027   0.7954
156          sayur  10.214095  11.517409   Topic1  -4.1483   0.7825
135          fucuk   6.270940   7.082051   Topic1  -4.6361   0.7810
126         kacang  19.825752  22.411033   Topic1  -3.4850   0.7800
141          tauhu  13.982218  15.999944   Topic1  -3.8342   0.7678
131          letak   8.568182   9.843717   Topic1  -4.3240   0.7638
70          kering  14.701560  17.219250   Topic1  -3.7841   0.7445
252      kepekatan   2.945747   3.475455   Topic1  -5.3917   0.7372
145          hidup  15.133024  17.869191   Topic1  -3.7552   0.7364
132         batang  25.065669  30.053217   Topic1  -3.2505   0.7211
144          udang  16.374183  20.141708   Topic1  -3.6763   0.6955
162           basi   2.008186   2.537883   Topic1  -5.7748   0.6685
151     sepenuhnya   2.008160   2.537877   Topic1  -5.7748   0.6685
152      tambahkan   2.008151   2.537885   Topic1  -5.7748   0.6685
163          didih   2.008124   2.537864   Topic1  -5.7748   0.6685
161        lontong   2.008116   2.537863   Topic1  -5.7748   0.6685
164          reneh   2.008085   2.537855   Topic1  -5.7748   0.6685
165       asingkan   2.008045   2.537838   Topic1  -5.7749   0.6684
104        secukup   6.208582   7.869155   Topic1  -4.6461   0.6656
175          rebus   4.798853   6.086062   Topic1  -4.9037   0.6650
140           dadu   4.813179   6.235846   Topic1  -4.9007   0.6436
147          pekat   5.249522   6.860923   Topic1  -4.8139   0.6349
134         terung   7.739191  10.281268   Topic1  -4.4257   0.6186
46          kunyit  11.596451  15.808669   Topic1  -4.0213   0.5927
68          keping  19.671669  26.822047   Topic1  -3.4929   0.5926
142          serai   8.675860  11.995801   Topic1  -4.3115   0.5786
133          karot   6.676674   9.303252   Topic1  -4.5734   0.5709
146         santan  14.144136  21.146644   Topic1  -3.8227   0.5004
60          sambal  10.227247  14.909220   Topic1  -4.1470   0.5257
47            biji  28.295736  48.558581   Topic1  -3.1293   0.3625
48           telur   3.853363   5.294002   Topic1  -5.1231   0.5850
13          goreng  16.890922  35.059461   Topic1  -3.6453   0.1723
72           merah  17.269400  36.305361   Topic1  -3.6231   0.1596
71           kisar  14.662990  34.363574   Topic1  -3.7867   0.0509
49           garam  13.127841  30.303215   Topic1  -3.8973   0.0661
69            cili  13.965890  36.948889   Topic1  -3.8354  -0.0703
33           hiris   7.385350  16.867406   Topic1  -4.4725   0.0767
12           tempe   8.661635  29.217804   Topic1  -4.3131  -0.3133
149           inci   6.660214  12.848597   Topic1  -4.5759   0.2455
41          bawang   7.200037  34.779965   Topic1  -4.4979  -0.6724
14          rangup   5.450061   5.986442   Topic2  -4.3573   1.2278
54            gaul   3.674011   4.211723   Topic2  -4.7516   1.1851
83          garing  10.418216  11.996328   Topic2  -3.7094   1.1807
23           pokok   2.788429   3.324760   Topic2  -5.0274   1.1458
116          panas   2.788161   3.324715   Topic2  -5.0275   1.1457
66           bilis  22.794737  27.260968   Topic2  -2.9264   1.1428
103       perlahan   2.776829   3.321691   Topic2  -5.0316   1.1425
65            ikan  22.831802  28.746261   Topic2  -2.9248   1.0913
205            ubi   3.259743   4.126815   Topic2  -4.8713   1.0858
85       ketepikan   1.901208   2.437531   Topic2  -5.4104   1.0732
269          basuh   1.901160   2.437522   Topic2  -5.4105   1.0732
260            dah   1.901139   2.437518   Topic2  -5.4105   1.0732
77        ditumbuk   1.895790   2.436656   Topic2  -5.4133   1.0707
39          tumbuk   3.675541   5.149424   Topic2  -4.7512   0.9845
79            padi   2.788402   4.064921   Topic2  -5.0275   0.9448
3             buah   2.788479   4.068709   Topic2  -5.0274   0.9439
111        mangkuk   3.105845   4.671631   Topic2  -4.9196   0.9135
89           siapp   1.013978   1.550300   Topic2  -6.0390   0.8971
84      berasingan   1.013978   1.550300   Topic2  -6.0390   0.8971
86           blend   1.013978   1.550300   Topic2  -6.0390   0.8971
273       bertahun   1.013978   1.550300   Topic2  -6.0390   0.8971
280        secubit   1.013978   1.550300   Topic2  -6.0390   0.8971
275           baca   1.013978   1.550300   Topic2  -6.0390   0.8971
279           biar   1.013978   1.550300   Topic2  -6.0390   0.8971
284        dihiris   1.013978   1.550300   Topic2  -6.0390   0.8971
285          cover   1.013978   1.550300   Topic2  -6.0390   0.8971
80           mesti   1.013978   1.550300   Topic2  -6.0390   0.8971
274          versi   1.013978   1.550300   Topic2  -6.0390   0.8971
283        lebihan   1.013978   1.550300   Topic2  -6.0390   0.8971
276      pemilihan   1.013978   1.550300   Topic2  -6.0390   0.8971
119           nota   3.668508   5.694183   Topic2  -4.7531   0.8820
100          nipis   4.182544   6.525453   Topic2  -4.6220   0.8769
120     dimasukkan   3.618508   5.684401   Topic2  -4.7669   0.8700
97         mencuba   5.164243   8.375081   Topic2  -4.4112   0.8382
12           tempe  14.612579  29.217804   Topic2  -3.3710   0.6288
13          goreng  16.722351  35.059461   Topic2  -3.2362   0.5814
41          bawang  14.802569  34.779965   Topic2  -3.3581   0.4675
82        digoreng   3.664984   6.960246   Topic2  -4.7541   0.6803
69            cili  14.784602  36.948889   Topic2  -3.3593   0.4058
76            gula   8.452072  20.656640   Topic2  -3.9185   0.4281
73         kentang   6.026025  13.880293   Topic2  -4.2568   0.4873
224           lupa   2.635927   5.010945   Topic2  -5.0837   0.6793
81            asam   3.446901   6.993403   Topic2  -4.8155   0.6142
49           garam  11.085593  30.303215   Topic2  -3.6473   0.3161
42           putih   5.785019  13.893607   Topic2  -4.2977   0.4455
40            ulas   6.978542  18.287254   Topic2  -4.1101   0.3583
71           kisar   8.730232  34.363574   Topic2  -3.8861  -0.0485
47            biji   9.757580  48.558581   Topic2  -3.7749  -0.2830
72           merah   7.878524  36.305361   Topic2  -3.9888  -0.2061
50             air   4.678285  12.859121   Topic2  -4.5100   0.3106
33           hiris   5.053494  16.867406   Topic2  -4.4328   0.1164
58             tos   3.675845   8.898839   Topic2  -4.7511   0.4376
88           tutup   3.372096   7.040069   Topic2  -4.8374   0.5856
68          keping   4.451185  26.822047   Topic2  -4.5598  -0.4744
101          tumis   3.441054  10.592316   Topic2  -4.8171   0.1974
167       ketumbar   1.594088   2.150968   Topic3  -4.5660   2.0427
242          knorr   1.593987   2.150987   Topic3  -4.5661   2.0426
99          simple   1.593613   2.151059   Topic3  -4.5663   2.0424
174   kacangsambal   1.593209   2.151156   Topic3  -4.5665   2.0421
91       keutamaan   1.592320   2.151309   Topic3  -4.5671   2.0414
241         daging   3.081772   4.378995   Topic3  -3.9068   1.9910
169        dimakan   0.850220   1.407012   Topic3  -5.1946   1.8386
171        diratah   0.850220   1.407012   Topic3  -5.1946   1.8386
240     disediakan   0.850143   1.407026   Topic3  -5.1947   1.8385
245    dicampurkan   0.850135   1.407028   Topic3  -5.1947   1.8385
98           lihat   0.849531   1.407144   Topic3  -5.1954   1.8377
178     kekuningan   0.849519   1.407173   Topic3  -5.1954   1.8377
185         duadua   0.849488   1.407176   Topic3  -5.1954   1.8376
95        berhenti   0.849467   1.407157   Topic3  -5.1954   1.8376
180   sayursayuran   0.849466   1.407182   Topic3  -5.1954   1.8376
181          suhun   0.849448   1.407194   Topic3  -5.1955   1.8376
90         sempena   0.849408   1.407168   Topic3  -5.1955   1.8375
93    menghapuskan   0.849392   1.407171   Topic3  -5.1955   1.8375
176          belah   0.849282   1.407241   Topic3  -5.1957   1.8373
94         setahun   0.849241   1.407200   Topic3  -5.1957   1.8373
102          wangi   0.849226   1.407203   Topic3  -5.1957   1.8373
92         muharam   0.849209   1.407206   Topic3  -5.1957   1.8373
177       panaskan   1.593691   2.770047   Topic3  -4.5662   1.7895
186          empuk   1.593695   2.770290   Topic3  -4.5662   1.7894
172      semalaman   1.593102   2.770149   Topic3  -4.5666   1.7891
244          salam   2.337936   4.340934   Topic3  -4.1830   1.7235
234            pes   1.594066   3.389031   Topic3  -4.5660   1.5881
235           jawa   1.594067   3.389105   Topic3  -4.5660   1.5881
45          serbuk   3.617533   8.136489   Topic3  -3.7465   1.5318
182          pucuk   0.849500   2.026154   Topic3  -5.1954   1.4731
228           daun   2.338092   5.700882   Topic3  -4.1830   1.4510
76            gula   5.340767  20.656640   Topic3  -3.3569   0.9897
81            asam   2.337979   6.993403   Topic3  -4.1830   1.2466
71           kisar   5.632983  34.363574   Topic3  -3.3037   0.5340
101          tumis   2.787295  10.592316   Topic3  -4.0072   1.0073
42           putih   3.082315  13.893607   Topic3  -3.9066   0.8366
100          nipis   1.910872   6.525453   Topic3  -4.3847   1.1142
72           merah   4.644610  36.305361   Topic3  -3.4966   0.2861
12           tempe   3.902433  29.217804   Topic3  -3.6707   0.3292
75        opsyenal   1.592872   4.925312   Topic3  -4.5668   1.2135
37          jintan   1.594277   5.202120   Topic3  -4.5659   1.1597
203       lengkuas   1.594211   5.631172   Topic3  -4.5659   1.0804
127  penyediaannya   1.594341   5.633968   Topic3  -4.5658   1.0800
160           gram   1.594395   6.618098   Topic3  -4.5658   0.9190
170           nasi   1.452261   5.937777   Topic3  -4.6592   0.9341
41          bawang   2.147353  34.779965   Topic3  -4.2681  -0.4425
50             air   1.594773  12.859121   Topic3  -4.5656   0.2550
47            biji   2.071477  48.558581   Topic3  -4.3040  -0.8122
146         santan   1.733238  21.146644   Topic3  -4.4823  -0.1592
66           bilis   1.741538  27.260968   Topic3  -4.4775  -0.4084
65            ikan   1.742189  28.746261   Topic3  -4.4772  -0.4610
340            sos   3.065493   3.623458   Topic4  -3.8939   2.1933
308          timun   3.065470   3.623749   Topic4  -3.8940   2.1932
342           cuka   1.585656   2.143287   Topic4  -4.5532   2.0591
338            aji   1.585601   2.143263   Topic4  -4.5532   2.0591
341          tiram   1.585590   2.143252   Topic4  -4.5532   2.0591
301           kena   1.585684   2.143400   Topic4  -4.5531   2.0591
339          hijau   1.585460   2.143341   Topic4  -4.5533   2.0590
337           ekor   0.845690   1.403153   Topic4  -5.1818   1.8541
336         tulang   0.845692   1.403180   Topic4  -5.1818   1.8541
335            sup   0.845666   1.403150   Topic4  -5.1818   1.8541
300    mengaminkan   0.845705   1.403234   Topic4  -5.1817   1.8541
302       pastikan   0.845693   1.403238   Topic4  -5.1818   1.8541
310       diangkat   0.845685   1.403239   Topic4  -5.1818   1.8541
299       mengamin   0.845677   1.403234   Topic4  -5.1818   1.8541
305       perbaiki   0.845676   1.403238   Topic4  -5.1818   1.8541
307        jadikan   0.845675   1.403240   Topic4  -5.1818   1.8541
306   kekeluargaan   0.845666   1.403237   Topic4  -5.1818   1.8541
303           raih   0.845667   1.403243   Topic4  -5.1818   1.8541
298         yusoff   0.845652   1.403243   Topic4  -5.1818   1.8540
304         ukhwah   0.845644   1.403242   Topic4  -5.1818   1.8540
297        zuwairi   0.845642   1.403239   Topic4  -5.1818   1.8540
309        dibuang   0.845637   1.403245   Topic4  -5.1818   1.8540
356        diketuk   0.845451   1.403285   Topic4  -5.1820   1.8538
353           kiub   0.845432   1.403282   Topic4  -5.1821   1.8538
354         sangar   0.845433   1.403287   Topic4  -5.1821   1.8538
359         serong   0.845408   1.403292   Topic4  -5.1821   1.8537
361       caracara   0.845385   1.403295   Topic4  -5.1821   1.8537
355        dititik   0.845380   1.403298   Topic4  -5.1821   1.8537
358           suun   0.845378   1.403300   Topic4  -5.1821   1.8537
360            utk   0.845377   1.403299   Topic4  -5.1821   1.8537
296           jari   1.585082   2.849165   Topic4  -4.5535   1.7741
266         tomato   1.585620   3.030502   Topic4  -4.5532   1.7127
61           kicap   1.585592   3.030471   Topic4  -4.5532   1.7127
200        tangkai   2.325147   6.326315   Topic4  -4.1704   1.3595
243          helai   1.585336   3.593142   Topic4  -4.5534   1.5422
113        menumis   1.555850   3.707052   Topic4  -4.5721   1.4923
251          kulit   2.130007   6.684186   Topic4  -4.2580   1.2169
206          halia   1.584852   4.175532   Topic4  -4.5537   1.3917
47            biji   4.767943  48.558581   Topic4  -3.4522   0.0396
41          bawang   4.025178  34.779965   Topic4  -3.6216   0.2040
46          kunyit   2.731529  15.808669   Topic4  -4.0093   0.6048
40            ulas   2.826193  18.287254   Topic4  -3.9752   0.4932
69            cili   3.847030  36.948889   Topic4  -3.6669   0.0982
49           garam   3.455967  30.303215   Topic4  -3.7741   0.1893
228           daun   1.585114   5.700882   Topic4  -4.5535   1.0805
42           putih   2.215812  13.893607   Topic4  -4.2185   0.5247
62          tengok   1.402902   4.952883   Topic4  -4.6756   1.0990
150       mendidih   1.585752   7.231718   Topic4  -4.5531   0.8431
145          hidup   2.223148  17.869191   Topic4  -4.2152   0.2763
76            gula   2.325932  20.656640   Topic4  -4.1700   0.1766
144          udang   2.189568  20.141708   Topic4  -4.2305   0.1414
33           hiris   1.977147  16.867406   Topic4  -4.3325   0.2167
146         santan   1.879490  21.146644   Topic4  -4.3832  -0.0600
72           merah   2.102922  36.305361   Topic4  -4.2708  -0.4882
71           kisar   1.837219  34.363574   Topic4  -4.4059  -0.5683
149           inci   1.585850  12.848597   Topic4  -4.5530   0.2684
287         talian   1.511075   2.074330   Topic5  -4.4236   2.2214
288          hayat   1.511057   2.074325   Topic5  -4.4236   2.2214
201     santansusu   0.806088   1.368648   Topic5  -5.0520   2.0088
187           esok   0.806032   1.368662   Topic5  -5.0520   2.0088
197       pelajari   0.806008   1.368668   Topic5  -5.0521   2.0087
204       sejemput   0.806008   1.368668   Topic5  -5.0521   2.0087
198            isi   0.806006   1.368669   Topic5  -5.0521   2.0087
207        bergaul   0.805958   1.368682   Topic5  -5.0521   2.0087
193      instagram   0.805953   1.368683   Topic5  -5.0521   2.0087
192       follower   0.805945   1.368684   Topic5  -5.0521   2.0086
289          setia   0.805945   1.368694   Topic5  -5.0521   2.0086
189       kejayaan   0.805939   1.368686   Topic5  -5.0521   2.0086
194       facebook   0.805922   1.368691   Topic5  -5.0522   2.0086
291    kegembiraan   0.805925   1.368701   Topic5  -5.0522   2.0086
294      menyambut   0.805912   1.368704   Topic5  -5.0522   2.0086
286          sibuk   0.805888   1.368714   Topic5  -5.0522   2.0086
290          penuh   0.805888   1.368714   Topic5  -5.0522   2.0086
190    kebahagiaan   0.805874   1.368704   Topic5  -5.0522   2.0085
293       kenangan   0.805876   1.368713   Topic5  -5.0522   2.0085
292     kesyukuran   0.805875   1.368715   Topic5  -5.0522   2.0085
295        ingatan   0.805861   1.368719   Topic5  -5.0522   2.0085
196     memasukkan   0.805852   1.368709   Topic5  -5.0523   2.0085
188      melangkah   0.805832   1.368712   Topic5  -5.0523   2.0085
200        tangkai   2.921072   6.326315   Topic5  -3.7644   1.7655
199          petai   1.510235   3.657339   Topic5  -4.4241   1.6538
203       lengkuas   2.214979   5.631172   Topic5  -4.0412   1.6052
206          halia   1.510509   4.175532   Topic5  -4.4239   1.5214
191     kesempatan   0.805929   2.306188   Topic5  -5.0522   1.4869
139           hoon   2.750528   8.228726   Topic5  -3.8246   1.4424
138            soo   2.749803   8.228758   Topic5  -3.8249   1.4421
37          jintan   1.511097   5.202120   Topic5  -4.4236   1.3020
143          ketuk   2.487126  10.697590   Topic5  -3.9253   1.0793
149           inci   2.466744  12.848597   Topic5  -3.9335   0.8879
133          karot   1.942426   9.303252   Topic5  -4.1725   0.9718
72           merah   3.286095  36.305361   Topic5  -3.6467   0.1360
134         terung   1.911722  10.281268   Topic5  -4.1884   0.8559
146         santan   2.566519  21.146644   Topic5  -3.8938   0.4293
40            ulas   2.296827  18.287254   Topic5  -4.0049   0.4636
142          serai   1.884710  11.995801   Topic5  -4.2026   0.6875
69            cili   2.823894  36.948889   Topic5  -3.7983  -0.0332
132         batang   2.523915  30.053217   Topic5  -3.9106   0.0611
66           bilis   2.372686  27.260968   Topic5  -3.9724   0.0968
41          bawang   2.536918  34.779965   Topic5  -3.9054  -0.0799
65            ikan   2.371131  28.746261   Topic5  -3.9730   0.0431
68          keping   2.150013  26.822047   Topic5  -4.0709   0.0145
73         kentang   1.651968  13.880293   Topic5  -4.3344   0.4097
47            biji   2.374629  48.558581   Topic5  -3.9716  -0.4797
82        digoreng   1.261780   6.960246   Topic5  -4.6039   0.8305

Topic: 1
merah, tangkai, cili, hoon, soo, santan, bawang, batang, ketuk, inci, biji, bilis, ikan, ulas, lengkuas, keping, karot, terung, serai, tempe, kacang, kisar, kentang, jintan, talian, hayat, halia, petai, putih, selamat

Topic: 2
biji, batang, kacang, keping, rendam, merah, goreng, udang, hidup, kering, kisar, santan, tauhu, cili, garam, kunyit, sambal, sayur, kuah, serai, tempe, letak, terung, hiris, kubis, bawang, ikat, sengkuang, karot, inci

Topic: 3
ikan, bilis, goreng, bawang, cili, tempe, garam, garing, biji, kisar, gula, merah, ulas, kentang, putih, rangup, mencuba, hiris, air, keping, nipis, tos, tumbuk, gaul, nota, digoreng, dimasukkan, asam, tumis, tutup

Topic: 4
biji, bawang, cili, garam, sos, timun, ulas, kunyit, gula, tangkai, hidup, putih, udang, kulit, merah, hiris, santan, kisar, inci, mendidih, kena, cuka, tomato, aji, kicap, tiram, hijau, helai, daun, jari

Topic: 5
bawang, sayuran, opsyenal, kisar, gula, putih, suuhun, layu, pes, jawa, biji, udang, sambal, hiris, mendidih, merah, mangkuk, inci, batang, digoreng, asam, sayur, tumis, semalaman, pucuk, limau, bau, rashid, lambat, pasir

Topic: 6
bawang, sos, hiris, biji, ulas, garam, cili, kisar, kicap, tiram, merah, aji, putih, gula, tomato, cuka, inci, mendidih, ikan, bilis, hijau, goreng, sup, lumur, ekor, udang, halia, kunyit, opsyenal, daging

Topic: 7
kisar, gula, merah, tempe, serbuk, putih, daging, tumis, daun, asam, salam, bawang, biji, nipis, ikan, bilis, santan, air, gram, penyediaannya, jintan, lengkuas, ketumbar, jawa, pes, knorr, empuk, panaskan, simple, kacangsambal

[(0,
  '0.026*"merah" + 0.023*"tangkai" + 0.022*"cili" + 0.022*"hoon" + 0.022*"soo" + 0.020*"santan" + 0.020*"bawang" + 0.020*"batang" + 0.020*"ketuk" + 0.020*"inci"'),
 (1,
  '0.044*"biji" + 0.039*"batang" + 0.031*"kacang" + 0.030*"keping" + 0.030*"rendam" + 0.027*"merah" + 0.026*"goreng" + 0.025*"udang" + 0.023*"hidup" + 0.023*"kering"'),
 (2,
  '0.054*"ikan" + 0.054*"bilis" + 0.039*"goreng" + 0.035*"bawang" + 0.035*"cili" + 0.034*"tempe" + 0.026*"garam" + 0.024*"garing" + 0.023*"biji" + 0.021*"kisar"'),
 (3,
  '0.032*"biji" + 0.027*"bawang" + 0.026*"cili" + 0.023*"garam" + 0.020*"sos" + 0.020*"timun" + 0.019*"ulas" + 0.018*"kunyit" + 0.015*"gula" + 0.015*"tangkai"'),
 (4,
  '0.044*"bawang" + 0.021*"sayuran" + 0.020*"opsyenal" + 0.020*"kisar" + 0.018*"gula" + 0.014*"putih" + 0.014*"suuhun" + 0.014*"layu" + 0.014*"pes" + 0.014*"jawa"'),
 (5,
  '0.003*"bawang" + 0.003*"sos" + 0.003*"hiris" + 0.003*"biji" + 0.003*"ulas" + 0.003*"garam" + 0.003*"cili" + 0.003*"kisar" + 0.003*"kicap" + 0.003*"tiram"'),
 (6,
  '0.037*"kisar" + 0.035*"gula" + 0.030*"merah" + 0.025*"tempe" + 0.024*"serbuk" + 0.020*"putih" + 0.020*"daging" + 0.018*"tumis" + 0.015*"daun" + 0.015*"asam"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
tempeProb = make_dictionary_terms_prob(ldamodel, id_map, d)
tempeProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
tempeWN = dfWordnet.copy()

tempeWN["Synonym_clean"] = cleanWN_Synonym(tempeWN["Synonym"])
tempeWN["Hypernim_clean"] = cleanWN(tempeWN["Hypernim"])
tempeWN["Hyponim_clean"] = cleanWN(tempeWN["Hyponim"])
tempeWN

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
1,1,tangkai,Synset('stalk.n.04'),[Synset('pursuit.n.01')],[],the act of following prey stealthily,stalk,[pursuit],None
2,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
3,1,hoon,None,None,None,None,None,None,None
4,1,soo,None,None,None,None,None,None,None
5,1,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
6,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
7,1,batang,Synset('bar.n.03'),[Synset('implement.n.01')],"[Synset('belaying_pin.n.01'), Synset('bolt.n.0...",a rigid piece of metal or wood; usually used a...,bar,[implement],"[belaying_pin, bolt, bolt, carpenter's_level, ..."
8,1,ketuk,Synset('tap.n.08'),[Synset('touch.n.05')],[],a light touch or stroke,tap,[touch],None
9,1,inci,Synset('inch.n.01'),[Synset('linear_unit.n.01')],[],a unit of length equal to one twelfth of a foot,inch,[linear_unit],None
10,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
11,1,bilis,None,None,None,None,None,None,None
12,1,ikan,Synset('fish.n.01'),[Synset('aquatic_vertebrate.n.01')],"[Synset('bony_fish.n.01'), Synset('bottom-feed...",any of various mostly cold-blooded aquatic ver...,fish,[aquatic_vertebrate],"[bony_fish, bottom-feeder, bottom_lurkers, car..."
13,1,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
14,1,lengkuas,Synset('galangal.n.01'),[Synset('ginger.n.01')],[],southeastern Asian perennial with aromatic roots,galangal,[ginger],None
15,1,keping,Synset('piece.n.01'),[Synset('part.n.02')],"[Synset('beam.n.02'), Synset('piece_of_cloth.n...",a separate part of a whole,piece,[part],"[beam, piece_of_cloth, piece_of_leather, scrap..."
16,1,karot,None,None,None,None,None,None,None
17,1,terung,Synset('eggplant.n.01'),[Synset('solanaceous_vegetable.n.01')],[],egg-shaped vegetable having a shiny skin typic...,eggplant,[solanaceous_vegetable],None
18,1,serai,Synset('lemongrass.n.02'),[Synset('grass.n.01')],[],a tropical grass native to India and Sri Lanka,lemongrass,[grass],None
19,1,tempe,None,None,None,None,None,None,None
20,1,kacang,Synset('cinch.n.01'),[Synset('undertaking.n.01')],[Synset('doddle.n.01')],any undertaking that is easy to do,cinch,[undertaking],[doddle]
21,1,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
22,1,kentang,Synset('brunswick_stew.n.01'),[Synset('stew.n.02')],[],spicy southern specialty: chicken (or small ga...,brunswick_stew,[stew],None
23,1,jintan,Synset('caraway.n.01'),[Synset('herb.n.01')],[Synset('whorled_caraway.n.01')],a Eurasian plant with small white flowers yiel...,caraway,[herb],[whorled_caraway]
24,1,talian,Synset('line.n.16'),[Synset('conformity.n.02')],[],acting in conformity,line,[conformity],None
25,1,hayat,Synset('life.n.05'),[Synset('time_period.n.01')],[Synset('afterlife.n.01')],the period during which something is functiona...,life,[time_period],[afterlife]
26,1,halia,Synset('peppery.s.01'),[],[],having the piquant burning taste of peppers,peppery,None,None
27,1,petai,None,None,None,None,None,None,None
28,1,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
29,1,selamat,Synset('redemption.n.01'),[Synset('rescue.n.01')],"[Synset('absolution.n.02'), Synset('conversion...",(theology) the act of delivering from sin or s...,redemption,[rescue],"[absolution, conversion, expiation]"
30,2,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
31,2,batang,Synset('bar.n.03'),[Synset('implement.n.01')],"[Synset('belaying_pin.n.01'), Synset('bolt.n.0...",a rigid piece of metal or wood; usually used a...,bar,[implement],"[belaying_pin, bolt, bolt, carpenter's_level, ..."
32,2,kacang,Synset('cinch.n.01'),[Synset('undertaking.n.01')],[Synset('doddle.n.01')],any undertaking that is easy to do,cinch,[undertaking],[doddle]
33,2,keping,Synset('piece.n.01'),[Synset('part.n.02')],"[Synset('beam.n.02'), Synset('piece_of_cloth.n...",a separate part of a whole,piece,[part],"[beam, piece_of_cloth, piece_of_leather, scrap..."
34,2,rendam,None,None,None,None,None,None,None
35,2,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
36,2,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
37,2,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
38,2,hidup,Synset('life.n.10'),[Synset('living_thing.n.01')],[Synset('wildlife.n.01')],living things collectively,life,[living_thing],[wildlife]
39,2,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
40,2,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
41,2,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
42,2,tauhu,Synset('bean_curd.n.01'),[Synset('curd.n.01')],[],cheeselike food made of curdled soybean milk,bean_curd,[curd],None
43,2,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
44,2,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
45,2,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
46,2,sambal,None,None,None,None,None,None,None
47,2,sayur,Synset('vegetable.n.01'),[Synset('produce.n.01')],"[Synset('artichoke.n.02'), Synset('artichoke_h...",edible seeds or roots or stems or leaves or bu...,vegetable,[produce],"[artichoke, artichoke_heart, asparagus, bamboo..."
48,2,kuah,Synset('dressing.n.04'),[Synset('cloth_covering.n.01')],"[Synset('bandage.n.01'), Synset('compress.n.01...",a cloth covering for a wound or sore,dressing,[cloth_covering],"[bandage, compress, poultice, surgical_dressing]"
49,2,serai,Synset('lemongrass.n.02'),[Synset('grass.n.01')],[],a tropical grass native to India and Sri Lanka,lemongrass,[grass],None
50,2,tempe,None,None,None,None,None,None,None
51,2,letak,Synset('put.v.01'),[Synset('move.v.02')],"[Synset('appose.v.01'), Synset('arrange.v.01')...",put into a certain place or abstract location,put,[move],"[appose, arrange, barrel, bed, bottle, bucket,..."
52,2,terung,Synset('eggplant.n.01'),[Synset('solanaceous_vegetable.n.01')],[],egg-shaped vegetable having a shiny skin typic...,eggplant,[solanaceous_vegetable],None
53,2,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
54,2,kubis,Synset('cabbage.n.01'),[Synset('cruciferous_vegetable.n.01')],"[Synset('bok_choy.n.02'), Synset('chinese_cabb...",any of various types of cabbage,cabbage,[cruciferous_vegetable],"[bok_choy, chinese_cabbage, head_cabbage, kale]"
55,2,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
56,2,ikat,Synset('tie.v.05'),[Synset('shape.v.03')],[],form a knot or bow in,tie,[shape],None
57,2,sengkuang,None,None,None,None,None,None,None
58,2,karot,None,None,None,None,None,None,None
59,2,inci,Synset('inch.n.01'),[Synset('linear_unit.n.01')],[],a unit of length equal to one twelfth of a foot,inch,[linear_unit],None
60,3,ikan,Synset('fish.n.01'),[Synset('aquatic_vertebrate.n.01')],"[Synset('bony_fish.n.01'), Synset('bottom-feed...",any of various mostly cold-blooded aquatic ver...,fish,[aquatic_vertebrate],"[bony_fish, bottom-feeder, bottom_lurkers, car..."
61,3,bilis,None,None,None,None,None,None,None
62,3,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
63,3,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
64,3,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
65,3,tempe,None,None,None,None,None,None,None
66,3,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
67,3,garing,Synset('crisp.s.04'),[],[],pleasingly firm and fresh,crisp,None,None
68,3,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
69,3,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
70,3,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
71,3,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
72,3,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
73,3,kentang,Synset('brunswick_stew.n.01'),[Synset('stew.n.02')],[],spicy southern specialty: chicken (or small ga...,brunswick_stew,[stew],None
74,3,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
75,3,rangup,Synset('delicate.s.03'),[],[],easily broken or damaged or destroyed,delicate,None,None
76,3,mencuba,Synset('try_on.v.01'),[Synset('wear.v.09')],[],put on a garment in order to see whether it fi...,try_on,[wear],None
77,3,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
78,3,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
79,3,keping,Synset('piece.n.01'),[Synset('part.n.02')],"[Synset('beam.n.02'), Synset('piece_of_cloth.n...",a separate part of a whole,piece,[part],"[beam, piece_of_cloth, piece_of_leather, scrap..."
80,3,nipis,Synset('thinly.r.02'),[],[],without viscosity,thinly,None,None
81,3,tos,None,None,None,None,None,None,None
82,3,tumbuk,Synset('crushed.s.01'),[],[],treated so as to have a permanently wrinkled a...,crushed,None,None
83,3,gaul,None,None,None,None,None,None,None
84,3,nota,Synset('note.n.01'),[Synset('written_record.n.01')],"[Synset('jotting.n.01'), Synset('marginalia.n....",a brief written record,note,[written_record],"[jotting, marginalia, memo, minute]"
85,3,digoreng,None,None,None,None,None,None,None
86,3,dimasukkan,None,None,None,None,None,None,None
87,3,asam,Synset('sourly.r.01'),[],[],in a sour manner,sourly,None,None
88,3,tumis,None,None,None,None,None,None,None
89,3,tutup,Synset('dark.s.11'),[],[],not giving performances; closed,dark,None,None
90,4,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
91,4,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
92,4,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
93,4,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
94,4,sos,Synset('sauce.n.01'),[Synset('condiment.n.01')],"[Synset('aioli.n.01'), Synset('allemande.n.01'...",flavorful relish or dressing or topping served...,sauce,[condiment],"[aioli, allemande, anchovy_sauce, apricot_sauc..."
95,4,timun,Synset('cucumber.n.02'),[Synset('vegetable.n.01')],[Synset('gherkin.n.02')],cylindrical green fruit with thin green rind a...,cucumber,[vegetable],[gherkin]
96,4,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
97,4,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
98,4,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
99,4,tangkai,Synset('stalk.n.04'),[Synset('pursuit.n.01')],[],the act of following prey stealthily,stalk,[pursuit],None
100,4,hidup,Synset('life.n.10'),[Synset('living_thing.n.01')],[Synset('wildlife.n.01')],living things collectively,life,[living_thing],[wildlife]
101,4,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
102,4,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
103,4,kulit,Synset('cover.n.03'),[Synset('concealment.n.03')],[],the act of concealing the existence of somethi...,cover,[concealment],None
104,4,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
105,4,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
106,4,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
107,4,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
108,4,inci,Synset('inch.n.01'),[Synset('linear_unit.n.01')],[],a unit of length equal to one twelfth of a foot,inch,[linear_unit],None
109,4,mendidih,Synset('seethe.v.04'),[Synset('churn.v.02')],[],boil vigorously,seethe,[churn],None
110,4,kena,Synset('contract.v.04'),[Synset('sicken.v.02')],[Synset('catch.v.19')],"be stricken by an illness, fall victim to an i...",contract,[sicken],[catch]
111,4,cuka,Synset('vinegar.n.01'),[Synset('condiment.n.01')],"[Synset('chili_vinegar.n.01'), Synset('cider_v...",sour-tasting liquid produced usually by oxidat...,vinegar,[condiment],"[chili_vinegar, cider_vinegar, wine_vinegar]"
112,4,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
113,4,aji,None,None,None,None,None,None,None
114,4,kicap,Synset('soy_sauce.n.01'),[Synset('condiment.n.01')],[],thin sauce made of fermented soy beans,soy_sauce,[condiment],None
115,4,tiram,Synset('oyster.n.01'),[Synset('bivalve.n.01')],"[Synset('bluepoint.n.02'), Synset('japanese_oy...",marine mollusks having a rough irregular shell...,oyster,[bivalve],"[bluepoint, japanese_oyster, pearl_oyster, sad..."
116,4,hijau,Synset('green.s.01'),[],[],of the color between blue and yellow in the co...,green,None,None
117,4,helai,Synset('sheet.n.02'),[Synset('paper.n.01')],"[Synset('foolscap.n.01'), Synset('leaf.n.02'),...",paper used for writing or printing,sheet,[paper],"[foolscap, leaf, revenue_stamp, signature, sli..."
118,4,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
119,4,jari,Synset('finger.n.03'),[Synset('covering.n.02')],[],one of the parts of a glove that provides cove...,finger,[covering],None
120,5,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
121,5,sayuran,Synset('vegetable.n.01'),[Synset('produce.n.01')],"[Synset('artichoke.n.02'), Synset('artichoke_h...",edible seeds or roots or stems or leaves or bu...,vegetable,[produce],"[artichoke, artichoke_heart, asparagus, bamboo..."
122,5,opsyenal,None,None,None,None,None,None,None
123,5,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
124,5,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
125,5,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
126,5,suuhun,None,None,None,None,None,None,None
127,5,layu,Synset('shrivel.v.01'),[Synset('decrease.v.01')],"[Synset('atrophy.v.01'), Synset('blast.v.10'),...","wither, as with a loss of moisture",shrivel,[decrease],"[atrophy, blast, die_back, mummify]"
128,5,pes,Synset('spread.n.05'),[Synset('condiment.n.01')],"[Synset('anchovy_butter.n.01'), Synset('cheese...",a tasty mixture to be spread on bread or crack...,spread,[condiment],"[anchovy_butter, cheese_spread, fishpaste, gar..."
129,5,jawa,Synset('javanese.a.01'),[],[],of or relating to or characteristic of Java or...,javanese,None,None
130,5,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
131,5,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
132,5,sambal,None,None,None,None,None,None,None
133,5,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
134,5,mendidih,Synset('seethe.v.04'),[Synset('churn.v.02')],[],boil vigorously,seethe,[churn],None
135,5,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
136,5,mangkuk,Synset('bowl.n.03'),[Synset('dish.n.01')],"[Synset('cereal_bowl.n.01'), Synset('finger_bo...",a dish that is round and open at the top for s...,bowl,[dish],"[cereal_bowl, finger_bowl, mixing_bowl, porrin..."
137,5,inci,Synset('inch.n.01'),[Synset('linear_unit.n.01')],[],a unit of length equal to one twelfth of a foot,inch,[linear_unit],None
138,5,batang,Synset('bar.n.03'),[Synset('implement.n.01')],"[Synset('belaying_pin.n.01'), Synset('bolt.n.0...",a rigid piece of metal or wood; usually used a...,bar,[implement],"[belaying_pin, bolt, bolt, carpenter's_level, ..."
139,5,digoreng,None,None,None,None,None,None,None
140,5,asam,Synset('sourly.r.01'),[],[],in a sour manner,sourly,None,None

### Make Ontology

In [ ]:
# Make Ontology
azieTempeOnto = get_ontology("http://test.org/azieTempe.owl")
makeOntology(azieTempeOnto, tempeWN)
azieTempeOnto.save(file = "azieTempe.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1HsXWNDNuv483p7U-DjlR6cjD_4DUFunD"

In [ ]:
wiki_tempe = pd.read_excel("AzieTempeFinal.xlsx").iloc[:, 1:]

# Translate
wiki_tempe["Category"] = translate(wiki_tempe["Category"])
wiki_tempe.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_tempe[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
tempeTabel_new = tabel_1981.copy()
tempeTabel_new["correct_category"] = all_cat
tempeTabel_new["suggestion"] = all_suggestion

# Export Result to File
tempeTabel_new.to_excel("tempeTabel_Result.xlsx")
tempeTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tempeTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
tempeTabel_new = concatListInColumn(tempeTabel_new)
tempeTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, tempeTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_tempe.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
tempeWiki_new = wiki_df.copy()
tempeWiki_new["suggest"] = all_cat
tempeWiki_new


# Export Result to file
tempeWiki_new.to_excel("tempeWiki_Result.xlsx")
tempeWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tempeWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieTempeOntoWiki = get_ontology("http://test.org/azieTempe_onto_wiki.owl")
makeOntology_wiki(azieTempeOntoWiki, tempeWiki_new)
azieTempeOntoWiki.save(file = "azieTempe_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = tempeWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
tempeWN_new = listToDataframe(changesList, tableWordnet)
tempeWN_new.to_excel("tempeWN_Result.xlsx")
tempeWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tempeWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Telur

In [ ]:
!gdown --id "1hWA53v9OWJtCqT-QOEtszdTvtVtsNv0F"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hWA53v9OWJtCqT-QOEtszdTvtVtsNv0F
To: /content/aziekitchen-telur.jl
100% 3.07M/3.07M [00:00<00:00, 232MB/s]

In [ ]:
telur=pd.read_json(r'/content/aziekitchen-telur.jl', lines = True)
telur.to_pickle(r'/content/raw_df.pkl')

telur = pre_cleaning_text(telur, threshold=20)

# telur["cleaned_description"] = cleaning_text(telur["page_description"])
# ingredients_all = telur["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Telur

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = telur.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2      0.225612  0.034817       1        1  29.325068
5      0.181723  0.050457       2        1  20.931190
6     -0.172845  0.119034       3        1  14.447273
4     -0.170914  0.094648       4        1  12.882242
3     -0.059055  0.126442       5        1  12.547131
1      0.134837 -0.117029       6        1   6.695483
0     -0.139358 -0.308368       7        1   3.171613, topic_info=               Term        Freq       Total Category  logprob  loglift
62           bawang  601.000000  601.000000  Default  30.0000  30.0000
1              cili  410.000000  410.000000  Default  29.0000  29.0000
226          goreng  272.000000  272.000000  Default  28.0000  28.0000
261             mee   97.000000   97.000000  Default  27.0000  27.0000
54             nasi  218.000000  218.000000  Default  26.0000  26.0000
152          tepung  255.000000  255.000000  Default  25.0000  25.0000
314             sos   89.000000   89.000000  Default  24.0000  24.0000
59             gula  402.000000  402.000000  Default  23.0000  23.0000
16           santan  149.000000  149.000000  Default  22.0000  22.0000
492             kek   88.000000   88.000000  Default  21.0000  21.0000
18             daun  236.000000  236.000000  Default  20.0000  20.0000
265           kicap   63.000000   63.000000  Default  19.0000  19.0000
210            susu  108.000000  108.000000  Default  18.0000  18.0000
158          pandan   80.000000   80.000000  Default  17.0000  17.0000
40              air  315.000000  315.000000  Default  16.0000  16.0000
37             ikan  200.000000  200.000000  Default  15.0000  15.0000
13             asam   88.000000   88.000000  Default  14.0000  14.0000
19            hiris  190.000000  190.000000  Default  13.0000  13.0000
63            merah  290.000000  290.000000  Default  12.0000  12.0000
14            garam  433.000000  433.000000  Default  11.0000  11.0000
61             ulas  211.000000  211.000000  Default  10.0000  10.0000
43            kisar  233.000000  233.000000  Default   9.0000   9.0000
399           bilis   99.000000   99.000000  Default   8.0000   8.0000
313          kuning   87.000000   87.000000  Default   7.0000   7.0000
168          adunan  117.000000  117.000000  Default   6.0000   6.0000
299          tomato   45.000000   45.000000  Default   5.0000   5.0000
234           udang   80.000000   80.000000  Default   4.0000   4.0000
188            esen   77.000000   77.000000  Default   3.0000   3.0000
189         vanilla   77.000000   77.000000  Default   2.0000   2.0000
494          baking   51.000000   51.000000  Default   1.0000   1.0000
54             nasi  218.213229  218.908771   Topic1  -3.4515   1.2235
399           bilis   98.404874   99.098864   Topic1  -4.2479   1.2197
243          garing   46.627202   47.326492   Topic1  -4.9948   1.2118
718           kubis   29.611049   30.305254   Topic1  -5.4488   1.2036
296           karot   67.824298   69.475499   Topic1  -4.6200   1.2027
363           bendi   20.002667   20.696918   Topic1  -5.8411   1.1926
426           sulah   15.346558   16.040964   Topic1  -6.1061   1.1825
865        perencah   14.274353   14.969333   Topic1  -6.1785   1.1792
553           halba   12.452624   13.150863   Topic1  -6.3150   1.1722
795           blend   13.067676   13.801603   Topic1  -6.2668   1.1721
548           petai   11.851527   12.545875   Topic1  -6.3645   1.1698
522        hidangan   11.001189   11.702197   Topic1  -6.4390   1.1650
774      kekuningan   10.937702   11.644506   Topic1  -6.4447   1.1641
697       tambahkan   10.483114   11.193999   Topic1  -6.4872   1.1611
1694           stok    9.909755   10.613164   Topic1  -6.5434   1.1582
866         seriaji    9.596772   10.290216   Topic1  -6.5755   1.1570
694        ditumbuk    9.484264   10.178674   Topic1  -6.5873   1.1561
867             pot    8.822430    9.516570   Topic1  -6.6597   1.1510
1129       sejemput    8.418629    9.112872   Topic1  -6.7065   1.1475
1433        keropok    8.273220    8.967245   Topic1  -6.7239   1.1462
226          goreng  250.633277  272.967922   Topic1  -3.3130   1.1414
355        bersalut    7.764901    8.460557   Topic1  -6.7874   1.1409
1687        kembung    7.588156    8.282826   Topic1  -6.8104   1.1391
356        diangkat   29.787946   32.556886   Topic1  -5.4429   1.1378
1265          zaman    7.161387    7.856006   Topic1  -6.8683   1.1342
454           lumat    7.103814    7.798510   Topic1  -6.8763   1.1334
264         sayuran   24.834063   27.296293   Topic1  -5.6247   1.1322
1387       peraduan    7.013952    7.709670   Topic1  -6.8891   1.1322
869         tongkol    6.654186    7.350086   Topic1  -6.9417   1.1273
60           tumbuk  100.508068  111.093615   Topic1  -4.2267   1.1266
667          kacang   54.305216   61.985591   Topic1  -4.8423   1.0944
81          mangkuk   89.962551  105.492466   Topic1  -4.3376   1.0675
37             ikan  157.589087  200.919665   Topic1  -3.7770   0.9838
72         mengeras   24.042084   27.769200   Topic1  -5.6572   1.0826
19            hiris  145.209533  190.376559   Topic1  -3.8588   0.9559
55            putih  222.490117  299.832805   Topic1  -3.4321   0.9284
62           bawang  418.395348  601.031757   Topic1  -2.8005   0.8645
63            merah  208.387891  290.800620   Topic1  -3.4976   0.8935
61             ulas  145.662208  211.654407   Topic1  -3.8557   0.8531
66          dikacau   48.018450   63.291646   Topic1  -4.9654   0.9506
263           sayur   40.943560   53.073076   Topic1  -5.1248   0.9673
219            lada   42.205406   55.061892   Topic1  -5.0944   0.9608
209           tumis   81.911362  118.972688   Topic1  -4.4313   0.8535
196          perasa   30.176838   37.928071   Topic1  -5.4299   0.9981
14            garam  237.791252  433.715301   Topic1  -3.3656   0.6257
1              cili  225.801133  410.393225   Topic1  -3.4173   0.6293
44          tangkai   79.838422  124.024018   Topic1  -4.4570   0.7863
3             telur  270.985450  619.753253   Topic1  -3.2349   0.3995
222          lembut   37.611906   52.468958   Topic1  -5.2096   0.8938
166       ketepikan   45.387154   67.106270   Topic1  -5.0217   0.8357
242        panaskan   80.946400  147.376900   Topic1  -4.4432   0.6275
5              biji  175.361104  479.702352   Topic1  -3.6701   0.2204
154            ayam   70.181354  140.441441   Topic1  -4.5859   0.5330
83           batang   54.101447   96.520018   Topic1  -4.8461   0.6478
45           kering   60.631150  116.776204   Topic1  -4.7322   0.5713
195          serbuk   74.271078  169.480117   Topic1  -4.5292   0.4017
43            kisar   82.017468  233.746694   Topic1  -4.4300   0.1794
30            layan   71.116240  177.834436   Topic1  -4.5726   0.3102
18             daun   70.861648  236.951380   Topic1  -4.5762   0.0196
34          selamat   59.605511  148.167401   Topic1  -4.7492   0.3161
35          mencuba   56.736060  155.042862   Topic1  -4.7986   0.2214
13             asam   87.528403   88.248782   Topic2  -4.0278   1.5557
262            hoon   51.954222   52.676871   Topic2  -4.5494   1.5501
300           halia   42.436195   43.156548   Topic2  -4.7518   1.5471
84            serai   39.242587   39.963120   Topic2  -4.8300   1.5457
212            jawa   39.176407   39.896872   Topic2  -4.8317   1.5457
292          rempah   33.574322   34.295481   Topic2  -4.9860   1.5427
74            gulai   17.179510   17.899955   Topic2  -5.6560   1.5228
127        lengkuas   16.127734   16.847912   Topic2  -5.7192   1.5202
290           empuk   15.581934   16.304456   Topic2  -5.7536   1.5186
578           purut   14.827531   15.548253   Topic2  -5.8033   1.5165
905            teow   14.324963   15.048690   Topic2  -5.8378   1.5146
49             lauk   14.207733   14.927979   Topic2  -5.8460   1.5145
23             pati   13.347165   14.069322   Topic2  -5.9085   1.5112
304          lawang   11.209572   11.929861   Topic2  -6.0830   1.5017
255           rebus   50.143140   53.855226   Topic2  -4.5849   1.4925
41            pucuk    9.426330   10.146673   Topic2  -6.2563   1.4903
311         direbus    9.441216   10.165697   Topic2  -6.2547   1.4900
1038         jintan    9.289405   10.009895   Topic2  -6.2709   1.4892
301         tumisan    8.898526    9.620889   Topic2  -6.3139   1.4859
128        ketumbar    8.735256    9.455817   Topic2  -6.3324   1.4847
759         gembira    8.216806    8.938355   Topic2  -6.3936   1.4798
100        direndam    7.856342    8.578305   Topic2  -6.4384   1.4760
340            labu   26.258704   28.748717   Topic2  -5.2318   1.4733
1045          tempe    7.377803    8.098504   Topic2  -6.5013   1.4707
2172        sekawan    7.083574    7.803817   Topic2  -6.5420   1.4671
329        tempoyak    7.096149    7.819793   Topic2  -6.5402   1.4668
276            kari   33.807483   37.257841   Topic2  -4.9791   1.4667
1344          noxxa    7.010693    7.747633   Topic2  -6.5523   1.4640
199          sambal   54.422520   60.148177   Topic2  -4.5030   1.4639
211             pes    6.787936    7.513561   Topic2  -6.5846   1.4624
202           maggi   24.882040   28.507496   Topic2  -5.2856   1.4279
11            hidup   34.350202   39.845505   Topic2  -4.9632   1.4155
9              inci   71.338904   85.971539   Topic2  -4.2323   1.3774
96             kuah   45.020536   53.488008   Topic2  -4.6926   1.3916
12           keping   70.860797   94.003674   Topic2  -4.2390   1.2813
162           ketuk   26.723212   32.775520   Topic2  -5.2142   1.3598
295         kentang   17.875824   21.976612   Topic2  -5.6163   1.3574
10           kunyit   54.612700   82.048219   Topic2  -4.4995   1.1569
903          sotong   45.743727   67.510990   Topic2  -4.6767   1.1747
0             lemak   24.353898   33.415513   Topic2  -5.3071   1.2476
43            kisar  112.770274  233.746694   Topic2  -3.7744   0.8350
154            ayam   68.855051  140.441441   Topic2  -4.2678   0.8511
47         mendidih   40.869255   74.188633   Topic2  -4.7894   0.9677
40              air  111.057259  315.456874   Topic2  -3.7897   0.5200
1              cili  126.916781  410.393225   Topic2  -3.6562   0.3903
24            pekat   47.025294   96.324457   Topic2  -4.6491   0.8469
62           bawang  151.065705  601.031757   Topic2  -3.4820   0.1830
16           santan   60.459003  149.736914   Topic2  -4.3978   0.6570
5              biji  116.775608  479.702352   Topic2  -3.7395   0.1510
14            garam  107.250264  433.715301   Topic2  -3.8246   0.1667
59             gula   85.422544  402.926279   Topic2  -4.0522   0.0128
61             ulas   59.789770  211.654407   Topic2  -4.4089   0.2998
18             daun   62.686716  236.951380   Topic2  -4.3616   0.2342
63            merah   65.470530  290.800620   Topic2  -4.3182   0.0729
3             telur   68.806836  619.753253   Topic2  -4.2685  -0.6341
195          serbuk   44.968990  169.480117   Topic2  -4.6938   0.2372
19            hiris   44.595577  190.376559   Topic2  -4.7021   0.1126
37             ikan   42.759532  200.919665   Topic2  -4.7442   0.0166
55            putih   44.544937  299.832805   Topic2  -4.7033  -0.3428
25             nota   40.410643  144.173477   Topic2  -4.8007   0.2920
492             kek   87.903841   88.626208   Topic3  -3.6528   1.9265
494          baking   51.040319   51.763033   Topic3  -4.1964   1.9206
495          powder   42.973860   43.696336   Topic3  -4.3684   1.9180
600            soda   33.434446   34.156452   Topic3  -4.6194   1.9133
646          diayak   26.542034   27.264201   Topic3  -4.8503   1.9078
602            ayak   22.566512   23.290861   Topic3  -5.0126   1.9031
1111          paper   11.976165   12.700809   Topic3  -5.6461   1.8759
937          coklat   11.310926   12.034676   Topic3  -5.7033   1.8726
649            kaup   10.883080   11.604858   Topic3  -5.7418   1.8704
636         karamel   10.860302   11.586987   Topic3  -5.7439   1.8699
1327          susun   11.165029   11.923648   Topic3  -5.7162   1.8689
1152       campuran   10.669557   11.398401   Topic3  -5.7616   1.8686
601      bikarbonat   10.192102   10.913718   Topic3  -5.8074   1.8663
598          kastor   10.316187   11.049335   Topic3  -5.7953   1.8660
640         berbuih    9.551937   10.275145   Topic3  -5.8723   1.8617
501          tartar    9.380594   10.102461   Topic3  -5.8904   1.8605
1237          icing    9.017499    9.739205   Topic3  -5.9299   1.8577
1949         muffin    8.054299    8.781374   Topic3  -6.0428   1.8482
971            koko    7.529887    8.252537   Topic3  -6.1101   1.8430
2196         emping    7.230654    7.952323   Topic3  -6.1507   1.8395
411          hangus   15.554724   17.123414   Topic3  -5.3847   1.8386
1722          mixed    6.993954    7.715667   Topic3  -6.1840   1.8365
1724           pala    6.993954    7.715667   Topic3  -6.1840   1.8365
1113       whipping    6.546073    7.268545   Topic3  -6.2502   1.8300
1328           sapu    6.673542    7.423980   Topic3  -6.2309   1.8281
815       aluminium    6.424059    7.148711   Topic3  -6.2690   1.8278
1723          fruit    6.164452    6.886165   Topic3  -6.3102   1.8239
1727        mencair    6.164435    6.886164   Topic3  -6.3102   1.8239
1062       keemasan    5.816905    6.539754   Topic3  -6.3683   1.8175
1024          mulut    5.742780    6.475835   Topic3  -6.3811   1.8145
51           pisang   31.773378   36.568332   Topic3  -4.6704   1.7941
497             jus   31.521333   37.089118   Topic3  -4.6784   1.7720
662            oven   42.267707   54.856904   Topic3  -4.3850   1.6740
929       kurangkan   15.203880   18.447773   Topic3  -5.4075   1.7413
188            esen   53.044402   77.936407   Topic3  -4.1579   1.5499
781            gred   29.290900   42.827183   Topic3  -4.7517   1.5548
471             dgn   10.256913   12.360289   Topic3  -5.8011   1.7481
489          kaster   28.495226   41.858796   Topic3  -4.7793   1.5501
189         vanilla   44.811366   77.586056   Topic3  -4.3266   1.3857
152          tepung  114.180286  255.634000   Topic3  -3.3912   1.1287
280          sebati   50.121056   92.057363   Topic3  -4.2146   1.3267
500           cream   28.222413   45.064578   Topic3  -4.7889   1.4667
273         mentega   46.355074   86.147275   Topic3  -4.2927   1.3149
59             gula  138.343598  402.926279   Topic3  -3.1993   0.8657
168          adunan   54.990971  117.725407   Topic3  -4.1219   1.1735
679         kembang   25.573514   45.977854   Topic3  -4.8875   1.3481
153          gandum   43.474764  104.781133   Topic3  -4.3568   1.0550
785            suhu   33.266050   69.983006   Topic3  -4.6245   1.1909
210            susu   42.134712  108.132661   Topic3  -4.3882   0.9922
150          loyang   31.696195   70.436662   Topic3  -4.6728   1.1361
3             telur  102.635626  619.753253   Topic3  -3.4978   0.1365
378           bakar   30.297397   73.600888   Topic3  -4.7180   1.0471
244           panas   27.793924   68.752330   Topic3  -4.8042   1.0290
36             gram   39.708115  162.872936   Topic3  -4.4475   0.5232
5              biji   57.212336  479.702352   Topic3  -4.0823  -0.1917
156            saiz   24.128465   65.852067   Topic3  -4.9456   0.9306
40              air   38.970394  315.456874   Topic3  -4.4662  -0.1566
30            layan   30.755969  177.834436   Topic3  -4.7029   0.1799
195          serbuk   28.391514  169.480117   Topic3  -4.7829   0.1480
35          mencuba   27.946726  155.042862   Topic3  -4.7987   0.2213
428            roti   39.429069   40.150703   Topic4  -4.3399   2.0312
784           putar   36.714501   37.438409   Topic4  -4.4112   2.0298
974           nenas   32.571319   33.292235   Topic4  -4.5309   2.0274
973            tart   22.712567   23.433483   Topic4  -4.8915   2.0181
385             ais   19.200320   19.922560   Topic4  -5.0594   2.0124
1228           suam   13.360889   14.084742   Topic4  -5.4220   1.9966
989             doh   12.857273   13.578764   Topic4  -5.4605   1.9947
907          sardin   12.773702   13.497615   Topic4  -5.4670   1.9942
928        kelajuan   11.572667   12.295548   Topic4  -5.5657   1.9887
1053         kismis   10.272924   10.994333   Topic4  -5.6849   1.9815
936         filling    9.611315   10.332514   Topic4  -5.7514   1.9770
927         diputar    9.189321    9.911203   Topic4  -5.7963   1.9737
1217     bergantung    8.765662    9.489975   Topic4  -5.8435   1.9699
1561    blueberries    8.686241    9.407094   Topic4  -5.8526   1.9696
519          lembab    8.162806    8.884345   Topic4  -5.9148   1.9646
1923           oren    8.108790    8.829878   Topic4  -5.9214   1.9641
806           fresh    6.914387    7.637149   Topic4  -6.0808   1.9499
976          bentuk    6.716863    7.445156   Topic4  -6.1097   1.9464
692           olive    6.653438    7.379529   Topic4  -6.1192   1.9457
685        asingkan    6.592156    7.325410   Topic4  -6.1285   1.9439
1925         orange    6.320008    7.041777   Topic4  -6.1707   1.9412
1973          moist    6.319504    7.041689   Topic4  -6.1707   1.9411
1300            yis    6.274010    6.996025   Topic4  -6.1780   1.9404
438         sapukan    6.097969    6.820311   Topic4  -6.2064   1.9374
993            food    6.080264    6.802583   Topic4  -6.2093   1.9371
2036        yoghurt    6.081244    6.803692   Topic4  -6.2092   1.9371
190           tebal    5.857902    6.581562   Topic4  -6.2466   1.9328
1194           sapi    5.611018    6.336648   Topic4  -6.2896   1.9277
618         diletak    5.538998    6.261704   Topic4  -6.3026   1.9267
1494          udara    5.385429    6.106268   Topic4  -6.3307   1.9237
777         majerin   15.525459   18.760488   Topic4  -5.2719   1.8600
464          butter   47.340699   61.542639   Topic4  -4.1570   1.7870
370             utk    9.456900   11.368961   Topic4  -5.7676   1.8652
210            susu   65.397275  108.132661   Topic4  -3.8339   1.5464
298            buah   45.527325   71.109648   Topic4  -4.1961   1.6034
503             tin   23.329823   33.383241   Topic4  -4.8646   1.6910
1324        dibakar   11.340502   14.302709   Topic4  -5.5860   1.8173
384            peti   18.108452   25.407651   Topic4  -5.1180   1.7106
92           sebiji   11.948296   15.486441   Topic4  -5.5338   1.7899
923         extract   16.613469   23.518711   Topic4  -5.2042   1.7017
313          kuning   46.106716   87.898196   Topic4  -4.1834   1.4041
1077         cheese   18.828656   29.361216   Topic4  -5.0790   1.6050
152          tepung   83.114423  255.634000   Topic4  -3.5942   0.9258
36             gram   53.865298  162.872936   Topic4  -4.0279   0.9428
189         vanilla   32.174601   77.586056   Topic4  -4.5432   1.1691
499         pewarna   24.414371   52.216390   Topic4  -4.8192   1.2891
3             telur  102.045577  619.753253   Topic4  -3.3890   0.2454
785            suhu   28.143827   69.983006   Topic4  -4.6770   1.1384
607           acuan   23.444250   53.829241   Topic4  -4.8597   1.2181
59             gula   62.114672  402.926279   Topic4  -3.8854   0.1795
172        sejukkan   18.470785   38.574537   Topic4  -5.0982   1.3129
153          gandum   29.937218  104.781133   Topic4  -4.6153   0.7965
25             nota   34.361595  144.173477   Topic4  -4.4774   0.6152
5              biji   58.745678  479.702352   Topic4  -3.9412  -0.0506
168          adunan   29.800873  117.725407   Topic4  -4.6198   0.6755
273         mentega   25.739583   86.147275   Topic4  -4.7663   0.8413
378           bakar   23.988205   73.600888   Topic4  -4.8368   0.9282
188            esen   24.281946   77.936407   Topic4  -4.8246   0.8832
40              air   40.122348  315.456874   Topic4  -4.3224  -0.0128
383           sejuk   22.518467   66.697760   Topic4  -4.9000   0.9635
280          sebati   21.184328   92.057363   Topic4  -4.9611   0.5802
14            garam   22.837178  433.715301   Topic4  -4.8860  -0.8947

Topic: 1
salmon, cheese, cream, camca, lemon, pie, buttermilk, teh, flour, oil, burger, garam, jus, cake, spatula, begedil, hadiah, keju, link, gantikan, shell, vegetable, red, potongan, berdurasi, parutan, gliserin, jenama, quiche, spaghetti

Topic: 2
mee, sos, cili, kicap, daun, tomato, bawang, tiram, udang, biji, limau, nipis, kuning, goreng, air, telur, daging, fish, kisar, tabur, ikat, manis, sup, makan, bok, pek, gram, kering, sayur, kue

Topic: 3
bawang, telur, goreng, garam, cili, putih, nasi, merah, biji, ikan, ulas, hiris, tumbuk, bilis, mangkuk, kisar, tumis, panaskan, tangkai, serbuk, layan, daun, ayam, karot, kering, selamat, mencuba, kacang, batang, dikacau

Topic: 4
air, gula, santan, pandan, daun, garam, tepung, telur, biji, kuih, pulut, adunan, gandum, helai, loyang, mendidih, beras, pekat, pengukus, acuan, lapisan, nota, periuk, kelapa, mencuba, kukus, layan, gram, sejuk, kisar

Topic: 5
telur, tepung, susu, gula, biji, gram, butter, kuning, buah, air, roti, putar, nota, nenas, vanilla, gandum, adunan, suhu, mentega, pewarna, esen, bakar, acuan, tin, garam, tart, sejuk, sebati, ais, cheese

Topic: 6
bawang, cili, biji, kisar, air, garam, asam, gula, inci, keping, ayam, telur, merah, daun, santan, ulas, kunyit, sambal, hoon, rebus, pekat, sotong, kuah, serbuk, hiris, putih, ikan, halia, mendidih, nota

Topic: 7
gula, tepung, telur, kek, biji, adunan, esen, baking, sebati, mentega, vanilla, gandum, powder, oven, susu, gram, air, soda, suhu, pisang, loyang, jus, layan, bakar, gred, kaster, serbuk, cream, mencuba, panas

[(0,
  '0.017*"salmon" + 0.013*"cheese" + 0.013*"cream" + 0.010*"camca" + 0.009*"lemon" + 0.009*"pie" + 0.008*"buttermilk" + 0.008*"teh" + 0.008*"flour" + 0.008*"oil"'),
 (1,
  '0.062*"mee" + 0.050*"sos" + 0.036*"cili" + 0.033*"kicap" + 0.023*"daun" + 0.022*"tomato" + 0.020*"bawang" + 0.016*"tiram" + 0.016*"udang" + 0.015*"biji"'),
 (2,
  '0.061*"bawang" + 0.039*"telur" + 0.036*"goreng" + 0.035*"garam" + 0.033*"cili" + 0.032*"putih" + 0.032*"nasi" + 0.030*"merah" + 0.025*"biji" + 0.023*"ikan"'),
 (3,
  '0.033*"air" + 0.031*"gula" + 0.030*"santan" + 0.025*"pandan" + 0.021*"daun" + 0.020*"garam" + 0.020*"tepung" + 0.019*"telur" + 0.016*"biji" + 0.014*"kuih"'),
 (4,
  '0.034*"telur" + 0.027*"tepung" + 0.022*"susu" + 0.021*"gula" + 0.019*"biji" + 0.018*"gram" + 0.016*"butter" + 0.015*"kuning" + 0.015*"buah" + 0.013*"air"'),
 (5,
  '0.031*"bawang" + 0.026*"cili" + 0.024*"biji" + 0.023*"kisar" + 0.023*"air" + 0.022*"garam" + 0.018*"asam" + 0.017*"gula" + 0.015*"inci" + 0.014*"keping"'),
 (6,
  '0.041*"gula" + 0.034*"tepung" + 0.030*"telur" + 0.026*"kek" + 0.017*"biji" + 0.016*"adunan" + 0.016*"esen" + 0.015*"baking" + 0.015*"sebati" + 0.014*"mentega"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
telurProb = make_dictionary_terms_prob(ldamodel, id_map, d)
telurProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
telurWN = dfWordnet.copy()

telurWN["Synonym_clean"] = cleanWN_Synonym(telurWN["Synonym"])
telurWN["Hypernim_clean"] = cleanWN(telurWN["Hypernim"])
telurWN["Hyponim_clean"] = cleanWN(telurWN["Hyponim"])
telurWN

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,salmon,Synset('salmon.n.01'),"[Synset('food_fish.n.01'), Synset('salmonid.n....","[Synset('atlantic_salmon.n.02'), Synset('black...",any of various large food and game fishes of n...,salmon,"[food_fish, salmonid]","[atlantic_salmon, blackfish, chinook, chum_sal..."
1,1,cheese,None,None,None,None,None,None,None
2,1,cream,None,None,None,None,None,None,None
3,1,camca,Synset('spoon.n.01'),"[Synset('container.n.01'), Synset('cutlery.n.0...","[Synset('dessert_spoon.n.01'), Synset('runcibl...",a piece of cutlery with a shallow bowl-shaped ...,spoon,"[container, cutlery]","[dessert_spoon, runcible_spoon, soupspoon, sug..."
4,1,lemon,Synset('lemony.s.01'),[],[],tasting sour like a lemon,lemony,None,None
5,1,pie,None,None,None,None,None,None,None
6,1,buttermilk,None,None,None,None,None,None,None
7,1,teh,Synset('tea.n.02'),[Synset('meal.n.01')],[],a light midafternoon meal of tea and sandwiche...,tea,[meal],None
8,1,flour,None,None,None,None,None,None,None
9,1,oil,None,None,None,None,None,None,None
10,1,burger,Synset('burger.n.01'),[],[],United States jurist appointed chief justice o...,burger,None,None
11,1,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
12,1,jus,Synset('juice.n.04'),[Synset('liquid_body_substance.n.01')],"[Synset('cancer_juice.n.01'), Synset('digestiv...",any of several liquids of the body,juice,[liquid_body_substance],"[cancer_juice, digestive_juice]"
13,1,cake,None,None,None,None,None,None,None
14,1,spatula,None,None,None,None,None,None,None
15,1,begedil,None,None,None,None,None,None,None
16,1,hadiah,Synset('giving.n.01'),[Synset('sharing.n.04')],"[Synset('accordance.n.02'), Synset('alms-givin...",the act of giving,giving,[sharing],"[accordance, alms-giving, bestowal, charity, c..."
17,1,keju,Synset('cheese.n.01'),"[Synset('dairy_product.n.01'), Synset('food.n....","[Synset('bleu.n.01'), Synset('brick_cheese.n.0...",a solid food prepared from the pressed curd of...,cheese,"[dairy_product, food]","[bleu, brick_cheese, brie, camembert, cheddar,..."
18,1,link,None,None,None,None,None,None,None
19,1,gantikan,None,None,None,None,None,None,None
20,1,shell,None,None,None,None,None,None,None
21,1,vegetable,None,None,None,None,None,None,None
22,1,red,None,None,None,None,None,None,None
23,1,potongan,Synset('decrease.n.04'),[Synset('change_of_magnitude.n.01')],"[Synset('amortization.n.01'), Synset('contract...",the act of decreasing or reducing something,decrease,[change_of_magnitude],"[amortization, contraction, cut, cutback, de-e..."
24,1,berdurasi,None,None,None,None,None,None,None
25,1,parutan,None,None,None,None,None,None,None
26,1,gliserin,Synset('glycerol.n.01'),[Synset('alcohol.n.02')],[],a sweet syrupy trihydroxy alcohol obtained by ...,glycerol,[alcohol],None
27,1,jenama,Synset('trade_name.n.01'),[Synset('name.n.01')],[Synset('label.n.02')],a name given to a product or service,trade_name,[name],[label]
28,1,quiche,None,None,None,None,None,None,None
29,1,spaghetti,None,None,None,None,None,None,None
30,2,mee,None,None,None,None,None,None,None
31,2,sos,Synset('sauce.n.01'),[Synset('condiment.n.01')],"[Synset('aioli.n.01'), Synset('allemande.n.01'...",flavorful relish or dressing or topping served...,sauce,[condiment],"[aioli, allemande, anchovy_sauce, apricot_sauc..."
32,2,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
33,2,kicap,Synset('soy_sauce.n.01'),[Synset('condiment.n.01')],[],thin sauce made of fermented soy beans,soy_sauce,[condiment],None
34,2,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
35,2,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
36,2,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
37,2,tiram,Synset('oyster.n.01'),[Synset('bivalve.n.01')],"[Synset('bluepoint.n.02'), Synset('japanese_oy...",marine mollusks having a rough irregular shell...,oyster,[bivalve],"[bluepoint, japanese_oyster, pearl_oyster, sad..."
38,2,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
39,2,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
40,2,limau,Synset('orange.n.01'),[Synset('citrus.n.01')],"[Synset('bitter_orange.n.02'), Synset('sweet_o...",round yellow to orange fruit of any of several...,orange,[citrus],"[bitter_orange, sweet_orange, temple_orange]"
41,2,nipis,Synset('thinly.r.02'),[],[],without viscosity,thinly,None,None
42,2,kuning,Synset('yellow.s.01'),[],[],of the color intermediate between green and or...,yellow,None,None
43,2,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
44,2,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
45,2,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
46,2,daging,Synset('fiber.n.05'),[Synset('fabric.n.01')],[],a leatherlike material made by compressing lay...,fiber,[fabric],None
47,2,fish,None,None,None,None,None,None,None
48,2,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
49,2,tabur,None,None,None,None,None,None,None
50,2,ikat,Synset('tie.v.05'),[Synset('shape.v.03')],[],form a knot or bow in,tie,[shape],None
51,2,manis,Synset('attractive.a.01'),[],[],pleasing to the eye or mind especially through...,attractive,None,None
52,2,sup,Synset('soup.n.01'),[Synset('dish.n.02')],"[Synset('alphabet_soup.n.02'), Synset('bisque....",liquid food especially of meat or fish or vege...,soup,[dish],"[alphabet_soup, bisque, borsch, broth, broth, ..."
53,2,makan,Synset('food.n.01'),[Synset('substance.n.07')],"[Synset('beverage.n.01'), Synset('chyme.n.01')...",any substance that can be metabolized by an an...,food,[substance],"[beverage, chyme, comestible, comfort_food, co..."
54,2,bok,None,None,None,None,None,None,None
55,2,pek,Synset('compact.v.01'),[Synset('be.v.01')],[],have the property of being packable or of comp...,compact,[be],None
56,2,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
57,2,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
58,2,sayur,Synset('vegetable.n.01'),[Synset('produce.n.01')],"[Synset('artichoke.n.02'), Synset('artichoke_h...",edible seeds or roots or stems or leaves or bu...,vegetable,[produce],"[artichoke, artichoke_heart, asparagus, bamboo..."
59,2,kue,None,None,None,None,None,None,None
60,3,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
61,3,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
62,3,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
63,3,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
64,3,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
65,3,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
66,3,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
67,3,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
68,3,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
69,3,ikan,Synset('fish.n.01'),[Synset('aquatic_vertebrate.n.01')],"[Synset('bony_fish.n.01'), Synset('bottom-feed...",any of various mostly cold-blooded aquatic ver...,fish,[aquatic_vertebrate],"[bony_fish, bottom-feeder, bottom_lurkers, car..."
70,3,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
71,3,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
72,3,tumbuk,Synset('crushed.s.01'),[],[],treated so as to have a permanently wrinkled a...,crushed,None,None
73,3,bilis,None,None,None,None,None,None,None
74,3,mangkuk,Synset('bowl.n.03'),[Synset('dish.n.01')],"[Synset('cereal_bowl.n.01'), Synset('finger_bo...",a dish that is round and open at the top for s...,bowl,[dish],"[cereal_bowl, finger_bowl, mixing_bowl, porrin..."
75,3,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
76,3,tumis,None,None,None,None,None,None,None
77,3,panaskan,None,None,None,None,None,None,None
78,3,tangkai,Synset('stalk.n.04'),[Synset('pursuit.n.01')],[],the act of following prey stealthily,stalk,[pursuit],None
79,3,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
80,3,layan,Synset('listen.v.01'),[Synset('perceive.v.01')],"[Synset('attend.v.05'), Synset('hark.v.01'), S...",hear with intention,listen,[perceive],"[attend, hark, hear_out, listen_in, listen_in]"
81,3,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
82,3,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
83,3,karot,None,None,None,None,None,None,None
84,3,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
85,3,selamat,Synset('redemption.n.01'),[Synset('rescue.n.01')],"[Synset('absolution.n.02'), Synset('conversion...",(theology) the act of delivering from sin or s...,redemption,[rescue],"[absolution, conversion, expiation]"
86,3,mencuba,Synset('try_on.v.01'),[Synset('wear.v.09')],[],put on a garment in order to see whether it fi...,try_on,[wear],None
87,3,kacang,Synset('cinch.n.01'),[Synset('undertaking.n.01')],[Synset('doddle.n.01')],any undertaking that is easy to do,cinch,[undertaking],[doddle]
88,3,batang,Synset('bar.n.03'),[Synset('implement.n.01')],"[Synset('belaying_pin.n.01'), Synset('bolt.n.0...",a rigid piece of metal or wood; usually used a...,bar,[implement],"[belaying_pin, bolt, bolt, carpenter's_level, ..."
89,3,dikacau,None,None,None,None,None,None,None
90,4,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
91,4,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
92,4,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
93,4,pandan,None,None,None,None,None,None,None
94,4,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
95,4,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
96,4,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
97,4,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
98,4,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
99,4,kuih,Synset('cake.n.03'),[Synset('baked_goods.n.01')],"[Synset('applesauce_cake.n.01'), Synset('baba....",baked goods made from or based on a mixture of...,cake,[baked_goods],"[applesauce_cake, baba, birthday_cake, boston_..."
100,4,pulut,None,None,None,None,None,None,None
101,4,adunan,Synset('blend.n.03'),[Synset('combination.n.07')],"[Synset('confluence.n.02'), Synset('homogeniza...",the act of blending components together thorou...,blend,[combination],"[confluence, homogenization]"
102,4,gandum,Synset('grain.n.02'),[Synset('foodstuff.n.02')],"[Synset('barley.n.01'), Synset('buckwheat.n.02...",foodstuff prepared from the starchy grains of ...,grain,[foodstuff],"[barley, buckwheat, corn, grist, groats, malt,..."
103,4,helai,Synset('sheet.n.02'),[Synset('paper.n.01')],"[Synset('foolscap.n.01'), Synset('leaf.n.02'),...",paper used for writing or printing,sheet,[paper],"[foolscap, leaf, revenue_stamp, signature, sli..."
104,4,loyang,Synset('brazen.a.02'),[],[],made of or resembling brass (as in color or ha...,brazen,None,None
105,4,mendidih,Synset('seethe.v.04'),[Synset('churn.v.02')],[],boil vigorously,seethe,[churn],None
106,4,beras,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
107,4,pekat,Synset('gluey.s.01'),[],[],having the sticky properties of an adhesive,gluey,None,None
108,4,pengukus,None,None,None,None,None,None,None
109,4,acuan,Synset('model.v.02'),[Synset('shape.v.02')],[],"form in clay, wax, etc",model,[shape],None
110,4,lapisan,Synset('layer.n.05'),[Synset('structure.n.04')],"[Synset('blastoderm.n.01'), Synset('hypodermis...",thin structure composed of a single thickness ...,layer,[structure],"[blastoderm, hypodermis]"
111,4,nota,Synset('note.n.01'),[Synset('written_record.n.01')],"[Synset('jotting.n.01'), Synset('marginalia.n....",a brief written record,note,[written_record],"[jotting, marginalia, memo, minute]"
112,4,periuk,Synset('pan.n.01'),[Synset('cooking_utensil.n.01')],"[Synset('dripping_pan.n.01'), Synset('frying_p...",cooking utensil consisting of a wide metal vessel,pan,[cooking_utensil],"[dripping_pan, frying_pan, omelet_pan, patty-p..."
113,4,kelapa,Synset('coconut.n.02'),[Synset('edible_nut.n.01')],[],large hard-shelled oval nut with a fibrous hus...,coconut,[edible_nut],None
114,4,mencuba,Synset('try_on.v.01'),[Synset('wear.v.09')],[],put on a garment in order to see whether it fi...,try_on,[wear],None
115,4,kukus,Synset('steamed.s.01'),[],[],cooked in steam,steamed,None,None
116,4,layan,Synset('listen.v.01'),[Synset('perceive.v.01')],"[Synset('attend.v.05'), Synset('hark.v.01'), S...",hear with intention,listen,[perceive],"[attend, hark, hear_out, listen_in, listen_in]"
117,4,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
118,4,sejuk,Synset('balmy.s.02'),[],[],mild and pleasant,balmy,None,None
119,4,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
120,5,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
121,5,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
122,5,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None
123,5,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
124,5,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
125,5,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
126,5,butter,None,None,None,None,None,None,None
127,5,kuning,Synset('yellow.s.01'),[],[],of the color intermediate between green and or...,yellow,None,None
128,5,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
129,5,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
130,5,roti,Synset('bread.n.01'),"[Synset('baked_goods.n.01'), Synset('starches....","[Synset('anadama_bread.n.01'), Synset('bap.n.0...",food made from dough of flour or meal and usua...,bread,"[baked_goods, starches]","[anadama_bread, bap, barmbrack, breadstick, br..."
131,5,putar,Synset('spin.n.02'),[Synset('rotation.n.01')],"[Synset('birling.n.01'), Synset('pirouette.n.0...",the act of rotating rapidly,spin,[rotation],"[birling, pirouette]"
132,5,nota,Synset('note.n.01'),[Synset('written_record.n.01')],"[Synset('jotting.n.01'), Synset('marginalia.n....",a brief written record,note,[written_record],"[jotting, marginalia, memo, minute]"
133,5,nenas,None,None,None,None,None,None,None
134,5,vanilla,None,None,None,None,None,None,None
135,5,gandum,Synset('grain.n.02'),[Synset('foodstuff.n.02')],"[Synset('barley.n.01'), Synset('buckwheat.n.02...",foodstuff prepared from the starchy grains of ...,grain,[foodstuff],"[barley, buckwheat, corn, grist, groats, malt,..."
136,5,adunan,Synset('blend.n.03'),[Synset('combination.n.07')],"[Synset('confluence.n.02'), Synset('homogeniza...",the act of blending components together thorou...,blend,[combination],"[confluence, homogenization]"
137,5,suhu,Synset('temperature.n.01'),"[Synset('fundamental_quantity.n.01'), Synset('...","[Synset('absolute_temperature.n.01'), Synset('...",the degree of hotness or coldness of a body or...,temperature,"[fundamental_quantity, physical_property]","[absolute_temperature, absolute_zero, body_tem..."
138,5,mentega,Synset('penuche.n.01'),[Synset('fudge.n.01')],[],fudge made with brown sugar and butter and mil...,penuche,[fudge],None

### Make Ontology

In [ ]:
# Make Ontology
azieTelurOnto = get_ontology("http://test.org/azieTelur.owl")
makeOntology(azieTelurOnto, telurWN)
azieTelurOnto.save(file = "azieTelur.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1g-pUsOrn9SVSd9yvoTgNN5JrlVEIU0pA"

In [ ]:
wiki_telur = pd.read_excel("AzieTelurFinal.xlsx").iloc[:, 1:]

# Translate
wiki_telur["Category"] = translate(wiki_telur["Category"])
wiki_telur.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_telur[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
telurTabel_new = tabel_1981.copy()
telurTabel_new["correct_category"] = all_cat
telurTabel_new["suggestion"] = all_suggestion

# Export Result to File
telurTabel_new.to_excel("telurTabel_Result.xlsx")
telurTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "telurTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
telurTabel_new = concatListInColumn(telurTabel_new)
telurTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, telurTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_telur.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
telurWiki_new = wiki_df.copy()
telurWiki_new["suggest"] = all_cat

# Export Result to file
telurWiki_new.to_excel("telurWiki_Result.xlsx")
telurWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "telurWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieTelurgOntoWiki = get_ontology("http://test.org/azieTelurg_onto_wiki.owl")
makeOntology_wiki(azieTelurgOntoWiki, telurgWiki_new)
azieTelurgOntoWiki.save(file = "azieTelurg_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = telurWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
telurWN_new = listToDataframe(changesList, tableWordnet)
telurWN_new.to_excel("telurWN_Result.xlsx")
telurWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "telurWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Tahu

In [ ]:
!gdown --id "1hdmUEtcYw_oPbDjARWqq3_muGGgIOvSP"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hdmUEtcYw_oPbDjARWqq3_muGGgIOvSP
To: /content/aziekitchen-tahu.jl
100% 5.99M/5.99M [00:00<00:00, 19.1MB/s]

In [ ]:
tahu=pd.read_json(r'/content/aziekitchen-tahu.jl', lines = True)

tahu.to_pickle(r'/content/raw_df.pkl')
tahu = pre_cleaning_text(tahu, threshold=20)

#tahu["cleaned_description"] = cleaning_text(tahu["page_description"])
#ingredients_all = tahu["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Tahu

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = tahu.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5      0.221312  0.033289       1        1  39.595308
6      0.196397 -0.050944       2        1  18.861479
4     -0.003690  0.303936       3        1  16.978463
0      0.233395 -0.129605       4        1  13.182474
2     -0.224273 -0.072141       5        1   5.447509
3     -0.209072 -0.053514       6        1   3.070367
1     -0.214069 -0.031022       7        1   2.864400, topic_info=                           Term         Freq        Total Category  logprob  \
20                       bawang  1080.000000  1080.000000  Default  30.0000
67                         cili   694.000000   694.000000  Default  29.0000
884                      sotong   144.000000   144.000000  Default  28.0000
171                      tepung   232.000000   232.000000  Default  27.0000
74                         gula   674.000000   674.000000  Default  26.0000
163                       layan   227.000000   227.000000  Default  25.0000
504                         sos   155.000000   155.000000  Default  24.0000
69                       santan   487.000000   487.000000  Default  23.0000
76                       keping   328.000000   328.000000  Default  22.0000
60                         daun   495.000000   495.000000  Default  21.0000
21                        putih   463.000000   463.000000  Default  20.0000
29                        tumis   204.000000   204.000000  Default  19.0000
482                      goreng   225.000000   225.000000  Default  18.0000
235                       telur   309.000000   309.000000  Default  17.0000
19                         ulas   392.000000   392.000000  Default  16.0000
688                      tomato   150.000000   150.000000  Default  15.0000
22                        hiris   313.000000   313.000000  Default  14.0000
84                        merah   430.000000   430.000000  Default  13.0000
89                        pulut   240.000000   240.000000  Default  12.0000
23                       serbuk   292.000000   292.000000  Default  11.0000
27                        garam   899.000000   899.000000  Default  10.0000
534                      perasa   125.000000   125.000000  Default   9.0000
501                       udang   160.000000   160.000000  Default   8.0000
280                      daging   141.000000   141.000000  Default   7.0000
1226                        mee    95.000000    95.000000  Default   6.0000
61                       kunyit   312.000000   312.000000  Default   5.0000
172                       beras   214.000000   214.000000  Default   4.0000
4104                   catilisa    50.000000    50.000000  Default   3.0000
126                        kari   111.000000   111.000000  Default   2.0000
169                        jawa   109.000000   109.000000  Default   1.0000
76                       keping   327.799591   328.541061   Topic1  -3.8250
89                        pulut   240.043601   240.785697   Topic1  -4.1365
172                       beras   213.686650   214.429406   Topic1  -4.2528
164               penyediaannya    93.250799    93.992221   Topic1  -5.0821
222                     youtube    83.071533    83.812523   Topic1  -5.1977
83                     lengkuas    62.010977    62.751783   Topic1  -5.4900
1150                    dikisar    56.382213    57.130292   Topic1  -5.5852
217                         jer    51.443797    52.195168   Topic1  -5.6769
479                     dikacau    49.960674    50.704498   Topic1  -5.7061
1260                     kepala    47.273433    48.015584   Topic1  -5.7614
600                    direndam    44.536574    45.278943   Topic1  -5.8210
55                      rendang    44.301328    45.042389   Topic1  -5.8263
1216                      masin    38.592743    39.334040   Topic1  -5.9643
263                      kerang    37.638121    38.378971   Topic1  -5.9893
1071                        teh    37.586811    38.333899   Topic1  -5.9907
703                   menpunyai    36.702346    37.445358   Topic1  -6.0145
545                     dimasak    35.179830    35.923178   Topic1  -6.0569
466                       basuh    33.846741    34.590577   Topic1  -6.0955
216                     separuh    34.356619    35.115948   Topic1  -6.0806
542                     kampung    33.383458    34.126693   Topic1  -6.1093
1147                      petai    32.857469    33.598432   Topic1  -6.1252
1246                     terung    32.200044    32.941461   Topic1  -6.1454
15                      mencuba   140.630137   144.051364   Topic1  -4.6712
278                       gulai    29.410773    30.153409   Topic1  -6.2360
59                        helai   127.739928   131.272261   Topic1  -4.7674
420                       mesti    26.078965    26.824218   Topic1  -6.3562
255                   segenggam    24.494334    25.236497   Topic1  -6.4189
225                       nenas    23.743340    24.486746   Topic1  -6.4501
462                       pucuk    22.669686    23.409922   Topic1  -6.4963
120                    kelantan    22.712905    23.456175   Topic1  -6.4944
69                       santan   467.928790   487.443264   Topic1  -3.4690
14                      selamat   152.863697   158.263843   Topic1  -4.5878
244                         tos    52.037260    53.778881   Topic1  -5.6654
130                      kering   196.693939   207.187309   Topic1  -4.3357
79                        serai   147.563300   157.184522   Topic1  -4.6231
1006                     sambal    68.626939    72.040034   Topic1  -5.3887
61                       kunyit   278.685056   312.096972   Topic1  -3.9873
894                   kegemaran    69.222564    73.293332   Topic1  -5.3800
213                     sekejap    51.122031    53.768934   Topic1  -5.6831
167                       ketuk    67.070840    72.493535   Topic1  -5.4116
135                        kuah   102.235143   117.615685   Topic1  -4.9901
80                         inci   211.355177   269.926787   Topic1  -4.2638
77                         asam   253.767689   336.814330   Topic1  -4.0809
68                        kisar   306.390899   422.755038   Topic1  -3.8925
117                     tangkai   132.741551   162.970049   Topic1  -4.7290
27                        garam   584.027096   899.172481   Topic1  -3.2474
25                         ikan   254.223112   368.412473   Topic1  -4.0791
74                         gula   411.268867   674.759540   Topic1  -3.5981
163                       layan   167.254928   227.524007   Topic1  -4.4978
109                      kacang    85.203703   103.165792   Topic1  -5.1723
184                        nota   112.273934   151.497553   Topic1  -4.8964
60                         daun   264.900944   495.918325   Topic1  -4.0380
134                        biji   299.858439   631.323256   Topic1  -3.9140
67                         cili   319.982264   694.054587   Topic1  -3.8491
57                         ayam   193.463037   338.122839   Topic1  -4.3523
227                        padi   126.523620   193.618222   Topic1  -4.7769
84                        merah   209.255908   430.655404   Topic1  -4.2738
70                        pekat   131.159057   208.000072   Topic1  -4.7409
78                       batang   119.818602   181.108137   Topic1  -4.8314
31                          air   228.617014   620.685358   Topic1  -4.1853
20                       bawang   244.578916  1080.760843   Topic1  -4.1178
19                         ulas   157.441868   392.733161   Topic1  -4.5583
21                        putih   145.628444   463.069848   Topic1  -4.6363
126                        kari   110.768213   111.518603   Topic2  -4.1683
169                        jawa   108.644430   109.395206   Topic2  -4.1877
125                      rempah   108.335037   109.085051   Topic2  -4.1905
283                       bunga    85.334444    86.086310   Topic2  -4.4292
687                     kentang    57.971188    58.721748   Topic2  -4.8158
86                         labu    44.813625    45.566842   Topic2  -5.0733
533                      jintan    38.554302    39.304657   Topic2  -5.2237
284                      lawang    37.980148    38.729994   Topic2  -5.2387
285                     rebusan    37.482810    38.234401   Topic2  -5.2519
330                     atasnya    35.807141    36.602832   Topic2  -5.2976
226                       bendi    32.964116    33.714184   Topic2  -5.3803
631                    ditumbuk    33.168812    33.928969   Topic2  -5.3742
168                         pes    29.611609    30.363804   Topic2  -5.4876
690                      pelaga    27.158706    27.909249   Topic2  -5.5741
1213                      halba    22.333302    23.083497   Topic2  -5.7697
1898                      bawal    34.680577    35.922015   Topic2  -5.3296
699                     cengkih    19.882622    20.636022   Topic2  -5.8859
689                     penumis    18.177230    18.927097   Topic2  -5.9756
583                      kuntum    17.755771    18.506542   Topic2  -5.9991
1142                     kantan    15.717473    16.468132   Topic2  -6.1210
1143                    pelepah    14.233689    14.985089   Topic2  -6.2202
1557                   dimayang    13.886367    14.638858   Topic2  -6.2449
677                        dadu    41.674159    44.204718   Topic2  -5.1459
286                     diikuti    12.507646    13.281888   Topic2  -6.3494
700                        sapi    12.084530    12.838146   Topic2  -6.3838
1727                    kerutuk    11.840738    12.591183   Topic2  -6.4042
1214                      knorr    11.157776    11.908954   Topic2  -6.4636
2112                      babas     9.726467    10.476220   Topic2  -6.6009
3314                       rose     9.598157    10.349627   Topic2  -6.6142
2868                     cooker     8.086567     8.836979   Topic2  -6.7856
549                       hitam    44.420287    48.719404   Topic2  -5.0821
280                      daging   127.398938   141.785540   Topic2  -4.0284
685                       belah    31.160103    34.222450   Topic2  -5.4366
1818                menggelegak    31.275387    34.437028   Topic2  -5.4329
852                    taburkan    53.182901    62.547945   Topic2  -4.9020
282                        kayu    54.739717    67.710918   Topic2  -4.8732
129                      campur    25.519155    30.302371   Topic2  -5.6363
22                        hiris   168.058191   313.980030   Topic2  -3.7515
211                       manis    89.592026   156.233465   Topic2  -4.3805
20                       bawang   403.141902  1080.760843   Topic2  -2.8765
81                        halia   113.596759   226.652415   Topic2  -4.1431
680                         sup    47.887628    71.841603   Topic2  -5.0069
19                         ulas   157.177307   392.733161   Topic2  -3.8184
134                        biji   210.034835   631.323256   Topic2  -3.5285
29                        tumis    96.261309   204.309796   Topic2  -4.3087
21                        putih   158.508415   463.069848   Topic2  -3.8100
31                          air   176.572662   620.685358   Topic2  -3.7020
84                        merah   130.783900   430.655404   Topic2  -4.0022
322                        buah    58.274197   135.858708   Topic2  -4.8106
23                       serbuk    81.962258   292.460336   Topic2  -4.4695
77                         asam    82.475845   336.814330   Topic2  -4.4633
25                         ikan    81.252709   368.412473   Topic2  -4.4782
60                         daun    88.624350   495.918325   Topic2  -4.3914
57                         ayam    77.443777   338.122839   Topic2  -4.5262
27                        garam   106.187874   899.172481   Topic2  -4.2106
67                         cili    93.360788   694.054587   Topic2  -4.3393
78                       batang    59.437135   181.108137   Topic2  -4.7908
80                         inci    58.000348   269.926787   Topic2  -4.8153
28                     panaskan    49.668182   163.591289   Topic2  -4.9704
68                        kisar    50.576497   422.755038   Topic2  -4.9523
290                      gandum    75.641595    76.411620   Topic3  -4.4446
249                      adunan    73.677684    74.447551   Topic3  -4.4709
287                      butter    71.461702    72.231288   Topic3  -4.5014
383                     pewarna    62.370949    63.141746   Topic3  -4.6375
352                        kuih    62.217577    62.987650   Topic3  -4.6400
849                      loyang    57.081254    57.850754   Topic3  -4.7261
298                     mentega    56.230211    57.000544   Topic3  -4.7411
171                      tepung   229.307885   232.518512   Topic3  -3.3355
303                        suhu    50.379942    51.149395   Topic3  -4.8510
295                     vanilla    49.740087    50.509647   Topic3  -4.8638
301                        oven    42.272704    43.042452   Topic3  -5.0264
754                       cream    41.161932    41.932673   Topic3  -5.0531
378                     lapisan    38.426359    39.195734   Topic3  -5.1218
741                         kek    37.590721    38.362911   Topic3  -5.1438
1097                     cheese    37.387465    38.158046   Topic3  -5.1493
747                        esen    35.315643    36.084836   Topic3  -5.2063
291                      baking    35.213888    35.983245   Topic3  -5.2091
906                    sejukkan    31.751085    32.520820   Topic3  -5.3127
633                        peti    27.923063    28.693504   Topic3  -5.4411
292                      powder    27.457684    28.227084   Topic3  -5.4579
1444                      acuan    27.465069    28.235059   Topic3  -5.4577
363                        sagu    28.094737    28.885268   Topic3  -5.4350
1081                        jus    27.323900    28.097141   Topic3  -5.4628
743                        gred    25.301073    26.070291   Topic3  -5.5397
240                     kembang    21.330568    22.100659   Topic3  -5.7104
1291                      tapis    21.273106    22.042583   Topic3  -5.7131
288                      kaster    20.888878    21.658266   Topic3  -5.7314
751                        soda    20.717645    21.486903   Topic3  -5.7396
1165                     perang    20.738715    21.513792   Topic3  -5.7386
640                         ais    20.470381    21.242381   Topic3  -5.7516
289                        susu    84.526557    91.724135   Topic3  -4.3335
396                       sejuk    70.057411    83.274439   Topic3  -4.5213
746                      jagung    44.893821    54.146902   Topic3  -4.9663
235                       telur   141.986551   309.949430   Topic3  -3.8149
180                       bakar    43.607670    60.491344   Topic3  -4.9954
238                     satukan    36.608027    47.793528   Topic3  -5.1703
74                         gula   220.329413   674.759540   Topic3  -3.3755
229                      sebati    53.714672    85.685861   Topic3  -4.7869
31                          air   169.791516   620.685358   Topic3  -3.6360
379                      pandan    72.545947   151.042334   Topic3  -4.4864
331                       tuang    42.952759    61.941388   Topic3  -5.0105
368                    caracara    41.382854    68.948385   Topic3  -5.0477
265                        gram    57.255799   146.895611   Topic3  -4.7231
134                        biji    92.709440   631.323256   Topic3  -4.2411
23                       serbuk    59.907084   292.460336   Topic3  -4.6778
598                        cair    40.250028    80.259919   Topic3  -5.0755
27                        garam    59.004775   899.172481   Topic3  -4.6930
90                       kuning    39.163842    74.556882   Topic3  -5.1028
70                        pekat    40.622408   208.000072   Topic3  -5.0663
504                         sos   154.181733   155.006404   Topic4  -3.4794
1226                        mee    94.710426    95.533911   Topic4  -3.9667
678                       maggi    62.403447    63.227437   Topic4  -4.3839
1162                      sadri    35.606443    36.429870   Topic4  -4.9450
1227                       hoon    32.156368    32.979826   Topic4  -5.0469
676                       karot    26.148581    26.974328   Topic4  -5.2537
1462                       sawi    23.862690    24.686427   Topic4  -5.3452
512                       tiram    23.221791    24.045491   Topic4  -5.3724
541                     berkuah    20.245456    21.071965   Topic4  -5.5096
1205                        haa    18.250649    19.076827   Topic4  -5.6133
1744                    seafood    16.755899    17.579381   Topic4  -5.6988
2113                      order    16.446937    17.270767   Topic4  -5.7174
1617                        kat    16.373239    17.196823   Topic4  -5.7219
4112                   bahannya    16.064865    16.888023   Topic4  -5.7409
4108                 dipecahkan    16.064469    16.888100   Topic4  -5.7409
4109                   worldddd    16.064469    16.888100   Topic4  -5.7409
4110                    mabeles    16.064469    16.888100   Topic4  -5.7409
4111                  berselera    16.064469    16.888100   Topic4  -5.7409
1199                        cap    10.425879    11.254789   Topic4  -6.1732
737                     holland    10.261430    11.086239   Topic4  -6.1891
1806                     mayang     9.867449    10.695077   Topic4  -6.2283
507                      taugeh     6.460548     7.284663   Topic4  -6.6518
4050                   layannnn    16.066640    18.297295   Topic4  -5.7408
1238                      tauhu     5.684679     6.509090   Topic4  -6.7798
17                        sayur    26.372393    30.525557   Topic4  -5.2452
1808                       sour     5.044932     5.888675   Topic4  -6.8991
1229                       fish     4.922510     5.746064   Topic4  -6.9237
1621                      kobis     4.898955     5.726660   Topic4  -6.9285
1405                     serong     4.570916     5.397959   Topic4  -6.9978
534                      perasa   105.350376   125.005246   Topic4  -3.8602
421                       lidah    10.427408    12.499911   Topic4  -6.1731
688                      tomato   109.289305   150.840779   Topic4  -3.8235
503                       kicap    54.699065    72.670975   Topic4  -4.5157
1464                     hidang    18.136705    23.353531   Topic4  -5.6196
16                         ikat    22.991569    31.013447   Topic4  -5.3824
482                      goreng   123.849076   225.805631   Topic4  -3.6985
679                      hiasan    22.163487    30.575466   Topic4  -5.4191
20                       bawang   432.565214  1080.760843   Topic4  -2.4478
29                        tumis   107.393850   204.309796   Topic4  -3.8410
501                       udang    87.562796   160.746143   Topic4  -4.0452
67                         cili   280.236845   694.054587   Topic4  -2.8819
23                       serbuk   121.367947   292.460336   Topic4  -3.7187
21                        putih   143.263679   463.069848   Topic4  -3.5528
60                         daun   141.917481   495.918325   Topic4  -3.5623
322                        buah    59.854913   135.858708   Topic4  -4.4256
323                       limau    42.721687    82.617785   Topic4  -4.7628
243                     disukai    47.145040   101.612958   Topic4  -4.6643
235                       telur    88.856124   309.949430   Topic4  -4.0305
82                        hidup    62.807405   178.990608   Topic4  -4.3775
27                        garam   149.627727   899.172481   Topic4  -3.5094
85                      dihiris    41.385597    95.636045   Topic4  -4.7946
84                        merah    90.140424   430.655404   Topic4  -4.0162
227                        padi    56.879103   193.618222   Topic4  -4.4766

Topic: 1
bawang, cili, sos, garam, putih, daun, goreng, serbuk, tomato, tumis, perasa, mee, merah, telur, udang, ulas, ayam, kisar, hidup, maggi, buah, padi, kicap, hiris, halia, disukai, air, limau, dihiris, lada

Topic: 2
catilisa, pisang, layan, sebiji, cerita, httpwwwcatilisacatterycom, httpcatilisablogspotcom, cattery, teow, kue, kucai, jala, dibelah, dah, versi, kegelapan, jantung, bancuhan, keledek, laksa, percik, susun, balikkan, dibalik, penerangnya, kaup, nak, gelas, laksam, tisu

Topic: 3
gambar, letakkan, freezer, entri, doh, pastri, pastikan, pasta, kebakaran, klik, simpan, pepper, disediakan, buah, pulak, cuba, soket, karipap, hidangan, parsley, sesuai, membuatnya, paste, unsalted, icing, perkakasan, malaysia, memasak, olive, lampu

Topic: 4
sotong, bilis, aween, makanan, ketupat, mahal, sumbatkan, tarik, dimakan, nasi, selera, menjamu, ikan, resepinya, makan, syarat, memasak, dah, garfu, tembok, zakat, keropok, dibeli, kangkung, hidangan, kongsikan, flakes, dikongsikan, dibina, spaghetti

Topic: 5
tepung, gula, air, telur, biji, susu, gandum, adunan, pandan, butter, sejuk, pewarna, kuih, serbuk, garam, gram, loyang, mentega, sebati, suhu, vanilla, jagung, bakar, tuang, oven, caracara, cream, pekat, cair, kuning

Topic: 6
garam, santan, gula, keping, cili, kisar, biji, kunyit, daun, ikan, asam, bawang, pulut, air, beras, inci, merah, kering, ayam, layan, ulas, selamat, serai, putih, mencuba, tangkai, pekat, helai, padi, batang

Topic: 7
bawang, biji, air, hiris, putih, ulas, merah, daging, halia, kari, jawa, rempah, garam, tumis, cili, manis, daun, bunga, asam, serbuk, ikan, ayam, batang, buah, inci, kentang, kayu, taburkan, kisar, panaskan

[(0,
  '0.086*"bawang" + 0.056*"cili" + 0.031*"sos" + 0.030*"garam" + 0.029*"putih" + 0.028*"daun" + 0.025*"goreng" + 0.024*"serbuk" + 0.022*"tomato" + 0.021*"tumis"'),
 (1,
  '0.045*"catilisa" + 0.026*"pisang" + 0.020*"layan" + 0.017*"sebiji" + 0.017*"cerita" + 0.015*"httpcatilisablogspotcom" + 0.015*"httpwwwcatilisacatterycom" + 0.015*"cattery" + 0.008*"teow" + 0.007*"kue"'),
 (2,
  '0.018*"gambar" + 0.013*"letakkan" + 0.008*"freezer" + 0.007*"entri" + 0.006*"doh" + 0.006*"pastri" + 0.006*"pastikan" + 0.005*"pasta" + 0.005*"kebakaran" + 0.005*"klik"'),
 (3,
  '0.123*"sotong" + 0.023*"bilis" + 0.017*"aween" + 0.017*"makanan" + 0.016*"ketupat" + 0.015*"mahal" + 0.014*"sumbatkan" + 0.014*"tarik" + 0.013*"dimakan" + 0.012*"nasi"'),
 (4,
  '0.036*"tepung" + 0.034*"gula" + 0.026*"air" + 0.022*"telur" + 0.014*"biji" + 0.013*"susu" + 0.012*"gandum" + 0.011*"adunan" + 0.011*"pandan" + 0.011*"butter"'),
 (5,
  '0.039*"garam" + 0.031*"santan" + 0.027*"gula" + 0.022*"keping" + 0.021*"cili" + 0.020*"kisar" + 0.020*"biji" + 0.019*"kunyit" + 0.018*"daun" + 0.017*"ikan"'),
 (6,
  '0.056*"bawang" + 0.029*"biji" + 0.025*"air" + 0.023*"hiris" + 0.022*"putih" + 0.022*"ulas" + 0.018*"merah" + 0.018*"daging" + 0.016*"halia" + 0.015*"kari"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
tahuProb = make_dictionary_terms_prob(ldamodel, id_map, d)
tahuProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
tahuWN = dfWordnet.copy()

tahuWN["Synonym_clean"] = cleanWN_Synonym(tahuWN["Synonym"])
tahuWN["Hypernim_clean"] = cleanWN(tahuWN["Hypernim"])
tahuWN["Hyponim_clean"] = cleanWN(tahuWN["Hyponim"])
tahuWN

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
1,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
2,1,sos,Synset('sauce.n.01'),[Synset('condiment.n.01')],"[Synset('aioli.n.01'), Synset('allemande.n.01'...",flavorful relish or dressing or topping served...,sauce,[condiment],"[aioli, allemande, anchovy_sauce, apricot_sauc..."
3,1,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
4,1,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
5,1,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
6,1,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
7,1,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
8,1,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
9,1,tumis,None,None,None,None,None,None,None
10,1,perasa,Synset('antenna.n.03'),[Synset('tentacle.n.02')],[],one of a pair of mobile appendages on the head...,antenna,[tentacle],None
11,1,mee,None,None,None,None,None,None,None
12,1,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
13,1,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
14,1,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
15,1,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
16,1,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
17,1,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"
18,1,hidup,Synset('life.n.10'),[Synset('living_thing.n.01')],[Synset('wildlife.n.01')],living things collectively,life,[living_thing],[wildlife]
19,1,maggi,None,None,None,None,None,None,None
20,1,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
21,1,padi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
22,1,kicap,Synset('soy_sauce.n.01'),[Synset('condiment.n.01')],[],thin sauce made of fermented soy beans,soy_sauce,[condiment],None
23,1,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
24,1,halia,Synset('peppery.s.01'),[],[],having the piquant burning taste of peppers,peppery,None,None
25,1,disukai,None,None,None,None,None,None,None
26,1,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
27,1,limau,Synset('orange.n.01'),[Synset('citrus.n.01')],"[Synset('bitter_orange.n.02'), Synset('sweet_o...",round yellow to orange fruit of any of several...,orange,[citrus],"[bitter_orange, sweet_orange, temple_orange]"
28,1,dihiris,None,None,None,None,None,None,None
29,1,lada,Synset('ratatouille.n.01'),[Synset('stew.n.02')],[],"a vegetable stew; usually made with tomatoes, ...",ratatouille,[stew],None
30,2,catilisa,None,None,None,None,None,None,None
31,2,pisang,Synset('banana.n.02'),[Synset('edible_fruit.n.01')],[],elongated crescent-shaped yellow fruit with so...,banana,[edible_fruit],None
32,2,layan,Synset('listen.v.01'),[Synset('perceive.v.01')],"[Synset('attend.v.05'), Synset('hark.v.01'), S...",hear with intention,listen,[perceive],"[attend, hark, hear_out, listen_in, listen_in]"
33,2,sebiji,None,None,None,None,None,None,None
34,2,cerita,Synset('interpretation.n.01'),[Synset('representation.n.01')],"[Synset('anagoge.n.01'), Synset('reinterpretat...",a mental representation of the meaning or sign...,interpretation,[representation],"[anagoge, reinterpretation]"
35,2,httpwwwcatilisacatterycom,None,None,None,None,None,None,None
36,2,httpcatilisablogspotcom,None,None,None,None,None,None,None
37,2,cattery,None,None,None,None,None,None,None
38,2,teow,None,None,None,None,None,None,None
39,2,kue,None,None,None,None,None,None,None
40,2,kucai,Synset('leek.n.02'),[Synset('vegetable.n.01')],[],related to onions; white cylindrical bulb and ...,leek,[vegetable],None
41,2,jala,Synset('net.n.06'),[Synset('fabric.n.01')],"[Synset('chicken_wire.n.01'), Synset('gauze.n....",an open fabric of string or rope or wire woven...,net,[fabric],"[chicken_wire, gauze, hairnet, reseau, safety_..."
42,2,dibelah,None,None,None,None,None,None,None
43,2,dah,None,None,None,None,None,None,None
44,2,versi,Synset('version.n.06'),[Synset('turn.n.02')],[],manual turning of a fetus in the uterus (usual...,version,[turn],None
45,2,kegelapan,Synset('dark.a.01'),[],[],devoid of or deficient in light or brightness;...,dark,None,None
46,2,jantung,Synset('cardiac.a.01'),[],[],of or relating to the heart,cardiac,None,None
47,2,bancuhan,Synset('brewing.n.01'),[Synset('production.n.07')],[],the production of malt beverages (as beer or a...,brewing,[production],None
48,2,keledek,Synset('sweet_potato.n.01'),[Synset('morning_glory.n.01')],[],pantropical vine widely cultivated in several ...,sweet_potato,[morning_glory],None
49,2,laksa,None,None,None,None,None,None,None
50,2,percik,Synset('sprinkle.n.02'),[Synset('watering.n.02')],[],the act of sprinkling or splashing water,sprinkle,[watering],None
51,2,susun,Synset('arrange.v.01'),[Synset('put.v.01')],"[Synset('alphabetize.v.01'), Synset('cascade.v...",put into a proper or systematic order,arrange,[put],"[alphabetize, cascade, catenate, chain, concor..."
52,2,balikkan,None,None,None,None,None,None,None
53,2,dibalik,None,None,None,None,None,None,None
54,2,penerangnya,None,None,None,None,None,None,None
55,2,kaup,None,None,None,None,None,None,None
56,2,nak,Synset('cub.n.02'),[Synset('male_child.n.01')],[],a male child (a familiar term of address to a ...,cub,[male_child],None
57,2,gelas,Synset('glass.n.02'),[Synset('container.n.01')],"[Synset('beer_glass.n.01'), Synset('bumper.n.0...",a container for holding liquids while drinking,glass,[container],"[beer_glass, bumper, goblet, highball_glass, l..."
58,2,laksam,None,None,None,None,None,None,None
59,2,tisu,Synset('tissue.n.01'),[Synset('body_part.n.01')],"[Synset('animal_tissue.n.01'), Synset('isthmus...",part of an organism consisting of an aggregate...,tissue,[body_part],"[animal_tissue, isthmus]"
60,3,gambar,Synset('frame.n.02'),[Synset('photograph.n.01')],[],a single one of a series of still transparent ...,frame,[photograph],None
61,3,letakkan,None,None,None,None,None,None,None
62,3,freezer,None,None,None,None,None,None,None
63,3,entri,None,None,None,None,None,None,None
64,3,doh,Synset('do.n.02'),[Synset('solfa_syllable.n.01')],[],the syllable naming the first (tonic) note of ...,do,[solfa_syllable],None
65,3,pastri,Synset('pastry.n.01'),[Synset('dough.n.01')],[Synset('puff_paste.n.01')],a dough of flour and water and shortening,pastry,[dough],[puff_paste]
66,3,pastikan,None,None,None,None,None,None,None
67,3,pasta,Synset('pasta.n.02'),[Synset('food.n.02')],"[Synset('couscous.n.02'), Synset('dumpling.n.0...",shaped and dried dough made from flour and wat...,pasta,[food],"[couscous, dumpling, farfalle, fedelline, fett..."
68,3,kebakaran,Synset('fire.n.02'),[Synset('attack.n.01')],"[Synset('antiaircraft_fire.n.01'), Synset('art...",the act of firing weapons or artillery at an e...,fire,[attack],"[antiaircraft_fire, artillery_fire, barrage, b..."
69,3,klik,Synset('snap.v.10'),[Synset('move.v.03')],[],cause to make a snapping sound,snap,[move],None
70,3,simpan,Synset('write.v.08'),[Synset('record.v.02')],[Synset('overwrite.v.01')],record data on a computer,write,[record],[overwrite]
71,3,pepper,None,None,None,None,None,None,None
72,3,disediakan,None,None,None,None,None,None,None
73,3,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
74,3,pulak,None,None,None,None,None,None,None
75,3,cuba,Synset('merely.r.01'),[],[],and nothing more,merely,None,None
76,3,soket,Synset('point.n.25'),[Synset('wall_socket.n.01')],[],a wall socket,point,[wall_socket],None
77,3,karipap,None,None,None,None,None,None,None
78,3,hidangan,Synset('course.n.07'),[Synset('nutriment.n.01')],"[Synset('appetizer.n.01'), Synset('dessert.n.0...",part of a meal served at one time,course,[nutriment],"[appetizer, dessert, entree]"
79,3,parsley,None,None,None,None,None,None,None
80,3,sesuai,Synset('appropriate.a.01'),[],[],suitable for a particular person or place or c...,appropriate,None,None
81,3,membuatnya,None,None,None,None,None,None,None
82,3,paste,None,None,None,None,None,None,None
83,3,unsalted,None,None,None,None,None,None,None
84,3,icing,None,None,None,None,None,None,None
85,3,perkakasan,Synset('equipment.n.01'),[Synset('instrumentality.n.03')],"[Synset('apparatus.n.01'), Synset('automation....",an instrumentality needed for an undertaking o...,equipment,[instrumentality],"[apparatus, automation, cooling_system, electr..."
86,3,malaysia,Synset('malaysia.n.01'),[],[],a constitutional monarchy in southeastern Asia...,malaysia,None,None
87,3,memasak,Synset('cooking.n.01'),[Synset('change_of_state.n.01')],"[Synset('baking.n.02'), Synset('boiling.n.02')...",the act of preparing something (as food) by th...,cooking,[change_of_state],"[baking, boiling, braising, broil, cuisine, fr..."
88,3,olive,None,None,None,None,None,None,None
89,3,lampu,Synset('lamp.n.01'),[Synset('source_of_illumination.n.01')],"[Synset('aladdin's_lamp.n.01'), Synset('candle...",an artificial source of visible illumination,lamp,[source_of_illumination],"[aladdin's_lamp, candle, discharge_lamp, elect..."
90,4,sotong,Synset('squid.n.02'),[Synset('decapod.n.02')],"[Synset('architeuthis.n.01'), Synset('loligo.n...",widely distributed fast-moving ten-armed cepha...,squid,[decapod],"[architeuthis, loligo, ommastrephes]"
91,4,bilis,None,None,None,None,None,None,None
92,4,aween,None,None,None,None,None,None,None
93,4,makanan,Synset('food.n.01'),[Synset('substance.n.07')],"[Synset('beverage.n.01'), Synset('chyme.n.01')...",any substance that can be metabolized by an an...,food,[substance],"[beverage, chyme, comestible, comfort_food, co..."
94,4,ketupat,None,None,None,None,None,None,None
95,4,mahal,Synset('dearly.r.02'),[],[],at a great cost,dearly,None,None
96,4,sumbatkan,None,None,None,None,None,None,None
97,4,tarik,Synset('pull.n.01'),[Synset('propulsion.n.02')],"[Synset('draft.n.11'), Synset('drag.n.06'), Sy...",the act of pulling; applying force to move som...,pull,[propulsion],"[draft, drag, draw, extirpation, pluck, tracti..."
98,4,dimakan,None,None,None,None,None,None,None
99,4,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
100,4,selera,Synset('appetite.n.01'),[Synset('craving.n.01')],"[Synset('stomach.n.04'), Synset('sweet_tooth.n...",a feeling of craving something; ; - Granville ...,appetite,[craving],"[stomach, sweet_tooth]"
101,4,menjamu,Synset('serve.v.15'),[Synset('move.v.15')],[Synset('ace.v.04')],put the ball into play,serve,[move],[ace]
102,4,ikan,Synset('fish.n.01'),[Synset('aquatic_vertebrate.n.01')],"[Synset('bony_fish.n.01'), Synset('bottom-feed...",any of various mostly cold-blooded aquatic ver...,fish,[aquatic_vertebrate],"[bony_fish, bottom-feeder, bottom_lurkers, car..."
103,4,resepinya,None,None,None,None,None,None,None
104,4,makan,Synset('food.n.01'),[Synset('substance.n.07')],"[Synset('beverage.n.01'), Synset('chyme.n.01')...",any substance that can be metabolized by an an...,food,[substance],"[beverage, chyme, comestible, comfort_food, co..."
105,4,syarat,Synset('circumstance.n.03'),[Synset('information.n.02')],"[Synset('justification.n.01'), Synset('mitigat...",information that should be kept in mind when m...,circumstance,[information],"[justification, mitigating_circumstance]"
106,4,memasak,Synset('cooking.n.01'),[Synset('change_of_state.n.01')],"[Synset('baking.n.02'), Synset('boiling.n.02')...",the act of preparing something (as food) by th...,cooking,[change_of_state],"[baking, boiling, braising, broil, cuisine, fr..."
107,4,dah,None,None,None,None,None,None,None
108,4,garfu,None,None,None,None,None,None,None
109,4,tembok,Synset('barricade.n.02'),[Synset('barrier.n.01')],[],a barrier (usually thrown up hastily) to imped...,barricade,[barrier],None
110,4,zakat,None,None,None,None,None,None,None
111,4,keropok,None,None,None,None,None,None,None
112,4,dibeli,None,None,None,None,None,None,None
113,4,kangkung,None,None,None,None,None,None,None
114,4,hidangan,Synset('course.n.07'),[Synset('nutriment.n.01')],"[Synset('appetizer.n.01'), Synset('dessert.n.0...",part of a meal served at one time,course,[nutriment],"[appetizer, dessert, entree]"
115,4,kongsikan,None,None,None,None,None,None,None
116,4,flakes,None,None,None,None,None,None,None
117,4,dikongsikan,None,None,None,None,None,None,None
118,4,dibina,None,None,None,None,None,None,None
119,4,spaghetti,None,None,None,None,None,None,None
120,5,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
121,5,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
122,5,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
123,5,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
124,5,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
125,5,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None
126,5,gandum,Synset('grain.n.02'),[Synset('foodstuff.n.02')],"[Synset('barley.n.01'), Synset('buckwheat.n.02...",foodstuff prepared from the starchy grains of ...,grain,[foodstuff],"[barley, buckwheat, corn, grist, groats, malt,..."
127,5,adunan,Synset('blend.n.03'),[Synset('combination.n.07')],"[Synset('confluence.n.02'), Synset('homogeniza...",the act of blending components together thorou...,blend,[combination],"[confluence, homogenization]"
128,5,pandan,None,None,None,None,None,None,None
129,5,butter,None,None,None,None,None,None,None
130,5,sejuk,Synset('balmy.s.02'),[],[],mild and pleasant,balmy,None,None
131,5,pewarna,Synset('coloring_material.n.01'),[Synset('material.n.01')],"[Synset('dye.n.01'), Synset('hematochrome.n.01...",any material used for its color,coloring_material,[material],"[dye, hematochrome, indicator, mordant, paint,..."
132,5,kuih,Synset('cake.n.03'),[Synset('baked_goods.n.01')],"[Synset('applesauce_cake.n.01'), Synset('baba....",baked goods made from or based on a mixture of...,cake,[baked_goods],"[applesauce_cake, baba, birthday_cake, boston_..."
133,5,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
134,5,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
135,5,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
136,5,loyang,Synset('brazen.a.02'),[],[],made of or resembling brass (as in color or ha...,brazen,None,None
137,5,mentega,Synset('penuche.n.01'),[Synset('fudge.n.01')],[],fudge made with brown sugar and butter and mil...,penuche,[fudge],None
138,5,sebati,Synset('appropriate.a.01'),[],[],suitable for a particular person or place or c...,appropriate,None,None
139,5,suhu,Synset('temperature.n.01'),"[Synset('fundamental_quantity.n.01'), Synset('...","[Synset('absolute_temperature.n.01'), Synset('...",the degree of hotness or coldness of a body or...,temperature,"[fundamental_quantity, physical_property]","[absolute_temperature, absolute_zero, body_tem..."
140,5,vanilla,None,None,None,None,None,None,None
141,5,jagung,Synset('corn.n.03'),[Synset('grain.n.02')],"[Synset('hominy.n.01'), Synset('popcorn.n.02')...",ears of corn that can be prepared and served f...,corn,[grain],"[hominy, popcorn, sweet_corn]"
142,5,bakar,Synset('burn.v.15'),[Synset('damage.v.01')],"[Synset('char.v.02'), Synset('scald.v.04')]","burn with heat, fire, or radiation",burn,[damage],"[char, scald]"
143,5,tuang,Synset('pour.v.01'),[Synset('move.v.02')],"[Synset('decant.v.01'), Synset('dribble.v.02')...",cause to run,pour,[move],"[decant, dribble, effuse, spill, transfuse]"
144,5,oven,None,None,None,None,None,None,None
145,5,caracara,None,None,None,None,None,None,None
146,5,cream,None,None,None,None,None,None,None
147,5,pekat,Synset('gluey.s.01'),[],[],having the sticky properties of an adhesive,gluey,None,None
148,5,cair,Synset('dissolve.v.09'),[Synset('liquefy.v.03')],"[Synset('defrost.v.01'), Synset('deliquesce.v....",become or cause to become soft or liquid,dissolve,[liquefy],"[defrost, deliquesce]"
149,5,kuning,Synset('yellow.s.01'),[],[],of the color intermediate between green and or...,yellow,None,None
150,6,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
151,6,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
152,6,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
153,6,keping,Synset('piece.n.01'),[Synset('part.n.02')],"[Synset('beam.n.02'), Synset('piece_of_cloth.n...",a separate part of a whole,piece,[part],"[beam, piece_of_cloth, piece_of_leather, scrap..."
154,6,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"

### Make Ontology

In [ ]:
# Make Ontology
azieTahuOnto = get_ontology("http://test.org/azieTahu.owl")
makeOntology(azieTahuOnto, tahuWN)
azieTahuOnto.save(file = "azieTahu.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1gwlbGvmECGXWAAcKeTOCbrZcR3XGSjoA"

In [ ]:
wiki_tahu = pd.read_excel("AzieTahuFinal.xlsx").iloc[:, 1:]

# Translate
wiki_tahu["Category"] = translate(wiki_tahu["Category"])
wiki_tahu.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_tahu[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
tahuTabel_new = tabel_1981.copy()
tahuTabel_new["correct_category"] = all_cat
tahuTabel_new["suggestion"] = all_suggestion

# Export Result to File
tahuTabel_new.to_excel("tahuTabel_Result.xlsx")
tahuTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tahuTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
tahuTabel_new = concatListInColumn(tahuTabel_new)
tahuTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, tahuTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_tahu.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
tahuWiki_new = wiki_df.copy()
tahuWiki_new["suggest"] = all_cat

# Export Result to file
tahuWiki_new.to_excel("tahuWiki_Result.xlsx")
tahuWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tahuWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieTahuOntoWiki = get_ontology("http://test.org/azieTahu_onto_wiki.owl")
makeOntology_wiki(azieTahuOntoWiki, tahuWiki_new)
azieTahuOntoWiki.save(file = "azieTahu_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = tahuWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
tahuWN_new = listToDataframe(changesList, tableWordnet)
tahuWN_new.to_excel("tahuWN_Result.xlsx")
tahuWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tahuWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Sapi

In [ ]:
!gdown --id "1hQOC2z9SX-wILlMSPn2ottwBLjZTqOEU"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1hQOC2z9SX-wILlMSPn2ottwBLjZTqOEU
To: /content/aziekitchen-sapi.jl
100% 264k/264k [00:00<00:00, 85.3MB/s]

In [ ]:
sapi=pd.read_json(r'/content/aziekitchen-sapi.jl', lines = True)

sapi.to_pickle(r'/content/raw_df.pkl')
sapi = pre_cleaning_text(sapi, threshold=20)

# sapi["cleaned_description"] = cleaning_text(sapi["page_description"])
# ingredients_all = sapi["cleaned_description"].apply(lambda x: treat_ingredients(x))

## GUI Sapi

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = sapi.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4     -0.067647  0.037148       1        1  46.623386
1     -0.131794 -0.004537       2        1  18.574887
0     -0.078108  0.037132       3        1  11.525455
3      0.152823  0.032354       4        1   7.683538
5      0.016459 -0.154635       5        1   5.764095
6      0.007403  0.030849       6        1   5.049435
2      0.100862  0.021690       7        1   4.779204, topic_info=              Term       Freq      Total Category  logprob  loglift
21          bawang  75.000000  75.000000  Default  30.0000  30.0000
54            ayam  43.000000  43.000000  Default  29.0000  29.0000
5             nasi  49.000000  49.000000  Default  28.0000  28.0000
26           kisar  24.000000  24.000000  Default  27.0000  27.0000
58          batang  15.000000  15.000000  Default  26.0000  26.0000
30           garam  35.000000  35.000000  Default  25.0000  25.0000
20            biji  53.000000  53.000000  Default  24.0000  24.0000
83          goreng  21.000000  21.000000  Default  23.0000  23.0000
190         tomato  28.000000  28.000000  Default  22.0000  22.0000
151            sup   9.000000   9.000000  Default  21.0000  21.0000
65            cili  26.000000  26.000000  Default  20.0000  20.0000
73           putih  34.000000  34.000000  Default  19.0000  19.0000
22           merah  34.000000  34.000000  Default  18.0000  18.0000
23           hiris  29.000000  29.000000  Default  17.0000  17.0000
79            daun  37.000000  37.000000  Default  16.0000  16.0000
158         tepung   8.000000   8.000000  Default  15.0000  15.0000
33           telur  13.000000  13.000000  Default  14.0000  14.0000
183         rempah  31.000000  31.000000  Default  13.0000  13.0000
47          kering  23.000000  23.000000  Default  12.0000  12.0000
82       ketepikan  10.000000  10.000000  Default  11.0000  11.0000
181         daging  23.000000  23.000000  Default  10.0000  10.0000
102          tumis  20.000000  20.000000  Default   9.0000   9.0000
3          selamat  11.000000  11.000000  Default   8.0000   8.0000
157           gram   8.000000   8.000000  Default   7.0000   7.0000
68            gula  22.000000  22.000000  Default   6.0000   6.0000
152         serbuk  10.000000  10.000000  Default   5.0000   5.0000
11            sapi  35.000000  35.000000  Default   4.0000   4.0000
77          kacang   6.000000   6.000000  Default   3.0000   3.0000
160         santan   7.000000   7.000000  Default   2.0000   2.0000
188         jintan   9.000000   9.000000  Default   1.0000   1.0000
309         puding   8.515218   9.114457   Topic1  -4.9342   0.6951
312         pisang   6.652547   7.251548   Topic1  -5.1811   0.6769
86            kuah   6.652211   7.251429   Topic1  -5.1811   0.6768
80        ketumbar  13.170652  14.549095   Topic1  -4.4981   0.6635
28             jus   5.720696   6.319950   Topic1  -5.3320   0.6634
52           gajus   3.858301   4.457105   Topic1  -5.7258   0.6188
338         mayang   3.858082   4.457058   Topic1  -5.7259   0.6187
12         majerin   3.858048   4.457021   Topic1  -5.7259   0.6187
29        sunquick   3.858052   4.457029   Topic1  -5.7259   0.6187
13          planta   3.858052   4.457041   Topic1  -5.7259   0.6187
284          basah   3.857942   4.456948   Topic1  -5.7259   0.6187
182         pinang   2.927026   3.525631   Topic1  -6.0021   0.5770
487        kastard   2.927016   3.525656   Topic1  -6.0021   0.5770
61           serai   2.927001   3.525649   Topic1  -6.0021   0.5770
323        aturkan   2.926941   3.525641   Topic1  -6.0021   0.5770
49         gaulkan   2.926879   3.525615   Topic1  -6.0021   0.5769
75           bulat   2.926842   3.525597   Topic1  -6.0021   0.5769
330       rosemary   2.926862   3.525627   Topic1  -6.0021   0.5769
27           ambil   2.926832   3.525604   Topic1  -6.0021   0.5769
87      disediakan   2.926855   3.525661   Topic1  -6.0021   0.5769
188         jintan   7.586804   9.402939   Topic1  -5.0497   0.5485
125        mangkuk   4.789885   5.985284   Topic1  -5.5096   0.5403
26           kisar  19.695725  24.872141   Topic1  -4.0957   0.5297
276         tumbuk   7.584118   9.810156   Topic1  -5.0500   0.5057
478         sardin   1.996060   2.594279   Topic1  -6.3849   0.5009
479          karot   1.996060   2.594279   Topic1  -6.3849   0.5009
480          kubis   1.996060   2.594279   Topic1  -6.3849   0.5009
299       cairsusu   1.995908   2.594226   Topic1  -6.3850   0.5009
386       letakkan   1.995912   2.594246   Topic1  -6.3850   0.5009
388        meresap   1.995905   2.594245   Topic1  -6.3850   0.5009
279        beriani   4.789637   6.248142   Topic1  -5.5096   0.4972
46          periuk   4.789559   6.248139   Topic1  -5.5096   0.4972
44         biarkan   4.789399   6.248124   Topic1  -5.5097   0.4972
47          kering  17.830322  23.980295   Topic1  -4.1952   0.4667
192        sekawan   5.723512   7.539814   Topic1  -5.3315   0.4875
17           manis  16.746064  23.592376   Topic1  -4.2579   0.4203
68            gula  15.971568  22.811352   Topic1  -4.3053   0.4066
76             tin  11.310223  16.185097   Topic1  -4.6504   0.4047
18            buah  16.686796  25.597805   Topic1  -4.2614   0.3352
79            daun  22.293059  37.897566   Topic1  -3.9718   0.2325
16            kayu  11.092712  16.747872   Topic1  -4.6698   0.3511
15          lawang  11.091336  16.747597   Topic1  -4.6699   0.3510
30           garam  20.368831  35.263279   Topic1  -4.0621   0.2142
4          mencuba   8.516967  12.636490   Topic1  -4.9340   0.3685
83          goreng  13.171735  21.411826   Topic1  -4.4980   0.2772
20            biji  27.854309  53.126481   Topic1  -3.7491   0.1174
21          bawang  36.632096  75.367769   Topic1  -3.4751   0.0416
34            susu  16.345947  28.046238   Topic1  -4.2821   0.2232
73           putih  18.416589  34.443767   Topic1  -4.1628   0.1370
14           bunga  12.877513  21.824306   Topic1  -4.5206   0.2355
11            sapi  18.252418  35.003084   Topic1  -4.1718   0.1119
33           telur   8.516521  13.146706   Topic1  -4.9341   0.3289
65            cili  14.107956  26.518252   Topic1  -4.4293   0.1320
58          batang   9.446608  15.278192   Topic1  -4.8304   0.2823
35            cair  14.380210  27.738985   Topic1  -4.4102   0.1061
5             nasi  21.834150  49.961278   Topic1  -3.9926  -0.0647
22           merah  16.903697  34.874953   Topic1  -4.2485   0.0388
54            ayam  19.516602  43.646542   Topic1  -4.1048  -0.0418
183         rempah  15.039328  31.920538   Topic1  -4.3654   0.0105
40             air  14.656553  32.231684   Topic1  -4.3912  -0.0250
25           halia  11.312081  20.647359   Topic1  -4.6502   0.1614
100         pandan  10.063837  17.661935   Topic1  -4.7671   0.2006
72            ulas  11.094000  22.027892   Topic1  -4.6697   0.0772
181         daging  11.320206  23.873572   Topic1  -4.6495   0.0169
23           hiris  12.285190  29.531867   Topic1  -4.5677  -0.1140
190         tomato  10.384361  28.800430   Topic1  -4.7358  -0.2570
229          kurma   3.558618   4.169780   Topic2  -4.8864   1.5249
103        penumis   3.509240   4.174157   Topic2  -4.9004   1.5098
256        dikacau   2.700351   3.310210   Topic2  -5.1624   1.4797
263         kelapa   2.698286   3.310025   Topic2  -5.1632   1.4790
265        belacan   2.698201   3.310051   Topic2  -5.1632   1.4790
223         teruja   2.697790   3.310055   Topic2  -5.1633   1.4788
264          parut   2.697717   3.310025   Topic2  -5.1634   1.4788
379          patah   1.841612   2.450586   Topic2  -5.5451   1.3977
225          pulak   1.840705   2.450528   Topic2  -5.5456   1.3972
244        dijamin   1.840554   2.450545   Topic2  -5.5457   1.3971
216         dengar   1.840202   2.450527   Topic2  -5.5459   1.3969
273           jawa   1.840150   2.450507   Topic2  -5.5459   1.3969
270          belah   1.839161   2.450431   Topic2  -5.5465   1.3964
272           asam   1.838281   2.450320   Topic2  -5.5469   1.3960
98           nipis   2.621333   4.020150   Topic2  -5.1921   1.2557
412        sukatan   0.982303   1.590948   Topic2  -6.1736   1.2012
289           tice   0.982272   1.590930   Topic2  -6.1737   1.2012
382         selera   0.982264   1.590927   Topic2  -6.1737   1.2011
288     kesemuanya   0.982260   1.590925   Topic2  -6.1737   1.2011
374        dicarik   0.982255   1.590925   Topic2  -6.1737   1.2011
381        menjamu   0.982260   1.590934   Topic2  -6.1737   1.2011
372            bwg   0.982257   1.590934   Topic2  -6.1737   1.2011
376         tompok   0.982245   1.590927   Topic2  -6.1737   1.2011
286   melaksanakan   0.982239   1.590923   Topic2  -6.1737   1.2011
411  majerinminyak   0.982258   1.590954   Topic2  -6.1737   1.2011
413         hancur   0.982254   1.590953   Topic2  -6.1737   1.2011
409     bahanbahan   0.982255   1.590957   Topic2  -6.1737   1.2011
415          dalca   0.982248   1.590955   Topic2  -6.1737   1.2011
408     gandingkan   0.982239   1.590956   Topic2  -6.1737   1.2011
380     dagingayam   0.982196   1.590926   Topic2  -6.1737   1.2011
254           pati   3.486016   5.718164   Topic2  -4.9070   1.1885
232        cincang   3.560107   6.032860   Topic2  -4.8860   1.1559
377       perlahan   1.841729   3.153920   Topic2  -5.5451   1.1454
378          lahan   1.841662   3.153905   Topic2  -5.5451   1.1454
135        memasak   3.558654   6.629425   Topic2  -4.8864   1.0612
259        rebusan   2.698026   4.882409   Topic2  -5.1633   1.0902
23           hiris  12.105513  29.531867   Topic2  -3.6621   0.7916
7            beras   9.456684  22.426825   Topic2  -3.9091   0.8198
31         pewarna   4.419917   9.458742   Topic2  -4.6697   0.9225
5             nasi  17.482261  49.961278   Topic2  -3.2946   0.6333
290       masaklah   1.841706   3.382037   Topic2  -5.5451   1.0756
375       disimpul   1.841703   3.382056   Topic2  -5.5451   1.0756
234         nampak   1.840525   3.382048   Topic2  -5.5457   1.0749
222     menjadikan   1.840388   3.382027   Topic2  -5.5458   1.0749
8         basmathi   3.995404   8.634545   Topic2  -4.7706   0.9127
181         daging   8.529842  23.873572   Topic2  -4.0122   0.6542
40             air  10.675250  32.231684   Topic2  -3.7878   0.5783
190         tomato   9.363043  28.800430   Topic2  -3.9190   0.5597
2            layan   3.559633   8.170435   Topic2  -4.8861   0.8525
35            cair   8.402559  27.738985   Topic2  -4.0272   0.4891
14           bunga   6.395360  21.824306   Topic2  -4.3002   0.4559
34            susu   7.440046  28.046238   Topic2  -4.1489   0.3564
100         pandan   5.524259  17.661935   Topic2  -4.4466   0.5211
183         rempah   7.467577  31.920538   Topic2  -4.1452   0.2307
20            biji   9.577013  53.126481   Topic2  -3.8964  -0.0300
11            sapi   7.419824  35.003084   Topic2  -4.1516   0.1321
102          tumis   5.569347  20.406639   Topic2  -4.4385   0.3848
21          bawang  10.012323  75.367769   Topic2  -3.8520  -0.3352
25           halia   5.243520  20.647359   Topic2  -4.4988   0.3128
79            daun   6.257468  37.897566   Topic2  -4.3220  -0.1178
18            buah   5.316214  25.597805   Topic2  -4.4850   0.1116
24            inci   4.408003  15.440481   Topic2  -4.6724   0.4298
22           merah   5.153909  34.874953   Topic2  -4.5160  -0.2287
186        cengkih   3.560587   9.467885   Topic2  -4.8858   0.7054
64             sos   3.484734   9.153380   Topic2  -4.9074   0.7176
54            ayam   5.059908  43.646542   Topic2  -4.5344  -0.4714
73           putih   4.671834  34.443767   Topic2  -4.6142  -0.3144
32          kuning   3.814808  13.831804   Topic2  -4.8169   0.3953
19          pelaga   3.799899  13.948986   Topic2  -4.8208   0.3829
15          lawang   3.747267  16.747597   Topic2  -4.8347   0.1861
16            kayu   3.746875  16.747872   Topic2  -4.8348   0.1860
72            ulas   3.727588  22.027892   Topic2  -4.8400  -0.0932
30           garam   3.749920  35.263279   Topic2  -4.8340  -0.5577
496           kuzi   2.443856   3.064435   Topic3  -4.7849   1.9343
428            dsb   2.443833   3.064432   Topic3  -4.7850   1.9343
274         campur   2.441081   3.064744   Topic3  -4.7861   1.9331
238           hati   2.440672   3.064785   Topic3  -4.7862   1.9329
499      memanjang   1.666324   2.286716   Topic3  -5.1679   1.8441
497        saffron   1.666318   2.286717   Topic3  -5.1679   1.8441
501            del   1.666291   2.286711   Topic3  -5.1679   1.8441
502          monte   1.666255   2.286704   Topic3  -5.1679   1.8441
503           roti   1.666248   2.286710   Topic3  -5.1679   1.8441
498       hempedal   1.666237   2.286704   Topic3  -5.1680   1.8441
500          blend   3.221457   4.545410   Topic3  -4.5087   1.8163
508            nya   0.888738   1.509003   Topic3  -5.7965   1.6312
509       istimewa   0.888717   1.509001   Topic3  -5.7965   1.6312
511           cuba   0.888705   1.508996   Topic3  -5.7965   1.6312
510        diganti   0.888701   1.508995   Topic3  -5.7965   1.6312
495        layannn   0.888675   1.509009   Topic3  -5.7965   1.6311
439       susunkan   0.888665   1.509009   Topic3  -5.7966   1.6311
445        blender   0.888661   1.509006   Topic3  -5.7966   1.6311
436         leaves   0.888661   1.509007   Topic3  -5.7966   1.6311
430       kejadian   0.888648   1.509005   Topic3  -5.7966   1.6311
440      diatasnya   0.888644   1.509005   Topic3  -5.7966   1.6311
417         juadah   0.888642   1.509003   Topic3  -5.7966   1.6311
421        ringkas   0.888641   1.509005   Topic3  -5.7966   1.6311
418          salah   0.888641   1.509006   Topic3  -5.7966   1.6311
425      contohnya   0.888637   1.509004   Topic3  -5.7966   1.6311
424      sampingan   0.888636   1.509003   Topic3  -5.7966   1.6311
435            bay   0.888633   1.509005   Topic3  -5.7966   1.6311
444          pasir   0.888630   1.509002   Topic3  -5.7966   1.6311
432         yellow   0.888630   1.509003   Topic3  -5.7966   1.6311
442          salsa   0.888629   1.509003   Topic3  -5.7966   1.6311
228       ditumbuk   2.439884   4.471443   Topic3  -4.7866   1.5549
253           kiub   3.761817   7.367387   Topic3  -4.3536   1.4885
251          rebus   2.437958   4.637375   Topic3  -4.7874   1.5176
255          maggi   2.705433   5.615790   Topic3  -4.6833   1.4303
118       kelantan   1.666336   3.218158   Topic3  -5.1679   1.5024
367          perap   1.666285   3.218135   Topic3  -5.1679   1.5024
54            ayam  13.681774  43.646542   Topic3  -3.0625   1.0006
83          goreng   7.109533  21.411826   Topic3  -3.7171   1.0581
152         serbuk   3.983224  10.303568   Topic3  -4.2964   1.2102
57          kunyit   2.443754   5.537117   Topic3  -4.7850   1.3427
195        dimakan   2.443953   5.630615   Topic3  -4.7849   1.3260
184           kari   2.443774   5.858686   Topic3  -4.7850   1.2862
5             nasi   9.058311  49.961278   Topic3  -3.4748   0.4530
21          bawang  11.242944  75.367769   Topic3  -3.2588   0.2580
183         rempah   5.906982  31.920538   Topic3  -3.9024   0.4735
314           jala   1.666537   4.149597   Topic3  -5.1678   1.2483
63           botol   1.666376   4.149605   Topic3  -5.1679   1.2482
218       facebook   1.429258   3.243133   Topic3  -5.3214   1.3412
190         tomato   4.970250  28.800430   Topic3  -4.0750   0.4037
20            biji   4.968198  53.126481   Topic3  -4.0755  -0.2090
22           merah   4.115135  34.874953   Topic3  -4.2638   0.0235
73           putih   4.063356  34.443767   Topic3  -4.2765   0.0233
35            cair   3.278152  27.738985   Topic3  -4.4912   0.0251
34            susu   3.285741  28.046238   Topic3  -4.4889   0.0163
65            cili   2.698505  26.518252   Topic3  -4.6858  -0.1245
18            buah   2.587439  25.597805   Topic3  -4.7279  -0.1312
7            beras   2.519698  22.426825   Topic3  -4.7544  -0.0255
25           halia   2.476936  20.647359   Topic3  -4.7715   0.0400
40             air   2.545687  32.231684   Topic3  -4.7441  -0.3779
76             tin   2.258457  16.185097   Topic3  -4.8638   0.1912
11            sapi   2.492085  35.003084   Topic3  -4.7654  -0.4817
79            daun   2.500480  37.897566   Topic3  -4.7620  -0.5578
30           garam   2.492555  35.263279   Topic3  -4.7652  -0.4889
393         adunan   2.912879   3.544517   Topic4  -4.2039   2.3698
558            cwn   2.912874   3.544547   Topic4  -4.2039   2.3698
404           tart   2.209690   2.841259   Topic4  -4.4802   2.3147
567          lecek   1.506699   2.137909   Topic4  -4.8631   2.2162
563         loyang   1.506684   2.137914   Topic4  -4.8631   2.2162
396          tebal   1.506669   2.137919   Topic4  -4.8631   2.2162
397           suhu   1.506650   2.137925   Topic4  -4.8632   2.2161
561           oven   1.506586   2.137946   Topic4  -4.8632   2.2161
434           labu   2.912957   4.963120   Topic4  -4.2039   2.0332
285          tuang   2.209927   3.772582   Topic4  -4.4801   2.0313
292          bakar   2.209834   3.772674   Topic4  -4.4801   2.0312
572       berkerak   0.803608   1.434591   Topic4  -5.4917   1.9866
505          segar   0.803593   1.434581   Topic4  -5.4917   1.9866
507         disapu   0.803589   1.434583   Topic4  -5.4917   1.9865
564       sebentar   0.803593   1.434596   Topic4  -5.4917   1.9865
504            cap   0.803584   1.434586   Topic4  -5.4917   1.9865
573     pembakaran   0.803590   1.434597   Topic4  -5.4917   1.9865
506       asingkan   0.803583   1.434585   Topic4  -5.4917   1.9865
401         kampit   0.803585   1.434599   Topic4  -5.4917   1.9865
575    dikeluarkan   0.803584   1.434599   Topic4  -5.4917   1.9865
407       keenakan   0.803583   1.434599   Topic4  -5.4917   1.9865
565         diatas   0.803582   1.434599   Topic4  -5.4917   1.9865
569        bersatu   0.803582   1.434600   Topic4  -5.4917   1.9865
562         lenser   0.803582   1.434600   Topic4  -5.4917   1.9865
559        dilecek   0.803577   1.434601   Topic4  -5.4917   1.9865
571   permukaannya   0.803576   1.434602   Topic4  -5.4917   1.9865
557          semak   0.803575   1.434602   Topic4  -5.4917   1.9865
566        kecuali   0.803573   1.434603   Topic4  -5.4917   1.9865
400         airnya   0.803572   1.434603   Topic4  -5.4917   1.9865
395            tat   0.803570   1.434604   Topic4  -5.4917   1.9865
160         santan   3.616229   7.485000   Topic4  -3.9876   1.8386
149          udang   2.210042   4.369226   Topic4  -4.4800   1.8845
159         gandum   2.209894   4.369304   Topic4  -4.4801   1.8844
157           gram   3.616043   8.201464   Topic4  -3.9877   1.7472
158         tepung   3.615876   8.832256   Topic4  -3.9877   1.6730
490          tapis   1.506721   3.069348   Topic4  -4.8631   1.8546
155            utk   1.506681   3.512278   Topic4  -4.8631   1.7197
287         butter   1.506865   3.857187   Topic4  -4.8630   1.6262
154          sulah   1.506793   3.972011   Topic4  -4.8631   1.5968
164        satukan   1.506724   3.985078   Topic4  -4.8631   1.5935
33           telur   2.912858  13.146706   Topic4  -4.2039   1.0591
228       ditumbuk   1.506786   4.471443   Topic4  -4.8631   1.4784
136           kuih   1.506702   4.597456   Topic4  -4.8631   1.4505
173          sejuk   1.506655   4.597495   Topic4  -4.8631   1.4505
68            gula   2.913444  22.811352   Topic4  -4.2037   0.5082
21          bawang   4.320746  75.367769   Topic4  -3.8096  -0.2929
20            biji   3.616668  53.126481   Topic4  -3.9875  -0.1210
97           halus   1.506739   6.487719   Topic4  -4.8631   1.1061
153           lada   1.506798   6.612629   Topic4  -4.8631   1.0871
22           merah   2.913515  34.874953   Topic4  -4.2037   0.0837
11            sapi   2.913419  35.003084   Topic4  -4.2037   0.0800
30           garam   2.913208  35.263279   Topic4  -4.2038   0.0725
79            daun   2.913532  37.897566   Topic4  -4.2037   0.0006
40             air   2.210390  32.231684   Topic4  -4.4799  -0.1137

Topic: 1
ayam, bawang, nasi, goreng, rempah, tomato, biji, merah, putih, serbuk, kiub, susu, cair, blend, maggi, cili, buah, air, beras, daun, garam, sapi, halia, dimakan, kuzi, dsb, kari, kunyit, campur, hati

Topic: 2
nasi, hiris, air, bawang, biji, beras, tomato, daging, cair, rempah, susu, sapi, bunga, daun, tumis, pandan, buah, halia, merah, ayam, putih, pewarna, inci, basmathi, kuning, pelaga, garam, lawang, kayu, ulas

Topic: 3
bawang, daun, merah, ayam, garam, ketepikan, selamat, tepung, talam, berlauk, putih, cili, sapi, mencuba, gula, digoreng, gram, sulah, serbuk, lada, sup, lauk, cina, kering, biji, tumis, air, panaskan, beras, ulas

Topic: 4
bawang, biji, santan, gram, tepung, daun, merah, gula, sapi, garam, labu, adunan, cwn, telur, air, udang, tuang, gandum, bakar, tart, ayam, ulas, cili, putih, kering, serbuk, panaskan, sup, butter, lada

Topic: 5
bawang, biji, daun, nasi, garam, kisar, ayam, putih, sapi, kering, merah, manis, buah, susu, gula, rempah, air, cair, cili, goreng, ketumbar, bunga, hiris, daging, halia, tin, ulas, kayu, lawang, tomato

Topic: 6
sup, bawang, batang, biji, hiris, rempah, ulas, merah, dadu, tulang, tomato, air, daun, putih, manis, kisar, cili, bunga, kuntum, kicap, lobak, padi, celery, amer, makan, chef, buah, lawang, inci, sapi

Topic: 7
bawang, cili, putih, biji, garam, tumis, tomato, kisar, kacang, puree, kering, sapi, gram, ayam, daging, nasi, bilis, telur, ketepikan, ikan, ulas, mentega, rempah, serbuk, dipotong, panaskan, sekawan, jintan, merah, tin

[(0,
  '0.047*"ayam" + 0.038*"bawang" + 0.031*"nasi" + 0.024*"goreng" + 0.020*"rempah" + 0.017*"tomato" + 0.017*"biji" + 0.014*"merah" + 0.014*"putih" + 0.014*"serbuk"'),
 (1,
  '0.037*"nasi" + 0.026*"hiris" + 0.023*"air" + 0.021*"bawang" + 0.020*"biji" + 0.020*"beras" + 0.020*"tomato" + 0.018*"daging" + 0.018*"cair" + 0.016*"rempah"'),
 (2,
  '0.035*"bawang" + 0.020*"daun" + 0.020*"merah" + 0.015*"ayam" + 0.015*"garam" + 0.015*"ketepikan" + 0.015*"selamat" + 0.015*"tepung" + 0.015*"talam" + 0.015*"berlauk"'),
 (3,
  '0.022*"bawang" + 0.019*"biji" + 0.019*"santan" + 0.019*"gram" + 0.019*"tepung" + 0.015*"daun" + 0.015*"merah" + 0.015*"gula" + 0.015*"sapi" + 0.015*"garam"'),
 (4,
  '0.031*"bawang" + 0.024*"biji" + 0.019*"daun" + 0.018*"nasi" + 0.017*"garam" + 0.017*"kisar" + 0.016*"ayam" + 0.016*"putih" + 0.015*"sapi" + 0.015*"kering"'),
 (5,
  '0.036*"sup" + 0.027*"bawang" + 0.027*"batang" + 0.023*"biji" + 0.018*"hiris" + 0.014*"rempah" + 0.014*"ulas" + 0.014*"merah" + 0.014*"dadu" + 0.014*"tulang"'),
 (6,
  '0.039*"bawang" + 0.024*"cili" + 0.024*"putih" + 0.024*"biji" + 0.024*"garam" + 0.020*"tumis" + 0.020*"tomato" + 0.020*"kisar" + 0.015*"kacang" + 0.015*"puree"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sapiProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sapiProb["bawang"] #probabilitas kata bawang pada setiap topik

## Wordnet

In [ ]:
sapiWN = dfWordnet.copy()

sapiWN["Synonym_clean"] = cleanWN_Synonym(sapiWN["Synonym"])
sapiWN["Hypernim_clean"] = cleanWN(sapiWN["Hypernim"])
sapiWN["Hyponim_clean"] = cleanWN(sapiWN["Hyponim"])
sapiWN

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
1,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
2,1,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
3,1,goreng,Synset('fried.s.01'),[],[],cooked by frying in fat,fried,None,None
4,1,rempah,Synset('spiciness.n.01'),[Synset('taste_property.n.01')],"[Synset('hotness.n.03'), Synset('nip.n.05'), S...",the property of being seasoned with spice and ...,spiciness,[taste_property],"[hotness, nip, pungency]"
5,1,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
6,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
7,1,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
8,1,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
9,1,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
10,1,kiub,Synset('cube.n.05'),[Synset('block.n.01')],"[Synset('die.n.01'), Synset('ice_cube.n.01')]",a block in the (approximate) shape of a cube,cube,[block],"[die, ice_cube]"
11,1,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None
12,1,cair,Synset('dissolve.v.09'),[Synset('liquefy.v.03')],"[Synset('defrost.v.01'), Synset('deliquesce.v....",become or cause to become soft or liquid,dissolve,[liquefy],"[defrost, deliquesce]"
13,1,blend,None,None,None,None,None,None,None
14,1,maggi,None,None,None,None,None,None,None
15,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
16,1,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
17,1,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
18,1,beras,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
19,1,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
20,1,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
21,1,sapi,Synset('cattle.n.01'),[Synset('bovine.n.01')],"[Synset('africander.n.01'), Synset('beef.n.01'...",domesticated bovine animals as a group regardl...,cattle,[bovine],"[africander, beef, bull, bullock, cow, dairy_c..."
22,1,halia,Synset('peppery.s.01'),[],[],having the piquant burning taste of peppers,peppery,None,None
23,1,dimakan,None,None,None,None,None,None,None
24,1,kuzi,None,None,None,None,None,None,None
25,1,dsb,None,None,None,None,None,None,None
26,1,kari,Synset('curry.n.01'),[Synset('dish.n.02')],[Synset('lamb_curry.n.01')],(East Indian cookery) a pungent dish of vegeta...,curry,[dish],[lamb_curry]
27,1,kunyit,Synset('turmeric.n.02'),[Synset('flavorer.n.01')],[],ground dried rhizome of the turmeric plant use...,turmeric,[flavorer],None
28,1,campur,Synset('blend.v.03'),[Synset('change_integrity.v.01')],"[Synset('absorb.v.05'), Synset('accrete.v.01')...",mix together different elements,blend,[change_integrity],"[absorb, accrete, admix, alloy, blend_in, conj..."
29,1,hati,Synset('heart.n.06'),[Synset('disposition.n.01')],[],an inclination or tendency of a certain kind,heart,[disposition],None
30,2,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
31,2,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"
32,2,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
33,2,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
34,2,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
35,2,beras,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
36,2,tomato,Synset('tomato.n.01'),[Synset('solanaceous_vegetable.n.01')],"[Synset('beefsteak_tomato.n.01'), Synset('cher...",mildly acid red or yellow pulpy fruit eaten as...,tomato,[solanaceous_vegetable],"[beefsteak_tomato, cherry_tomato]"
37,2,daging,Synset('fiber.n.05'),[Synset('fabric.n.01')],[],a leatherlike material made by compressing lay...,fiber,[fabric],None
38,2,cair,Synset('dissolve.v.09'),[Synset('liquefy.v.03')],"[Synset('defrost.v.01'), Synset('deliquesce.v....",become or cause to become soft or liquid,dissolve,[liquefy],"[defrost, deliquesce]"
39,2,rempah,Synset('spiciness.n.01'),[Synset('taste_property.n.01')],"[Synset('hotness.n.03'), Synset('nip.n.05'), S...",the property of being seasoned with spice and ...,spiciness,[taste_property],"[hotness, nip, pungency]"
40,2,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None
41,2,sapi,Synset('cattle.n.01'),[Synset('bovine.n.01')],"[Synset('africander.n.01'), Synset('beef.n.01'...",domesticated bovine animals as a group regardl...,cattle,[bovine],"[africander, beef, bull, bullock, cow, dairy_c..."
42,2,bunga,Synset('bloom.v.01'),[Synset('develop.v.10')],[Synset('effloresce.v.01')],produce or yield flowers,bloom,[develop],[effloresce]
43,2,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
44,2,tumis,None,None,None,None,None,None,None
45,2,pandan,None,None,None,None,None,None,None
46,2,buah,Synset('man.n.10'),[Synset('game_equipment.n.01')],"[Synset('black.n.06'), Synset('checker.n.03'),...",game equipment consisting of an object used in...,man,[game_equipment],"[black, checker, chessman, tile, white]"
47,2,halia,Synset('peppery.s.01'),[],[],having the piquant burning taste of peppers,peppery,None,None
48,2,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
49,2,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
50,2,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
51,2,pewarna,Synset('coloring_material.n.01'),[Synset('material.n.01')],"[Synset('dye.n.01'), Synset('hematochrome.n.01...",any material used for its color,coloring_material,[material],"[dye, hematochrome, indicator, mordant, paint,..."
52,2,inci,Synset('inch.n.01'),[Synset('linear_unit.n.01')],[],a unit of length equal to one twelfth of a foot,inch,[linear_unit],None
53,2,basmathi,None,None,None,None,None,None,None
54,2,kuning,Synset('yellow.s.01'),[],[],of the color intermediate between green and or...,yellow,None,None
55,2,pelaga,None,None,None,None,None,None,None
56,2,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
57,2,lawang,Synset('gate.n.01'),[Synset('movable_barrier.n.01')],"[Synset('head_gate.n.02'), Synset('lock-gate.n...",a movable barrier in a fence or wall,gate,[movable_barrier],"[head_gate, lock-gate, lychgate, portcullis, p..."
58,2,kayu,Synset('wooden.s.01'),[],[],made or consisting of (entirely or in part) or...,wooden,None,None
59,2,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
60,3,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
61,3,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
62,3,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
63,3,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
64,3,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
65,3,ketepikan,None,None,None,None,None,None,None
66,3,selamat,Synset('redemption.n.01'),[Synset('rescue.n.01')],"[Synset('absolution.n.02'), Synset('conversion...",(theology) the act of delivering from sin or s...,redemption,[rescue],"[absolution, conversion, expiation]"
67,3,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
68,3,talam,Synset('tray.n.01'),[Synset('receptacle.n.01')],"[Synset('alms_dish.n.01'), Synset('cafeteria_t...",an open receptacle for holding or displaying o...,tray,[receptacle],"[alms_dish, cafeteria_tray, cheeseboard, icetr..."
69,3,berlauk,None,None,None,None,None,None,None
70,3,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
71,3,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
72,3,sapi,Synset('cattle.n.01'),[Synset('bovine.n.01')],"[Synset('africander.n.01'), Synset('beef.n.01'...",domesticated bovine animals as a group regardl...,cattle,[bovine],"[africander, beef, bull, bullock, cow, dairy_c..."
73,3,mencuba,Synset('try_on.v.01'),[Synset('wear.v.09')],[],put on a garment in order to see whether it fi...,try_on,[wear],None
74,3,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
75,3,digoreng,None,None,None,None,None,None,None
76,3,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
77,3,sulah,Synset('hairless.a.01'),[],[],having no hair or fur,hairless,None,None
78,3,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
79,3,lada,Synset('ratatouille.n.01'),[Synset('stew.n.02')],[],"a vegetable stew; usually made with tomatoes, ...",ratatouille,[stew],None
80,3,sup,Synset('soup.n.01'),[Synset('dish.n.02')],"[Synset('alphabet_soup.n.02'), Synset('bisque....",liquid food especially of meat or fish or vege...,soup,[dish],"[alphabet_soup, bisque, borsch, broth, broth, ..."
81,3,lauk,Synset('dish.n.02'),[Synset('nutriment.n.01')],"[Synset('adobo.n.01'), Synset('applesauce.n.01...",a particular item of prepared food,dish,[nutriment],"[adobo, applesauce, bacon_and_eggs, barbecue, ..."
82,3,cina,Synset('china.n.01'),[],[],a communist nation that covers a vast territor...,china,None,None
83,3,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
84,3,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
85,3,tumis,None,None,None,None,None,None,None
86,3,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
87,3,panaskan,None,None,None,None,None,None,None
88,3,beras,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
89,3,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
90,4,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
91,4,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
92,4,santan,Synset('coconut_milk.n.02'),[Synset('milk.n.04')],[],clear to whitish fluid from within a fresh coc...,coconut_milk,[milk],None
93,4,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
94,4,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
95,4,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
96,4,merah,Synset('red.s.01'),[],[],of a color at the end of the color spectrum (n...,red,None,None
97,4,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
98,4,sapi,Synset('cattle.n.01'),[Synset('bovine.n.01')],"[Synset('africander.n.01'), Synset('beef.n.01'...",domesticated bovine animals as a group regardl...,cattle,[bovine],"[africander, beef, bull, bullock, cow, dairy_c..."
99,4,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
100,4,labu,Synset('gourd.n.01'),[Synset('bottle.n.01')],[],bottle made from the dried shell of a bottle g...,gourd,[bottle],None
101,4,adunan,Synset('blend.n.03'),[Synset('combination.n.07')],"[Synset('confluence.n.02'), Synset('homogeniza...",the act of blending components together thorou...,blend,[combination],"[confluence, homogenization]"
102,4,cwn,None,None,None,None,None,None,None
103,4,telur,Synset('egg.n.01'),[Synset('ovum.n.01')],"[Synset('nit.n.02'), Synset('roe.n.02'), Synse...",animal reproductive body consisting of an ovum...,egg,[ovum],"[nit, roe, roe, silkworm_seed, spawn]"
104,4,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
105,4,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
106,4,tuang,Synset('pour.v.01'),[Synset('move.v.02')],"[Synset('decant.v.01'), Synset('dribble.v.02')...",cause to run,pour,[move],"[decant, dribble, effuse, spill, transfuse]"
107,4,gandum,Synset('grain.n.02'),[Synset('foodstuff.n.02')],"[Synset('barley.n.01'), Synset('buckwheat.n.02...",foodstuff prepared from the starchy grains of ...,grain,[foodstuff],"[barley, buckwheat, corn, grist, groats, malt,..."
108,4,bakar,Synset('burn.v.15'),[Synset('damage.v.01')],"[Synset('char.v.02'), Synset('scald.v.04')]","burn with heat, fire, or radiation",burn,[damage],"[char, scald]"
109,4,tart,Synset('tart.n.02'),[Synset('pie.n.01')],"[Synset('apple_tart.n.01'), Synset('lobster_ta...",a small open pie with a fruit filling,tart,[pie],"[apple_tart, lobster_tart, quiche, tartlet]"
110,4,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
111,4,ulas,Synset('comment.v.01'),[Synset('note.v.01')],"[Synset('kibitz.v.01'), Synset('knock.v.06'), ...",make or write a comment on,comment,[note],"[kibitz, knock, wisecrack]"
112,4,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
113,4,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
114,4,kering,Synset('dead.s.17'),[],[],devoid of activity,dead,None,None
115,4,serbuk,Synset('crumb.n.03'),[Synset('morsel.n.02')],"[Synset('breadcrumb.n.01'), Synset('cracker_cr...",small piece of e.g. bread or cake,crumb,[morsel],"[breadcrumb, cracker_crumbs]"
116,4,panaskan,None,None,None,None,None,None,None
117,4,sup,Synset('soup.n.01'),[Synset('dish.n.02')],"[Synset('alphabet_soup.n.02'), Synset('bisque....",liquid food especially of meat or fish or vege...,soup,[dish],"[alphabet_soup, bisque, borsch, broth, broth, ..."
118,4,butter,None,None,None,None,None,None,None
119,4,lada,Synset('ratatouille.n.01'),[Synset('stew.n.02')],[],"a vegetable stew; usually made with tomatoes, ...",ratatouille,[stew],None
120,5,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
121,5,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
122,5,daun,Synset('blade.n.08'),[Synset('rotating_mechanism.n.01')],"[Synset('fan_blade.n.01'), Synset('impeller.n....",flat surface that rotates and pushes against a...,blade,[rotating_mechanism],"[fan_blade, impeller, paddle, rudder_blade]"
123,5,nasi,Synset('rice.n.01'),"[Synset('grain.n.02'), Synset('starches.n.01')]","[Synset('brown_rice.n.01'), Synset('paddy.n.03...",grains used as food either unpolished or more ...,rice,"[grain, starches]","[brown_rice, paddy, white_rice]"
124,5,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
125,5,kisar,Synset('grind.v.05'),[Synset('break_up.v.16')],"[Synset('mill.v.02'), Synset('pestle.v.01'), S...",reduce to small pieces or particles by poundin...,grind,[break_up],"[mill, pestle, pulp]"

### Make Ontology

In [ ]:
# Make Ontology
azieSapiOnto = get_ontology("http://test.org/azieSapi.owl")
makeOntology(azieSapiOnto, sapiWN)
azieSapiOnto.save(file = "azieSapi.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "129XYWHaftY_wNGcOIsI6xW6UvQMjKNT7"

In [ ]:
wiki_sapi = pd.read_excel("AzieSapiFinal.xlsx").iloc[:, 1:]

# Translate
wiki_sapi["Category"] = translate(wiki_sapi["Category"])
wiki_sapi.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_sapi[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
sapiTabel_new = tabel_1981.copy()
sapiTabel_new["correct_category"] = all_cat
sapiTabel_new["suggestion"] = all_suggestion

# Export Result to File
sapiTabel_new.to_excel("sapiTabel_Result.xlsx")
sapiTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
sapiTabel_new = concatListInColumn(sapiTabel_new)
sapiTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, sapiTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_sapi.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
sapiWiki_new = wiki_df.copy()
sapiWiki_new["suggest"] = all_cat

# Export Result to file
sapiWiki_new.to_excel("sapiWiki_Result.xlsx")
sapiWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
azieSapiOntoWiki = get_ontology("http://test.org/azieSapi_onto_wiki.owl")
makeOntology_wiki(azieSapiOntoWiki, sapiWiki_new)
azieSapiOntoWiki.save(file = "azieSapi_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = sapiWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
sapiWN_new = listToDataframe(changesList, tableWordnet)
sapiWN_new.to_excel("sapiWN_Result.xlsx")
sapiWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Apakah Performa Meningkat?
Ya, karena setelah stopword dihapus, pada visualisasi data, topik terlihat memiliki makna lebih jelas dan mudah untuk di klasifikasikan.

# Fiza

In [ ]:
!gdown --id "11Yf4HVqR_pLKHYP3jPsB9eL2M7Qtzjdp"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=11Yf4HVqR_pLKHYP3jPsB9eL2M7Qtzjdp
To: /content/Fiza.jl
100% 1.07M/1.07M [00:00<00:00, 145MB/s]

In [ ]:
fiza=pd.read_json(r'/content/Fiza.jl', lines = True)
fiza.rename(columns = {"Page_description":"page_description"}, inplace=True)
fiza["page_description"] = delist(fiza, "page_description")
fiza = pre_cleaning_text(fiza, threshold=30)

In [ ]:
fiza.head()

,URL,Page_Title,Publish_Date,Number_of_Commentary,page_description
0,http://fizalgk.blogspot.com/2017/01/6-kelebiha...,6 KELEBIHAN ACUAN SILIKON BERBANDING LOYANG BIASA,Khamis Januari 19 2017,0,"[-, , Semoga perkongsian dibawah ini memberi m..."
1,http://fizalgk.blogspot.com/2015/06/sayur-camp...,SAYUR CAMPUR BERGAJUS,Isnin Jun 22 2015,0,"[-, , -, Maggi® CukupRasa™ , Maggi® CukupRasa™..."
2,http://fizalgk.blogspot.com/2015/01/aiskrim-pa...,AISKRIM PASU,Khamis Januari 15 2015,0,"[Assalamualaikum, , , -, , -, AISKRIM PASU, Ba..."
3,http://fizalgk.blogspot.com/2013/09/aiskrim-bu...,AISKRIM BUAH CAMPURAN,Rabu September 25 2013,0,"[Assalamualaikum, , , -, , Aiskrim buah campur..."
4,http://fizalgk.blogspot.com/2012/10/pumkin-ais...,PUMPKIN ICE CREAM,Rabu Oktober 03 2012,2,"[-, , Sabar je lah...dalam cuaca panas begini ..."

## GUI Fiza

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = fiza.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0      0.213945 -0.028162       1        1  48.063741
2     -0.148415  0.199010       2        1  16.881908
4      0.104777  0.016820       3        1   9.431461
5     -0.065762  0.053686       4        1   8.480387
1     -0.117095  0.067976       5        1   7.052502
6      0.190214 -0.026280       6        1   6.875081
3     -0.177664 -0.283050       7        1   3.214920, topic_info=                     Term        Freq       Total Category  logprob  loglift
130                   air  714.000000  714.000000  Default  30.0000  30.0000
300                bawang  900.000000  900.000000  Default  29.0000  29.0000
394                 telur  463.000000  463.000000  Default  28.0000  28.0000
111                  cili  529.000000  529.000000  Default  27.0000  27.0000
92                    sos  248.000000  248.000000  Default  26.0000  26.0000
95                 tepung  356.000000  356.000000  Default  25.0000  25.0000
40                 adunan  214.000000  214.000000  Default  24.0000  24.0000
197                  gula  587.000000  587.000000  Default  23.0000  23.0000
514               mentega  192.000000  192.000000  Default  22.0000  22.0000
530                 udang  294.000000  294.000000  Default  21.0000  21.0000
85                 serbuk  325.000000  325.000000  Default  20.0000  20.0000
301                 putih  455.000000  455.000000  Default  19.0000  19.0000
84                  garam  555.000000  555.000000  Default  18.0000  18.0000
66                kedalam  406.000000  406.000000  Default  17.0000  17.0000
395                   teh  331.000000  331.000000  Default  16.0000  16.0000
234              mendidih  202.000000  202.000000  Default  15.0000  15.0000
165                  daun  390.000000  390.000000  Default  14.0000  14.0000
119                 merah  356.000000  356.000000  Default  13.0000  13.0000
337                  ikan  324.000000  324.000000  Default  12.0000  12.0000
476                coklat   85.000000   85.000000  Default  11.0000  11.0000
576                 pulut   91.000000   91.000000  Default  10.0000  10.0000
229                  susu  167.000000  167.000000  Default   9.0000   9.0000
261                 halus  160.000000  160.000000  Default   8.0000   8.0000
299                  ulas  305.000000  305.000000  Default   7.0000   7.0000
6                  loyang  148.000000  148.000000  Default   6.0000   6.0000
252                kacang  145.000000  145.000000  Default   5.0000   5.0000
110               tangkai  257.000000  257.000000  Default   4.0000   4.0000
113                   isi  136.000000  136.000000  Default   3.0000   3.0000
397                gandum  136.000000  136.000000  Default   2.0000   2.0000
618                  kari  182.000000  182.000000  Default   1.0000   1.0000
337                  ikan  323.524229  324.300598   Topic1  -4.0563   0.7302
525                  asam  177.495737  178.272074   Topic1  -4.6566   0.7283
340                sambal  154.531064  155.307240   Topic1  -4.7952   0.7276
593                   sup  151.340217  152.116967   Topic1  -4.8161   0.7275
583                 halia  150.999642  151.836818   Topic1  -4.8183   0.7271
835                 bilis  126.335019  127.111089   Topic1  -4.9967   0.7265
714                  jawa  118.069121  118.845323   Topic1  -5.0643   0.7261
661                  padi  103.489327  104.266654   Topic1  -5.1961   0.7252
777                 hiris   95.512245   96.289084   Topic1  -5.2763   0.7245
545                tumbuk   84.138064   84.923964   Topic1  -5.4031   0.7233
637               kentang   72.066923   72.844210   Topic1  -5.5580   0.7219
1382              holland   66.593103   67.372258   Topic1  -5.6370   0.7210
535               belacan   65.746678   66.522896   Topic1  -5.6498   0.7209
701                 serai   64.069470   64.845344   Topic1  -5.6756   0.7206
560              dimayang   63.130061   63.910118   Topic1  -5.6904   0.7204
580                  ekor   59.378107   60.154180   Topic1  -5.7517   0.7197
114                  ayam  223.015415  226.187363   Topic1  -4.4284   0.7185
534               secukup  237.685840  241.219962   Topic1  -4.3646   0.7179
805                 ketuk   48.166608   48.942652   Topic1  -5.9609   0.7167
610                rempah   47.278697   48.054855   Topic1  -5.9795   0.7164
755                 renih   45.634056   46.410137   Topic1  -6.0149   0.7158
662               kasturi   43.068293   43.845381   Topic1  -6.0728   0.7148
675                   bau   37.141992   37.918521   Topic1  -6.2208   0.7120
601                 timun   36.598554   37.378409   Topic1  -6.2356   0.7116
1826                laksa   35.141621   35.918312   Topic1  -6.2762   0.7108
746                tulang   34.835817   35.611912   Topic1  -6.2849   0.7106
704                 hidup   34.759127   35.534953   Topic1  -6.2872   0.7106
761               dibelah   33.819705   34.605424   Topic1  -6.3145   0.7097
2101                tempe   31.167173   31.943015   Topic1  -6.3962   0.7081
656               direbus   29.602940   30.381138   Topic1  -6.4477   0.7067
529                batang  120.486099  124.061367   Topic1  -5.0441   0.7034
146                  nasi  171.342538  179.467886   Topic1  -4.6919   0.6863
299                  ulas  287.177412  305.128158   Topic1  -4.1755   0.6720
300                bawang  819.070631  900.150212   Topic1  -3.1274   0.6383
110               tangkai  238.218205  257.016997   Topic1  -4.3624   0.6567
551                 hitam   91.295071   95.712046   Topic1  -5.3215   0.6854
619                daging  105.416432  111.134264   Topic1  -5.1777   0.6798
596                 tumis  194.483390  211.453041   Topic1  -4.5652   0.6490
127                  lada  168.280079  184.308223   Topic1  -4.7100   0.6417
108                goreng  234.098778  263.442191   Topic1  -4.3798   0.6146
111                  cili  445.546518  529.620189   Topic1  -3.7363   0.5598
119                 merah  301.284093  356.648200   Topic1  -4.1275   0.5639
112                kering  231.482031  273.132790   Topic1  -4.3911   0.5672
618                  kari  160.723908  182.181969   Topic1  -4.7559   0.6073
84                  garam  427.952777  555.965719   Topic1  -3.7766   0.4709
592                 limau  107.525989  117.516561   Topic1  -5.1579   0.6438
165                  daun  299.494461  390.930137   Topic1  -4.1335   0.4662
339                 rebus  132.295627  150.382423   Topic1  -4.9506   0.6045
302                 kisar  182.615290  227.149645   Topic1  -4.6282   0.5144
306                  inci  176.523509  221.064321   Topic1  -4.6621   0.5076
106                  biji  359.595857  551.803899   Topic1  -3.9506   0.3044
301                 putih  306.753619  455.865688   Topic1  -4.1095   0.3365
602                tomato  135.727194  158.132844   Topic1  -4.9249   0.5799
130                   air  365.092393  714.105498   Topic1  -3.9354   0.0618
85                 serbuk  188.885651  325.549596   Topic1  -4.5945   0.1883
530                 udang  179.824487  294.551070   Topic1  -4.6436   0.2392
197                  gula  243.134916  587.493325   Topic1  -4.3420  -0.1496
153            bahanbahan  181.640642  310.938171   Topic1  -4.6336   0.1951
256                santan  136.035868  209.422734   Topic1  -4.9227   0.3012
473                  esen   80.312956   81.069488   Topic2  -4.4034   1.7696
474               vanilla   64.350133   65.106681   Topic2  -4.6250   1.7672
1122                 keju   64.430512   65.188426   Topic2  -4.6237   1.7672
14                    kek   54.674150   55.430624   Topic2  -4.7879   1.7652
918                kastor   47.712898   48.469415   Topic2  -4.9241   1.7632
514               mentega  189.612286  192.619382   Topic2  -3.5443   1.7632
15                 muffin   45.109248   45.950211   Topic2  -4.9802   1.7605
25                   oven   87.496553   89.164423   Topic2  -4.3177   1.7600
497                  sapu   38.283342   39.040611   Topic2  -5.1443   1.7593
399                powder   34.094710   35.097389   Topic2  -5.2602   1.7499
46                  putar   25.736713   26.493694   Topic2  -5.5414   1.7499
1154              berbuih   25.761311   26.519513   Topic2  -5.5404   1.7499
265                  krim   25.133859   25.892245   Topic2  -5.5651   1.7492
161                  oreo   23.363159   24.121320   Topic2  -5.6381   1.7470
407                  gebu   21.337799   22.094438   Topic2  -5.7288   1.7441
877                diayak   20.186974   20.943572   Topic2  -5.7843   1.7421
177                keatas   19.350123   20.107028   Topic2  -5.8266   1.7406
74                   suhu   65.997636   68.642457   Topic2  -4.5997   1.7396
27                  lapik   18.663481   19.420272   Topic2  -5.8627   1.7392
1135               almond   17.956726   18.713189   Topic2  -5.9013   1.7377
2769                swiss   17.843674   18.600416   Topic2  -5.9077   1.7374
2770                 roll   17.843674   18.600416   Topic2  -5.9077   1.7374
199                  atur   16.609634   17.366759   Topic2  -5.9793   1.7344
519                  ayak   16.034487   16.791571   Topic2  -6.0146   1.7328
40                 adunan  204.141851  214.009842   Topic2  -3.4705   1.7317
1398          buttercream   15.439345   16.195892   Topic2  -6.0524   1.7311
1552           mengembang   14.557138   15.314102   Topic2  -6.1112   1.7282
259                 whisk   14.324821   15.082144   Topic2  -6.1273   1.7274
2758             rollcake   14.305645   15.062344   Topic2  -6.1287   1.7274
2477              karamel   13.662107   14.419178   Topic2  -6.1747   1.7250
756                  roti   75.282900   79.574665   Topic2  -4.4681   1.7235
6                  loyang  127.385563  148.302288   Topic2  -3.9421   1.6269
338                 bakar   84.620735  100.108413   Topic2  -4.3511   1.6109
397                gandum  105.290246  136.362409   Topic2  -4.1326   1.5203
229                  susu  126.243880  167.784623   Topic2  -3.9511   1.4945
821                  kaup   23.575086   26.267909   Topic2  -5.6291   1.6708
917                  gred   36.214902   43.703229   Topic2  -5.1998   1.5910
95                 tepung  206.469953  356.101477   Topic2  -3.4592   1.2339
392                kertas   32.690205   40.760266   Topic2  -5.3022   1.5583
516                 tabur   42.154559   58.451054   Topic2  -5.0480   1.4521
394                 telur  180.750060  463.643902   Topic2  -3.5922   0.8369
376                   yis   39.336975   55.059573   Topic2  -5.1171   1.4427
398                baking   36.870206   51.423209   Topic2  -5.1819   1.4462
66                kedalam  146.660164  406.368648   Topic2  -3.8012   0.7598
197                  gula  161.369730  587.493325   Topic2  -3.7056   0.4868
12                didalam   56.844545  109.202190   Topic2  -4.7490   1.1260
395                   teh  106.402246  331.541556   Topic2  -4.1221   0.6424
39                  tuang   61.851586  150.910516   Topic2  -4.6646   0.8870
132            membuatnya   78.899902  268.478730   Topic2  -4.4211   0.5543
1                 dibawah   46.532823  101.631910   Topic2  -4.9491   0.9977
153            bahanbahan   68.214867  310.938171   Topic2  -4.5666   0.2620
106                  biji   75.688473  551.803899   Topic2  -4.4627  -0.2076
230                  cair   52.258347  160.041934   Topic2  -4.8331   0.6597
357                sebati   48.036341  138.512944   Topic2  -4.9173   0.7199
468                pisang   43.446662   89.549937   Topic2  -5.0178   1.0557
154               mangkuk   45.481989  125.183802   Topic2  -4.9720   0.7665
133              panaskan   45.558168  205.931675   Topic2  -4.9703   0.2704
576                 pulut   90.303127   91.095345   Topic3  -3.7039   2.3524
828                 kobis   61.728448   62.528831   Topic3  -4.0844   2.3482
99                  sayur   35.252241   36.043657   Topic3  -4.6446   2.3389
847                   mee   30.006173   30.796635   Topic3  -4.8057   2.3351
814              cendawan   29.283620   30.076177   Topic3  -4.8301   2.3344
128              benggala   18.319933   19.113477   Topic3  -5.2991   2.3187
829                 dadar   17.597657   18.389290   Topic3  -5.3394   2.3171
2834              tempura   11.110079   11.901806   Topic3  -5.7993   2.2923
2049              diracik   11.189172   11.986993   Topic3  -5.7922   2.2922
732               dibuang    9.305339   10.099465   Topic3  -5.9765   2.2792
1694             lauklauk    9.023220    9.814268   Topic3  -6.0073   2.2771
1779               berair   17.510638   19.065907   Topic3  -5.3443   2.2760
842              kecilkan    8.867320    9.658784   Topic3  -6.0247   2.2756
1438                camca    8.802592    9.593721   Topic3  -6.0321   2.2751
1271             didihkan    8.679498    9.481265   Topic3  -6.0462   2.2728
2131                 oats    8.464793    9.256231   Topic3  -6.0712   2.2717
1269               serong    8.120793    8.915102   Topic3  -6.1127   2.2678
1923             bancuhan    7.983769    8.779055   Topic3  -6.1297   2.2662
1692      barulahmasukkan    6.721236    7.512062   Topic3  -6.3018   2.2499
1693      masaksepenuhnya    6.721236    7.512062   Topic3  -6.3018   2.2499
124                 putik    6.620637    7.417145   Topic3  -6.3169   2.2475
1492               butang    6.590615    7.385705   Topic3  -6.3215   2.2472
734                 pipit    6.477468    7.268230   Topic3  -6.3388   2.2459
1446                bendi    6.374902    7.167355   Topic3  -6.3547   2.2440
2146              sehelai    6.310202    7.100956   Topic3  -6.3649   2.2431
122                   bok    6.250990    7.042035   Topic3  -6.3744   2.2420
1494               saderi    6.167792    6.958755   Topic3  -6.3878   2.2405
1003                padat    6.052851    6.845825   Topic3  -6.4066   2.2380
123                  choy    5.810753    6.601860   Topic3  -6.4474   2.2335
1837              pembaca    5.675995    6.473589   Topic3  -6.4709   2.2296
819                 tauhu   20.649761   24.510835   Topic3  -5.1794   2.1897
224                 kukus   45.182624   62.201985   Topic3  -4.3964   2.0414
788                 bihun   16.544692   20.766861   Topic3  -5.4011   2.1338
2359            spaghetti   15.282726   19.654676   Topic3  -5.4804   2.1095
93                  tiram   40.571764   61.342270   Topic3  -4.5040   1.9477
92                    sos  115.405174  248.310468   Topic3  -3.4587   1.5949
234              mendidih   95.367750  202.146353   Topic3  -3.6494   1.6099
394                 telur  165.221515  463.643902   Topic3  -3.0998   1.3293
468                pisang   45.465413   89.549937   Topic3  -4.3902   1.6833
129                kuning   47.380459   99.059771   Topic3  -4.3489   1.6236
802                 masin   29.049240   56.768682   Topic3  -4.8381   1.6911
130                   air  173.495520  714.105498   Topic3  -3.0510   0.9462
640                  kuah   48.909044  132.607005   Topic3  -4.3172   1.3637
311                 kicap   38.356352  106.226540   Topic3  -4.5602   1.3425
530                 udang   70.706841  294.551070   Topic3  -3.9486   0.9342
628            sepenuhnya   20.437331   41.199277   Topic3  -5.1898   1.6601
301                 putih   80.077200  455.865688   Topic3  -3.8241   0.6219
26               pastikan   15.464241   25.943177   Topic3  -5.4686   1.8437
96                 jagung   32.501618  119.170263   Topic3  -4.7258   1.0619
725                 hijau   26.639125   83.832470   Topic3  -4.9247   1.2147
145             hidangkan   34.554724  180.085154   Topic3  -4.6646   0.7102
230                  cair   31.065866  160.041934   Topic3  -4.7710   0.7218
313                sotong   21.752519   66.174307   Topic3  -5.1274   1.2486
165                  daun   39.246573  390.930137   Topic3  -4.5373   0.0625
256                santan   30.397173  209.422734   Topic3  -4.7928   0.4311
197                  gula   30.084901  587.493325   Topic3  -4.8031  -0.6107
255                 pekat   24.361044  166.891098   Topic3  -5.0141   0.4368
664               cincang   21.296053   67.461793   Topic3  -5.1486   1.2081
95                 tepung   25.062756  356.101477   Topic3  -4.9857  -0.2927
119                 merah   25.044669  356.648200   Topic3  -4.9865  -0.2950
66                kedalam   23.093085  406.368648   Topic3  -5.0676  -0.5066
84                  garam   22.951323  555.965719   Topic3  -5.0737  -0.8262
2383             agaragar   48.165352   48.929484   Topic4  -4.2262   2.4517
204                   ais   42.395687   43.160465   Topic4  -4.3538   2.4495
409                 pasta   24.591925   25.358806   Topic4  -4.8984   2.4367
187              tembikai   22.975987   23.740367   Topic4  -4.9664   2.4347
79              cukuprasa   21.324091   22.088006   Topic4  -5.0410   2.4322
2280                laici   20.826297   21.590073   Topic4  -5.0646   2.4314
206                  beku   15.030929   15.796203   Topic4  -5.3907   2.4178
1861                whole   13.565005   14.329602   Topic4  -5.4933   2.4126
1862               kernel   13.565005   14.329602   Topic4  -5.4933   2.4126
1656                  boi   12.188599   12.952833   Topic4  -5.6003   2.4066
17                   kuih   11.773701   12.537801   Topic4  -5.6350   2.4045
1527                gelas   11.028124   11.792702   Topic4  -5.7004   2.4004
4                 silikon   10.443877   11.208045   Topic4  -5.7548   2.3968
2193             teringin    9.851057   10.618795   Topic4  -5.8132   2.3924
2124            mencukupi    9.839348   10.615598   Topic4  -5.8144   2.3915
210            buahbuahan    9.432420   10.198363   Topic4  -5.8567   2.3893
30             memudahkan    8.771112    9.551756   Topic4  -5.9294   2.3822
1953           baiklahjom    7.913738    8.677929   Topic4  -6.0322   2.3752
1955             tukarkan    7.913738    8.677929   Topic4  -6.0322   2.3752
2385        masakagaragar    7.824253    8.588478   Topic4  -6.0436   2.3742
2528               newage    7.630004    8.393909   Topic4  -6.0687   2.3720
2529             cookware    7.630004    8.393909   Topic4  -6.0687   2.3720
2831              truffle    6.864083    7.630172   Topic4  -6.1745   2.3616
136              golekkan    9.929165   11.111328   Topic4  -5.8053   2.3549
1984             langsung    6.310530    7.082647   Topic4  -6.2586   2.3520
444              mauripan    6.182702    6.946625   Topic4  -6.2791   2.3509
1914              nikmati    6.137874    6.907000   Topic4  -6.2863   2.3494
370                   eno    6.081575    6.845310   Topic4  -6.2956   2.3491
2384              bertali    5.904233    6.668624   Topic4  -6.3252   2.3457
331                kenyal    5.946258    6.719989   Topic4  -6.3181   2.3451
52               pengukus   15.967359   18.635849   Topic4  -5.3303   2.3129
78                  maggi   26.410507   32.120914   Topic4  -4.8271   2.2717
1954                cucur   14.935610   17.944652   Topic4  -5.3971   2.2839
11                  jenis   20.342098   28.734319   Topic4  -5.0881   2.1220
49                   peti   27.886197   42.956198   Topic4  -4.7727   2.0354
373                kelapa   39.421258   65.908961   Topic4  -4.4265   1.9534
242               blender   22.098338   33.933305   Topic4  -5.0053   2.0385
228                   tin   29.898344   58.530048   Topic4  -4.7030   1.7957
1769                siput   19.311125   33.039248   Topic4  -5.1401   1.9304
3                   acuan   23.215717   43.584284   Topic4  -4.9560   1.8375
237                 larut   19.532441   34.028774   Topic4  -5.1287   1.9123
130                   air  136.595619  714.105498   Topic4  -3.1838   0.8134
113                   isi   46.021633  136.551793   Topic4  -4.2717   1.3798
66                kedalam   87.704677  406.368648   Topic4  -3.6268   0.9341

Topic: 1
bawang, cili, garam, air, biji, ikan, putih, merah, daun, ulas, gula, tangkai, secukup, goreng, kering, ayam, tumis, serbuk, kisar, bahanbahan, udang, asam, inci, nasi, lada, kari, sambal, sup, halia, santan

Topic: 2
tepung, coklat, gula, garam, doh, teh, serbuk, air, masakan, secubit, pizza, gandum, cairkan, bebola, membuatnya, uli, cincang, ubi, telur, biji, keluarkan, sagu, campurkan, sebiji, ketepikan, greentea, double, badam, betik, didalam

Topic: 3
tepung, adunan, mentega, telur, gula, kedalam, loyang, susu, teh, gandum, oven, bakar, esen, membuatnya, biji, roti, bahanbahan, suhu, keju, vanilla, tuang, didalam, kek, cair, sebati, kastor, dibawah, panaskan, mangkuk, muffin

Topic: 4
coleslaw, mayonis, gula, cuka, biskut, singapore, halus, makan, bawang, digaul, foto, merah, menjaga, lobak, diperap, gaul, nestum, gram, kesegaran, perap, canai, jem, pastikan, toskan, untukmengelakkan, minitperah, benarbenar, udara, kedap, garam

Topic: 5
air, telur, sos, mendidih, pulut, putih, udang, kobis, kuah, kuning, pisang, kukus, tiram, daun, kicap, sayur, hidangkan, jagung, cair, santan, gula, mee, cendawan, masin, hijau, tepung, merah, pekat, kedalam, garam

Topic: 6
air, kedalam, gula, agaragar, isi, ais, tuang, kelapa, susu, jagung, tepung, pasir, beras, buah, tin, biji, kiub, garam, peti, kisar, maggi, membuatnya, pasta, acuan, tembikai, pekat, blender, sosej, halus, cukuprasa

Topic: 7
cili, serbuk, bawang, biji, udang, teh, daun, hijau, putih, sos, kacang, manis, puding, kicap, mangga, dapur, kuali, pekat, isi, panaskan, matikan, bunga, pucuk, kulit, kunyit, pes, cair, kayu, kue, inci

[(0,
  '0.044*"bawang" + 0.024*"cili" + 0.023*"garam" + 0.020*"air" + 0.019*"biji" + 0.017*"ikan" + 0.016*"putih" + 0.016*"merah" + 0.016*"daun" + 0.015*"ulas"'),
 (1,
  '0.030*"tepung" + 0.030*"coklat" + 0.023*"gula" + 0.022*"garam" + 0.020*"doh" + 0.020*"teh" + 0.016*"serbuk" + 0.014*"air" + 0.014*"masakan" + 0.013*"secubit"'),
 (2,
  '0.031*"tepung" + 0.031*"adunan" + 0.029*"mentega" + 0.028*"telur" + 0.025*"gula" + 0.022*"kedalam" + 0.019*"loyang" + 0.019*"susu" + 0.016*"teh" + 0.016*"gandum"'),
 (3,
  '0.027*"coleslaw" + 0.018*"mayonis" + 0.017*"gula" + 0.017*"cuka" + 0.016*"biskut" + 0.016*"singapore" + 0.015*"halus" + 0.013*"makan" + 0.012*"bawang" + 0.011*"digaul"'),
 (4,
  '0.047*"air" + 0.045*"telur" + 0.031*"sos" + 0.026*"mendidih" + 0.025*"pulut" + 0.022*"putih" + 0.019*"udang" + 0.017*"kobis" + 0.013*"kuah" + 0.013*"kuning"'),
 (5,
  '0.041*"air" + 0.027*"kedalam" + 0.021*"gula" + 0.015*"agaragar" + 0.014*"isi" + 0.013*"ais" + 0.012*"tuang" + 0.012*"kelapa" + 0.011*"susu" + 0.011*"jagung"'),
 (6,
  '0.025*"cili" + 0.022*"serbuk" + 0.021*"bawang" + 0.019*"biji" + 0.016*"udang" + 0.015*"teh" + 0.015*"daun" + 0.014*"hijau" + 0.013*"putih" + 0.013*"sos"')]

### Inspect Probability

In [ ]:
fizaProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata bawang pada setiap topik
fizaProb["garam"]

## Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
fizaWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"
fizaWN["Synonym_clean"] = cleanWN_Synonym(fizaWN["Synonym"])
fizaWN["Hypernim_clean"] = cleanWN(fizaWN["Hypernim"])
fizaWN["Hyponim_clean"] = cleanWN(fizaWN["Hyponim"])

# output 5 data teratas
fizaWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
1,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"
2,1,garam,Synset('strategic_arms_limitation_talks.n.01'),[],[],negotiations between the United States and the...,strategic_arms_limitation_talks,None,None
3,1,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
4,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]

### Make Ontology

In [ ]:
# Make Ontology
fizaOnto = get_ontology("http://test.org/fiza.owl")
makeOntology(fizaOnto, fizaWN)
fizaOnto.save(file = "fiza.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1yNT1pPMobdn7jzP3ggI-GrGZWrjvV0y4"

In [ ]:
wiki_fiza = pd.read_excel("Fiza_final.xlsx").iloc[:, 1:]
wiki_fiza.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_fiza["Category"] = translate(wiki_fiza["Category"])
wiki_fiza.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_fiza[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
fizaTabel_new = tabel_1981.copy()
fizaTabel_new["correct_category"] = all_cat
fizaTabel_new["suggestion"] = all_suggestion

# Export Result to File
fizaTabel_new.to_excel("fizaTabel_Result.xlsx")
fizaTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "fizaTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
fizaTabel_new = concatListInColumn(fizaTabel_new)
fizaTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, fizaTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_fiza.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
fizaWiki_new = wiki_df.copy()
fizaWiki_new["suggest"] = all_cat

# Export Result to file
fizaWiki_new.to_excel("fizaWiki_Result.xlsx")
fizaWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "fizaWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
fizaOntoWiki = get_ontology("http://test.org/fiza_onto_wiki.owl")
makeOntology_wiki(fizaOntoWiki, fizaWiki_new)
fizaOntoWiki.save(file = "fiza_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = fizaWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
fizaWN_new = listToDataframe(changesList, tableWordnet)
fizaWN_new.to_excel("fizaWN_Result.xlsx")
fizaWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "fizaWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Sajian Dapur Bonda

In [ ]:
!gdown --id "1FaTkf1nWCzEegMyeorB3g8ydRbHNjniy"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1FaTkf1nWCzEegMyeorB3g8ydRbHNjniy
To: /content/SajianDapurBonda.jl
100% 721k/721k [00:00<00:00, 70.8MB/s]

In [ ]:
bonda=pd.read_json(r'/content/SajianDapurBonda.jl', lines = True)
bonda.rename(columns = {"Page_description":"page_description"}, inplace=True)
bonda["page_description"] = delist(bonda, "page_description")
bonda = pre_cleaning_text(bonda, threshold=30)

## GUI Sajian Dapur Bonda

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = bonda.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4      0.274821 -0.038605       1        1  55.830144
0      0.019467  0.121251       2        1  21.016001
5     -0.131465 -0.261862       3        1   7.481161
2      0.104037 -0.052523       4        1   5.069288
1     -0.193096  0.105438       5        1   4.817668
6      0.084154  0.080937       6        1   3.535355
3     -0.157918  0.045365       7        1   2.250383, topic_info=                  Term        Freq       Total Category  logprob  loglift
293             bawang  360.000000  360.000000  Default  30.0000  30.0000
367             periuk  111.000000  111.000000  Default  29.0000  29.0000
809             daging   94.000000   94.000000  Default  28.0000  28.0000
298                sos  108.000000  108.000000  Default  27.0000  27.0000
3                  kak  120.000000  120.000000  Default  26.0000  26.0000
4                 noor  119.000000  119.000000  Default  25.0000  25.0000
137              putih  176.000000  176.000000  Default  24.0000  24.0000
306               cili  199.000000  199.000000  Default  23.0000  23.0000
83            dipotong  105.000000  105.000000  Default  22.0000  22.0000
294              tumis  124.000000  124.000000  Default  21.0000  21.0000
288              garam  125.000000  125.000000  Default  20.0000  20.0000
30                gula  223.000000  223.000000  Default  19.0000  19.0000
109                nak   67.000000   67.000000  Default  18.0000  18.0000
360                air  196.000000  196.000000  Default  17.0000  17.0000
735               lada   39.000000   39.000000  Default  16.0000  16.0000
424             tomato   50.000000   50.000000  Default  15.0000  15.0000
609              noxxa   37.000000   37.000000  Default  14.0000  14.0000
371           pressure   36.000000   36.000000  Default  13.0000  13.0000
1302          agaragar   28.000000   28.000000  Default  12.0000  12.0000
459             kering   89.000000   89.000000  Default  11.0000  11.0000
411              kisar   72.000000   72.000000  Default  10.0000  10.0000
40              serbuk  114.000000  114.000000  Default   9.0000   9.0000
304               daun  144.000000  144.000000  Default   8.0000   8.0000
290              kuali   58.000000   58.000000  Default   7.0000   7.0000
364             fungsi   34.000000   34.000000  Default   6.0000   6.0000
37              tepung   54.000000   54.000000  Default   5.0000   5.0000
60              adunan   46.000000   46.000000  Default   4.0000   4.0000
127              manis   80.000000   80.000000  Default   3.0000   3.0000
303              tutup   73.000000   73.000000  Default   2.0000   2.0000
94                gram   53.000000   53.000000  Default   1.0000   1.0000
310               ikan  149.510845  150.287561   Topic1  -3.9522   0.5777
414               kuah  146.268483  147.046318   Topic1  -3.9741   0.5776
323               ulas   70.215257   70.992220   Topic1  -4.7080   0.5719
286               enaq   63.091778   63.868473   Topic1  -4.8150   0.5706
355              masin   58.891342   59.668124   Topic1  -4.8839   0.5698
1008            buncis   53.537002   54.314054   Topic1  -4.9792   0.5684
328           perencah   53.210040   53.986728   Topic1  -4.9853   0.5684
326             sambal   50.256075   51.032740   Topic1  -5.0425   0.5675
409               asam   49.919093   50.695720   Topic1  -5.0492   0.5674
300              pedas   44.684666   45.461947   Topic1  -5.1600   0.5656
299              tiram   43.682490   44.460453   Topic1  -5.1826   0.5652
305                sup   41.817612   42.595334   Topic1  -5.2263   0.5644
692              empuk   41.742449   42.521087   Topic1  -5.2281   0.5644
311              bilis   38.335412   39.112114   Topic1  -5.3132   0.5628
313             garing   37.129383   37.906993   Topic1  -5.3452   0.5621
810             kunyit   33.474043   34.251683   Topic1  -5.4488   0.5599
285              kicap  135.398056  138.572014   Topic1  -4.0514   0.5597
456              udang   32.666641   33.444013   Topic1  -5.4732   0.5593
318            menumis   32.515665   33.292480   Topic1  -5.4779   0.5592
388               ayam  121.760557  124.886764   Topic1  -4.1575   0.5575
425              tumix   30.193290   30.970036   Topic1  -5.5520   0.5575
971            rendang   27.742174   28.519813   Topic1  -5.6366   0.5552
358              mesra   26.921527   27.698437   Topic1  -5.6667   0.5544
295         kekuningan   25.776190   26.554022   Topic1  -5.7101   0.5531
408             keping   25.097492   25.874456   Topic1  -5.7368   0.5524
348             bebola   24.888133   25.664504   Topic1  -5.7452   0.5521
1077            talang   24.506974   25.283562   Topic1  -5.7606   0.5517
319         menghidang   24.148041   24.925726   Topic1  -5.7754   0.5512
410            gelugor   24.012440   24.789175   Topic1  -5.7810   0.5510
822           gegelang   23.260133   24.036881   Topic1  -5.8128   0.5500
187            dihiris  113.346378  117.370672   Topic1  -4.2291   0.5480
306               cili  190.542276  199.490931   Topic1  -3.7097   0.5370
361           mendidih  103.096181  108.489330   Topic1  -4.3239   0.5319
293             bawang  325.552580  360.121565   Topic1  -3.1741   0.4819
294              tumis  114.624576  124.634052   Topic1  -4.2179   0.4991
111               inci   48.807374   51.655311   Topic1  -5.0717   0.5261
137              putih  158.335447  176.876979   Topic1  -3.8949   0.4721
284             goreng   91.852113  100.494262   Topic1  -4.4394   0.4929
459             kering   82.543436   89.898977   Topic1  -4.5463   0.4975
27                biji  202.361703  234.027616   Topic1  -3.6495   0.4375
411              kisar   65.272634   72.979180   Topic1  -4.7810   0.4713
386               kari   71.533984   81.257637   Topic1  -4.6894   0.4554
283               nasi   62.594846   70.290144   Topic1  -4.8229   0.4669
304               daun  116.681866  144.182634   Topic1  -4.2001   0.3712
40              serbuk   94.763088  114.670188   Topic1  -4.4082   0.3922
298                sos   90.649038  108.786586   Topic1  -4.4526   0.4005
360                air  144.346188  196.386261   Topic1  -3.9874   0.2750
288              garam   99.952220  125.451559   Topic1  -4.3549   0.3556
170         bahanbahan  141.021797  193.510552   Topic1  -4.0107   0.2664
83            dipotong   84.298338  105.835295   Topic1  -4.5252   0.3553
30                gula  125.502170  223.777539   Topic1  -4.1273   0.0045
219             santan   67.337070   82.923556   Topic1  -4.7499   0.3746
461              merah   72.324129   97.134252   Topic1  -4.6784   0.2879
809             daging   71.236002   94.484326   Topic1  -4.6936   0.3004
127              manis   61.672445   80.732785   Topic1  -4.8378   0.3135
37              tepung   53.534628   54.263325   Topic2  -4.0022   1.5464
94                gram   52.435073   53.163939   Topic2  -4.0230   1.5461
633              darat   34.272436   35.003684   Topic2  -4.4482   1.5388
780              nanas   31.265214   31.996244   Topic2  -4.5401   1.5368
95              jagung   22.823168   23.552581   Topic2  -4.8548   1.5284
768             kismis   22.140599   22.875106   Topic2  -4.8851   1.5272
42                susu   54.715714   56.971978   Topic2  -3.9804   1.5195
122             gandum   16.969950   17.698252   Topic2  -5.1511   1.5179
65              baking   15.796117   16.524446   Topic2  -5.2228   1.5148
128              letak   15.745688   16.477536   Topic2  -5.2260   1.5145
555                kfc   15.192143   15.924139   Topic2  -5.2618   1.5128
882               kaup   14.704029   15.436281   Topic2  -5.2944   1.5113
883           balikkan   14.704029   15.436281   Topic2  -5.2944   1.5113
635              halba   14.318668   15.049453   Topic2  -5.3210   1.5101
63              loyang   16.601729   17.455321   Topic2  -5.1731   1.5097
38           disatukan   13.935153   14.665320   Topic2  -5.3481   1.5088
656                tin   13.708885   14.439983   Topic2  -5.3645   1.5079
76          bergantung   13.505057   14.234614   Topic2  -5.3795   1.5073
197           tuangkan   13.393019   14.123913   Topic2  -5.3878   1.5068
756          sederhana   41.838629   44.304401   Topic2  -4.2487   1.5026
664               dadu   12.028328   12.758046   Topic2  -5.4953   1.5010
612           seminggu   11.492311   12.226596   Topic2  -5.5409   1.4980
1178           merebus   11.306900   12.042105   Topic2  -5.5571   1.4969
559                ais   11.164630   11.894708   Topic2  -5.5698   1.4965
402              basuh   10.885104   11.617366   Topic2  -5.5952   1.4948
535              keras   10.363998   11.095296   Topic2  -5.6442   1.4917
717              licin   10.426875   11.163936   Topic2  -5.6382   1.4916
0                salam   10.225124   10.955576   Topic2  -5.6577   1.4909
66               paper   10.143386   10.871773   Topic2  -5.6657   1.4905
51             satukan    9.561569   10.291832   Topic2  -5.7248   1.4863
212             pandan   39.783515   45.005762   Topic2  -4.2991   1.4365
57                cair   28.933598   33.207649   Topic2  -4.6176   1.4221
682             kongsi   12.520282   13.719617   Topic2  -5.4552   1.4684
60              adunan   35.455865   46.521094   Topic2  -4.4143   1.2883
58              sebati   38.712830   52.699310   Topic2  -4.3264   1.2515
28               telur   42.939368   67.738304   Topic2  -4.2228   1.1040
728              rebus   21.788422   28.298420   Topic2  -4.9012   1.2985
30                gula   89.679676  223.777539   Topic2  -3.4863   0.6455
153         membuatnya   14.977136   18.378674   Topic2  -5.2760   1.3552
4                 noor   43.652177  119.448065   Topic2  -4.2063   0.5533
3                  kak   43.882814  120.704095   Topic2  -4.2010   0.5481
170         bahanbahan   48.429031  193.510552   Topic2  -4.1025   0.1747
652             kacang   26.519279   72.034750   Topic2  -4.7047   0.5606
50         caracaranya   25.812342   69.040140   Topic2  -4.7317   0.5761
93               dapur   24.850977   88.293585   Topic2  -4.7697   0.2921
92              sajian   21.211398   58.543043   Topic2  -4.9280   0.5447
96               pekat   17.754395   38.416189   Topic2  -5.1059   0.7880
27                biji   25.973215  234.027616   Topic2  -4.7255  -0.6385
461              merah   21.191558   97.134252   Topic2  -4.9290   0.0374
360                air   23.264227  196.386261   Topic2  -4.8356  -0.5733
304               daun   18.484479  144.182634   Topic2  -5.0656  -0.4943
609              noxxa   36.253646   37.013155   Topic3  -3.3591   2.5720
371           pressure   35.947148   36.706647   Topic3  -3.3676   2.5719
369             tombol   28.803907   29.563295   Topic3  -3.5892   2.5668
370               arah   20.528994   21.288303   Topic3  -3.9278   2.5565
368              putar   17.305113   18.064468   Topic3  -4.0987   2.5498
630              steam   15.073442   15.832647   Topic3  -4.2367   2.5436
608                set   14.853626   15.613568   Topic3  -4.2514   2.5429
800              ketam   13.182927   13.942208   Topic3  -4.3707   2.5368
628                wap   13.016575   13.775879   Topic3  -4.3834   2.5361
498           samperit   11.231275   11.992214   Topic3  -4.5310   2.5272
374         senantiasa   10.364151   11.125947   Topic3  -4.6113   2.5219
610           berbunyi    8.428424    9.187686   Topic3  -4.8181   2.5065
437           wassalam    8.021963    8.781313   Topic3  -4.8675   2.5023
363           perlahan    7.636972    8.398850   Topic3  -4.9167   2.4977
1379          marhaban    7.468109    8.227526   Topic3  -4.9390   2.4959
1380         diberkati    7.468109    8.227526   Topic3  -4.9390   2.4959
1381           mahrifa    7.468109    8.227526   Topic3  -4.9390   2.4959
364             fungsi   30.854714   34.010850   Topic3  -3.5204   2.4954
226               high   20.360600   22.562035   Topic3  -3.9361   2.4901
621              inner    6.850534    7.609907   Topic3  -5.0253   2.4877
626               beep    6.767040    7.526347   Topic3  -5.0376   2.4864
1015        warmreheat    6.499119    7.258730   Topic3  -5.0780   2.4822
1354             pulut    5.675580    6.435248   Topic3  -5.2135   2.4672
1036     menghidangkan    5.512619    6.271864   Topic3  -5.2426   2.4637
1037           ditabur    5.512619    6.271864   Topic3  -5.2426   2.4637
1038           enaknya    5.512619    6.271864   Topic3  -5.2426   2.4637
1039           terkata    5.512619    6.271864   Topic3  -5.2426   2.4637
77                buka    9.066953   10.549102   Topic3  -4.7450   2.4414
1120         bercampur    4.583761    5.347620   Topic3  -5.4271   2.4387
620            kampung    4.554040    5.314963   Topic3  -5.4336   2.4383
372              tekan   23.802604   27.927671   Topic3  -3.7799   2.4330
367             periuk   74.019795  111.342746   Topic3  -2.6453   2.1845
365               stir    9.355776   12.207382   Topic3  -4.7137   2.3267
366                fry    9.355776   12.207382   Topic3  -4.7137   2.3267
263            selamat   22.534289   43.360499   Topic3  -3.8346   1.9383
919             tulang    8.849771   12.489864   Topic3  -4.7693   2.2483
503         penggunaan    8.304752   11.883880   Topic3  -4.8328   2.2344
89    assalammualaikum   11.345714   20.007135   Topic3  -4.5208   2.0255
303              tutup   14.471327   73.476773   Topic3  -4.2775   0.9680
360                air   12.785351  196.386261   Topic3  -4.4014  -0.1390
375              panas    8.857304   34.555379   Topic3  -4.7684   1.2315
469             hujung    7.711797   17.534471   Topic3  -4.9069   1.7714
863                mee   11.917873   12.691619   Topic4  -4.0824   2.9191
400             pelaga    8.375399    9.146992   Topic4  -4.4352   2.8938
759                ala    8.291676    9.066452   Topic4  -4.4452   2.8926
860                tsp    8.000315    8.771465   Topic4  -4.4810   2.8899
857          memanjang    7.143334    7.915457   Topic4  -4.5943   2.8793
845               tbsp    7.058035    7.829820   Topic4  -4.6063   2.8782
875           hidangan    6.628494    7.404295   Topic4  -4.6691   2.8713
870              harum    6.501115    7.272325   Topic4  -4.6885   2.8699
858             kandar    5.989368    6.761220   Topic4  -4.7705   2.8608
837               urat    4.237357    5.010069   Topic4  -5.1165   2.8145
861             kaskas    3.727927    4.499154   Topic4  -5.2446   2.7939
856              belah    3.560558    4.332783   Topic4  -5.2906   2.7857
847              pilih    3.129418    3.902182   Topic4  -5.4196   2.7613
865               labu    3.106261    3.898300   Topic4  -5.4271   2.7548
1025        masakannya    2.825483    3.597125   Topic4  -5.5218   2.7405
859          bungkusan    2.750238    3.523524   Topic4  -5.5488   2.7342
1062             jiran    2.406980    3.178632   Topic4  -5.6821   2.7039
1063           berhari    2.406980    3.178632   Topic4  -5.6821   2.7039
1064   rempahrempahnya    2.406980    3.178632   Topic4  -5.6821   2.7039
1065        membezakan    2.406980    3.178632   Topic4  -5.6821   2.7039
1066            melayu    2.406980    3.178632   Topic4  -5.6821   2.7039
1234         sebungkus    2.181968    2.953788   Topic4  -5.7802   2.6791
1239         terpercik    2.181968    2.953788   Topic4  -5.7802   2.6791
1240             leper    2.181968    2.953788   Topic4  -5.7802   2.6791
1241         sehinggal    2.181968    2.953788   Topic4  -5.7802   2.6791
864         kisartumis    2.109125    2.880275   Topic4  -5.8142   2.6704
866            pangkal    2.109125    2.880275   Topic4  -5.8142   2.6704
869             ramuan    2.109125    2.880275   Topic4  -5.8142   2.6704
871           keemasan    2.109125    2.880275   Topic4  -5.8142   2.6704
872        haliabawang    2.109125    2.880275   Topic4  -5.8142   2.6704
399             lawang    7.557226   11.708118   Topic4  -4.5380   2.5442
867            cengkih    6.935592   10.699589   Topic4  -4.6238   2.5484
809             daging   22.615252   94.484326   Topic4  -3.4419   1.5522
398              bunga    9.101264   25.031082   Topic4  -4.3521   1.9703
556            masakan    7.929676   22.338971   Topic4  -4.4899   1.9462
195               kayu    6.751100   20.570362   Topic4  -4.6508   1.8678
354                bau    8.940593   34.923367   Topic4  -4.3699   1.6194
163               buah    7.045756   29.082928   Topic4  -4.6081   1.5642
293             bawang   23.977833  360.121565   Topic4  -3.3833   0.2727
384            diketuk    3.741457    8.824478   Topic4  -5.2410   2.1239
127              manis    8.910687   80.732785   Topic4  -4.3732   0.7781
815             jintan    6.339965   37.128994   Topic4  -4.7136   1.2144
137              putih   10.196401  176.876979   Topic4  -4.2384   0.1286
40              serbuk    8.505443  114.670188   Topic4  -4.4198   0.3806
411              kisar    7.072796   72.979180   Topic4  -4.6042   0.6481
304               daun    8.572898  144.182634   Topic4  -4.4119   0.1595
320             batang    5.768020   45.318533   Topic4  -4.8081   0.9206
306               cili    8.316501  199.490931   Topic4  -4.4422  -0.1956
459             kering    6.645834   89.898977   Topic4  -4.6665   0.3773
360                air    7.570995  196.386261   Topic4  -4.5362  -0.2738
375              panas    5.174943   34.555379   Topic4  -4.9166   1.0832
289            secukup    5.559069   65.740474   Topic4  -4.8450   0.5117
284             goreng    5.416616  100.494262   Topic4  -4.8710   0.0613
1302          agaragar   27.497506   28.276061   Topic5  -3.1955   3.0050
527                doh   11.397595   12.175634   Topic5  -4.0762   2.9668
470             biskut   10.553715   11.332003   Topic5  -4.1531   2.9617
214              penuh    8.849777    9.633094   Topic5  -4.3292   2.9481
506              cream    8.456262    9.234068   Topic5  -4.3747   2.9449
160             cheese    7.961399    8.740386   Topic5  -4.4350   2.9395
53               mixer    6.998568    7.776984   Topic5  -4.5639   2.9274
528              acuan    6.992058    7.769972   Topic5  -4.5648   2.9274
1276          pengisar    6.979225    7.756399   Topic5  -4.5666   2.9273
1304           lapisan    6.979067    7.756521   Topic5  -4.5667   2.9273
1275            balang    6.002098    6.779273   Topic5  -4.7175   2.9111
1312              tali    5.022178    5.802099   Topic5  -4.8957   2.8885
681           anakanak    6.374563    7.436828   Topic5  -4.6573   2.8788
483              susun    4.544545    5.322175   Topic5  -4.9956   2.8749
507         eksperimen    4.537621    5.315346   Topic5  -4.9972   2.8747
1305            puding   10.844767   12.774212   Topic5  -4.1259   2.8691
471         cornflakes    4.061182    4.838629   Topic5  -5.1081   2.8577
563          cranberry    4.061068    4.838654   Topic5  -5.1081   2.8577
1301              oreo    4.047743    4.825126   Topic5  -5.1114   2.8572
17                chip    3.567663    4.344978   Topic5  -5.2377   2.8358
775              salah    3.152102    3.935991   Topic5  -5.3615   2.8108
2             brownies    3.080736    3.858121   Topic5  -5.3844   2.8079
604               hati    2.869563    3.650617   Topic5  -5.4554   2.7921
689               kuih    2.590100    3.367991   Topic5  -5.5579   2.7703
569          bentukkan    2.589943    3.368048   Topic5  -5.5579   2.7702
557             simpan    2.587113    3.364476   Topic5  -5.5590   2.7702
236          bahagikan    2.584178    3.364599   Topic5  -5.5602   2.7690
1303             larut    8.814314   11.933464   Topic5  -4.3332   2.7299
542            dibakar    2.099714    2.877766   Topic5  -5.7678   2.7177
46            hazelnut    2.096944    2.874199   Topic5  -5.7691   2.7176
558               peti   11.374517   17.184891   Topic5  -4.0782   2.6202

Topic: 1
gula, susu, tepung, gram, bahanbahan, kak, noor, telur, sederhana, pandan, sebati, adunan, darat, nanas, cair, kacang, biji, caracaranya, dapur, air, jagung, kismis, rebus, sajian, merah, daun, pekat, gandum, loyang, baking

Topic: 2
agaragar, coklat, doh, peti, puding, biskut, adunan, sejuk, kak, penuh, larut, cream, noor, diblend, cheese, mixer, acuan, pengisar, lapisan, oven, anakanak, balang, butter, tali, badam, chocolate, susun, eksperimen, suhu, dikeluarkan

Topic: 3
bawang, daging, mee, putih, bunga, bau, manis, daun, serbuk, pelaga, cili, ala, tsp, masakan, air, lawang, memanjang, kisar, tbsp, buah, cengkih, kayu, kering, hidangan, harum, jintan, kandar, batang, secukup, goreng

Topic: 4
alhamdulillah, kak, noor, order, make, nak, syukur, limau, cerita, ambil, lengkuas, hadrat, bendi, pleasure, kindly, please, reading, fund, sebalik, today, family, serba, enjoy, haha, resepinya, toskan, stirfry, cubalah, kasturi, nipis

Topic: 5
bawang, biji, cili, putih, ikan, kuah, air, bahanbahan, kicap, gula, ayam, daun, tumis, dihiris, mendidih, garam, serbuk, goreng, sos, dipotong, kering, merah, kari, daging, ulas, santan, kisar, enaq, nasi, manis

Topic: 6
periuk, noxxa, pressure, fungsi, tombol, tekan, selamat, arah, high, putar, steam, set, tutup, ketam, wap, air, assalammualaikum, samperit, senantiasa, fry, stir, buka, panas, tulang, berbunyi, penggunaan, wassalam, hujung, perlahan, mahrifa

Topic: 7
lada, sos, spaghetti, tomato, sosej, bawang, chef, kiub, dipotong, garam, air, mixed, toskan, teh, benggala, sotong, bau, mentega, makaroni, dicincang, cendawan, tumis, dimasukkan, taburkan, hitam, rebus, gula, putih, panaskan, kuali

[(0,
  '0.031*"gula" + 0.019*"susu" + 0.018*"tepung" + 0.018*"gram" + 0.017*"bahanbahan" + 0.015*"kak" + 0.015*"noor" + 0.015*"telur" + 0.014*"sederhana" + 0.014*"pandan"'),
 (1,
  '0.041*"agaragar" + 0.022*"coklat" + 0.017*"doh" + 0.017*"peti" + 0.016*"puding" + 0.016*"biskut" + 0.016*"adunan" + 0.015*"sejuk" + 0.013*"kak" + 0.013*"penuh"'),
 (2,
  '0.034*"bawang" + 0.032*"daging" + 0.017*"mee" + 0.014*"putih" + 0.013*"bunga" + 0.013*"bau" + 0.013*"manis" + 0.012*"daun" + 0.012*"serbuk" + 0.012*"pelaga"'),
 (3,
  '0.037*"alhamdulillah" + 0.028*"kak" + 0.027*"noor" + 0.023*"make" + 0.023*"order" + 0.021*"nak" + 0.019*"syukur" + 0.016*"limau" + 0.015*"cerita" + 0.014*"ambil"'),
 (4,
  '0.042*"bawang" + 0.026*"biji" + 0.024*"cili" + 0.020*"putih" + 0.019*"ikan" + 0.019*"kuah" + 0.019*"air" + 0.018*"bahanbahan" + 0.017*"kicap" + 0.016*"gula"'),
 (5,
  '0.071*"periuk" + 0.035*"noxxa" + 0.034*"pressure" + 0.030*"fungsi" + 0.028*"tombol" + 0.023*"tekan" + 0.022*"selamat" + 0.020*"arah" + 0.020*"high" + 0.017*"putar"'),
 (6,
  '0.029*"lada" + 0.027*"sos" + 0.026*"spaghetti" + 0.021*"tomato" + 0.021*"sosej" + 0.020*"bawang" + 0.020*"chef" + 0.019*"kiub" + 0.019*"dipotong" + 0.017*"garam"')]

###Inspect Probability

In [ ]:
bondaProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata garam pada setiap topik
bondaProb["garam"]

##Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
bondaWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"

bondaWN["Synonym_clean"] = cleanWN_Synonym(bondaWN["Synonym"])
bondaWN["Hypernim_clean"] = cleanWN(bondaWN["Hypernim"])
bondaWN["Hyponim_clean"] = cleanWN(bondaWN["Hyponim"])

# output 5 data teratas
bondaWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,gula,Synset('pecan_pie.n.01'),[Synset('pie.n.01')],[],pie made of pecans and sugar and corn syrup an...,pecan_pie,[pie],None
1,1,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None
2,1,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
3,1,gram,Synset('gram.n.01'),[Synset('metric_weight_unit.n.01')],[],a metric unit of weight equal to one thousandt...,gram,[metric_weight_unit],None
4,1,bahanbahan,None,None,None,None,None,None,None

### Make Ontology

In [ ]:
# Make Ontology
bondaOnto = get_ontology("http://test.org/bonda.owl")
makeOntology(bondaOnto, bondaWN)
bondaOnto.save(file = "bonda.owl")

##Wikipedia & Category

In [ ]:
!gdown --id "1qI339gOiXnnxiutzZJ5Th288DSvBFNX9"

In [ ]:
wiki_bonda = pd.read_excel("Bonda_final.xlsx").iloc[:, 1:]
wiki_bonda.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_bonda["Category"] = translate(wiki_bonda["Category"])
wiki_bonda.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_bonda[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
bondaTabel_new = tabel_1981.copy()
bondaTabel_new["correct_category"] = all_cat
bondaTabel_new["suggestion"] = all_suggestion

# Export Result to File
bondaTabel_new.to_excel("bondaTabel_Result.xlsx")
bondaTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "bondaTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
bondaTabel_new = concatListInColumn(bondaTabel_new)
bondaTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, bondaTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_bonda.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
bondaWiki_new = wiki_df.copy()
bondaWiki_new["suggest"] = all_cat

# Export Result to file
bondaWiki_new.to_excel("bondaWiki_Result.xlsx")
bondaWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "bondaWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
bondaOntoWiki = get_ontology("http://test.org/bonda_onto_wiki.owl")
makeOntology_wiki(bondaOntoWiki, bondaWiki_new)
bondaOntoWiki.save(file = "bonda_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = bondaWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()


benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
bondaWN_new = listToDataframe(changesList, tableWordnet)
bondaWN_new.to_excel("bondaWN_Result.xlsx")
bondaWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "bondaWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# banyak resepi

In [ ]:
!gdown --id "1Ti4mXlJY-shdnNp9-kcxoLgyQlZBpZFN"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1Ti4mXlJY-shdnNp9-kcxoLgyQlZBpZFN
To: /content/banyakResepi.jl
100% 131k/131k [00:00<00:00, 85.2MB/s]

In [ ]:
resepi = pd.read_json(r'/content/banyakResepi.jl', lines = True)

resepi.rename(columns = {"Page_description":"page_description"}, inplace=True)
resepi["page_description"] = delist(resepi, "page_description")
resepi = pre_cleaning_text(resepi, threshold=30)

## GUI Banyak Resepi

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = resepi.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4     -0.066144 -0.033108       1        1  23.659652
6     -0.137865 -0.007465       2        1  21.673622
5     -0.032099  0.088333       3        1  18.165464
0      0.007361 -0.021776       4        1  16.466621
1      0.066014 -0.132593       5        1  15.121684
2      0.066601  0.058206       6        1   4.162422
3      0.096133  0.048403       7        1   0.750534, topic_info=                 Term       Freq      Total Category  logprob  loglift
327             udang  20.000000  20.000000  Default  30.0000  30.0000
4                ikan  35.000000  35.000000  Default  29.0000  29.0000
288              ayam  37.000000  37.000000  Default  28.0000  28.0000
349             pastu  23.000000  23.000000  Default  27.0000  27.0000
373               mee  10.000000  10.000000  Default  26.0000  26.0000
226               sos  23.000000  23.000000  Default  25.0000  25.0000
8               merah  23.000000  23.000000  Default  24.0000  24.0000
384             lemak   3.000000   3.000000  Default  23.0000  23.0000
411             lazat   4.000000   4.000000  Default  22.0000  22.0000
337             telur  20.000000  20.000000  Default  21.0000  21.0000
537             beras   8.000000   8.000000  Default  20.0000  20.0000
785              roti  13.000000  13.000000  Default  19.0000  19.0000
6                biji  42.000000  42.000000  Default  18.0000  18.0000
10               cili  38.000000  38.000000  Default  17.0000  17.0000
254          tempoyak   4.000000   4.000000  Default  16.0000  16.0000
44                nak  26.000000  26.000000  Default  15.0000  15.0000
162            kunyit  11.000000  11.000000  Default  14.0000  14.0000
78            masukan   4.000000   4.000000  Default  13.0000  13.0000
145              nasi  11.000000  11.000000  Default  12.0000  12.0000
54             serbuk  15.000000  15.000000  Default  11.0000  11.0000
186             kesum   4.000000   4.000000  Default  10.0000  10.0000
11               padi  11.000000  11.000000  Default   9.0000   9.0000
35               step  32.000000  32.000000  Default   8.0000   8.0000
76               kuah  13.000000  13.000000  Default   7.0000   7.0000
94              tutup  12.000000  12.000000  Default   6.0000   6.0000
259             hidup   4.000000   4.000000  Default   5.0000   5.0000
328            maggie   3.000000   3.000000  Default   4.0000   4.0000
542           rebusan   5.000000   5.000000  Default   3.0000   3.0000
522            tunggu   5.000000   5.000000  Default   2.0000   2.0000
935             petai   4.000000   4.000000  Default   1.0000   1.0000
349             pastu  21.141921  23.231491   Topic1  -3.6529   1.3471
121               pes   5.164185   5.710947   Topic1  -5.0624   1.3408
102              pari   4.323283   4.870050   Topic1  -5.2401   1.3223
859            tomyam   3.482767   4.029018   Topic1  -5.4563   1.2957
352          kuayteaw   2.642626   3.188104   Topic1  -5.7324   1.2537
28               hehe   2.642401   3.188021   Topic1  -5.7325   1.2537
455           holland   2.642367   3.188104   Topic1  -5.7325   1.2536
873             botol   2.642183   3.188088   Topic1  -5.7325   1.2536
973           topping   2.641798   3.187975   Topic1  -5.7327   1.2535
706           kentang   2.641790   3.187995   Topic1  -5.7327   1.2535
1038          brokoli   1.801930   2.347116   Topic1  -6.1153   1.1771
1032          mariana   1.801926   2.347115   Topic1  -6.1153   1.1771
1033           ismail   1.801912   2.347103   Topic1  -6.1153   1.1771
1036        spaghetti   1.801893   2.347086   Topic1  -6.1153   1.1771
1031              ana   1.801858   2.347061   Topic1  -6.1153   1.1771
24             tulang   1.801778   2.347069   Topic1  -6.1154   1.1770
109               bji   1.801692   2.347187   Topic1  -6.1154   1.1769
453             kobis   1.801637   2.347163   Topic1  -6.1155   1.1769
848              info   1.801538   2.347157   Topic1  -6.1155   1.1768
124              esok   1.801563   2.347195   Topic1  -6.1155   1.1768
849          tambahan   1.801534   2.347157   Topic1  -6.1155   1.1768
969           secubit   1.801476   2.347107   Topic1  -6.1155   1.1768
847           hasikin   1.801510   2.347162   Topic1  -6.1155   1.1768
136         terkeluar   1.801535   2.347196   Topic1  -6.1155   1.1768
846             hajar   1.801502   2.347155   Topic1  -6.1155   1.1768
858          cendawan   1.801490   2.347157   Topic1  -6.1155   1.1768
968          mauripan   1.801438   2.347095   Topic1  -6.1156   1.1768
974             pasta   1.801431   2.347093   Topic1  -6.1156   1.1768
712           dimasak   1.801398   2.347081   Topic1  -6.1156   1.1768
717              mini   1.801376   2.347110   Topic1  -6.1156   1.1768
50                lak   4.324426   5.656194   Topic1  -5.2399   1.1729
279               yer   5.164995   7.285152   Topic1  -5.0622   1.0975
79              tuang   3.483099   4.815087   Topic1  -5.4562   1.1176
13             kering   6.004956   8.926669   Topic1  -4.9116   1.0449
21                isi   6.005553  10.541675   Topic1  -4.9115   0.8787
33              letak  11.891772  26.808026   Topic1  -4.2283   0.6285
7              bawang  21.139826  58.028262   Topic1  -3.6530   0.4316
71                dah  13.575112  35.099229   Topic1  -4.0959   0.4915
94              tutup   6.005375  12.263954   Topic1  -4.9115   0.7274
74         kacaukacau   2.642633   3.974191   Topic1  -5.7324   1.0334
26              takpe   2.642452   3.974215   Topic1  -5.7324   1.0333
765               uli   2.644531   3.990675   Topic1  -5.7317   1.0299
271              thai   2.642240   3.990742   Topic1  -5.7325   1.0290
422           chicken   2.642732   4.016839   Topic1  -5.7323   1.0227
25              kecik   2.642351   4.016782   Topic1  -5.7325   1.0226
70           panaskan   5.165119  10.457581   Topic1  -5.0622   0.7360
289              kiub   4.324141   8.137112   Topic1  -5.2399   0.8092
6                biji  13.574664  42.750745   Topic1  -4.0959   0.2942
16              limau   7.686715  19.556089   Topic1  -4.6647   0.5076
96              makan   5.164624  10.959959   Topic1  -5.0623   0.6890
66              kuali   4.323377   8.828600   Topic1  -5.2401   0.7274
59                air  11.894075  54.572756   Topic1  -4.2281  -0.0821
100              daun   8.527813  30.962302   Topic1  -4.5608   0.1520
35               step   8.530122  32.124976   Topic1  -4.5605   0.1154
10               cili   9.369035  38.764794   Topic1  -4.4667   0.0213
18              garam   8.527834  34.816202   Topic1  -4.5608   0.0347
288              ayam   8.529147  37.168435   Topic1  -4.5607  -0.0306
108             putih   6.846589  24.423099   Topic1  -4.7804   0.1696
38            mencuba   6.847237  27.104208   Topic1  -4.7803   0.0656
37            selamat   6.846981  27.103993   Topic1  -4.7803   0.0655
36               lupa   6.846778  27.844192   Topic1  -4.7804   0.0386
19               gula   6.006855  21.523930   Topic1  -4.9112   0.1651
194             tumis   5.165520  15.374193   Topic1  -5.0621   0.3507
2          bahanbahan   5.164886  20.951975   Topic1  -5.0623   0.0410
4                ikan   5.164552  35.611048   Topic1  -5.0623  -0.4894
206          mendidih   4.324645  12.520119   Topic1  -5.2398   0.3784
14             tomato   4.324165  26.579580   Topic1  -5.2399  -0.3745
537             beras   8.392263   8.952309   Topic2  -4.4892   1.4645
542           rebusan   5.089960   5.637951   Topic2  -4.9892   1.4268
522            tunggu   5.089752   5.638007   Topic2  -4.9892   1.4268
799             jepun   3.432920   3.980363   Topic2  -5.3831   1.3811
302           mangkuk   3.429222   3.980282   Topic2  -5.3841   1.3801
547             lemon   2.604442   3.151667   Topic2  -5.6593   1.3384
533            jintan   2.604363   3.151669   Topic2  -5.6593   1.3383
634               pot   2.604315   3.151663   Topic2  -5.6593   1.3383
531             ketul   2.604204   3.151647   Topic2  -5.6593   1.3383
101          ketumbar   5.769407   7.248213   Topic2  -4.8639   1.3009
910            crispy   1.776009   2.322894   Topic2  -6.0421   1.2606
536              madu   1.775736   2.322869   Topic2  -6.0423   1.2605
527              arab   1.775734   2.322868   Topic2  -6.0423   1.2605
528              smua   1.775734   2.322868   Topic2  -6.0423   1.2605
638           pewarna   1.775714   2.322874   Topic2  -6.0423   1.2605
798             dashi   1.775676   2.322832   Topic2  -6.0423   1.2605
635           sekawan   1.775705   2.322871   Topic2  -6.0423   1.2605
639             telor   1.775692   2.322869   Topic2  -6.0423   1.2605
822             start   1.775650   2.322825   Topic2  -6.0423   1.2605
808          takoyaki   1.775634   2.322824   Topic2  -6.0423   1.2604
631              ummi   1.775652   2.322870   Topic2  -6.0423   1.2604
633             ganja   1.775649   2.322873   Topic2  -6.0423   1.2604
632              dhia   1.775625   2.322869   Topic2  -6.0423   1.2604
535           perapan   1.775606   2.322847   Topic2  -6.0423   1.2604
609              cuci   1.775601   2.322847   Topic2  -6.0423   1.2604
830            bebola   1.775540   2.322791   Topic2  -6.0424   1.2604
617           cormick   1.775489   2.322808   Topic2  -6.0424   1.2604
546             timun   1.775508   2.322840   Topic2  -6.0424   1.2604
600               mug   1.775495   2.322824   Topic2  -6.0424   1.2604
620            mayang   1.775471   2.322822   Topic2  -6.0424   1.2604
369            jagung   4.261164   5.650086   Topic2  -5.1669   1.2469
288              ayam  26.131743  37.168435   Topic2  -3.3533   1.1768
145              nasi   7.832461  11.297391   Topic2  -4.5582   1.1628
619               sup   5.089887   7.319760   Topic2  -4.9892   1.1658
54             serbuk   9.233104  15.256934   Topic2  -4.3937   1.0268
117              asam   5.738160   8.869284   Topic2  -4.8693   1.0936
47              halia   8.379589  13.756617   Topic2  -4.4907   1.0334
343              gaul   2.603445   3.634477   Topic2  -5.6596   1.1954
161              inci   5.090345   8.497149   Topic2  -4.9891   1.0167
572            rempah   7.322811  13.737444   Topic2  -4.6255   0.8999
324             manis   5.419106  10.078045   Topic2  -4.9265   0.9086
353            goreng   6.368398  12.838240   Topic2  -4.7651   0.8280
8               merah   9.675989  23.106067   Topic2  -4.3468   0.6586
59                air  17.828266  54.572756   Topic2  -3.7357   0.4103
545             salad   2.604746   3.923172   Topic2  -5.6591   1.1195
815           mayonis   2.604546   3.923129   Topic2  -5.6592   1.1194
653              kari   5.919047  12.099337   Topic2  -4.8383   0.8141
226               sos   9.476443  23.486520   Topic2  -4.3677   0.6215
7              bawang  17.353657  58.028262   Topic2  -3.7627   0.3219
559           cincang   2.602619   3.992402   Topic2  -5.6600   1.1012
108             putih   8.468988  24.423099   Topic2  -4.4801   0.4700
6                biji  11.723070  42.750745   Topic2  -4.1549   0.2352
14             tomato   8.608660  26.579580   Topic2  -4.4637   0.4017
368            tepung   5.090251  11.409530   Topic2  -4.9891   0.7220
71                dah   8.869046  35.099229   Topic2  -4.4339   0.1535
100              daun   8.310632  30.962302   Topic2  -4.4989   0.2138
10               cili   9.113161  38.764794   Topic2  -4.4068   0.0813
44                nak   7.217546  26.396974   Topic2  -4.6400   0.2323
18              garam   7.587390  34.816202   Topic2  -4.5900   0.0055
110              lada   5.090601  14.557310   Topic2  -4.9891   0.4784
38            mencuba   5.611320  27.104208   Topic2  -4.8917  -0.0458
37            selamat   5.611167  27.103993   Topic2  -4.8917  -0.0458
148               ina   2.521710   3.072827   Topic3  -5.5150   1.5080
696            nangka   2.521628   3.072867   Topic3  -5.5150   1.5079
787               pap   2.521292   3.073024   Topic3  -5.5151   1.5078
235          pressure   2.519255   3.072763   Topic3  -5.5159   1.5070
411             lazat   3.324919   4.163580   Topic3  -5.2385   1.4807
917           seafood   1.719628   2.270382   Topic3  -5.8978   1.4278
467              blue   1.719535   2.270427   Topic3  -5.8978   1.4277
147            azlina   1.719455   2.270335   Topic3  -5.8979   1.4277
155              besa   1.719429   2.270334   Topic3  -5.8979   1.4277
199             bendi   1.719406   2.270330   Topic3  -5.8979   1.4277
468             ocean   1.719454   2.270429   Topic3  -5.8979   1.4277
172               die   1.719360   2.270323   Topic3  -5.8979   1.4277
189              korg   1.719355   2.270316   Topic3  -5.8980   1.4277
149              fans   1.719298   2.270304   Topic3  -5.8980   1.4277
683               afy   1.719292   2.270360   Topic3  -5.8980   1.4276
682             cikgu   1.719260   2.270333   Topic3  -5.8980   1.4276
249          dihidang   1.719098   2.270343   Topic3  -5.8981   1.4275
758            kastor   1.718979   2.270448   Topic3  -5.8982   1.4274
755          muhammad   1.718659   2.270464   Topic3  -5.8984   1.4272
756             irfan   1.718639   2.270466   Topic3  -5.8984   1.4272
763        shortening   1.718610   2.270466   Topic3  -5.8984   1.4272
298           kukusan   1.718372   2.270394   Topic3  -5.8985   1.4271
299          curahkan   1.718250   2.270405   Topic3  -5.8986   1.4270
690         tambahkan   3.323935   4.704212   Topic3  -5.2388   1.3583
175              plak   2.521724   3.859099   Topic3  -5.5150   1.2802
412               yan   0.917219   1.467852   Topic3  -6.5263   1.2354
413               mie   0.917219   1.467852   Topic3  -6.5263   1.2354
920           panggil   0.917148   1.467835   Topic3  -6.5264   1.2354
931          hasilkan   0.917149   1.467836   Topic3  -6.5264   1.2354
924          bestbest   0.917143   1.467834   Topic3  -6.5264   1.2354
186             kesum   2.521707   4.038757   Topic3  -5.5150   1.2346
216           biarkan   4.126254   6.773336   Topic3  -5.0225   1.2100
4                ikan  20.141453  35.611048   Topic3  -3.4371   1.1358
278              cuba   3.323839   5.930896   Topic3  -5.2388   1.1266
41               labu   2.521460   4.630548   Topic3  -5.5151   1.0978
111             serai   4.872455  11.948918   Topic3  -4.8563   0.8086
16              limau   6.086208  19.556089   Topic3  -4.6339   0.5384
59                air  11.010812  54.572756   Topic3  -4.0410   0.1050
19               gula   6.357878  21.523930   Topic3  -4.5902   0.4862
766               doh   3.321123   7.239324   Topic3  -5.2396   0.9264
108             putih   6.240923  24.423099   Topic3  -4.6088   0.3412
14             tomato   6.527540  26.579580   Topic3  -4.5639   0.3015
38            mencuba   6.436155  27.104208   Topic3  -4.5780   0.2679
37            selamat   6.435333  27.103993   Topic3  -4.5781   0.2678
36               lupa   6.450733  27.844192   Topic3  -4.5757   0.2432
7              bawang   9.365167  58.028262   Topic3  -4.2029  -0.1183
18              garam   7.097772  34.816202   Topic3  -4.4801   0.1153
100              daun   6.647596  30.962302   Topic3  -4.5456   0.1671
215             empuk   2.521760   4.742630   Topic3  -5.5149   1.0740
35               step   6.472977  32.124976   Topic3  -4.5723   0.1037
76               kuah   4.126072  13.066030   Topic3  -5.0226   0.5530
110              lada   4.126582  14.557310   Topic3  -5.0225   0.4450
10               cili   6.222121  38.764794   Topic3  -4.6118  -0.1238
8               merah   4.501248  23.106067   Topic3  -4.9355   0.0699
232             kisar   3.324294  10.469219   Topic3  -5.2386   0.5585
373               mee   3.325862  10.508104   Topic3  -5.2382   0.5552
166              ulas   3.323816  10.499497   Topic3  -5.2388   0.5554
2          bahanbahan   3.866977  20.951975   Topic3  -5.0874   0.0159
226               sos   3.626932  23.486520   Topic3  -5.1515  -0.1624
39         disediakan   3.296997  15.554164   Topic3  -5.2469   0.1543
44                nak   3.324138  26.396974   Topic3  -5.2387  -0.3664
935             petai   4.042571   4.596460   Topic4  -4.9448   1.6754
730           kembang   4.042439   4.596542   Topic4  -4.9449   1.6754
739           dikisar   3.256343   3.810240   Topic4  -5.1611   1.6467
55              knorr   2.470720   3.023819   Topic4  -5.4372   1.6018
732            cendol   2.470357   3.024040   Topic4  -5.4374   1.6016
746           kathira   2.470347   3.024042   Topic4  -5.4374   1.6016
733            cincau   2.470313   3.024043   Topic4  -5.4374   1.6016
1012        mozarella   2.469075   3.024064   Topic4  -5.4379   1.6011
67              malas   1.684420   2.237671   Topic4  -5.8203   1.5198
385             tauge   1.684403   2.237721   Topic4  -5.8203   1.5198
740             sirap   1.684410   2.237786   Topic4  -5.8203   1.5198
949           berkuah   1.684365   2.237752   Topic4  -5.8203   1.5198
736             barli   1.684369   2.237788   Topic4  -5.8203   1.5197
952            kepala   1.684336   2.237762   Topic4  -5.8203   1.5197
945               jea   1.684317   2.237759   Topic4  -5.8204   1.5197
943               yea   1.684305   2.237756   Topic4  -5.8204   1.5197
734             kurma   1.684329   2.237790   Topic4  -5.8203   1.5197
729           selasih   1.684261   2.237793   Topic4  -5.8204   1.5197
1007         habeebah   1.683713   2.237798   Topic4  -5.8207   1.5193
1001           cheesy   1.683698   2.237797   Topic4  -5.8207   1.5193
1002             boat   1.683614   2.237799   Topic4  -5.8208   1.5193
1008             daud   1.683505   2.237811   Topic4  -5.8208   1.5192
345              sawi   2.470559   3.506853   Topic4  -5.4373   1.4536
561              buah   2.470475   3.804756   Topic4  -5.4373   1.3720
77             korang   2.470484   3.864881   Topic4  -5.4373   1.3563
484          pengisar   0.898561   1.451526   Topic4  -6.4487   1.3243
486   shareinsyaallah   0.898561   1.451526   Topic4  -6.4487   1.3243
487      pahalasumber   0.898561   1.451526   Topic4  -6.4487   1.3243
489            katira   0.898561   1.451526   Topic4  -6.4487   1.3243
938        bendabenda   0.898561   1.451526   Topic4  -6.4487   1.3243
57              takde   3.256801   5.453675   Topic4  -5.1610   1.2883
539            rendam   3.256399   5.467883   Topic4  -5.1611   1.2856
373               mee   5.614800  10.508104   Topic4  -4.6163   1.1771
44                nak  11.905324  26.396974   Topic4  -3.8647   1.0076
48              halus   4.042811   7.923718   Topic4  -4.9448   1.1309
6                biji  13.477252  42.750745   Topic4  -3.7407   0.6495
327             udang   7.974179  20.820955   Topic4  -4.2655   0.8441
30             sebati   4.828986  11.105742   Topic4  -4.7671   0.9710
2          bahanbahan   7.187344  20.951975   Topic4  -4.3694   0.7339
565            pandan   3.256718   6.267843   Topic4  -5.1610   1.1491
42              hiris   4.043357   9.483349   Topic4  -4.9446   0.9514
59                air   9.547897  54.572756   Topic4  -4.0854   0.0606
36               lupa   6.401905  27.844192   Topic4  -4.4851   0.3338
4                ikan   7.187900  35.611048   Topic4  -4.3693   0.2036
31                tau   3.256743   7.825504   Topic4  -5.1610   0.9272
43              belah   2.470993   4.636264   Topic4  -5.4371   1.1745
35               step   6.401551  32.124976   Topic4  -4.4852   0.1907
785              roti   4.039048  13.183900   Topic4  -4.9457   0.6208
33              letak   5.616072  26.808026   Topic4  -4.6161   0.2408
10               cili   6.402084  38.764794   Topic4  -4.4851   0.0029
217             pekat   4.041958  15.316603   Topic4  -4.9450   0.4716
37            selamat   4.829820  27.103993   Topic4  -4.7669   0.0790
38            mencuba   4.828291  27.104208   Topic4  -4.7672   0.0786

Topic: 1
biji, nak, air, udang, ikan, bahanbahan, cili, lupa, step, letak, mee, selamat, sebati, mencuba, bawang, garam, hiris, telur, halus, petai, kembang, pekat, roti, dah, sos, takde, tau, pandan, sbs, susu

Topic: 2
telur, udang, step, roti, dah, garam, bawang, kunyit, cili, sikit, tomato, disediakan, kuning, sosej, daging, daun, sambal, air, gambar, serdak, butter, kat, padi, cantik, susu, slice, letakkan, cheese, puri, mendidih

Topic: 3
sos, cili, ikan, merah, tempoyak, kueyteow, masukan, char, patin, dah, air, garam, daun, step, kuah, kicap, tutup, maggie, kuey, kesum, teow, pekat, kunyit, hidup, padi, temerloh, disukai, asli, menggelegak, versi

Topic: 4
lemak, joha, hassan, udang, mee, lazat, lobster, berkrim, ketam, laksa, honey, rempah, bakar, kunyit, ikan, bawang, biji, cili, air, garam, hidupkan, step, pekat, padi, pastu, serbuk, hidup, serai, daun, lupa

Topic: 5
pastu, bawang, dah, biji, air, letak, cili, step, ayam, garam, daun, limau, mencuba, selamat, lupa, putih, gula, isi, tutup, kering, tumis, panaskan, yer, bahanbahan, makan, ikan, pes, mendidih, lak, tomato

Topic: 6
ikan, air, bawang, garam, daun, tomato, step, lupa, mencuba, selamat, gula, putih, cili, limau, serai, merah, lada, biarkan, kuah, bahanbahan, sos, mee, lazat, kisar, nak, tambahkan, cuba, ulas, doh, disediakan

Topic: 7
ayam, air, bawang, biji, merah, sos, serbuk, cili, dah, tomato, putih, beras, halia, daun, nasi, garam, rempah, nak, goreng, kari, ketumbar, asam, mencuba, selamat, manis, lada, inci, tepung, rebusan, sup

[(0,
  '0.024*"biji" + 0.021*"nak" + 0.017*"air" + 0.014*"udang" + 0.013*"ikan" + 0.013*"bahanbahan" + 0.011*"cili" + 0.011*"lupa" + 0.011*"step" + 0.010*"letak"'),
 (1,
  '0.021*"telur" + 0.016*"udang" + 0.015*"step" + 0.014*"roti" + 0.013*"dah" + 0.012*"garam" + 0.012*"bawang" + 0.010*"kunyit" + 0.010*"cili" + 0.009*"sikit"'),
 (2,
  '0.017*"sos" + 0.017*"cili" + 0.014*"ikan" + 0.014*"merah" + 0.014*"tempoyak" + 0.011*"kueyteow" + 0.011*"masukan" + 0.011*"char" + 0.011*"patin" + 0.007*"dah"'),
 (3,
  '0.023*"lemak" + 0.017*"joha" + 0.017*"hassan" + 0.015*"udang" + 0.012*"mee" + 0.012*"lazat" + 0.012*"berkrim" + 0.012*"lobster" + 0.012*"ketam" + 0.012*"laksa"'),
 (4,
  '0.026*"pastu" + 0.026*"bawang" + 0.017*"dah" + 0.017*"biji" + 0.015*"air" + 0.015*"letak" + 0.011*"cili" + 0.010*"step" + 0.010*"ayam" + 0.010*"garam"'),
 (5,
  '0.032*"ikan" + 0.018*"air" + 0.015*"bawang" + 0.011*"garam" + 0.011*"daun" + 0.010*"tomato" + 0.010*"step" + 0.010*"lupa" + 0.010*"mencuba" + 0.010*"selamat"'),
 (6,
  '0.035*"ayam" + 0.024*"air" + 0.023*"bawang" + 0.016*"biji" + 0.013*"merah" + 0.013*"sos" + 0.012*"serbuk" + 0.012*"cili" + 0.012*"dah" + 0.012*"tomato"')]

###Inspect Probability

In [ ]:
resepiProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata bawang pada setiap topik
resepiProb["garam"]

##Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
resepiWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"

resepiWN["Synonym_clean"] = cleanWN_Synonym(resepiWN["Synonym"])
resepiWN["Hypernim_clean"] = cleanWN(resepiWN["Hypernim"])
resepiWN["Hyponim_clean"] = cleanWN(resepiWN["Hyponim"])

# output 5 data teratas
resepiWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
1,1,nak,Synset('cub.n.02'),[Synset('male_child.n.01')],[],a male child (a familiar term of address to a ...,cub,[male_child],None
2,1,air,Synset('aquatic.a.02'),[],[],operating or living or growing in water,aquatic,None,None
3,1,udang,Synset('shrimp.n.03'),[Synset('decapod_crustacean.n.01')],[Synset('snapping_shrimp.n.01')],small slender-bodied chiefly marine decapod cr...,shrimp,[decapod_crustacean],[snapping_shrimp]
4,1,ikan,Synset('fish.n.01'),[Synset('aquatic_vertebrate.n.01')],"[Synset('bony_fish.n.01'), Synset('bottom-feed...",any of various mostly cold-blooded aquatic ver...,fish,[aquatic_vertebrate],"[bony_fish, bottom-feeder, bottom_lurkers, car..."

### Make Ontology

In [ ]:
# Make Ontology
resepiOnto = get_ontology("http://test.org/resepi.owl")
makeOntology(resepiOnto, resepiWN)
resepiOnto.save(file = "resepi.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1kHTJ2BC4j55z421dEi7iN01UNEFLtSFg"

In [ ]:
wiki_resepi = pd.read_excel("Resepi_final.xlsx").iloc[:, 1:]
wiki_resepi.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_resepi["Category"] = translate(wiki_resepi["Category"])
wiki_resepi.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_resepi[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
resepiTabel_new = tabel_1981.copy()
resepiTabel_new["correct_category"] = all_cat
resepiTabel_new["suggestion"] = all_suggestion

# Export Result to File
resepiTabel_new.to_excel("resepiTabel_Result.xlsx")
resepiTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "resepiTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
resepiTabel_new = concatListInColumn(resepiTabel_new)
resepiTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, resepiTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_resepi.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
resepiWiki_new = wiki_df.copy()
resepiWiki_new["suggest"] = all_cat

# Export Result to file
resepiWiki_new.to_excel("resepiWiki_Result.xlsx")
resepiWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "resepiWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
resepiOntoWiki = get_ontology("http://test.org/resepi_onto_wiki.owl")
makeOntology_wiki(resepiOntoWiki, resepiWiki_new)
resepiOntoWiki.save(file = "resepi_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = resepiWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
resepiWN_new = listToDataframe(changesList, tableWordnet)
resepiWN_new.to_excel("resepiWN_Result.xlsx")
resepiWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "resepiWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Mamawandiha

In [ ]:
!gdown --id "1ke2lx4sNHgMh7Es9f1_PA3hw7ITKR-54"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1ke2lx4sNHgMh7Es9f1_PA3hw7ITKR-54
To: /content/Mamawandiha.jl
100% 2.78M/2.78M [00:00<00:00, 133MB/s]

In [ ]:
mawa = pd.read_json(r'/content/Mamawandiha.jl', lines = True)

mawa.rename(columns = {"Page_description":"page_description"}, inplace=True)
mawa["page_description"] = delist(mawa, "page_description")
mawa = pre_cleaning_text(mawa, threshold=30)

## GUI Mawawandiha

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = mawa.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
6      0.210252 -0.136258       1        1  31.722263
1      0.210743 -0.077546       2        1  23.928347
0      0.023532  0.190887       3        1  10.831769
3      0.019344  0.085002       4        1  10.459616
2     -0.264202 -0.159911       5        1   8.456646
4     -0.129022 -0.060243       6        1   7.948684
5     -0.070646  0.158069       7        1   6.652675, topic_info=                 Term         Freq        Total Category  logprob  loglift
220            bawang   886.000000   886.000000  Default  30.0000  30.0000
311            tengok   255.000000   255.000000  Default  29.0000  29.0000
232              cili   673.000000   673.000000  Default  28.0000  28.0000
398             ambil   272.000000   272.000000  Default  27.0000  27.0000
91                kak   247.000000   247.000000  Default  26.0000  26.0000
179          bahannya   146.000000   146.000000  Default  25.0000  25.0000
19             tepung   193.000000   193.000000  Default  24.0000  24.0000
2             madihaa  1712.000000  1712.000000  Default  23.0000  23.0000
365         resepinya   207.000000   207.000000  Default  22.0000  22.0000
1099            pulut   123.000000   123.000000  Default  21.0000  21.0000
156               nak   388.000000   388.000000  Default  20.0000  20.0000
25              telur   276.000000   276.000000  Default  19.0000  19.0000
1218             rima   124.000000   124.000000  Default  18.0000  18.0000
24               biji   996.000000   996.000000  Default  17.0000  17.0000
279           mentega   130.000000   130.000000  Default  16.0000  16.0000
480              ikan   255.000000   255.000000  Default  15.0000  15.0000
3                 dah   384.000000   384.000000  Default  14.0000  14.0000
197           kentang   234.000000   234.000000  Default  13.0000  13.0000
30               gula   547.000000   547.000000  Default  12.0000  12.0000
0               salam   734.000000   734.000000  Default  11.0000  11.0000
205              ayam   335.000000   335.000000  Default  10.0000  10.0000
259              susu   185.000000   185.000000  Default   9.0000   9.0000
72             tepong   185.000000   185.000000  Default   8.0000   8.0000
1           sejahtera   688.000000   688.000000  Default   7.0000   7.0000
20             gandum   162.000000   162.000000  Default   6.0000   6.0000
276            gambar   162.000000   162.000000  Default   5.0000   5.0000
246              ulas   397.000000   397.000000  Default   4.0000   4.0000
791            sotong   208.000000   208.000000  Default   3.0000   3.0000
64            mencuba   657.000000   657.000000  Default   2.0000   2.0000
48             sebati   210.000000   210.000000  Default   1.0000   1.0000
480              ikan   255.119905   255.870138   Topic1  -4.3356   1.1452
341            kunyit   154.946485   155.749977   Topic1  -4.8343   1.1430
93               nasi   123.268278   124.018899   Topic1  -5.0630   1.1421
1288            petai   111.012208   111.762138   Topic1  -5.1677   1.1414
524              jawa    98.885730    99.635368   Topic1  -5.2834   1.1406
494             serai    92.856810    93.606448   Topic1  -5.3463   1.1401
759           belacan    85.083586    85.833476   Topic1  -5.4337   1.1394
3378            kucai    62.492360    63.241973   Topic1  -5.7423   1.1362
646           gelugur    59.027046    59.776474   Topic1  -5.7994   1.1355
1294           senduk    54.687769    55.439834   Topic1  -5.8757   1.1345
2236            pucuk    49.822028    50.576800   Topic1  -5.9689   1.1331
516             empuk    49.487151    50.237532   Topic1  -5.9757   1.1331
250             masin    47.442366    48.193048   Topic1  -6.0179   1.1325
485               ala    47.065091    47.815118   Topic1  -6.0258   1.1323
342            jintan    45.675188    46.426698   Topic1  -6.0558   1.1318
492           diketuk    44.251987    45.001656   Topic1  -6.0875   1.1314
497          ketumbar    43.157715    43.908101   Topic1  -6.1125   1.1309
1761              bwg    42.286624    43.036766   Topic1  -6.1329   1.1306
525               pes    42.011254    42.761845   Topic1  -6.1394   1.1304
511            kuntum    40.108314    40.861953   Topic1  -6.1858   1.1295
2325           bateri    39.683913    40.432693   Topic1  -6.1964   1.1295
696         hidangkan    34.403147    35.154531   Topic1  -6.3392   1.1265
1968             acar    32.650459    33.402932   Topic1  -6.3915   1.1254
2277       dimasukkan    32.321761    33.092196   Topic1  -6.4016   1.1246
175            potato    30.462990    31.212922   Topic1  -6.4609   1.1238
207        ulasbawang    27.939571    28.689769   Topic1  -6.5473   1.1217
692         kepedasan    27.730471    28.481160   Topic1  -6.5548   1.1214
1295           jusnya    27.642691    28.392547   Topic1  -6.5580   1.1214
293         memanjang    25.480892    26.231345   Topic1  -6.6394   1.1191
2226             soto    25.072251    25.821330   Topic1  -6.6556   1.1187
523              asam   196.567235   208.672440   Topic1  -4.5964   1.0884
778              sawi    55.263515    57.431296   Topic1  -5.8653   1.1097
253           memasak   109.314023   115.337354   Topic1  -5.1831   1.0945
691            tumbuk   169.653958   184.031757   Topic1  -4.7436   1.0668
232              cili   581.345858   673.104506   Topic1  -3.5120   1.0016
327            sambal   199.729973   222.558645   Topic1  -4.5804   1.0399
496              padi   186.392710   209.395543   Topic1  -4.6495   1.0318
339            rempah    87.915789    96.440630   Topic1  -5.4010   1.0556
467              inci   172.975621   202.214785   Topic1  -4.7242   0.9920
197           kentang   195.768544   234.055792   Topic1  -4.6004   0.9695
246              ulas   306.394762   397.559920   Topic1  -4.1525   0.8877
137             merah   305.322460   399.488918   Topic1  -4.1560   0.8793
249           secukup   233.624135   299.839033   Topic1  -4.4237   0.8986
508             tumis   166.202857   206.454121   Topic1  -4.7642   0.9313
741             udang   263.457116   357.354199   Topic1  -4.3035   0.8433
220            bawang   572.215326   886.252793   Topic1  -3.5279   0.7107
24               biji   614.401424   996.244101   Topic1  -3.4567   0.6648
242             hiris   170.881265   229.977115   Topic1  -4.7364   0.8511
236             kisar   169.921035   231.019924   Topic1  -4.7420   0.8410
287            keping   121.914745   154.551400   Topic1  -5.0740   0.9109
487              ekor    79.674626    91.658042   Topic1  -5.4994   1.0080
45              putih   305.324493   522.567938   Topic1  -4.1560   0.6108
216              daun   191.152178   285.004926   Topic1  -4.6243   0.7487
75              garam   393.199144   842.582323   Topic1  -3.9031   0.3860
82                air   295.623931   668.154252   Topic1  -4.1883   0.3327
31              halus   201.698920   430.540488   Topic1  -4.5706   0.3899
63            selamat   248.150671   772.915592   Topic1  -4.3633   0.0120
30               gula   206.587009   547.254738   Topic1  -4.5467   0.1740
69             serbuk   170.126524   370.464847   Topic1  -4.7408   0.3699
2             madihaa   260.650046  1712.564802   Topic1  -4.3142  -0.7344
0               salam   194.281037   734.589555   Topic1  -4.6081  -0.1819
1           sejahtera   188.439305   688.474013   Topic1  -4.6386  -0.1476
16                aka   159.965536   417.713386   Topic1  -4.8024   0.1883
238            carrot   113.241614   114.033120   Topic2  -4.8659   1.4231
370         spaghetti    95.576505    96.364577   Topic2  -5.0355   1.4219
2811           wantan    87.377967    88.165913   Topic2  -5.1252   1.4211
209               tin    80.974289    81.767491   Topic2  -5.2013   1.4204
2446             puff    79.378006    80.186101   Topic2  -5.2212   1.4200
503             lobak    71.689103    72.478151   Topic2  -5.3231   1.4192
294             sosej    70.581848    71.370926   Topic2  -5.3386   1.4190
369           avocado    68.536629    69.324858   Topic2  -5.3680   1.4187
228          cendawan    65.189794    65.979379   Topic2  -5.4181   1.4181
314             tauhu    64.810338    65.599163   Topic2  -5.4240   1.4180
797               mee    64.325691    65.115880   Topic2  -5.4315   1.4179
406          taburkan    56.273962    57.064424   Topic2  -5.5652   1.4162
566         dicincang    47.283124    48.071739   Topic2  -5.7393   1.4136
385            zaitun    44.583535    45.372779   Topic2  -5.7981   1.4126
387              ceri    43.140017    43.929404   Topic2  -5.8310   1.4120
1002             labu    38.415628    39.208221   Topic2  -5.9470   1.4097
380             lemon    37.485467    38.275926   Topic2  -5.9715   1.4092
402          berlebih    36.870155    37.658567   Topic2  -5.9880   1.4089
344              pati    35.251841    36.041201   Topic2  -6.0329   1.4080
1052            timun    34.795815    35.588283   Topic2  -6.0459   1.4076
375            pendek    34.278933    35.068567   Topic2  -6.0609   1.4073
743              dada    33.749636    34.538598   Topic2  -6.0764   1.4070
383             fresh    31.416215    32.205476   Topic2  -6.1481   1.4053
793       cauliflower    30.481687    31.270018   Topic2  -6.1783   1.4046
384             basil    30.228721    31.016782   Topic2  -6.1866   1.4044
1030           sardin    30.214784    31.002861   Topic2  -6.1871   1.4044
781           brokoli    29.447912    30.236864   Topic2  -6.2128   1.4037
399            jerang    29.518258    30.309693   Topic2  -6.2104   1.4036
460            seekor    27.804410    28.592703   Topic2  -6.2702   1.4021
2560           jejari    26.354909    27.147574   Topic2  -6.3238   1.4005
247             hitam   132.185638   144.714300   Topic2  -4.7112   1.3396
212              lada   175.822399   199.885695   Topic2  -4.4259   1.3018
777            bebola    91.984766   102.867136   Topic2  -5.0738   1.3183
204           cincang    98.109108   110.670908   Topic2  -5.0093   1.3096
244            didadu    83.056916    94.391584   Topic2  -5.1759   1.3022
290               sos   208.944088   291.852343   Topic2  -4.2534   1.0959
205              ayam   231.539757   335.516266   Topic2  -4.1507   1.0592
2             madihaa   816.763917  1712.564802   Topic2  -2.8901   0.6897
791            sotong   144.330965   208.787329   Topic2  -4.6233   1.0609
338             letak   165.433421   265.677378   Topic2  -4.4868   0.9564
217               sup   114.937558   166.535142   Topic2  -4.8510   1.0593
229              dadu    66.628379    83.130122   Topic2  -5.3963   1.2088
103               dlm    60.728491    75.229190   Topic2  -5.4890   1.2160
243            tomato   110.972441   178.709566   Topic2  -4.8861   0.9536
267               isi   135.226336   242.088759   Topic2  -4.6885   0.8478
220            bawang   313.392295   886.252793   Topic2  -3.8480   0.3906
185             rebus   116.710702   206.593265   Topic2  -4.8357   0.8591
25              telur   140.030693   276.922648   Topic2  -4.6536   0.7482
45              putih   198.232309   522.567938   Topic2  -4.3060   0.4608
75              garam   261.922676   842.582323   Topic2  -4.0274   0.2617
31              halus   169.895525   430.540488   Topic2  -4.4602   0.5002
69             serbuk   156.075059   370.464847   Topic2  -4.5451   0.5657
24               biji   228.576806   996.244101   Topic2  -4.1635  -0.0420
64            mencuba   179.793860   657.763851   Topic2  -4.4036   0.1331
0               salam   174.717895   734.589555   Topic2  -4.4322  -0.0060
82                air   162.719781   668.154252   Topic2  -4.5034   0.0176
63            selamat   170.423755   772.915592   Topic2  -4.4571  -0.0818
1           sejahtera   155.326495   688.474013   Topic2  -4.5499  -0.0588
346            kering   107.703524   266.132445   Topic2  -4.9160   0.5255
17              ratna   115.419359   413.371924   Topic2  -4.8468   0.1543
223            goreng    96.657958   251.942442   Topic2  -5.0242   0.4721
16                aka    97.311001   417.713386   Topic2  -5.0175  -0.0268
279           mentega   129.727565   130.503833   Topic3  -3.9374   2.2167
1000          cheddar    52.371972    53.147153   Topic3  -4.8445   2.2080
272              alas    35.498021    36.273216   Topic3  -5.2334   2.2011
95                yis    34.270519    35.044102   Topic3  -5.2686   2.2004
1149          vanilla    33.685052    34.459362   Topic3  -5.2858   2.2000
439            kastor    31.125187    31.899269   Topic3  -5.3648   2.1981
1987            camca    27.208302    27.982606   Topic3  -5.4993   2.1946
2431          beignet    26.695894    27.469305   Topic3  -5.5183   2.1941
1525              mat    26.352542    27.138470   Topic3  -5.5313   2.1933
1005         marjerin    25.351716    26.126909   Topic3  -5.5700   2.1926
34               soda    22.289529    23.063890   Topic3  -5.6987   2.1885
2215              mix    21.674739    22.455858   Topic3  -5.7267   2.1873
2435            basah    19.769342    20.547425   Topic3  -5.8187   2.1841
2429            lihat    18.958563    19.742101   Topic3  -5.8606   2.1822
3895            pizza    18.628304    19.402920   Topic3  -5.8782   2.1819
1892         cempedak    18.352964    19.127204   Topic3  -5.8930   2.1814
1849            basuh    18.251994    19.030415   Topic3  -5.8986   2.1809
52              tuang    17.929542    18.704834   Topic3  -5.9164   2.1804
2385            canai    17.752381    18.526700   Topic3  -5.9263   2.1800
2460           lenser    17.283992    18.057805   Topic3  -5.9531   2.1789
1535           kental    16.303230    17.077133   Topic3  -6.0115   2.1763
984          membakar    15.861009    16.639047   Topic3  -6.0390   2.1748
3792        tengahnya    15.653528    16.427486   Topic3  -6.0521   2.1744
1538             tepi    15.727704    16.506082   Topic3  -6.0474   2.1744
972            castor    15.466745    16.240805   Topic3  -6.0641   2.1739
3941             pide    15.263421    16.037460   Topic3  -6.0774   2.1732
616            sekata    14.916576    15.693088   Topic3  -6.1004   2.1719
3785             alex    14.812132    15.586111   Topic3  -6.1074   2.1718
3786              goh    14.812132    15.586111   Topic3  -6.1074   2.1718
3787              che    14.812132    15.586111   Topic3  -6.1074   2.1718
19             tepung   178.287869   193.292066   Topic3  -3.6194   2.1419
274             paper    28.099379    30.305147   Topic3  -5.4671   2.1471
922            butter    45.713600    50.786081   Topic3  -4.9804   2.1175
1008             suhu    48.766292    56.090740   Topic3  -4.9158   2.0828
54              acuan    37.575290    43.139233   Topic3  -5.1765   2.0846
830               doh    60.469166    73.912021   Topic3  -4.7007   2.0219
191              oven    86.949436   111.724960   Topic3  -4.3375   1.9720
974             cream    65.360685    82.261956   Topic3  -4.6229   1.9927
53             adunan    50.111051    62.323657   Topic3  -4.8886   2.0046
20             gandum   113.785918   162.181970   Topic3  -4.0685   1.8683
264            cheese    73.410404   111.344307   Topic3  -4.5068   1.8061
259              susu   109.776871   185.848085   Topic3  -4.1044   1.6962
48             sebati   105.118688   210.758182   Topic3  -4.1477   1.5271
373              akak    39.654595    56.573715   Topic3  -5.1226   1.8673
833              roti    50.560289    80.380836   Topic3  -4.8797   1.7591
84             loyang    41.762431    67.984669   Topic3  -5.0708   1.7354
190             bakar    51.225928    93.794677   Topic3  -4.8666   1.6178
139              suam    44.331770    79.291941   Topic3  -5.0111   1.6413
30               gula   107.542296   547.254738   Topic3  -4.1250   0.5957
25              telur    76.245264   276.922648   Topic3  -4.4689   0.9329
73                teh    42.793000    86.966110   Topic3  -5.0465   1.5135
146              gaul    60.598301   202.128450   Topic3  -4.6986   1.0181
41           panaskan    62.523495   252.671281   Topic3  -4.6673   0.8261
2             madihaa   128.085406  1712.564802   Topic3  -3.9501  -0.3704
278              cair    49.503277   146.111638   Topic3  -4.9008   1.1404
75              garam    80.133728   842.582323   Topic3  -4.4191  -0.1301
0               salam    62.686107   734.589555   Topic3  -4.6647  -0.2385
24               biji    66.336334   996.244101   Topic3  -4.6081  -0.4866
1           sejahtera    60.873405   688.474013   Topic3  -4.6940  -0.2030
44              pekat    45.701074   162.342473   Topic3  -4.9807   0.9551
82                air    53.737373   668.154252   Topic3  -4.8187  -0.2977
63            selamat    50.643491   772.915592   Topic3  -4.8780  -0.5027
64            mencuba    47.112246   657.763851   Topic3  -4.9503  -0.4136
98              parut    94.904519    95.646417   Topic4  -4.2150   2.2499
562            pandan    44.147193    44.887102   Topic4  -4.9803   2.2410
1134           mangga    40.581561    41.320797   Topic4  -5.0646   2.2396
1386             sagu    28.758430    29.496652   Topic4  -5.4089   2.2323
1592          filling    28.639147    29.396441   Topic4  -5.4131   2.2315
1125             oats    27.014990    27.753636   Topic4  -5.4715   2.2307
352           paipkan    24.430829    25.176697   Topic4  -5.5720   2.2276
361           keledek    23.623916    24.362343   Topic4  -5.6056   2.2269
2653           gulung    23.535634    24.274311   Topic4  -5.6094   2.2267
1303            jambu    23.336357    24.074502   Topic4  -5.6179   2.2265
920            bingka    22.858235    23.596910   Topic4  -5.6386   2.2258
3614            choux    21.827720    22.574295   Topic4  -5.6847   2.2240
1573           scones    20.541407    21.280370   Topic4  -5.7454   2.2223
915             jeruk    19.817558    20.560473   Topic4  -5.7813   2.2208
1304            golok    19.118025    19.856062   Topic4  -5.8172   2.2198
2648           laksam    19.132590    19.871271   Topic4  -5.8165   2.2198
1574       sepenuhnya    19.099213    19.838148   Topic4  -5.8182   2.2197
1277          rujukan    17.939999    18.679027   Topic4  -5.8808   2.2173
1127            seeds    16.694634    17.432673   Topic4  -5.9528   2.2144
1126             chia    16.239459    16.977496   Topic4  -5.9804   2.2132
2597              klu    16.247250    16.991210   Topic4  -5.9800   2.2129
1842          kedalam    15.948344    16.690692   Topic4  -5.9985   2.2122
1311             nama    15.735474    16.484378   Topic4  -6.0120   2.2112
1282           perisa    15.539828    16.279609   Topic4  -6.0245   2.2111
3339            comey    15.003752    15.741789   Topic4  -6.0596   2.2096
3340           pakcik    15.003752    15.741789   Topic4  -6.0596   2.2096
1004         tapiskan    14.908226    15.647152   Topic4  -6.0660   2.2093
4397          pindang    14.844253    15.582290   Topic4  -6.0703   2.2091
1377              sum    14.740280    15.478317   Topic4  -6.0773   2.2088
1390            kerek    14.649654    15.388138   Topic4  -6.0835   2.2085
575            campur    68.851588    79.703725   Topic4  -4.5359   2.1113
349            digaul    22.094688    23.810017   Topic4  -5.6725   2.1829
143          sejukkan    45.889658    55.056512   Topic4  -4.9416   2.0755
1539            pisau    26.605620    29.889336   Topic4  -5.4868   2.1413
94              pasir    37.905638    47.463151   Topic4  -5.1328   2.0328
65             pisang    65.193388    91.636696   Topic4  -4.5905   1.9172
26              sejuk    71.862707   125.612390   Topic4  -4.4931   1.6992
728          tuangkan    38.876647    57.966806   Topic4  -5.1075   1.8582
463               ubi    91.670534   213.604046   Topic4  -4.2497   1.4117
97             kelapa    69.139737   154.036045   Topic4  -4.5317   1.4566
64            mencuba   167.752141   657.763851   Topic4  -3.6454   0.8913

Topic: 1
tepung, mentega, madihaa, gandum, susu, gula, sebati, oven, garam, telur, cheese, biji, cream, salam, panaskan, sejahtera, gaul, doh, air, cheddar, bakar, selamat, roti, adunan, cair, suhu, mencuba, butter, pekat, suam

Topic: 2
madihaa, bawang, garam, ayam, biji, sos, putih, mencuba, lada, salam, selamat, halus, letak, air, serbuk, sejahtera, sotong, telur, isi, hitam, rebus, ratna, sup, carrot, tomato, kering, cincang, aka, goreng, spaghetti

Topic: 3
kak, madihaa, ambil, nak, resepinya, rima, dah, ayu, internet, kongsikan, berkongsi, gambar, makan, silap, asalnya, pulak, mencuba, idea, hehe, tengok, kat, kuih, susah, cuba, selamat, western, tkasih, ketandusan, meenmar, masaknya

Topic: 4
mencuba, madihaa, selamat, salam, sejahtera, gula, air, parut, ubi, aka, ratna, santan, sejuk, kelapa, campur, jagung, pisang, sotong, tepong, garam, sejukkan, beras, pandan, saiz, mangga, buah, susu, tuangkan, sikit, kuning

Topic: 5
pulut, madihaa, salam, sejahtera, nak, selamat, air, dah, kasih, kampong, gambar, oklah, kurangkan, terima, hihi, kepekatan, dimasak, durian, lauk, layan, masukan, mencuba, kat, gula, jumpa, ratna, disukai, aka, bilis, hehe

Topic: 6
tengok, bahannya, biji, salam, telur, sejahtera, tepong, bilis, mencuba, gambar, minum, selamat, garam, dapur, madihaa, kentang, teh, segar, susu, suam, muffin, panas, update, laksa, baking, powder, kacang, kayu, waffle, kroket

Topic: 7
biji, cili, bawang, garam, ulas, putih, merah, air, udang, madihaa, ikan, selamat, secukup, gula, halus, sambal, asam, kentang, salam, daun, sejahtera, padi, inci, hiris, serbuk, kisar, tumbuk, tumis, aka, kunyit

[(0,
  '0.027*"tepung" + 0.019*"mentega" + 0.019*"madihaa" + 0.017*"gandum" + 0.017*"susu" + 0.016*"gula" + 0.016*"sebati" + 0.013*"oven" + 0.012*"garam" + 0.011*"telur"'),
 (1,
  '0.056*"madihaa" + 0.021*"bawang" + 0.018*"garam" + 0.016*"ayam" + 0.016*"biji" + 0.014*"sos" + 0.013*"putih" + 0.012*"mencuba" + 0.012*"lada" + 0.012*"salam"'),
 (2,
  '0.037*"kak" + 0.035*"madihaa" + 0.032*"ambil" + 0.026*"nak" + 0.025*"resepinya" + 0.024*"rima" + 0.023*"dah" + 0.015*"ayu" + 0.014*"internet" + 0.013*"kongsikan"'),
 (3,
  '0.026*"mencuba" + 0.025*"madihaa" + 0.025*"selamat" + 0.024*"salam" + 0.023*"sejahtera" + 0.022*"gula" + 0.016*"air" + 0.015*"parut" + 0.014*"ubi" + 0.014*"aka"'),
 (4,
  '0.025*"pulut" + 0.025*"madihaa" + 0.017*"salam" + 0.014*"sejahtera" + 0.012*"nak" + 0.012*"selamat" + 0.011*"air" + 0.010*"dah" + 0.010*"kasih" + 0.010*"kampong"'),
 (5,
  '0.043*"tengok" + 0.036*"bahannya" + 0.017*"biji" + 0.015*"salam" + 0.015*"telur" + 0.015*"sejahtera" + 0.014*"tepong" + 0.013*"bilis" + 0.013*"mencuba" + 0.013*"gambar"'),
 (6,
  '0.032*"biji" + 0.030*"cili" + 0.029*"bawang" + 0.020*"garam" + 0.016*"ulas" + 0.016*"putih" + 0.016*"merah" + 0.015*"air" + 0.014*"udang" + 0.013*"madihaa"')]

### Inspect Probability

In [ ]:
mawaProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata garam pada setiap topik
mawaProb["garam"]

## Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
mawaWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"
mawaWN["Synonym_clean"] = cleanWN_Synonym(mawaWN["Synonym"])
mawaWN["Hypernim_clean"] = cleanWN(mawaWN["Hypernim"])
mawaWN["Hyponim_clean"] = cleanWN(mawaWN["Hyponim"])

# output 5 data teratas
mawaWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,tepung,Synset('meal.n.03'),[Synset('foodstuff.n.02')],"[Synset('cornmeal.n.01'), Synset('farina.n.01'...",coarsely ground foodstuff; especially seeds of...,meal,[foodstuff],"[cornmeal, farina, kibble, matzo_meal, oatmeal..."
1,1,mentega,Synset('penuche.n.01'),[Synset('fudge.n.01')],[],fudge made with brown sugar and butter and mil...,penuche,[fudge],None
2,1,madihaa,None,None,None,None,None,None,None
3,1,gandum,Synset('grain.n.02'),[Synset('foodstuff.n.02')],"[Synset('barley.n.01'), Synset('buckwheat.n.02...",foodstuff prepared from the starchy grains of ...,grain,[foodstuff],"[barley, buckwheat, corn, grist, groats, malt,..."
4,1,susu,Synset('white.s.09'),[],[],(of coffee) having cream or milk added,white,None,None

### Make Ontology

In [ ]:
# Make Ontology
mawaOnto = get_ontology("http://test.org/mamawandiha.owl")
makeOntology(mawaOnto, mawaWN)
mawaOnto.save(file = "mamawandiha.owl")

## Wikipedia & category

In [ ]:
!gdown --id "1mz7_P5JERgWh2IYZhGqUUlzs9RPrXRt_"

In [ ]:
wiki_mawa = pd.read_excel("Mawa_final.xlsx").iloc[:, 1:]
wiki_mawa.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_mawa["Category"] = translate(wiki_mawa["Category"])
wiki_mawa.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_mawa[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
mawaTabel_new = tabel_1981.copy()
mawaTabel_new["correct_category"] = all_cat
mawaTabel_new["suggestion"] = all_suggestion

# Export Result to File
mawaTabel_new.to_excel("mawaTabel_Result.xlsx")
mawaTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "mawaTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
mawaTabel_new = concatListInColumn(mawaTabel_new)
mawaTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, mawaTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_mawa.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
mawaWiki_new = wiki_df.copy()
mawaWiki_new["suggest"] = all_cat

# Export Result to file
mawaWiki_new.to_excel("mawaWiki_Result.xlsx")
mawaWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "mawaWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
mawaOntoWiki = get_ontology("http://test.org/mawa_onto_wiki.owl")
makeOntology_wiki(mawaOntoWiki, mawaWiki_new)
mawaOntoWiki.save(file = "mawa_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = mawaWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
mawaWN_new = listToDataframe(changesList, tableWordnet)
mawaWN_new.to_excel("mawaWN_Result.xlsx")
mawaWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "mawaWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Salamisimon

In [ ]:
!gdown --id "14W7cUo_TjgMeFbkWtYIpcwprR-lkWG6o"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=14W7cUo_TjgMeFbkWtYIpcwprR-lkWG6o
To: /content/Salamisimon.jl
100% 1.64M/1.64M [00:00<00:00, 181MB/s]

In [ ]:
misimon = pd.read_json(r'/content/Salamisimon.jl', lines = True)

misimon.rename(columns = {"Page_description":"page_description"}, inplace=True)
misimon["page_description"] = delist(misimon, "page_description")
misimon = pre_cleaning_text(misimon, threshold=30)

## GUI Salamisimon

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = misimon.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0     -0.221748  0.038121       1        1  29.199262
4     -0.239962  0.044908       2        1  27.069562
6     -0.100714 -0.221139       3        1  14.573332
3      0.101160  0.163806       4        1   9.491792
2      0.230226 -0.145260       5        1   8.012747
1      0.118744  0.062544       6        1   6.647604
5      0.112294  0.057020       7        1   5.005700, topic_info=                   Term        Freq       Total Category  logprob  loglift
6                  ikan  610.000000  610.000000  Default  30.0000  30.0000
55               bawang  815.000000  815.000000  Default  29.0000  29.0000
71                 gula  510.000000  510.000000  Default  28.0000  28.0000
63                makan  480.000000  480.000000  Default  27.0000  27.0000
58                 cili  504.000000  504.000000  Default  26.0000  26.0000
1771                kek  157.000000  157.000000  Default  25.0000  25.0000
39                 biji  723.000000  723.000000  Default  24.0000  24.0000
30               tepung  191.000000  191.000000  Default  23.0000  23.0000
25                 ayam  408.000000  408.000000  Default  22.0000  22.0000
331                asam  230.000000  230.000000  Default  21.0000  21.0000
13                 gram  275.000000  275.000000  Default  20.0000  20.0000
28               goreng  412.000000  412.000000  Default  19.0000  19.0000
61                  nak  236.000000  236.000000  Default  18.0000  18.0000
106              perasa  358.000000  358.000000  Default  17.0000  17.0000
47                  air  610.000000  610.000000  Default  16.0000  16.0000
251                susu  145.000000  145.000000  Default  15.0000  15.0000
1042               sate   77.000000   77.000000  Default  14.0000  14.0000
115               telur  338.000000  338.000000  Default  13.0000  13.0000
44                garam  543.000000  543.000000  Default  12.0000  12.0000
14                putih  524.000000  524.000000  Default  11.0000  11.0000
250              serbuk  224.000000  224.000000  Default  10.0000  10.0000
390             firdaus  143.000000  143.000000  Default   9.0000   9.0000
225              adunan  109.000000  109.000000  Default   8.0000   8.0000
363                 sos  154.000000  154.000000  Default   7.0000   7.0000
112              kacang  177.000000  177.000000  Default   6.0000   6.0000
124               encik  130.000000  130.000000  Default   5.0000   5.0000
4                  amie  620.000000  620.000000  Default   4.0000   4.0000
148             cincang  133.000000  133.000000  Default   3.0000   3.0000
540              daging  216.000000  216.000000  Default   2.0000   2.0000
96                bunga  183.000000  183.000000  Default   1.0000   1.0000
148             cincang  132.769746  133.520328   Topic1  -4.7636   1.2254
521               betik   83.636995   84.386259   Topic1  -5.2258   1.2221
997                itik   56.940501   57.693787   Topic1  -5.6102   1.2179
1050             kepala   52.842357   53.594806   Topic1  -5.6849   1.2169
1115              cocos   43.888862   44.639267   Topic1  -5.8706   1.2141
97               lawang   42.136314   42.885419   Topic1  -5.9113   1.2134
99               pelaga   37.034060   37.783049   Topic1  -6.0404   1.2110
2922              lodeh   35.689361   36.438329   Topic1  -6.0774   1.2103
584             cengkih   35.517141   36.266460   Topic1  -6.0822   1.2101
827             tradisi   31.799849   32.551119   Topic1  -6.1928   1.2077
362                madu   30.509775   31.273175   Topic1  -6.2342   1.2063
2081               inci   28.560551   29.311637   Topic1  -6.3002   1.2051
386          kekuningan   26.733579   27.483113   Topic1  -6.3663   1.2034
153             perahan   26.435466   27.185167   Topic1  -6.3775   1.2031
601             penumis   25.357354   26.106440   Topic1  -6.4192   1.2019
1706           shiitake   21.622774   22.373038   Topic1  -6.5785   1.1969
360             beriani   21.173828   21.922681   Topic1  -6.5995   1.1963
146         dibersihkan   20.446709   21.196942   Topic1  -6.6344   1.1950
42                tipis   21.229092   22.022752   Topic1  -6.5969   1.1943
403                 bdr   18.161784   18.914266   Topic1  -6.7529   1.1904
3624           brengkes   16.498934   17.252767   Topic1  -6.8490   1.1864
3461             pastil   15.701365   16.450195   Topic1  -6.8985   1.1844
2050               chef   15.692331   16.449247   Topic1  -6.8991   1.1839
1765              botol   15.533559   16.284808   Topic1  -6.9092   1.1838
343             sunkist   15.290277   16.041443   Topic1  -6.9250   1.1831
2073              kucai   15.202803   15.951890   Topic1  -6.9308   1.1829
495             kuetiau   14.577411   15.325923   Topic1  -6.9728   1.1810
581            kelmarin   13.424739   14.200052   Topic1  -7.0552   1.1749
1080            mendung   12.910890   13.663819   Topic1  -7.0942   1.1743
1072            sekejap   12.084844   12.835807   Topic1  -7.1603   1.1707
149              kuntum   62.789218   66.718115   Topic1  -5.5125   1.1703
504                sawi   40.535573   43.520859   Topic1  -5.9501   1.1600
5                  acar   28.927567   30.874574   Topic1  -6.2875   1.1659
52                kulit  173.086019  191.903086   Topic1  -4.4985   1.1278
250              serbuk  200.856902  224.430590   Topic1  -4.3497   1.1201
96                bunga  161.728474  183.218311   Topic1  -4.5663   1.1063
540              daging  188.720578  216.335081   Topic1  -4.4120   1.0945
3453              bihun   30.145683   32.658307   Topic1  -6.2462   1.1510
443                lada  107.535452  131.126319   Topic1  -4.9744   1.0327
774             rendang   34.775705   39.278496   Topic1  -6.1033   1.1093
55               bawang  527.081869  815.581291   Topic1  -3.3849   0.7945
134               udang  177.098562  248.859815   Topic1  -4.4755   0.8908
26                kurma   39.225269   45.010848   Topic1  -5.9829   1.0934
14                putih  321.205134  524.327640   Topic1  -3.8802   0.7410
56               tomato  150.641383  219.262763   Topic1  -4.6373   0.8557
88             panaskan  123.933440  174.922887   Topic1  -4.8325   0.8864
74                 gaul  122.992304  173.663147   Topic1  -4.8401   0.8860
31                sayur   70.128548   90.072555   Topic1  -5.4019   0.9807
363                 sos  107.308108  154.315396   Topic1  -4.9765   0.8677
385                layu   53.164683   64.939936   Topic1  -5.6789   1.0310
95                manis  137.690261  217.156860   Topic1  -4.7272   0.7754
439               halia  108.873650  165.458599   Topic1  -4.9621   0.8125
114              tumbuk  139.398500  231.061412   Topic1  -4.7149   0.7257
33                tumis  126.495725  205.053784   Topic1  -4.8120   0.7480
358                kari   82.775950  117.019881   Topic1  -5.2361   0.8848
59                merah  211.500010  413.203036   Topic1  -4.2980   0.5613
4                  amie  274.791367  620.664662   Topic1  -4.0362   0.4162
58                 cili  235.747203  504.911913   Topic1  -4.1895   0.4694
91                kuali   77.377376  108.672521   Topic1  -5.3036   0.8914
44                garam  224.598639  543.594028   Topic1  -4.2379   0.3471
28               goreng  179.737418  412.458022   Topic1  -4.4608   0.4004
39                 biji  253.566726  723.809826   Topic1  -4.1166   0.1821
106              perasa  156.969315  358.072287   Topic1  -4.5962   0.4063
92              hirisan  102.402805  181.021740   Topic1  -5.0233   0.6613
383                ulas  111.978757  214.714417   Topic1  -4.9339   0.5800
47                  air  192.269536  610.238667   Topic1  -4.3934   0.0761
25                 ayam  142.698287  408.549612   Topic1  -4.6915   0.1791
108               dapur  116.651745  295.921515   Topic1  -4.8931   0.3001
12           bahanbahan  117.425679  334.332865   Topic1  -4.8864   0.1847
23                 nasi  109.831875  292.868996   Topic1  -4.9533   0.2503
373               petai   73.277722   74.030725   Topic2  -5.2823   1.2965
1036            rebusan   58.433670   59.186562   Topic2  -5.5086   1.2940
1019           tempoyak   48.556526   49.309559   Topic2  -5.6938   1.2914
3635               coto   48.277534   49.031357   Topic2  -5.6996   1.2913
658            lengkuas   45.854052   46.607219   Topic2  -5.7511   1.2905
3636           makassar   34.851512   35.604953   Topic2  -6.0254   1.2854
693             gelugor   33.811230   34.563621   Topic2  -6.0557   1.2848
531               celur   32.467888   33.221057   Topic2  -6.0963   1.2838
420              sardin   30.878088   31.633107   Topic2  -6.1465   1.2826
351              bancuh   29.377454   30.131805   Topic2  -6.1963   1.2814
3879              pipit   26.858798   27.611060   Topic2  -6.2859   1.2791
2095              layar   25.103977   25.856596   Topic2  -6.3535   1.2772
655             gelugur   24.802091   25.554440   Topic2  -6.3656   1.2769
337               bendi   22.808339   23.562803   Topic2  -6.4494   1.2742
2094             kencur   22.101525   22.853877   Topic2  -6.4809   1.2733
93                serai  118.899641  123.215551   Topic2  -4.7982   1.2711
2192              kesum   20.383119   21.135302   Topic2  -6.5618   1.2705
336          ulamulaman   19.805209   20.558207   Topic2  -6.5906   1.2694
730              ambeng   18.902992   19.655750   Topic2  -6.6372   1.2677
547               galah   18.786733   19.540991   Topic2  -6.6434   1.2674
37              belacan  119.955208  125.147138   Topic2  -4.7894   1.2644
466            bancuhan   17.097444   17.853523   Topic2  -6.7376   1.2635
69                 cuka   16.454317   17.208225   Topic2  -6.7759   1.2620
459               ketuk   16.120196   16.872854   Topic2  -6.7964   1.2611
598             lettuce   16.085623   16.841546   Topic2  -6.7986   1.2608
3880              pecak   15.854765   16.606964   Topic2  -6.8130   1.2604
453              kerang   15.704436   16.458477   Topic2  -6.8226   1.2599
2956               kima   14.973323   15.726178   Topic2  -6.8702   1.2577
339               coral   14.335951   15.090814   Topic2  -6.9137   1.2554
3692               suam   14.224801   14.983458   Topic2  -6.9215   1.2548
1868             terung   46.860673   49.395870   Topic2  -5.7293   1.2541
7                 masin   73.369990   78.818850   Topic2  -5.2810   1.2351
331                asam  209.843203  230.594894   Topic2  -4.2302   1.2125
572              tulang   48.725429   52.733665   Topic2  -5.6903   1.2277
6                  ikan  523.776595  610.257080   Topic2  -3.3155   1.1539
535              keping   91.129099  100.741384   Topic2  -5.0642   1.2065
152             tangkai   73.612257   83.003067   Topic2  -5.2777   1.1867
656               purut   36.227795   39.511505   Topic2  -5.9867   1.2200
110               nanas   55.595243   62.892664   Topic2  -5.5584   1.1834
583               lembu   53.818532   61.732846   Topic2  -5.5909   1.1696
489                kuah  139.968174  189.642444   Topic2  -4.6351   1.0030
36               sambal  186.447369  275.030300   Topic2  -4.3484   0.9180
65                limau  135.497410  198.036531   Topic2  -4.6676   0.9273
350                jawa   75.370628   99.614003   Topic2  -5.2541   1.0279
101               kisar  184.607233  293.751774   Topic2  -4.3583   0.8423
213                daun  222.519683  371.281095   Topic2  -4.1715   0.7948
132              batang  101.043186  143.717954   Topic2  -4.9610   0.9545
39                 biji  373.441647  723.809826   Topic2  -3.6538   0.6450
58                 cili  268.545881  504.911913   Topic2  -3.9835   0.6754
112              kacang  117.090949  177.984642   Topic2  -4.8136   0.8880
106              perasa  200.483950  358.072287   Topic2  -4.2758   0.7268
224            mendidih  113.585867  171.917576   Topic2  -4.8440   0.8923
44                garam  264.579892  543.594028   Topic2  -3.9984   0.5867
60                 padi  133.635246  217.368567   Topic2  -4.6814   0.8203
382                 isi  113.281801  175.997366   Topic2  -4.8466   0.8662
47                  air  258.382154  610.238667   Topic2  -4.0221   0.4473
41                hiris  137.800051  242.930052   Topic2  -4.6507   0.7398
55               bawang  287.880872  815.581291   Topic2  -3.9140   0.2654
207              santan  127.255254  227.862249   Topic2  -4.7303   0.7242
71                 gula  200.505481  510.549130   Topic2  -4.2757   0.3721
12           bahanbahan  150.054952  334.332865   Topic2  -4.5655   0.5056
59                merah  169.554225  413.203036   Topic2  -4.4433   0.4160
14                putih  178.376211  524.327640   Topic2  -4.3926   0.2285
25                 ayam  147.205857  408.549612   Topic2  -4.5847   0.2860
63                makan  154.771797  480.039696   Topic2  -4.5346   0.1748
108               dapur  125.242562  295.921515   Topic2  -4.7463   0.4469
28               goreng  141.051289  412.458022   Topic2  -4.6274   0.2337
23                 nasi  105.605266  292.868996   Topic2  -4.9168   0.2867
279             pewarna   77.125939   77.857528   Topic3  -4.6119   1.9165
217            agaragar   69.953904   70.685614   Topic3  -4.7095   1.9156
884              loyang   50.270022   51.001675   Topic3  -5.0399   1.9115
255               acuan   46.550627   47.282373   Topic3  -5.1168   1.9104
2828           tempahan   40.518560   41.255984   Topic3  -5.2555   1.9079
2581            lapisan   30.012834   30.744649   Topic3  -5.5557   1.9019
1435               sagu   28.215136   28.949060   Topic3  -5.6174   1.9003
1440                doh   27.686243   28.418272   Topic3  -5.6364   1.8999
1433             candil   24.467396   25.198898   Topic3  -5.7600   1.8965
2551             kismis   24.183218   24.915585   Topic3  -5.7716   1.8961
834                soda   23.422780   24.154631   Topic3  -5.8036   1.8952
5221         casablanca   22.233924   22.970215   Topic3  -5.8557   1.8934
862                esen   20.427548   21.159001   Topic3  -5.9404   1.8908
1659                ais   18.803620   19.536114   Topic3  -6.0233   1.8878
800                apam   17.726117   18.457995   Topic3  -6.0823   1.8855
2794            majalah   17.649002   18.382665   Topic3  -6.0866   1.8852
819            pengukus   17.644824   18.379092   Topic3  -6.0869   1.8852
206                tali   17.155851   17.888446   Topic3  -6.1150   1.8842
843              senduk   16.504010   17.236138   Topic3  -6.1537   1.8826
278             setitik   15.877083   16.608561   Topic3  -6.1924   1.8809
835          bikarbonat   15.221544   15.953735   Topic3  -6.2346   1.8790
2457              gelas   14.998596   15.731615   Topic3  -6.2493   1.8783
2554           kelajuan   14.942785   15.674305   Topic3  -6.2531   1.8782
5194           gardenia   14.860137   15.591685   Topic3  -6.2586   1.8779
1771                kek  149.769640  157.504045   Topic3  -3.9482   1.8756
838                krim   14.000586   14.732565   Topic3  -6.3182   1.8750
2795              edisi   13.902952   14.636223   Topic3  -6.3252   1.8746
211                gred   13.747870   14.480153   Topic3  -6.3364   1.8741
2333             puding   35.493838   37.423502   Topic3  -5.3879   1.8730
1439          bahagikan   13.189257   13.920668   Topic3  -6.3779   1.8720
225              adunan   98.262278  109.275018   Topic3  -4.3697   1.8197
155               pasir   76.601399   85.416038   Topic3  -4.6187   1.8171
18             sejukkan   22.592943   24.228090   Topic3  -5.8397   1.8561
812              gandum   56.578146   64.020535   Topic3  -4.9217   1.8024
251                susu  119.109936  145.699567   Topic3  -4.1773   1.7245
488             mentega   77.212156   91.520734   Topic3  -4.6107   1.7560
2557              lapis   49.310211   60.348376   Topic3  -5.0592   1.7240
1385            kerepek   23.486994   26.374410   Topic3  -5.8009   1.8100
30               tepung  127.884356  191.506254   Topic3  -4.1062   1.5222
214              pandan   77.384669  106.338683   Topic3  -4.6085   1.6081
13                 gram  134.688774  275.936512   Topic3  -4.0543   1.2088
147                epal   46.099790   66.966681   Topic3  -5.1265   1.5526
71                 gula  204.466766  510.549130   Topic3  -3.6369   1.0109
115               telur  147.244858  338.664214   Topic3  -3.9652   1.0931
246               amies   38.915647   54.347015   Topic3  -5.2959   1.5920
825                kuih   48.626167   77.172923   Topic3  -5.0731   1.4641
227               sejuk   48.439296   79.091499   Topic3  -5.0770   1.4357
118              kuning   59.282390  117.656064   Topic3  -4.8750   1.2405
133               hijau   88.577125  233.379081   Topic3  -4.4734   0.9572
301               pekat   71.602980  174.413954   Topic3  -4.6862   1.0357
47                  air  120.961037  610.238667   Topic3  -4.1618   0.3076
247              little   34.225224   50.221388   Topic3  -5.4243   1.5425
95                manis   68.770260  217.156860   Topic3  -4.7265   0.7761
587                 ubi   37.735785   61.923162   Topic3  -5.3267   1.4307
39                 biji   96.334152  723.809826   Topic3  -4.3895  -0.0907
12           bahanbahan   66.384750  334.332865   Topic3  -4.7618   0.3093
4                  amie   75.867742  620.664662   Topic3  -4.6283  -0.1758
44                garam   53.948349  543.594028   Topic3  -4.9693  -0.3842
45                halus   43.219453  138.054501   Topic3  -5.1910   0.7646
207              santan   41.989688  227.862249   Topic3  -5.2199   0.2347
1758              pizza   43.060922   43.819894   Topic4  -4.7659   2.3373
1700               keju   37.983827   38.745037   Topic4  -4.8914   2.3349
447              zaitun   23.938427   24.697204   Topic4  -5.3531   2.3235
1802           dumpling   20.493912   21.251931   Topic4  -5.5084   2.3184
3558            lobster   19.712854   20.471812   Topic4  -5.5473   2.3170
1202          bismillah   16.260425   17.026008   Topic4  -5.7398   2.3087
3551              ajaib   15.938610   16.698537   Topic4  -5.7598   2.3082
1740            selasih   14.650735   15.413231   Topic4  -5.8440   2.3040
3710             hatyai   14.053828   14.813783   Topic4  -5.8856   2.3021
1912             pudina   13.533204   14.299054   Topic4  -5.9234   2.2997
1705          spaghetti   13.218517   13.977477   Topic4  -5.9469   2.2989
1201          kegemaran   13.242124   14.005658   Topic4  -5.9451   2.2987
1701           parmesan   12.004801   12.764297   Topic4  -6.0432   2.2934
1832              herba   11.913826   12.672983   Topic4  -6.0508   2.2930
1803           pencecah   11.667220   12.425890   Topic4  -6.0718   2.2917
1749            cheddar   11.234540   11.997195   Topic4  -6.1095   2.2891
1746               beef   10.493914   11.253211   Topic4  -6.1777   2.2849
1038               kiub   10.368424   11.129850   Topic4  -6.1898   2.2839
1178           kinabalu   17.374905   18.761767   Topic4  -5.6735   2.2779
2027               baby    9.509527   10.268783   Topic4  -6.2762   2.2779
4165              sepat    9.308956   10.067382   Topic4  -6.2976   2.2764
2241              sushi    9.234230    9.992062   Topic4  -6.3056   2.2759
1916            basuhan    9.096061    9.862773   Topic4  -6.3207   2.2738
5092             dinner    8.961190    9.719152   Topic4  -6.3356   2.2735
5093               dsss    8.961190    9.719152   Topic4  -6.3356   2.2735
5094        karbohidrat    8.961190    9.719152   Topic4  -6.3356   2.2735
518             makanan   41.206182   44.696438   Topic4  -4.8099   2.2734
2242             salmon    8.976889    9.739499   Topic4  -6.3339   2.2732
2528              lassi    8.664796    9.422800   Topic4  -6.3693   2.2709
1696              prego    8.562170    9.320432   Topic4  -6.3812   2.2699
1910           rosemary    8.581272    9.341296   Topic4  -6.3790   2.2699

Topic: 1
bawang, putih, amie, biji, cili, garam, merah, serbuk, air, daging, goreng, udang, kulit, bunga, perasa, tomato, ayam, tumbuk, manis, cincang, tumis, panaskan, gaul, bahanbahan, dapur, ulas, nasi, halia, lada, sos

Topic: 2
makan, biskut, nak, pie, kak, ketuhar, oven, kacang, yong, shepherds, panas, sarapan, belajar, dadar, buah, kering, selamat, durian, masakan, puff, popia, minum, anakanak, merah, kelas, daun, amie, kelapa, lupa, tengahari

Topic: 3
sate, amie, encik, kasih, terima, suami, firdaus, roti, makan, kuih, gambar, food, ingredients, chicken, post, malaysia, hosted, submitting, penang, water, set, nampak, oil, farid, fest, add, tbsp, pisang, pesan, milk

Topic: 4
makan, nak, ayam, amie, goreng, beli, ikan, nasi, firdaus, hidangan, sos, pizza, panggang, makanan, keju, fairuz, kentang, encik, bakar, suami, abang, jenis, nampak, anakanak, dah, telur, selera, ahaks, zaitun, fuad

Topic: 5
ikan, biji, bawang, cili, garam, air, daun, asam, gula, perasa, sambal, kisar, putih, merah, makan, bahanbahan, ayam, goreng, kuah, hiris, limau, padi, santan, dapur, belacan, serai, kacang, mendidih, isi, nasi

Topic: 6
makan, amie, tepung, ayam, jagung, firdaus, goreng, air, hati, soto, kentang, mommy, buras, kacang, tengok, maggi, pegedil, sup, sambal, marjerin, kuali, nasi, telur, jeruk, sukatan, digoreng, satukan, gambar, tuhau, petola

Topic: 7
gula, kek, telur, gram, tepung, air, susu, adunan, biji, hijau, pandan, mentega, pewarna, pasir, amie, pekat, agaragar, manis, bahanbahan, kuning, gandum, garam, loyang, lapis, kuih, sejuk, acuan, epal, halus, santan

[(0,
  '0.034*"bawang" + 0.021*"putih" + 0.018*"amie" + 0.016*"biji" + 0.015*"cili" + 0.014*"garam" + 0.014*"merah" + 0.013*"serbuk" + 0.012*"air" + 0.012*"daging"'),
 (1,
  '0.017*"makan" + 0.014*"biskut" + 0.009*"nak" + 0.009*"pie" + 0.008*"kak" + 0.007*"ketuhar" + 0.006*"oven" + 0.006*"kacang" + 0.006*"yong" + 0.006*"shepherds"'),
 (2,
  '0.018*"sate" + 0.014*"amie" + 0.012*"encik" + 0.011*"kasih" + 0.010*"terima" + 0.010*"suami" + 0.008*"firdaus" + 0.008*"roti" + 0.007*"makan" + 0.007*"kuih"'),
 (3,
  '0.026*"makan" + 0.018*"nak" + 0.015*"ayam" + 0.013*"amie" + 0.011*"goreng" + 0.010*"beli" + 0.010*"ikan" + 0.009*"nasi" + 0.009*"firdaus" + 0.009*"hidangan"'),
 (4,
  '0.036*"ikan" + 0.026*"biji" + 0.020*"bawang" + 0.019*"cili" + 0.018*"garam" + 0.018*"air" + 0.015*"daun" + 0.015*"asam" + 0.014*"gula" + 0.014*"perasa"'),
 (5,
  '0.013*"makan" + 0.013*"amie" + 0.013*"tepung" + 0.013*"ayam" + 0.013*"jagung" + 0.012*"firdaus" + 0.012*"goreng" + 0.011*"air" + 0.011*"hati" + 0.010*"soto"'),
 (6,
  '0.026*"gula" + 0.019*"kek" + 0.019*"telur" + 0.017*"gram" + 0.016*"tepung" + 0.016*"air" + 0.015*"susu" + 0.013*"adunan" + 0.012*"biji" + 0.011*"hijau"')]

### Inspect Probability

In [ ]:
misimonProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata bawang pada setiap topik
misimonProb["bawang"]

## Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
misimonWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"

misimonWN["Synonym_clean"] = cleanWN_Synonym(misimonWN["Synonym"])
misimonWN["Hypernim_clean"] = cleanWN(misimonWN["Hypernim"])
misimonWN["Hyponim_clean"] = cleanWN(misimonWN["Hyponim"])

# output 5 data teratas
misimonWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
1,1,putih,Synset('canescent.s.02'),[],[],covered with fine whitish hairs or down,canescent,None,None
2,1,amie,None,None,None,None,None,None,None
3,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
4,1,cili,Synset('pepper.n.04'),[Synset('solanaceous_vegetable.n.01')],"[Synset('hot_pepper.n.02'), Synset('sweet_pepp...",sweet and hot varieties of fruits of plants of...,pepper,[solanaceous_vegetable],"[hot_pepper, sweet_pepper]"

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/salamisimon.owl")
makeOntology(ontoName, misimonWN)
ontoName.save(file = "salamisimon.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1B-ClnWPpGgnTGjM1VrHHizVVm3IP8giP"

In [ ]:
wiki_misimon = pd.read_excel("Salamisimon_final.xlsx").iloc[:, 1:]
wiki_misimon.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_misimon["Category"] = translate(wiki_misimon["Category"])
wiki_misimon.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_misimon[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
misimonTabel_new = tabel_1981.copy()
misimonTabel_new["correct_category"] = all_cat
misimonTabel_new["suggestion"] = all_suggestion

# Export Result to File
misimonTabel_new.to_excel("misimonTabel_Result.xlsx")
misimonTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "misimonTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
misimonTabel_new = concatListInColumn(misimonTabel_new)
misimonTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, misimonTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_misimon.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
misimonWiki_new = wiki_df.copy()
misimonWiki_new["suggest"] = all_cat

# Export Result to file
misimonWiki_new.to_excel("misimonWiki_Result.xlsx")
misimonWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "misimonWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
misimonOntoWiki = get_ontology("http://test.org/misimon_onto_wiki.owl")
makeOntology_wiki(misimonOntoWiki, misimonWiki_new)
misimonOntoWiki.save(file = "misimon_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = misimonWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
misimonWN_new = listToDataframe(changesList, tableWordnet)
misimonWN_new.to_excel("misimonWN_Result.xlsx")
misimonWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "misimonWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Qasey Honey

In [ ]:
!gdown --id "1V5yx_lco3yEGCWOnCoerYr2-U2rrSYw5"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1V5yx_lco3yEGCWOnCoerYr2-U2rrSYw5
To: /content/Qasey.jl
100% 2.78M/2.78M [00:00<00:00, 193MB/s]

In [ ]:
qasey=pd.read_json(r'/content/Qasey.jl', lines = True)
qasey = pre_cleaning_text(qasey, threshold=20)

## GUI Qasey Honey

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = qasey.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2      0.231454  0.105580       1        1  38.712002
5      0.220322 -0.137553       2        1  19.284725
1      0.024289  0.150646       3        1  13.921810
0      0.036914  0.022359       4        1   9.319309
4     -0.234421  0.096124       5        1   8.574352
3     -0.114883 -0.305341       6        1   5.106577
6     -0.163676  0.068186       7        1   5.081226, topic_info=                    Term        Freq       Total Category  logprob  loglift
98                tepung  898.000000  898.000000  Default  30.0000  30.0000
274                  kek  575.000000  575.000000  Default  29.0000  29.0000
129                 ayam  451.000000  451.000000  Default  28.0000  28.0000
112               bawang  735.000000  735.000000  Default  27.0000  27.0000
179                 biji  809.000000  809.000000  Default  26.0000  26.0000
95                adunan  307.000000  307.000000  Default  25.0000  25.0000
116                 cili  464.000000  464.000000  Default  24.0000  24.0000
5438                 tel  171.000000  171.000000  Default  23.0000  23.0000
263                telur  474.000000  474.000000  Default  22.0000  22.0000
289                  teh  165.000000  165.000000  Default  21.0000  21.0000
271              mentega  265.000000  265.000000  Default  20.0000  20.0000
27                   air  724.000000  724.000000  Default  19.0000  19.0000
44                  gula  811.000000  811.000000  Default  18.0000  18.0000
283               biskut  214.000000  214.000000  Default  17.0000  17.0000
463               butter  264.000000  264.000000  Default  16.0000  16.0000
458               coklat  231.000000  231.000000  Default  15.0000  15.0000
216                  sos  264.000000  264.000000  Default  14.0000  14.0000
21                 garam  652.000000  652.000000  Default  13.0000  13.0000
180                merah  395.000000  395.000000  Default  12.0000  12.0000
259               gandum  179.000000  179.000000  Default  11.0000  11.0000
22                  daun  333.000000  333.000000  Default  10.0000  10.0000
0                  salam  513.000000  513.000000  Default   9.0000   9.0000
2040            membakar  114.000000  114.000000  Default   8.0000   8.0000
41                goreng  305.000000  305.000000  Default   7.0000   7.0000
11                  ikan  292.000000  292.000000  Default   6.0000   6.0000
270               loyang  161.000000  161.000000  Default   5.0000   5.0000
268                 suhu  159.000000  159.000000  Default   4.0000   4.0000
109                sejuk  139.000000  139.000000  Default   3.0000   3.0000
412                 lada  221.000000  221.000000  Default   2.0000   2.0000
358                 apam  121.000000  121.000000  Default   1.0000   1.0000
112               bawang  735.265674  735.937276   Topic1  -3.3945   0.9481
116                 cili  464.234085  464.905654   Topic1  -3.8544   0.9476
22                  daun  332.889584  333.561400   Topic1  -4.1869   0.9470
11                  ikan  291.469972  292.141293   Topic1  -4.3198   0.9467
181                 ulas  212.868055  213.539719   Topic1  -4.6341   0.9459
136                 inci  171.890585  172.563560   Topic1  -4.8479   0.9451
119                tumis  166.280950  166.952542   Topic1  -4.8811   0.9450
115               kunyit  160.900253  161.571589   Topic1  -4.9140   0.9449
408                hiris  159.481563  160.153072   Topic1  -4.9228   0.9448
719                udang  158.362681  159.034251   Topic1  -4.9299   0.9448
18                  asam  158.334530  159.006743   Topic1  -4.9300   0.9448
182               batang  157.125606  157.797090   Topic1  -4.9377   0.9448
381                 kari  151.911035  152.582756   Topic1  -4.9714   0.9446
114                halia  137.723297  138.394743   Topic1  -5.0695   0.9442
535              dihiris  123.646588  124.320106   Topic1  -5.1773   0.9436
33                toskan  116.089753  116.761662   Topic1  -5.2404   0.9432
828              dikacau  117.738594  118.427462   Topic1  -5.2263   0.9432
426                kicap  128.731844  129.493658   Topic1  -5.1370   0.9431
447                 padi  112.621352  113.292802   Topic1  -5.2707   0.9431
1439              sotong  108.482076  109.153695   Topic1  -5.3082   0.9428
103               sambal  102.842067  103.513673   Topic1  -5.3615   0.9425
120                serai  101.401368  102.072635   Topic1  -5.3757   0.9424
837              tangkai  100.171568  100.843105   Topic1  -5.3879   0.9423
105                kuali   99.732927  100.407221   Topic1  -5.3922   0.9423
210                 ekor   98.140896   98.812342   Topic1  -5.4083   0.9422
100                 kuah   95.014339   95.685977   Topic1  -5.4407   0.9420
221                lobak   87.000793   87.673335   Topic1  -5.5288   0.9413
592                limau   86.301309   86.972949   Topic1  -5.5369   0.9413
19                  jawa   81.841574   82.512874   Topic1  -5.5900   0.9409
192                bunga   73.233499   73.936749   Topic1  -5.7011   0.9395
213              secukup  277.991532  281.827158   Topic1  -4.3672   0.9353
180                merah  387.994064  395.806333   Topic1  -4.0338   0.9291
179                 biji  747.026666  809.640607   Topic1  -3.3786   0.8685
21                 garam  600.421529  652.697718   Topic1  -3.5971   0.8655
110                kisar  271.210939  288.285455   Topic1  -4.3918   0.8880
27                   air  604.017796  724.094559   Topic1  -3.5911   0.7677
43                 putih  331.991425  406.251329   Topic1  -4.1896   0.7472
41                goreng  257.038913  305.876473   Topic1  -4.4455   0.7751
152                 nasi  143.159784  157.426657   Topic1  -5.0308   0.8540
265              dikisar  145.987564  167.351537   Topic1  -5.0112   0.8124
211               serbuk  259.117591  378.759222   Topic1  -4.4375   0.5694
40              panaskan  185.017058  240.350428   Topic1  -4.7743   0.6874
44                  gula  403.378463  811.242433   Topic1  -3.9949   0.2503
412                 lada  166.424324  221.520025   Topic1  -4.8802   0.6630
129                 ayam  230.670753  451.863424   Topic1  -4.5538   0.2766
907            sejahtera  188.618202  305.267474   Topic1  -4.7550   0.4676
0                  salam  235.099042  513.475087   Topic1  -4.5347   0.1678
216                  sos  173.963263  264.104827   Topic1  -4.8359   0.5315
45                  gaul  158.110001  233.994240   Topic1  -4.9315   0.5570
95                adunan  306.578594  307.353806   Topic2  -3.5724   1.6433
283               biskut  213.383273  214.157799   Topic2  -3.9348   1.6422
270               loyang  160.639239  161.413359   Topic2  -4.2187   1.6410
268                 suhu  158.923216  159.697973   Topic2  -4.2295   1.6410
3135            margerin   82.171525   82.945517   Topic2  -4.8891   1.6365
750              memukul   81.665947   82.439888   Topic2  -4.8953   1.6364
634                 gebu   78.346262   79.122460   Topic2  -4.9368   1.6360
255                 esen   74.558758   75.332601   Topic2  -4.9863   1.6355
754              ketuhar   71.518411   72.293508   Topic2  -5.0280   1.6351
783               kastor   63.612261   64.386881   Topic2  -5.1451   1.6338
6489           terlampau   60.736702   61.510639   Topic2  -5.1914   1.6332
2530                 ita   60.743859   61.520665   Topic2  -5.1912   1.6331
635               piping   52.120506   52.895819   Topic2  -5.3443   1.6311
809              spatula   50.176343   50.950123   Topic2  -5.3824   1.6306
1761              penaik   49.814156   50.587985   Topic2  -5.3896   1.6304
261               powder   46.525897   47.300268   Topic2  -5.4579   1.6293
290               vanila   45.671225   46.444777   Topic2  -5.4764   1.6291
780           selebihnya   44.895910   45.672336   Topic2  -5.4936   1.6287
1027             sukatan   44.517498   45.291993   Topic2  -5.5020   1.6286
1342               licin   41.912279   42.686140   Topic2  -5.5623   1.6276
2993                 rak   41.199710   41.974102   Topic2  -5.5795   1.6272
5028         menyebabkan   41.040811   41.814764   Topic2  -5.5833   1.6272
2393           microwave   40.791143   41.564630   Topic2  -5.5894   1.6271
6482             panduan   40.514193   41.288135   Topic2  -5.5963   1.6269
6492             merekah   40.514193   41.288135   Topic2  -5.5963   1.6269
256              vanilla   40.011454   40.789653   Topic2  -5.6087   1.6266
183                 susu  131.333501  134.249883   Topic2  -4.4202   1.6239
914               diayak   34.576052   35.349821   Topic2  -5.7547   1.6237
2081            kelajuan   32.314496   33.090650   Topic2  -5.8224   1.6221
1078           berselang   29.846961   30.621165   Topic2  -5.9018   1.6202
271              mentega  256.299395  265.917882   Topic2  -3.7516   1.6090
274                  kek  546.361524  575.451750   Topic2  -2.9946   1.5940
1232                 dgn  130.316521  137.647208   Topic2  -4.4279   1.5911
463               butter  240.460646  264.758893   Topic2  -3.8154   1.5496
631                cream  116.399524  127.437226   Topic2  -4.5409   1.5553
260               baking  100.036549  108.406240   Topic2  -4.6924   1.5655
263                telur  289.262671  474.636087   Topic2  -3.6306   1.1506
267                 oven   70.407257   83.478560   Topic2  -5.0436   1.4756
323              kembang   46.716404   50.464955   Topic2  -5.4538   1.5687
44                  gula  308.755359  811.242433   Topic2  -3.5654   0.6798
1043             pewarna   90.896762  135.339536   Topic2  -4.7882   1.2478
98                tepung  306.524737  898.503606   Topic2  -3.5726   0.5704
93               mangkuk   78.458753  112.458471   Topic2  -4.9353   1.2858
162               sebati   86.025592  132.394728   Topic2  -4.8433   1.2147
157               kertas   54.768891   64.023317   Topic2  -5.2948   1.4897
211               serbuk   94.984830  378.759222   Topic2  -4.7442   0.2627
171              biarkan   79.622234  221.921684   Topic2  -4.9206   0.6208
907            sejahtera   80.443304  305.267474   Topic2  -4.9104   0.3122
259               gandum   70.260960  179.353363   Topic2  -5.0457   0.7087
856                  kak   67.861925  191.301257   Topic2  -5.0804   0.6095
43                 putih   72.502846  406.251329   Topic2  -5.0143  -0.0775
185                manis   65.799975  180.474925   Topic2  -5.1113   0.6369
358                 apam  120.418578  121.111218   Topic3  -4.1811   1.9660
686              masakan   89.861398   90.570389   Topic3  -4.4738   1.9639
338              lapisan   86.124209   86.810833   Topic3  -4.5163   1.9638
186                jenis   70.380526   71.164981   Topic3  -4.7181   1.9606
334                  ais   48.409287   49.096726   Topic3  -5.0924   1.9576
345           membuatnya   47.675105   48.366626   Topic3  -5.1076   1.9573
1098               paste   37.854440   38.542448   Topic3  -5.3383   1.9537
187                 krim   33.741333   34.428669   Topic3  -5.4533   1.9515
2872          strawberry   32.372335   33.058998   Topic3  -5.4947   1.9507
237             brownies   30.854972   31.541585   Topic3  -5.5428   1.9497
985                 kena   31.091253   31.783619   Topic3  -5.5351   1.9497
797               almond   29.688934   30.375632   Topic3  -5.5813   1.9488
143                 peti   70.093609   71.716302   Topic3  -4.7222   1.9488
1644             parutan   27.850004   28.536864   Topic3  -5.6452   1.9473
3107                tart   27.445525   28.131873   Topic3  -5.6598   1.9470
524               double   27.339637   28.026183   Topic3  -5.6637   1.9469
269                 sapu   26.088355   26.776621   Topic3  -5.7106   1.9457
679                jugak   24.092128   24.783381   Topic3  -5.7902   1.9434
352              separuh   23.715508   24.406585   Topic3  -5.8059   1.9430
82                  link   23.426886   24.115716   Topic3  -5.8182   1.9427
855                canai   22.020296   22.708079   Topic3  -5.8801   1.9410
353                penuh   21.520199   22.214644   Topic3  -5.9031   1.9400
480                tekan   21.257927   21.945244   Topic3  -5.9153   1.9399
759                 biru   20.580476   21.267481   Topic3  -5.9477   1.9389
662               nestum   19.643508   20.333320   Topic3  -5.9943   1.9372
565                 keju   19.186991   19.873661   Topic3  -6.0178   1.9366
34                  alas   18.667484   19.354674   Topic3  -6.0453   1.9356
1775                rose   17.738503   18.426144   Topic3  -6.0963   1.9337
77                pastry   17.219433   17.925509   Topic3  -6.1260   1.9315
2957                tbsp   16.704158   17.398305   Topic3  -6.1564   1.9310
791             sejukkan   61.359465   65.442982   Topic3  -4.8553   1.9073
109                sejuk  127.636361  139.427487   Topic3  -4.1229   1.8834
300                  doh  108.034791  119.533454   Topic3  -4.2896   1.8706
35             keluarkan   59.254737   64.471075   Topic3  -4.8902   1.8873
458               coklat  195.184868  231.748839   Topic3  -3.6981   1.8000
151              sapukan   39.017397   42.827209   Topic3  -5.3080   1.8785
2940          panaspanas   47.438715   53.095011   Topic3  -5.1126   1.8591
80                  klik   35.348329   38.711796   Topic3  -5.4068   1.8808
298                  uli   35.433496   40.231890   Topic3  -5.4044   1.8447
372             sediakan   75.035316  107.432658   Topic3  -4.6541   1.6128
29               satukan   58.214372   85.378489   Topic3  -4.9079   1.5888
184                 cair   63.882371  101.790347   Topic3  -4.8150   1.5058
466                bakar   84.307521  155.969018   Topic3  -4.5376   1.3565
414                ambil   69.873672  119.387684   Topic3  -4.7254   1.4360
144                  nak   94.868154  203.613143   Topic3  -4.4196   1.2080
23                pandan   57.895709   92.897252   Topic3  -4.9134   1.4989
0                  salam  147.341266  513.475087   Topic3  -3.9793   0.7233
2494               semua   76.996075  206.714424   Topic3  -4.6283   0.9841
833             letakkan   45.716830   72.186082   Topic3  -5.1496   1.5149
140                tuang   45.677194   72.613182   Topic3  -5.1505   1.5082
27                   air  100.662215  724.094559   Topic3  -4.3603  -0.0014
44                  gula   98.626551  811.242433   Topic3  -4.3807  -0.1355
45                  gaul   60.358706  233.994240   Topic3  -4.8717   0.6167
1759              tengok   42.095177   72.850609   Topic3  -5.2321   1.4232
89                  buah   46.864929  108.512345   Topic3  -5.1248   1.1321
52                 kasih   45.120809   94.631962   Topic3  -5.1627   1.2311
30             ketepikan   48.148572  150.067347   Topic3  -5.0978   0.8349
2040            membakar  113.781998  114.508086   Topic4  -3.8364   2.3667
591                  jus   74.843105   75.566490   Topic4  -4.2553   2.3635
1270                foil   49.300976   50.022689   Topic4  -4.6727   2.3585
1269           aluminium   49.214551   49.936096   Topic4  -4.6745   2.3585
578                  yea   46.778258   47.502665   Topic4  -4.7253   2.3577
993               hangus   39.876753   40.602231   Topic4  -4.8849   2.3551
4112                 tuk   39.200775   39.925486   Topic4  -4.9020   2.3548
3303          tertanggal   38.823492   39.550146   Topic4  -4.9117   2.3545
4629               kalbu   38.391066   39.116640   Topic4  -4.9229   2.3544
6064            penganut   37.668874   38.395314   Topic4  -4.9418   2.3540
6066               hindu   37.668874   38.395314   Topic4  -4.9418   2.3540
1132               lemon   36.990896   37.711792   Topic4  -4.9600   2.3538
2948          kekurangan   37.110057   37.837324   Topic4  -4.9568   2.3537
829                tauhu   36.158086   36.877416   Topic4  -4.9828   2.3534
821                  mee   35.601712   36.319823   Topic4  -4.9983   2.3531
504                maggi   34.649262   35.367656   Topic4  -5.0254   2.3526
556                  tin   27.809310   28.529397   Topic4  -5.2453   2.3475
994               nampak   26.243984   26.968119   Topic4  -5.3032   2.3459
320              chicken   22.197606   22.916497   Topic4  -5.4707   2.3412
2050            ditumbuk   22.236285   22.957277   Topic4  -5.4690   2.3412
506             perencah   21.659776   22.378774   Topic4  -5.4952   2.3404
799                 sawi   20.815865   21.536166   Topic4  -5.5350   2.3391
1496                 boi   19.068586   19.788557   Topic4  -5.6226   2.3360
145                perap   17.556010   18.276288   Topic4  -5.7053   2.3329
1353              fillet   16.947665   17.665938   Topic4  -5.7406   2.3316
599             capsicum   16.826055   17.544503   Topic4  -5.7478   2.3313
420             celupkan   15.708679   16.428667   Topic4  -5.8165   2.3283
3565                 jom   15.714834   16.439061   Topic4  -5.8161   2.3280
141             perapkan   13.779621   14.498759   Topic4  -5.9475   2.3222
1158            pecahkan   13.738801   14.459238   Topic4  -5.9505   2.3220
1149              perasa   33.479466   37.344028   Topic4  -5.0598   2.2638
135                 dadu   50.399435   61.168758   Topic4  -4.6507   2.1794
360                 roti   74.606599  114.875794   Topic4  -4.2585   1.9415
129                 ayam  220.646702  451.863424   Topic4  -3.1741   1.6563
128                  isi   27.842255   34.998102   Topic4  -5.2441   2.1443
2586                 ade   31.739141   42.138938   Topic4  -5.1131   2.0897
121                wangi   50.954544   81.746811   Topic4  -4.6397   1.9004
216                  sos   89.595687  264.104827   Topic4  -4.0754   1.2920
42                garing   53.766277  133.788589   Topic4  -4.5860   1.4615
412                 lada   54.549915  221.520025   Topic4  -4.5716   0.9717
587                hitam   36.858016   90.660046   Topic4  -4.9636   1.4730
263                telur   64.211391  474.636087   Topic4  -4.4085   0.3727
41                goreng   48.291610  305.876473   Topic4  -4.6934   0.5272
489                panas   35.630789  121.782074   Topic4  -4.9975   1.1441
98                tepung   45.531035  898.503606   Topic4  -4.7523  -0.6093
144                  nak   34.213417  203.613143   Topic4  -5.0381   0.5895
5438                 tel  170.510218  171.210820   Topic5  -3.3486   2.4523
1823               darul   80.457347   81.157977   Topic5  -4.0996   2.4477
5436               taman   57.373545   58.075479   Topic5  -4.4378   2.4442
3200            selangor   47.493723   48.194319   Topic5  -4.6268   2.4418
1327            pensonic   42.838529   43.539127   Topic5  -4.7299   2.4402
5499               ehsan   41.403099   42.103703   Topic5  -4.7640   2.4396
745               bakery   40.177840   40.882945   Topic5  -4.7941   2.4390
5443                 fax   36.079095   36.779698   Topic5  -4.9017   2.4372
5452             trading   29.424085   30.124689   Topic5  -5.1056   2.4329
2370                jaya   25.481200   26.181787   Topic5  -5.2494   2.4293
869              aiskrim   25.594236   26.300878   Topic5  -5.2450   2.4292
802                cucur   24.135507   24.845240   Topic5  -5.3037   2.4274
1006             bungkus   24.383430   25.120600   Topic5  -5.2935   2.4266
56                 tabah   22.680278   23.381463   Topic5  -5.3659   2.4259
60                  hero   22.680242   23.381454   Topic5  -5.3659   2.4259
2196            peraduan   22.145086   22.845701   Topic5  -5.3898   2.4252
53            frontliner   21.813742   22.514912   Topic5  -5.4048   2.4248
57                 cekal   21.813742   22.514912   Topic5  -5.4048   2.4248
58          melaksanakan   21.813742   22.514912   Topic5  -5.4048   2.4248
59             tugasanda   21.813742   22.514912   Topic5  -5.4048   2.4248
553               bebola   21.969295   22.675934   Topic5  -5.3977   2.4247

Topic: 1
ayam, membakar, sos, jus, roti, telur, lada, garing, wangi, dadu, foil, aluminium, goreng, yea, tepung, hangus, tuk, tertanggal, kalbu, penganut, hindu, kekurangan, lemon, hitam, tauhu, panas, mee, maggi, nak, perasa

Topic: 2
coklat, salam, sejuk, apam, doh, air, gula, nak, masakan, lapisan, bakar, semua, sediakan, jenis, peti, ambil, cair, sejukkan, gaul, keluarkan, satukan, pandan, ais, ketepikan, membuatnya, panaspanas, buah, letakkan, tuang, kasih

Topic: 3
biji, bawang, air, garam, cili, gula, merah, daun, putih, ikan, secukup, kisar, serbuk, goreng, salam, ayam, ulas, sejahtera, panaskan, sos, inci, lada, tumis, kunyit, hiris, udang, asam, gaul, batang, kari

Topic: 4
tepung, teh, berprotein, gandum, chef, sesuai, asma, oktober, jagung, ubi, acuan, roti, bancuhan, serba, fungsinya, pulut, yis, dimakan, kuih, kukus, serbaguna, ros, hidangkan, pau, berbeza, krimer, berwarna, sempurna, memekatkan, penggunaan

Topic: 5
tel, darul, taman, selangor, qasey, pensonic, ehsan, bakery, youtube, fax, honey, malaysia, trading, aiskrim, like, jaya, sihat, salam, bungkus, kuat, cucur, lupa, tabah, hero, peraduan, bebola, frontliner, melaksanakan, cekal, tugasanda

Topic: 6
kek, gula, adunan, tepung, telur, mentega, butter, biskut, loyang, suhu, susu, dgn, cream, baking, serbuk, pewarna, sebati, margerin, memukul, sejahtera, biarkan, mangkuk, gebu, esen, putih, ketuhar, oven, gandum, kak, manis

Topic: 7
kejadian, pendek, custard, salam, malaysia, aje, beragama, kilo, sukar, shaa, tema, majalah, yer, dah, pon, kek, design, tenggelam, belah, terima, menyenangkan, realisasikan, seawal, impian, menempah, tau, andaheeeetempahan, kasih, saje, kesayangan

[(0,
  '0.042*"ayam" + 0.022*"membakar" + 0.017*"sos" + 0.014*"jus" + 0.014*"roti" + 0.012*"telur" + 0.010*"lada" + 0.010*"garing" + 0.010*"wangi" + 0.010*"dadu"'),
 (1,
  '0.025*"coklat" + 0.019*"salam" + 0.016*"sejuk" + 0.015*"apam" + 0.014*"doh" + 0.013*"air" + 0.013*"gula" + 0.012*"nak" + 0.011*"masakan" + 0.011*"lapisan"'),
 (2,
  '0.034*"biji" + 0.034*"bawang" + 0.028*"air" + 0.027*"garam" + 0.021*"cili" + 0.018*"gula" + 0.018*"merah" + 0.015*"daun" + 0.015*"putih" + 0.013*"ikan"'),
 (3,
  '0.165*"tepung" + 0.026*"teh" + 0.024*"berprotein" + 0.024*"gandum" + 0.022*"chef" + 0.019*"sesuai" + 0.018*"asma" + 0.018*"oktober" + 0.014*"jagung" + 0.014*"ubi"'),
 (4,
  '0.035*"tel" + 0.017*"darul" + 0.012*"taman" + 0.010*"selangor" + 0.010*"qasey" + 0.009*"pensonic" + 0.009*"ehsan" + 0.008*"bakery" + 0.008*"youtube" + 0.007*"fax"'),
 (5,
  '0.050*"kek" + 0.028*"gula" + 0.028*"adunan" + 0.028*"tepung" + 0.027*"telur" + 0.023*"mentega" + 0.022*"butter" + 0.020*"biskut" + 0.015*"loyang" + 0.015*"suhu"'),
 (6,
  '0.025*"kejadian" + 0.024*"pendek" + 0.024*"custard" + 0.018*"salam" + 0.015*"malaysia" + 0.014*"aje" + 0.013*"beragama" + 0.012*"kilo" + 0.012*"sukar" + 0.011*"shaa"')]

### Inspect Probability

In [ ]:
qaseyProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata garam pada setiap topik
qaseyProb["garam"]

## Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
qaseyWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"

qaseyWN["Synonym_clean"] = cleanWN_Synonym(qaseyWN["Synonym"])
qaseyWN["Hypernim_clean"] = cleanWN(qaseyWN["Hypernim"])
qaseyWN["Hyponim_clean"] = cleanWN(qaseyWN["Hyponim"])

# output 5 data teratas
qaseyWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,ayam,Synset('domestic_fowl.n.01'),[Synset('gallinaceous_bird.n.01')],"[Synset('bantam.n.01'), Synset('chicken.n.02')...",a domesticated gallinaceous bird thought to be...,domestic_fowl,[gallinaceous_bird],"[bantam, chicken, cochin, cornish, dorking, ga..."
1,1,membakar,Synset('inflame.v.05'),[Synset('worsen.v.01')],[],become inflamed; get sore,inflame,[worsen],None
2,1,sos,Synset('sauce.n.01'),[Synset('condiment.n.01')],"[Synset('aioli.n.01'), Synset('allemande.n.01'...",flavorful relish or dressing or topping served...,sauce,[condiment],"[aioli, allemande, anchovy_sauce, apricot_sauc..."
3,1,jus,Synset('juice.n.04'),[Synset('liquid_body_substance.n.01')],"[Synset('cancer_juice.n.01'), Synset('digestiv...",any of several liquids of the body,juice,[liquid_body_substance],"[cancer_juice, digestive_juice]"
4,1,roti,Synset('bread.n.01'),"[Synset('baked_goods.n.01'), Synset('starches....","[Synset('anadama_bread.n.01'), Synset('bap.n.0...",food made from dough of flour or meal and usua...,bread,"[baked_goods, starches]","[anadama_bread, bap, barmbrack, breadstick, br..."

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/QaseyHoney.owl")
makeOntology(ontoName, qaseyWN)
ontoName.save(file = "QaseyHoney.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1z804RUur9y4XZwXg-gq9Wi9L9GG07Ed-"

In [ ]:
wiki_qasey = pd.read_excel("Qasey Honey_final.xlsx").iloc[:, 1:]
wiki_qasey.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_qasey["Category"] = translate(wiki_qasey["Category"])
wiki_qasey.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_qasey[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
qaseyTabel_new = tabel_1981.copy()
qaseyTabel_new["correct_category"] = all_cat
qaseyTabel_new["suggestion"] = all_suggestion

# Export Result to File
qaseyTabel_new.to_excel("qaseyTabel_Result.xlsx")
qaseyTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "qaseyTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
qaseyTabel_new = concatListInColumn(qaseyTabel_new)
qaseyTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, qaseyTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_qasey.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
qaseyWiki_new = wiki_df.copy()
qaseyWiki_new["suggest"] = all_cat

# Export Result to file
qaseyWiki_new.to_excel("qaseyWiki_Result.xlsx")
qaseyWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "qaseyWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
qaseyOntoWiki = get_ontology("http://test.org/qasey_onto_wiki.owl")
makeOntology_wiki(qaseyOntoWiki, qaseyWiki_new)
qaseyOntoWiki.save(file = "qasey_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = qaseyWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
qaseyWN_new = listToDataframe(changesList, tableWordnet)
qaseyWN_new.to_excel("qaseyWN_Result.xlsx")
qaseyWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "qaseyWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Tiffin Biru

In [ ]:
!gdown --id "1e-4GSAgdEsp9DotoqZj1niqXozT4BRIS"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1e-4GSAgdEsp9DotoqZj1niqXozT4BRIS
To: /content/Tiffinbiru.jl
100% 11.8M/11.8M [00:00<00:00, 41.9MB/s]

In [ ]:
tiffin=pd.read_json(r'/content/Tiffinbiru.jl', lines = True)
tiffin = pre_cleaning_text(tiffin, threshold=20)

## GUI TiffinBiru

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = tiffin.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5      0.229652 -0.048033       1        1  38.097012
0      0.175423 -0.046796       2        1  20.375566
2      0.093547  0.227229       3        1  15.226402
6      0.153967 -0.136797       4        1  10.203275
4     -0.384911 -0.024462       5        1   6.277035
3     -0.103751  0.238644       6        1   5.143543
1     -0.163927 -0.209785       7        1   4.677167, topic_info=                 Term          Freq         Total Category  logprob  loglift
33              camca  11331.000000  11331.000000  Default  30.0000  30.0000
45             bawang   7965.000000   7965.000000  Default  29.0000  29.0000
144            tepung   1766.000000   1766.000000  Default  28.0000  28.0000
49               inci   3719.000000   3719.000000  Default  27.0000  27.0000
34                teh   5004.000000   5004.000000  Default  26.0000  26.0000
38             santan   1848.000000   1848.000000  Default  25.0000  25.0000
85               gula   4454.000000   4454.000000  Default  24.0000  24.0000
110               sos   1917.000000   1917.000000  Default  23.0000  23.0000
74             kunyit   1943.000000   1943.000000  Default  22.0000  22.0000
11             rendam   1134.000000   1134.000000  Default  21.0000  21.0000
8                biji  10954.000000  10954.000000  Default  20.0000  20.0000
17              udang   1171.000000   1171.000000  Default  19.0000  19.0000
30               ikan   2545.000000   2545.000000  Default  18.0000  18.0000
53               cili   3838.000000   3838.000000  Default  17.0000  17.0000
27             toskan   1924.000000   1924.000000  Default  16.0000  16.0000
46              merah   4014.000000   4014.000000  Default  15.0000  15.0000
14              hiris   2760.000000   2760.000000  Default  14.0000  14.0000
40                mat   2129.000000   2129.000000  Default  13.0000  13.0000
20             kering    623.000000    623.000000  Default  12.0000  12.0000
124             telur   1640.000000   1640.000000  Default  11.0000  11.0000
36               asam   1425.000000   1425.000000  Default  10.0000  10.0000
47               ulas   3729.000000   3729.000000  Default   9.0000   9.0000
433              roti    533.000000    533.000000  Default   8.0000   8.0000
505               kak    621.000000    621.000000  Default   7.0000   7.0000
1              keping   1616.000000   1616.000000  Default   6.0000   6.0000
75              hidup   1102.000000   1102.000000  Default   5.0000   5.0000
29               pati    810.000000    810.000000  Default   4.0000   4.0000
57            hirisan   1555.000000   1555.000000  Default   3.0000   3.0000
50              halia   1484.000000   1484.000000  Default   2.0000   2.0000
148            gandum    751.000000    751.000000  Default   1.0000   1.0000
50              halia   1483.793174   1484.575154   Topic1  -4.2532   0.9645
92             kuntum   1091.416696   1092.198584   Topic1  -4.5604   0.9643
93              bunga   1090.981076   1091.762930   Topic1  -4.5608   0.9643
164              kari    866.945850    867.727609   Topic1  -4.7906   0.9641
89           lengkuas    671.355057    672.136612   Topic1  -5.0463   0.9639
345               jus    648.318059    649.101628   Topic1  -5.0812   0.9638
37               jawa    604.826483    605.608865   Topic1  -5.1507   0.9637
163            rempah    568.150573    568.932487   Topic1  -5.2132   0.9637
205            jintan    549.559721    550.341041   Topic1  -5.2465   0.9636
204          ketumbar    400.035999    400.817415   Topic1  -5.5640   0.9631
640             lumat    394.685373    395.468534   Topic1  -5.5775   0.9631
218            lawang    369.861723    370.642558   Topic1  -5.6425   0.9629
500            keladi    369.576608    370.395730   Topic1  -5.6432   0.9628
201             bulat    329.686279    330.471630   Topic1  -5.7575   0.9627
302             nenas    307.067406    307.851955   Topic1  -5.8285   0.9625
215           cengkih    291.992368    292.773252   Topic1  -5.8789   0.9624
350             halba    265.919811    266.701344   Topic1  -5.9724   0.9621
217            pelaga    259.553712    260.334447   Topic1  -5.9966   0.9620
326             purut    232.498120    233.279552   Topic1  -6.1067   0.9617
94             kantan    218.340950    219.121983   Topic1  -6.1695   0.9615
357           dibawah    219.616488    220.428148   Topic1  -6.1637   0.9613
523             pucuk    195.775545    196.560469   Topic1  -6.2786   0.9610
828          tenggiri    186.167134    186.949826   Topic1  -6.3290   0.9608
87            kerisik    169.773794    170.554792   Topic1  -6.4211   0.9604
107           dibakar    169.917178    170.701546   Topic1  -6.4203   0.9604
514            campur    167.471897    168.256258   Topic1  -6.4348   0.9604
234           supdaun    156.821939    157.606265   Topic1  -6.5005   0.9600
830             ramas    157.740390    158.531084   Topic1  -6.4947   0.9600
131            dicuci    157.810831    158.602524   Topic1  -6.4942   0.9600
529             bendi    153.654125    154.435630   Topic1  -6.5209   0.9600
216              buah    876.592653    925.092871   Topic1  -4.7796   0.9112
95              belah    873.920718    931.030082   Topic1  -4.7826   0.9017
63              jeruk    289.751193    299.919712   Topic1  -5.8866   0.9305
199            jusnya    395.577557    421.259069   Topic1  -5.5753   0.9021
49               inci   3036.654481   3719.912306   Topic1  -3.5371   0.7621
132             tumis    555.303104    615.401819   Topic1  -5.2361   0.8623
127             limau    749.125129    871.550253   Topic1  -4.9367   0.8137
97             terung    400.280634    441.726356   Topic1  -5.5634   0.8665
8                biji   6610.711722  10954.746899   Topic1  -2.7592   0.4600
84              kisar   1072.575426   1375.759850   Topic1  -4.5778   0.7161
45             bawang   4690.967394   7965.155534   Topic1  -3.1022   0.4356
214              kayu    420.037341    469.364524   Topic1  -5.5153   0.8540
47               ulas   2355.741844   3729.392606   Topic1  -3.7910   0.5056
30               ikan   1698.455488   2545.575466   Topic1  -4.1181   0.5604
106           belacan    855.685642   1112.022356   Topic1  -4.8037   0.7030
230              nasi    607.324248    733.004762   Topic1  -5.1465   0.7769
46              merah   2428.026290   4014.478358   Topic1  -3.7608   0.4622
48              putih   2151.700889   3794.131659   Topic1  -3.8816   0.3978
52              halus   2707.786106   5338.614621   Topic1  -3.6517   0.2862
53               cili   2089.375042   3838.391319   Topic1  -3.9110   0.3568
33              camca   4669.952303  11331.770395   Topic1  -3.1067   0.0786
43            secukup   1115.625259   1682.141943   Topic1  -4.5384   0.5544
42              garam   2007.338825   3892.646028   Topic1  -3.9510   0.3028
36               asam    956.845766   1425.097898   Topic1  -4.6920   0.5667
64             batang   1364.350155   2481.008765   Topic1  -4.3372   0.3670
34                teh   2039.244984   5004.988139   Topic1  -3.9353   0.0672
74             kunyit   1114.589278   1943.494596   Topic1  -4.5394   0.4090
4                daun   1415.717092   2938.965043   Topic1  -4.3002   0.2346
14              hiris   1363.033674   2760.172910   Topic1  -4.3381   0.2595
55         membuatnya   1671.107879   4318.273976   Topic1  -4.1344   0.0157
85               gula   1694.781395   4454.223688   Topic1  -4.1203  -0.0013
0       bahanbahannya   1269.816170   3239.200634   Topic1  -4.4090   0.0286
70                air   1212.566620   2928.748262   Topic1  -4.4551   0.0832
110               sos   1916.743718   1917.538208   Topic2  -3.3714   1.5904
219             kicap    783.286132    784.080517   Topic2  -4.2663   1.5898
419             tiram    559.693946    560.487932   Topic2  -4.6024   1.5894
676             tapis    472.855804    473.695600   Topic2  -4.7710   1.5891
2113              mee    368.327308    369.122614   Topic2  -5.0208   1.5887
453          capsicum    325.738314    326.532388   Topic2  -5.1437   1.5884
497            butang    264.188497    264.983560   Topic2  -5.3531   1.5878
117              hoon    175.868201    176.664623   Topic2  -5.7601   1.5863
718           mencuba    158.253754    159.061168   Topic2  -5.8656   1.5857
1741            pasta    146.926572    147.721086   Topic2  -5.9399   1.5854
200              leek    135.043468    135.837634   Topic2  -6.0242   1.5850
823           matikan    133.513426    134.313995   Topic2  -6.0356   1.5849
2017             stok    133.458702    134.259840   Topic2  -6.0360   1.5848
180             tuang    132.816839    133.627845   Topic2  -6.0408   1.5847
1802            putik    126.181527    126.976636   Topic2  -6.0921   1.5846
9518        menyerong    123.580483    124.397793   Topic2  -6.1129   1.5842
773            zaitun    106.343374    107.138106   Topic2  -6.2631   1.5834
887            saleri    105.673506    106.468207   Topic2  -6.2695   1.5833
1642         keemasan    102.961559    103.760991   Topic2  -6.2954   1.5831
3582              utk    104.466299    105.297227   Topic2  -6.2809   1.5829
774         cincangan     95.435851     96.239686   Topic2  -6.3714   1.5824
1853            sweet     85.951931     86.771557   Topic2  -6.4760   1.5813
1843            black     79.754327     80.551892   Topic2  -6.5509   1.5809
280              life     80.593046     81.412012   Topic2  -6.5404   1.5807
440           dikacau     68.635887     69.443471   Topic2  -6.7010   1.5791
752             tabur     65.951347     66.748888   Topic2  -6.7409   1.5788
775           parsley     59.931562     60.728755   Topic2  -6.8366   1.5776
821              fish     55.711132     56.506117   Topic2  -6.9096   1.5767
1066        spaghetti     55.415022     56.209197   Topic2  -6.9150   1.5766
168               sup    422.629308    429.126394   Topic2  -4.8833   1.5756
104             sulah    173.822392    177.799348   Topic2  -5.7718   1.5682
496          cendawan    364.981166    376.144364   Topic2  -5.0300   1.5607
7111          kreatif     82.497172     84.076362   Topic2  -6.5170   1.5719
10719             mmm     81.299367     83.145068   Topic2  -6.5317   1.5684
716         hidangkan    343.372424    384.773733   Topic2  -5.0910   1.4770
322            hiasan    589.316489    734.395650   Topic2  -4.5508   1.3707
290            didadu    490.487367    606.693374   Topic2  -4.7344   1.3782
57            hirisan   1110.056578   1555.873015   Topic2  -3.9176   1.2532
288           cincang    430.881603    549.481749   Topic2  -4.8640   1.3477
249             bijan    173.844848    197.128937   Topic2  -5.7716   1.4651
169            goreng    684.503014   1113.284473   Topic2  -4.4011   1.1045
14              hiris   1280.271474   2760.172910   Topic2  -3.7750   0.8226
33              camca   3472.625542  11331.770395   Topic2  -2.7771   0.4081
15             serong    252.218829    344.926811   Topic2  -5.3995   1.2778
45             bawang   2514.837755   7965.155534   Topic2  -3.0998   0.4380
103              lada    700.371550   1488.521852   Topic2  -4.3782   0.8369
96             tomato    573.794361   1136.697227   Topic2  -4.5775   0.9072
53               cili   1190.659877   3838.391319   Topic2  -3.8475   0.4203
8                biji   2263.645911  10954.746899   Topic2  -3.2051   0.0140
4                daun    941.815027   2938.965043   Topic2  -4.0820   0.4528
245             makan    404.506904    790.476555   Topic2  -4.9271   0.9209
48              putih   1067.180564   3794.131659   Topic2  -3.9570   0.3224
122           dihiris    569.645563   1441.960305   Topic2  -4.5848   0.6621
27             toskan    666.604315   1924.733983   Topic2  -4.4276   0.5305
47               ulas    956.490209   3729.392606   Topic2  -4.0665   0.2301
64             batang    760.341891   2481.008765   Topic2  -4.2960   0.4082
17              udang    499.881371   1171.872324   Topic2  -4.7154   0.7388
52              halus   1050.311424   5338.614621   Topic2  -3.9730  -0.0350
55         membuatnya    942.834917   4318.273976   Topic2  -4.0809   0.0691
0       bahanbahannya    752.772459   3239.200634   Topic2  -4.3060   0.1315
46              merah    800.457236   4014.478358   Topic2  -4.2446  -0.0216
70                air    660.400923   2928.748262   Topic2  -4.4370   0.1014
177              ayam    491.000846   1220.200575   Topic2  -4.7334   0.6805
34                teh    573.131589   5004.988139   Topic2  -4.5787  -0.5762
42              garam    505.557249   3892.646028   Topic2  -4.7041  -0.4503
144            tepung   1765.765937   1766.618648   Topic3  -3.1622   1.8817
148            gandum    750.375210    751.227455   Topic3  -4.0179   1.8810
186              gred    605.030963    605.883159   Topic3  -4.2332   1.8807
261              esen    555.169846    556.021084   Topic3  -4.3192   1.8806
262           vanilla    524.866554    525.717792   Topic3  -4.3754   1.8805
195             cream    413.495692    414.347485   Topic3  -4.6139   1.8801
193            diayak    385.939055    386.790461   Topic3  -4.6828   1.8799
187            baking    347.470885    348.323045   Topic3  -4.7878   1.8797
243             pasir    306.180485    307.035603   Topic3  -4.9143   1.8794
703               kek    249.539181    250.393377   Topic3  -5.1189   1.8787
811            sebati    231.477883    232.332665   Topic3  -5.1940   1.8785
188            powder    223.952929    224.804546   Topic3  -5.2271   1.8783
293            aising    203.715035    204.566533   Topic3  -5.3218   1.8780
253            kastor    199.694030    200.545611   Topic3  -5.3417   1.8779
393            coklat    189.744838    190.596625   Topic3  -5.3928   1.8777
296           pewarna    189.010054    189.861840   Topic3  -5.3967   1.8776
701            adunan    181.121719    181.974168   Topic3  -5.4393   1.8774
2025           cheese    178.177980    179.029647   Topic3  -5.4557   1.8774
327             pulut    177.838877    178.693231   Topic3  -5.4576   1.8773
337          whipping    166.813468    167.665235   Topic3  -5.5216   1.8770
817             larut    167.168012    168.024373   Topic3  -5.5195   1.8770
471           lapisan    159.337372    160.190664   Topic3  -5.5675   1.8768
414        strawberry    136.881792    137.733031   Topic3  -5.7194   1.8759
469             badam    136.343325    137.195073   Topic3  -5.7233   1.8759
271              soda    121.092583    121.943849   Topic3  -5.8419   1.8751
677          sejukkan    118.066774    118.919582   Topic3  -5.8672   1.8749
700              kuih    117.405670    118.259174   Topic3  -5.8729   1.8749
297           makanan    116.926714    117.804740   Topic3  -5.8770   1.8747
3205           muffin    112.271137    113.122832   Topic3  -5.9176   1.8746
876             pulak    103.431016    104.291790   Topic3  -5.9996   1.8739
286           mentega    789.237119    853.305367   Topic3  -3.9674   1.8041
259              susu    654.084596    734.690352   Topic3  -4.1553   1.7659
124             telur   1018.088088   1640.991518   Topic3  -3.7128   1.4048
34                teh   2245.618100   5004.988139   Topic3  -2.9218   1.0807
184            pandan    325.708671    435.446244   Topic3  -4.8525   1.5918
40                mat   1071.808282   2129.803052   Topic3  -3.6614   1.1955
85               gula   1778.303431   4454.223688   Topic3  -3.1551   0.9639
33              camca   3054.524763  11331.770395   Topic3  -2.6141   0.5712
79               gram    364.435649    547.497271   Topic3  -4.7401   1.4751
55         membuatnya   1008.006414   4318.273976   Topic3  -3.7228   0.4273
331             segar    259.655759    378.725848   Topic3  -5.0791   1.5047
146            kuning    323.941157    582.432752   Topic3  -4.8579   1.2955
70                air    714.083791   2928.748262   Topic3  -4.0675   0.4708
52              halus    936.315549   5338.614621   Topic3  -3.7965   0.1414
0       bahanbahannya    649.053587   3239.200634   Topic3  -4.1630   0.2746
42              garam    582.806000   3892.646028   Topic3  -4.2706  -0.0169
8                biji    700.012674  10954.746899   Topic3  -4.0874  -0.8683
206             manis    247.923787    926.961958   Topic3  -5.1254   0.5633
189            serbuk    243.379513   1475.061358   Topic3  -5.1439   0.0803
308              sagu    246.384882    247.178535   Topic4  -4.7313   2.2792
2500           pengat    182.224544    183.029322   Topic4  -5.0329   2.2781
804              biru    160.560881    161.345905   Topic4  -5.1595   2.2776
1038            bubur    158.488325    159.270789   Topic4  -5.1725   2.2775
492            disiat    147.942304    148.722220   Topic4  -5.2414   2.2772
871            kepala    144.051745    144.871919   Topic4  -5.2680   2.2768
1055            galah     97.119066     97.903744   Topic4  -5.6622   2.2744
2601             caca     93.698099     94.492656   Topic4  -5.6981   2.2740
62             rebung     77.565729     78.345493   Topic4  -5.8871   2.2725
1482        belimbing     70.608188     71.388212   Topic4  -5.9810   2.2715
859          potongan     72.472349     73.273495   Topic4  -5.9550   2.2715
853             kurau     67.201785     67.981398   Topic4  -6.0305   2.2709
1483            buluh     66.015441     66.795502   Topic4  -6.0483   2.2707
77             nangka     53.079124     53.859184   Topic4  -6.2664   2.2679
560             botol     45.019388     45.808612   Topic4  -6.4311   2.2651
10728    keladijuadah     88.879328     90.702413   Topic4  -5.7509   2.2622
856            pegaga     34.751965     35.534450   Topic4  -6.6899   2.2602
1533            siput     34.400992     35.185851   Topic4  -6.7001   2.2599
1060          pelepah     31.507782     32.289085   Topic4  -6.7879   2.2580
862    belacandikisar     31.646620     32.433945   Topic4  -6.7835   2.2579
1534            sedut     29.969839     30.749218   Topic4  -6.8380   2.2568
869            tamban     29.875091     30.655837   Topic4  -6.8412   2.2567
900              keli     26.774506     27.554683   Topic4  -6.9507   2.2537
1862          kotoran     25.816317     26.597824   Topic4  -6.9872   2.2526
2425             duri     25.354441     26.138145   Topic4  -7.0052   2.2520
9017    kasarditumbuk     25.724350     26.537769   Topic4  -6.9907   2.2513
858           ulamman     24.409939     25.196214   Topic4  -7.0432   2.2508
3414             muna     22.611954     23.400626   Topic4  -7.1197   2.2482
1140            selar     22.079856     22.861230   Topic4  -7.1435   2.2477
3756             jual     21.448824     22.233568   Topic4  -7.1725   2.2465
852             masin    150.431843    164.956441   Topic4  -5.2247   2.1903
175             ketul    428.860595    508.078816   Topic4  -4.1770   2.1130
38             santan   1366.965403   1848.605279   Topic4  -3.0178   1.9806
67            gelugor    559.559478    712.678988   Topic4  -3.9110   2.0406
922               tos    154.003788    185.071236   Topic4  -5.2012   2.0987
29               pati    586.269314    810.970626   Topic4  -3.8644   1.9580
73            kampung     99.171428    122.470047   Topic4  -5.6413   2.0714
207            tulang     90.382927    121.313017   Topic4  -5.7341   1.9881
336         kurangkan    132.991463    194.946322   Topic4  -5.3479   1.9000
81              helai    554.017825   1167.344266   Topic4  -3.9210   1.5372
74             kunyit    828.292041   1943.494596   Topic4  -3.5188   1.4296
1              keping    653.372905   1616.348028   Topic4  -3.7560   1.3767
72               padi    422.882460    920.729756   Topic4  -4.1911   1.5044
75              hidup    469.578951   1102.868606   Topic4  -4.0863   1.4286
65              serai    399.963277    963.963177   Topic4  -4.2468   1.4028

Topic: 1
camca, bawang, biji, sos, hiris, cili, hirisan, putih, halus, ulas, membuatnya, daun, merah, kicap, batang, bahanbahannya, lada, goreng, toskan, air, hiasan, tomato, teh, dihiris, tiram, garam, udang, ayam, didadu, tapis

Topic: 2
kering, rendam, udang, toskan, kacang, ketepikan, cekak, kembang, panaskan, kerat, ambil, sambal, kuah, nie, laksa, cuci, keperluan, lembut, goreng, thai, hiris, tauhu, sayur, yea, tumbuk, isi, garing, air, bilis, timun

Topic: 3
camca, teh, gula, tepung, mat, telur, membuatnya, halus, mentega, gandum, air, biji, susu, bahanbahannya, gred, garam, esen, vanilla, cream, diayak, gram, baking, pandan, kuning, pasir, segar, kek, manis, serbuk, sebati

Topic: 4
roti, doh, tin, halus, bread, flour, mat, telur, sosej, lecek, teh, dimakan, keju, serbuk, parutan, camca, kaedah, keping, lemon, hitam, cincang, didadu, sayur, yeast, instant, membuatnya, pilih, kecuali, tuna, improver

Topic: 5
kak, nak, kasih, terima, dah, kat, gambar, salah, nama, ben, tau, tag, yeaa, tengok, peranakan, klik, ummi, puan, cina, award, sorang, salam, malaysia, ashaari, canai, kesah, kena, masakan, mak, puteri

Topic: 6
biji, bawang, camca, inci, halus, merah, ulas, putih, cili, teh, garam, ikan, gula, membuatnya, halia, daun, batang, hiris, bahanbahannya, air, secukup, kunyit, kuntum, bunga, kisar, asam, buah, belah, kari, belacan

Topic: 7
santan, biji, gula, kunyit, bawang, garam, merah, inci, keping, ikan, membuatnya, pati, gelugor, cili, helai, bahanbahannya, hidup, asam, daun, ketul, padi, ulas, putih, serai, cair, halus, dititik, batang, toskan, cuci

[(0,
  '0.062*"camca" + 0.045*"bawang" + 0.041*"biji" + 0.034*"sos" + 0.023*"hiris" + 0.021*"cili" + 0.020*"hirisan" + 0.019*"putih" + 0.019*"halus" + 0.017*"ulas"'),
 (1,
  '0.046*"kering" + 0.042*"rendam" + 0.038*"udang" + 0.023*"toskan" + 0.020*"kacang" + 0.018*"ketepikan" + 0.016*"cekak" + 0.015*"kembang" + 0.013*"panaskan" + 0.012*"kerat"'),
 (2,
  '0.073*"camca" + 0.054*"teh" + 0.043*"gula" + 0.042*"tepung" + 0.026*"mat" + 0.024*"telur" + 0.024*"membuatnya" + 0.022*"halus" + 0.019*"mentega" + 0.018*"gandum"'),
 (3,
  '0.038*"roti" + 0.025*"doh" + 0.024*"tin" + 0.018*"halus" + 0.016*"bread" + 0.015*"flour" + 0.015*"mat" + 0.013*"telur" + 0.011*"sosej" + 0.011*"lecek"'),
 (4,
  '0.031*"kak" + 0.024*"nak" + 0.015*"kasih" + 0.013*"terima" + 0.013*"dah" + 0.011*"kat" + 0.010*"gambar" + 0.009*"salah" + 0.008*"nama" + 0.007*"ben"'),
 (5,
  '0.063*"biji" + 0.045*"bawang" + 0.045*"camca" + 0.029*"inci" + 0.026*"halus" + 0.023*"merah" + 0.023*"ulas" + 0.021*"putih" + 0.020*"cili" + 0.020*"teh"'),
 (6,
  '0.049*"santan" + 0.046*"biji" + 0.030*"gula" + 0.030*"kunyit" + 0.027*"bawang" + 0.026*"garam" + 0.026*"merah" + 0.024*"inci" + 0.023*"keping" + 0.023*"ikan"')]

### Inspect Probability

In [ ]:
tiffinProb = make_dictionary_terms_prob(ldamodel, id_map, d)
#probabilitas kata garam pada setiap topik
tiffinProb["garam"]

## Wordnet

In [ ]:
# dfWN = make_dataframe_wordnet(modelToText(ldamodel, 10)) # mengambil 10 kata dari tiap topik
tiffinWN = dfWordnet.copy()
pattern_wn = r"('.+?\.)"

tiffinWN["Synonym_clean"] = cleanWN_Synonym(tiffinWN["Synonym"])
tiffinWN["Hypernim_clean"] = cleanWN(tiffinWN["Hypernim"])
tiffinWN["Hyponim_clean"] = cleanWN(tiffinWN["Hyponim"])

# output 5 data teratas
tiffinWN.head()

,No. Topic,Word,Synonym,Hypernim,Hyponim,Definition,Synonym_clean,Hypernim_clean,Hyponim_clean
0,1,camca,Synset('spoon.n.01'),"[Synset('container.n.01'), Synset('cutlery.n.0...","[Synset('dessert_spoon.n.01'), Synset('runcibl...",a piece of cutlery with a shallow bowl-shaped ...,spoon,"[container, cutlery]","[dessert_spoon, runcible_spoon, soupspoon, sug..."
1,1,bawang,Synset('gazpacho.n.01'),[Synset('soup.n.01')],[],a soup made with chopped tomatoes and onions a...,gazpacho,[soup],None
2,1,biji,Synset('semen.n.01'),[Synset('liquid_body_substance.n.01')],[Synset('milt.n.02')],the thick white fluid containing spermatozoa t...,semen,[liquid_body_substance],[milt]
3,1,sos,Synset('sauce.n.01'),[Synset('condiment.n.01')],"[Synset('aioli.n.01'), Synset('allemande.n.01'...",flavorful relish or dressing or topping served...,sauce,[condiment],"[aioli, allemande, anchovy_sauce, apricot_sauc..."
4,1,hiris,Synset('piece.n.08'),[Synset('helping.n.01')],"[Synset('cutlet.n.01'), Synset('fillet.n.02')]",a serving that has been cut from a larger portion,piece,[helping],"[cutlet, fillet]"

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/TiffinBiru.owl")
makeOntology(ontoName, tiffinWN)
ontoName.save(file = "TiffinBiru.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1ANVxFEYIcw0tAsHYOJMABap0OFCDu1V2"

In [ ]:
wiki_tiffin = pd.read_excel("Tiffin Biru_final.xlsx").iloc[:, 1:]
wiki_tiffin.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_tiffin["Category"] = translate(wiki_tiffin["Category"])
wiki_tiffin.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_tiffin[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
tiffinTabel_new = tabel_1981.copy()
tiffinTabel_new["correct_category"] = all_cat
tiffinTabel_new["suggestion"] = all_suggestion

# Export Result to File
tiffinTabel_new.to_excel("tiffinTabel_Result.xlsx")
tiffinTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tiffinTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
tiffinTabel_new = concatListInColumn(tiffinTabel_new)
tiffinTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, tiffinTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_tiffin.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
tiffinWiki_new = wiki_df.copy()
tiffinWiki_new["suggest"] = all_cat

# Export Result to file
tiffinWiki_new.to_excel("tiffinWiki_Result.xlsx")
tiffinWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tiffinWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
tiffinOntoWiki = get_ontology("http://test.org/tiffin_onto_wiki.owl")
makeOntology_wiki(tiffinOntoWiki, tiffinWiki_new)
tiffinOntoWiki.save(file = "tiffin_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = tiffinWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
tiffinWN_new = listToDataframe(changesList, tableWordnet)
tiffinWN_new.to_excel("tiffinWN_Result.xlsx")
tiffinWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tiffinWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Ayam - Cookpad

In [ ]:
!gdown --id "1glKh8i7UA0Q8gyGxJ9nrXCwrC6WoOy6A"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1glKh8i7UA0Q8gyGxJ9nrXCwrC6WoOy6A
To: /content/cookpad-ayam.jl
100% 14.6k/14.6k [00:00<00:00, 21.0MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
ayam_cpd=pd.read_json(r'/content/cookpad-ayam.jl', lines = True)
ayam_cpd = concat_bahan_langkah(ayam_cpd)

# fill NaN with empty string
ayam_cpd["page_description"] = ayam_cpd["page_description"].fillna("")

#save dalam acar biar ngebut loading ntar.
ayam_cpd.to_pickle(r'/content/raw_df.pkl')

# covnert page_description to list
ayam_cpd["temp"] = ayam_cpd["page_description"]
ayam_cpd["page_description"] = ayam_cpd["page_bahan_langkah"]

# # clean text
ayam_cpd = pre_cleaning_text(ayam_cpd, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
ayam_cpd.head()

,url_search,list_scraping_time,list_item_url,list_item_title,list_item_ingredients,list_item_author_name,list_item_author_image_url,list_item_image_url,page_scraping_time,page_image_url,...,page_serving_count,page_bahan,page_langkah,page_post_datetime,page_post_love_count,page_post_clap_count,page_post_tasty_count,page_comment_count,page_bahan_langkah,temp
0,https://cookpad.com/id/cari/ayam?event=search....,2021-12-27 08:03:02,https://cookpad.com/id/resep/15827121-minyak-ayam,Minyak Ayam,"[Kulit ayam dan lemak, bawang putih iris tipis...",Ibu Tina,https://img-global.cpcdn.com/users/257098d9c19...,https://img-global.cpcdn.com/recipes/10a0f7cc2...,2021-12-27 08:03:02,https://img-global.cpcdn.com/recipes/10a0f7cc2...,...,None,"[secukupnya Kulit ayam dan lemak, 3 bawang put...",[],27 Desember 2021 06.40,NaN,NaN,NaN,NaN,"[secukupnya Kulit ayam dan lemak, 3 bawang put...","Sangat enak buat masak nasgor, mie maupun tumi..."
1,https://cookpad.com/id/cari/ayam?event=search....,2021-12-27 08:03:02,https://cookpad.com/id/resep/15827176-pindang-...,Pindang ayam khas palembang,"[ayam, air, laos geprek, serai geprek, cuka, g...",Tayooo,https://img-global.cpcdn.com/users/e30967ee548...,https://img-global.cpcdn.com/recipes/1a10091e7...,2021-12-27 08:03:04,https://img-global.cpcdn.com/recipes/1a10091e7...,...,2 orang,"[4 potong ayam, 400 ml air, 2-3 cm laos geprek...",[],27 Desember 2021 07.15,NaN,NaN,NaN,NaN,"[4 potong ayam, 400 ml air, 2-3 cm laos geprek...",Di rumah cuma ada ayam jadi pindang ayam saja
2,https://cookpad.com/id/cari/ayam?event=search....,2021-12-27 08:03:02,https://cookpad.com/id/resep/15826872-garang-a...,Garang Asem Ayam,"[ayam, Ayam tadi (lumuri kunyit bubuk,, lada b...",kdewi,https://img-global.cpcdn.com/users/e207585a1f1...,https://img-global.cpcdn.com/recipes/db9d432e8...,2021-12-27 08:03:17,https://img-global.cpcdn.com/recipes/db9d432e8...,...,None,"[1/2 kg ayam, Ayam tadi (lumuri kunyit bubuk,,...","[Ayam dimarinasi, diamkan 15 menit, Iris² bawa...",27 Desember 2021 04.04,2.0,1.0,3.0,NaN,"[1/2 kg ayam, Ayam tadi (lumuri kunyit bubuk,,...",
3,https://cookpad.com/id/cari/ayam?event=search....,2021-12-27 08:03:02,https://cookpad.com/id/resep/15826969-dimsum-a...,Dimsum Ayam Nori,"[ayam fillet, minyak wijen, saus tiram, gula, ...",Zarmaliawati,https://img-global.cpcdn.com/users/d8eb929105c...,https://img-global.cpcdn.com/recipes/14b9d1ac3...,2021-12-27 08:03:31,https://img-global.cpcdn.com/recipes/14b9d1ac3...,...,10 gulung nori,[10 lembar nori atau kulit lumpia besar dipoto...,[Giling ayam fillet. Saya gilingnya pke choppe...,27 Desember 2021 05.00,1.0,1.0,2.0,NaN,[10 lembar nori atau kulit lumpia besar dipoto...,Ini resep dari kakak yg jualan dimsum. Jd sdh ...
4,https://cookpad.com/id/cari/ayam?event=search....,2021-12-27 08:03:02,https://cookpad.com/id/resep/15827070-ayam-tep...,Ayam tepung crispy,"[ayam fillet aq pakai dada, kaldu ayam secukup...",Hariyati Zahwa,https://img-global.cpcdn.com/users/5539fe6e33a...,https://img-global.cpcdn.com/recipes/4de272159...,2021-12-27 08:03:40,https://img-global.cpcdn.com/recipes/4de272159...,...,2 orang,"[300 gram ayam fillet aq pakai dada, kaldu aya...",[],27 Desember 2021 06.07,2.0,NaN,NaN,NaN,"[300 gram ayam fillet aq pakai dada, kaldu aya...",

## GUI Ayam - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = ayam_cpd.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0     -0.100138 -0.067420       1        1  43.699991
1     -0.106764  0.103148       2        1  27.372145
3      0.142317  0.046896       3        1  22.412263
5      0.036642 -0.060135       4        1   6.409687
6      0.009288 -0.007472       5        1   0.037250
2      0.009314 -0.007495       6        1   0.036320
4      0.009342 -0.007522       7        1   0.032344, topic_info=                            Term       Freq      Total Category  logprob  \
108                         paha   5.000000   5.000000  Default  30.0000
1                           ayam  17.000000  17.000000  Default  29.0000
16                         merah   7.000000   7.000000  Default  28.0000
34                         salam   5.000000   5.000000  Default  27.0000
23                         bubuk   5.000000   5.000000  Default  26.0000
3                         bawang  14.000000  14.000000  Default  25.0000
19                          cabe   4.000000   4.000000  Default  24.0000
4                          putih   9.000000   9.000000  Default  23.0000
30                          ruas   4.000000   4.000000  Default  22.0000
110                       kemiri   3.000000   3.000000  Default  21.0000
117                       tunggu   3.000000   3.000000  Default  20.0000
118                     mendidih   3.000000   3.000000  Default  19.0000
109                         buah   3.000000   3.000000  Default  18.0000
132                       santan   3.000000   3.000000  Default  17.0000
71                         telur   5.000000   5.000000  Default  16.0000
24                          lada   3.000000   3.000000  Default  15.0000
38                         sereh   3.000000   3.000000  Default  14.0000
8                            air   7.000000   7.000000  Default  13.0000
14                         bumbu   4.000000   4.000000  Default  12.0000
69                      haluskan   3.000000   3.000000  Default  11.0000
33                          daun   7.000000   7.000000  Default  10.0000
18                        kunyit   3.000000   3.000000  Default   9.0000
17                          jahe   3.000000   3.000000  Default   8.0000
10                        geprek   3.000000   3.000000  Default   7.0000
84                          aduk   3.000000   3.000000  Default   6.0000
13                         garam   5.000000   5.000000  Default   5.0000
26                         siung   5.000000   5.000000  Default   4.0000
50                         tumis   2.000000   2.000000  Default   3.0000
11                         serai   2.000000   2.000000  Default   2.0000
58                     tambahkan   2.000000   2.000000  Default   1.0000
108                         paha   5.374691   5.678689   Topic1  -3.3282
132                       santan   2.750633   3.053700   Topic1  -3.9981
109                         buah   2.750478   3.053655   Topic1  -3.9981
118                     mendidih   2.750441   3.053628   Topic1  -3.9981
110                       kemiri   2.750230   3.053528   Topic1  -3.9982
117                       tunggu   2.749886   3.053456   Topic1  -3.9983
131                       sachet   1.875441   2.178507   Topic1  -4.3811
133                       instan   1.875438   2.178504   Topic1  -4.3811
137                        rebus   1.875435   2.178501   Topic1  -4.3811
144                      masukan   1.875430   2.178496   Topic1  -4.3811
111                        jamur   1.874859   2.178311   Topic1  -4.3814
34                         salam   4.500616   5.618144   Topic1  -3.5057
139                      merebus   1.000238   1.303303   Topic1  -5.0097
143                      kecuali   1.000235   1.303300   Topic1  -5.0097
130                       jinten   1.000235   1.303299   Topic1  -5.0097
147                     terendam   1.000233   1.303298   Topic1  -5.0097
136                     indofood   1.000232   1.303297   Topic1  -5.0097
146                    ayamtelur   1.000232   1.303297   Topic1  -5.0097
141                    berkurang   1.000232   1.303297   Topic1  -5.0097
145                      ayamdan   1.000232   1.303296   Topic1  -5.0097
140                     kulitnya   1.000231   1.303295   Topic1  -5.0097
135                        gulai   1.000229   1.303294   Topic1  -5.0097
142                        kupas   1.000229   1.303294   Topic1  -5.0097
134                         kara   1.000227   1.303291   Topic1  -5.0097
128                    disangrai   1.000228   1.303292   Topic1  -5.0097
129                         pala   1.000223   1.303288   Topic1  -5.0097
148                      sajikan   1.000221   1.303286   Topic1  -5.0097
127                         biji   1.000220   1.303285   Topic1  -5.0097
138                     optional   1.000220   1.303285   Topic1  -5.0097
113                       bersih   1.000018   1.303233   Topic1  -5.0099
69                      haluskan   2.750161   3.835722   Topic1  -3.9982
38                         sereh   2.750727   3.867906   Topic1  -3.9980
24                          lada   2.750195   3.867754   Topic1  -3.9982
23                         bubuk   3.625388   5.557264   Topic1  -3.7219
101                        kaldu   1.874945   2.686141   Topic1  -4.3813
14                         bumbu   2.750364   4.375714   Topic1  -3.9982
1                           ayam   7.999552  17.874150   Topic1  -2.9305
30                          ruas   2.750125   4.681915   Topic1  -3.9983
8                            air   3.625416   7.153686   Topic1  -3.7219
50                         tumis   1.875265   2.992646   Topic1  -4.3812
11                         serai   1.874675   2.992589   Topic1  -4.3815
58                     tambahkan   1.874638   2.992585   Topic1  -4.3815
71                         telur   2.750632   5.125950   Topic1  -3.9981
70                         butir   1.875425   3.468537   Topic1  -4.3811
33                          daun   2.750125   7.060469   Topic1  -3.9983
16                         merah   2.750702   7.124864   Topic1  -3.9981
84                          aduk   1.875229   3.742815   Topic1  -4.3812
52                        matang   1.875476   3.774927   Topic1  -4.3810
3                         bawang   3.625280  14.047389   Topic1  -3.7220
4                          putih   2.749928   9.915156   Topic1  -3.9983
26                         siung   1.875519   5.096983   Topic1  -4.3810
25                       diamkan   1.744665   2.056523   Topic2  -3.9855
45                    dimarinasi   1.744661   2.056531   Topic2  -3.9855
27                         hijau   1.744639   2.056524   Topic2  -3.9855
9                           laos   0.930605   1.242374   Topic2  -4.6140
12                          cuka   0.930605   1.242374   Topic2  -4.6140
20                        sesuai   0.930605   1.242374   Topic2  -4.6140
21                        selera   0.930605   1.242374   Topic2  -4.6140
39                     belimbing   0.930528   1.242323   Topic2  -4.6141
36                         jeruk   0.930512   1.242318   Topic2  -4.6141
55                      menyusut   0.930499   1.242303   Topic2  -4.6141
44                         pasir   0.930507   1.242314   Topic2  -4.6141
22                        lumuri   0.930518   1.242330   Topic2  -4.6141
51                   merahbawang   0.930510   1.242319   Topic2  -4.6141
29                         rawit   0.930507   1.242316   Topic2  -4.6141
31                      digeprek   0.930502   1.242313   Topic2  -4.6141
61                     disajikan   0.930500   1.242312   Topic2  -4.6141
47                         iris²   0.930493   1.242303   Topic2  -4.6141
59                  gulapenyedap   0.930488   1.242297   Topic2  -4.6141
57                           dll   0.930490   1.242299   Topic2  -4.6141
28                         pedas   0.930498   1.242312   Topic2  -4.6141
60                       koreksi   0.930499   1.242316   Topic2  -4.6141
40                         wuluh   0.930497   1.242316   Topic2  -4.6141
49                     wuluhdaun   0.930486   1.242303   Topic2  -4.6141
48   bawang²ancabetomatbelimbing   0.930490   1.242309   Topic2  -4.6141
56                        irisan   0.930482   1.242304   Topic2  -4.6141
54                         empuk   0.930469   1.242295   Topic2  -4.6142
42                penyedapmasako   0.930477   1.242306   Topic2  -4.6141
32                      lengkuas   0.930477   1.242308   Topic2  -4.6141
19                          cabe   3.373111   4.560240   Topic2  -3.3263
41                         tomat   1.744688   2.931753   Topic2  -3.9855
16                         merah   4.187418   7.124864   Topic2  -3.1100
3                         bawang   5.816683  14.047389   Topic2  -2.7814
1                           ayam   5.817854  17.874150   Topic2  -2.7812
33                          daun   2.559284   7.060469   Topic2  -3.6024
8                            air   2.559375   7.153686   Topic2  -3.6023
10                        geprek   1.745596   3.806903   Topic2  -3.9850
17                          jahe   1.745291   3.806748   Topic2  -3.9852
18                        kunyit   1.745187   3.806741   Topic2  -3.9852
4                          putih   2.559805   9.915156   Topic2  -3.6022
35                        lembar   1.744759   4.496163   Topic2  -3.9855
30                          ruas   1.745045   4.681915   Topic2  -3.9853
26                         siung   1.744753   5.096983   Topic2  -3.9855
13                         garam   1.745485   5.371204   Topic2  -3.9851
23                         bubuk   1.745131   5.557264   Topic2  -3.9853
58                     tambahkan   0.931204   2.992585   Topic2  -4.6134
11                         serai   0.931172   2.992589   Topic2  -4.6134
53                         tutup   0.930834   2.117441   Topic2  -4.6138
24                          lada   0.930814   3.867754   Topic2  -4.6138
34                         salam   0.930780   5.618144   Topic2  -4.6138
14                         bumbu   0.930770   4.375714   Topic2  -4.6138
37                        batang   0.930663   2.117374   Topic2  -4.6139
43                          gula   0.930649   3.681935   Topic2  -4.6140
50                         tumis   0.930639   2.992646   Topic2  -4.6140
62                          nori   2.457984   2.774684   Topic3  -3.4428
0                          kulit   1.676118   1.992569   Topic3  -3.8257
67                          saus   1.675954   1.992476   Topic3  -3.8258
75                        wortel   1.675983   1.992511   Topic3  -3.8258
74                         parut   1.675982   1.992519   Topic3  -3.8258
66                         wijen   1.675915   1.992466   Topic3  -3.8258
68                         tiram   1.675961   1.992522   Topic3  -3.8258
5                           iris   0.894017   1.210359   Topic3  -4.4542
6                          tipis   0.894017   1.210359   Topic3  -4.4542
97                         kukus   0.893880   1.210314   Topic3  -4.4544
93                         tebal   0.893872   1.210306   Topic3  -4.4544
78                    teksturnya   0.893862   1.210300   Topic3  -4.4544
79                        giling   0.893859   1.210302   Topic3  -4.4544
82                       chopper   0.893855   1.210296   Topic3  -4.4544
94                         robek   0.893855   1.210297   Topic3  -4.4544
77                     sesuaikan   0.893866   1.210313   Topic3  -4.4544
89                         ambil   0.893862   1.210308   Topic3  -4.4544
76                          sagu   0.893846   1.210287   Topic3  -4.4544
81                           pke   0.893853   1.210297   Topic3  -4.4544
90                      selembar   0.893853   1.210301   Topic3  -4.4544
86                           tdk   0.893855   1.210305   Topic3  -4.4544
83                      ditambah   0.893843   1.210294   Topic3  -4.4544
73                          siam   0.893846   1.210297   Topic3  -4.4544
80                     gilingnya   0.893836   1.210283   Topic3  -4.4544
92                       ratakan   0.893830   1.210279   Topic3  -4.4544
96                      digulung   0.893839   1.210292   Topic3  -4.4544
72                          labu   0.893842   1.210298   Topic3  -4.4544
85                       diperas   0.893847   1.210305   Topic3  -4.4544
91                        adonan   0.893840   1.210299   Topic3  -4.4544
63                        lumpia   0.893834   1.210300   Topic3  -4.4544
65                        fillet   1.675934   2.500324   Topic3  -3.8258
4                          putih   4.022420   9.915156   Topic3  -2.9503
3                         bawang   4.022474  14.047389   Topic3  -2.9503
43                          gula   1.675942   3.681935   Topic3  -3.8258
84                          aduk   1.676012   3.742815   Topic3  -3.8258
35                        lembar   1.676012   4.496163   Topic3  -3.8258
71                         telur   1.675933   5.125950   Topic3  -3.8258
13                         garam   1.675962   5.371204   Topic3  -3.8258
1                           ayam   2.458118  17.874150   Topic3  -3.4428
33                          daun   1.675996   7.060469   Topic3  -3.8258
2                          lemak   0.894017   2.085559   Topic3  -4.4542
7                         goreng   0.894017   2.593317   Topic3  -4.4542
8                            air   0.893867   7.153686   Topic3  -4.4544
87                        airnya   0.893861   2.085360   Topic3  -4.4544
103                       tepung   1.088222   1.443768   Topic4  -3.0058
99                         pakai   0.580385   0.935931   Topic4  -3.6344
100                         dada   0.580385   0.935931   Topic4  -3.6344
102                    secukupny   0.580385   0.935931   Topic4  -3.6344
104                    serbaguna   0.580385   0.935931   Topic4  -3.6344
105                       sendok   0.580385   0.935931   Topic4  -3.6344
106                      maizena   0.580385   0.935931   Topic4  -3.6344
107                   menggorebg   0.580385   0.935931   Topic4  -3.6344
98                          gram   0.580385   0.935931   Topic4  -3.6344
65                        fillet   0.580482   2.500324   Topic4  -3.6343
7                         goreng   0.580387   2.593317   Topic4  -3.6344
101                        kaldu   0.580388   2.686141   Topic4  -3.6344
70                         butir   0.580433   3.468537   Topic4  -3.6344
14                         bumbu   0.580390   4.375714   Topic4  -3.6344
26                         siung   0.580435   5.096983   Topic4  -3.6343
71                         telur   0.580487   5.125950   Topic4  -3.6343
1                           ayam   1.596182  17.874150   Topic4  -2.6228
63                        lumpia   0.072602   1.210300   Topic4  -5.7131
72                          labu   0.072602   1.210298   Topic4  -5.7131
80                     gilingnya   0.072600   1.210283   Topic4  -5.7132
90                      selembar   0.072599   1.210301   Topic4  -5.7132
92                       ratakan   0.072596   1.210279   Topic4  -5.7132
88                       smuanya   0.072596   1.210296   Topic4  -5.7132
96                      digulung   0.072595   1.210292   Topic4  -5.7132
95                         susah   0.072594   1.210300   Topic4  -5.7132
86                           tdk   0.072594   1.210305   Topic4  -5.7132
76                          sagu   0.072593   1.210287   Topic4  -5.7133
91                        adonan   0.072593   1.210299   Topic4  -5.7133
83                      ditambah   0.072592   1.210294   Topic4  -5.7133
73                          siam   0.072591   1.210297   Topic4  -5.7133
4                          putih   0.580562   9.915156   Topic4  -3.6341
3                         bawang   0.580510  14.047389   Topic4  -3.6342
62                          nori   0.072689   2.774684   Topic4  -5.7119
66                         wijen   0.072647   1.992466   Topic4  -5.7125
75                        wortel   0.072639   1.992511   Topic4  -5.7126
67                          saus   0.072638   1.992476   Topic4  -5.7126
13                         garam   0.072633   5.371204   Topic4  -5.7127
68                         tiram   0.072628   1.992522   Topic4  -5.7128
43                          gula   0.072626   3.681935   Topic4  -5.7128
84                          aduk   0.072624   3.742815   Topic4  -5.7128
33                          daun   0.072623   7.060469   Topic4  -5.7128
74                         parut   0.072619   1.992519   Topic4  -5.7129
35                        lembar   0.072612   4.496163   Topic4  -5.7130
98                          gram   0.000857   0.935931   Topic5  -5.0046
100                         dada   0.000857   0.935931   Topic5  -5.0046
102                    secukupny   0.000857   0.935931   Topic5  -5.0046
104                    serbaguna   0.000857   0.935931   Topic5  -5.0046
105                       sendok   0.000857   0.935931   Topic5  -5.0046
106                      maizena   0.000857   0.935931   Topic5  -5.0046
107                   menggorebg   0.000857   0.935931   Topic5  -5.0046
99                         pakai   0.000857   0.935931   Topic5  -5.0046
92                       ratakan   0.000857   1.210279   Topic5  -5.0041
80                     gilingnya   0.000857   1.210283   Topic5  -5.0042
76                          sagu   0.000857   1.210287   Topic5  -5.0042
81                           pke   0.000857   1.210297   Topic5  -5.0042
96                      digulung   0.000857   1.210292   Topic5  -5.0042
83                      ditambah   0.000857   1.210294   Topic5  -5.0042
82                       chopper   0.000857   1.210296   Topic5  -5.0042
94                         robek   0.000857   1.210297   Topic5  -5.0043
73                          siam   0.000857   1.210297   Topic5  -5.0043
88                       smuanya   0.000857   1.210296   Topic5  -5.0043
78                    teksturnya   0.000857   1.210300   Topic5  -5.0043
79                        giling   0.000857   1.210302   Topic5  -5.0043
91                        adonan   0.000857   1.210299   Topic5  -5.0043
95                         susah   0.000857   1.210300   Topic5  -5.0043
72                          labu   0.000857   1.210298   Topic5  -5.0043
85                       diperas   0.000857   1.210305   Topic5  -5.0043
93                         tebal   0.000857   1.210306   Topic5  -5.0043
63                        lumpia   0.000857   1.210300   Topic5  -5.0043
90                      selembar   0.000857   1.210301   Topic5  -5.0043
89                         ambil   0.000857   1.210308   Topic5  -5.0043
86                           tdk   0.000857   1.210305   Topic5  -5.0044
77                     sesuaikan   0.000857   1.210313   Topic5  -5.0044
124                     diungkep   0.000858   1.303168   Topic5  -5.0036
1                           ayam   0.000863  17.874150   Topic5  -4.9978
108                         paha   0.000861   5.678689   Topic5  -4.9995
33                          daun   0.000860   7.060469   Topic5  -5.0007
3                         bawang   0.000860  14.047389   Topic5  -5.0007
4                          putih   0.000860   9.915156   Topic5  -5.0013
13                         garam   0.000859   5.371204   Topic5  -5.0021
30                          ruas   0.000859   4.681915   Topic5  -5.0023
18                        kunyit   0.000859   3.806741   Topic5  -5.0023
17                          jahe   0.000859   3.806748   Topic5  -5.0024
8                            air   0.000859   7.153686   Topic5  -5.0025
117                       tunggu   0.000859   3.053456   Topic5  -5.0026
34                         salam   0.000859   5.618144   Topic5  -5.0026
69                      haluskan   0.000858   3.835722   Topic5  -5.0028
24                          lada   0.000858   3.867754   Topic5  -5.0030

Topic: 1
ayam, paha, salam, air, bubuk, bawang, sereh, merah, santan, telur, buah, mendidih, bumbu, kemiri, lada, haluskan, ruas, daun, putih, tunggu, siung, matang, sachet, instan, rebus, masukan, butir, tumis, aduk, kaldu

Topic: 2
ayam, bawang, merah, cabe, putih, air, daun, geprek, garam, jahe, kunyit, bubuk, ruas, lembar, siung, tomat, diamkan, dimarinasi, hijau, tambahkan, serai, tutup, lada, salam, bumbu, batang, gula, tumis, cuka, laos

Topic: 3
merah, bawang, ayam, daun, siung, air, ruas, sereh, cabe, putih, tomat, lembar, bubuk, diamkan, salam, matang, hijau, dimarinasi, santan, lada, telur, tumis, bumbu, gula, butir, gulapenyedap, kunyit, masukan, dll, wuluh

Topic: 4
bawang, putih, ayam, nori, kulit, lembar, aduk, daun, wortel, parut, garam, tiram, saus, gula, fillet, telur, wijen, lemak, tipis, iris, goreng, kukus, tebal, air, sesuaikan, teksturnya, ambil, airnya, giling, robek

Topic: 5
ayam, putih, bawang, bumbu, kulit, merah, goreng, siung, garam, tepung, daun, lemak, air, geprek, iris, telur, tipis, cabe, halus, jahe, kunyit, salam, gram, serai, paha, butir, laos, kemiri, sendok, kaldu

Topic: 6
ayam, tepung, putih, bawang, telur, fillet, siung, butir, bumbu, kaldu, goreng, pakai, gram, dada, sendok, secukupny, menggorebg, maizena, serbaguna, nori, wijen, wortel, saus, garam, tiram, gula, aduk, daun, parut, lembar

Topic: 7
ayam, paha, daun, bawang, putih, garam, ruas, kunyit, jahe, air, tunggu, salam, haluskan, lada, kaldu, airnya, aduk, jamur, kemiri, batang, bubuk, serai, lembar, tambahkan, nori, cabe, geprek, gula, diungkep, merah

[(0,
  '0.053*"ayam" + 0.036*"paha" + 0.030*"salam" + 0.024*"air" + 0.024*"bubuk" + 0.024*"bawang" + 0.018*"sereh" + 0.018*"merah" + 0.018*"santan" + 0.018*"telur"'),
 (1,
  '0.062*"ayam" + 0.062*"bawang" + 0.045*"merah" + 0.036*"cabe" + 0.027*"putih" + 0.027*"air" + 0.027*"daun" + 0.019*"geprek" + 0.019*"garam" + 0.019*"jahe"'),
 (2,
  '0.007*"merah" + 0.007*"bawang" + 0.007*"ayam" + 0.007*"daun" + 0.007*"siung" + 0.007*"air" + 0.007*"ruas" + 0.007*"sereh" + 0.007*"cabe" + 0.007*"putih"'),
 (3,
  '0.052*"bawang" + 0.052*"putih" + 0.032*"ayam" + 0.032*"nori" + 0.022*"kulit" + 0.022*"lembar" + 0.022*"aduk" + 0.022*"daun" + 0.022*"wortel" + 0.022*"parut"'),
 (4,
  '0.007*"putih" + 0.007*"ayam" + 0.007*"bawang" + 0.007*"merah" + 0.007*"kulit" + 0.007*"bumbu" + 0.007*"geprek" + 0.007*"daun" + 0.007*"garam" + 0.007*"siung"'),
 (5,
  '0.073*"ayam" + 0.049*"tepung" + 0.026*"putih" + 0.026*"bawang" + 0.026*"telur" + 0.026*"fillet" + 0.026*"siung" + 0.026*"butir" + 0.026*"bumbu" + 0.026*"kaldu"'),
 (6,
  '0.007*"ayam" + 0.007*"paha" + 0.007*"daun" + 0.007*"bawang" + 0.007*"putih" + 0.007*"garam" + 0.007*"ruas" + 0.007*"kunyit" + 0.007*"jahe" + 0.007*"air"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
ayamCpdProb = make_dictionary_terms_prob(ldamodel, id_map, d)
ayamCpdProb["ayam"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
ayamCpdWN = dfWordnet.copy()

ayamCpdWN["Synonym_clean"] = cleanWN_Synonym(ayamCpdWN["Synonym"])
ayamCpdWN["Hypernim_clean"] = cleanWN(ayamCpdWN["Hypernim"])
ayamCpdWN["Hyponim_clean"] = cleanWN(ayamCpdWN["Hyponim"])
ayamCpdWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/ayamCookpad.owl")
makeOntology(ontoName, ayamCpdWN)
ontoName.save(file = "ayamCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown "1KOTNxtJLNJjPbSEXb30LF1NX3m3cc54_"

In [ ]:
wiki_ayam_cpd = pd.read_excel("AyamCookpadFinal.xlsx").iloc[:, 1:]

# Translate
wiki_ayam_cpd["Category"] = translate(wiki_ayam_cpd["Category"])
wiki_ayam_cpd.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_ayam_cpd[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
ayamCpdTabel_new = tabel_1981.copy()
ayamCpdTabel_new["correct_category"] = all_cat
ayamCpdTabel_new["suggestion"] = all_suggestion

# Export Result to File
ayamCpdTabel_new.to_excel("ayamCpdTabel_Result.xlsx")
ayamCpdTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
ayamCpdTabel_new = concatListInColumn(ayamCpdTabel_new)
ayamCpdTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, ayamCpdTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_ayam_cpd.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
ayamCpdWiki_new = wiki_df.copy()
ayamCpdWiki_new["suggest"] = all_cat

# Export Result to file
ayamCpdWiki_new.to_excel("ayamCpdWiki_Result.xlsx")
ayamCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
ayamCpdOntoWiki = get_ontology("http://test.org/ayamCpd_onto_wiki.owl")
makeOntology_wiki(ayamCpdOntoWiki, ayamCpdWiki_new)
ayamCpdOntoWiki.save(file = "ayamCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = ayamCpdWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
ayamCpdWN_new = listToDataframe(changesList, tableWordnet)
ayamCpdWN_new.to_excel("ayamCpdWN_Result.xlsx")
ayamCpdWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Ayam Selenium - Cookpad

In [ ]:
!gdown --id "1OTIjGPazGUtKTsZ2jpatPRbvxft-Vp1o"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1OTIjGPazGUtKTsZ2jpatPRbvxft-Vp1o
To: /content/cookpad-selenium_ayam.jl
100% 431k/431k [00:00<00:00, 122MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
ayam_cpd_sln=pd.read_json(r'/content/cookpad-selenium_ayam.jl', lines = True)
ayam_cpd_sln = concat_bahan_langkah(ayam_cpd_sln)

# fill NaN with empty string
ayam_cpd_sln["page_description"] = ayam_cpd_sln["page_description"].fillna("")

#save dalam acar biar ngebut loading ntar.
ayam_cpd_sln.to_pickle(r'/content/raw_df.pkl')

# covnert page_description to list
ayam_cpd_sln["temp"] = ayam_cpd_sln["page_description"]
ayam_cpd_sln["page_description"] = ayam_cpd_sln["page_bahan_langkah"]

# # clean text
ayam_cpd_sln = pre_cleaning_text(ayam_cpd_sln, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
ayam_cpd_sln.head()

,url_search,list_scraping_time,list_item_url,list_item_title,list_item_ingredients,list_item_author_name,list_item_author_image_url,list_item_image_url,page_scraping_time,page_image_url,...,page_serving_count,page_bahan,page_langkah,page_post_datetime,page_post_love_count,page_post_clap_count,page_post_tasty_count,page_comment_count,page_bahan_langkah,temp
0,https://cookpad.com/id/cari/ayam?event=search....,2022-06-24 10:30:16,https://cookpad.com/id/resep/15937128-ayam-ung...,\n Ayam Ungkep Kepayang (Keluwek)\n,"[\n ayam potong menurut selera\n , \n ...",Windu Restina,https://img-global.cpcdn.com/users/0c4f59b4f58...,https://img-global.cpcdn.com/recipes/e980f20aa...,2022-06-24 10:30:19,https://img-global.cpcdn.com/recipes/e980f20aa...,...,None,"[500 gr ayam potong menurut selera, 100 ml air...",[],24 Juni 2022 09.28,7.0,5.0,4.0,NaN,"[500 gr ayam potong menurut selera, 100 ml air...",Selamat buat mba
1,https://cookpad.com/id/cari/ayam?event=search....,2022-06-24 10:30:16,https://cookpad.com/id/resep/16326158-nasi-tim...,\n Nasi Tim ayam\n,"[\n Dada ayam fillet\n , \n wortel\...",Elviana,https://img-global.cpcdn.com/users/d7c9e5004f6...,https://img-global.cpcdn.com/recipes/905b923a3...,2022-06-24 10:30:22,https://img-global.cpcdn.com/recipes/905b923a3...,...,4 orang,"[1 Dada ayam fillet, 2 buah wortel, 300 gram b...",[],24 Juni 2022 09.11,1.0,NaN,NaN,NaN,"[1 Dada ayam fillet, 2 buah wortel, 300 gram b...",
2,https://cookpad.com/id/cari/ayam?event=search....,2022-06-24 10:30:16,https://cookpad.com/id/resep/16326162-chicken-...,\n Chicken wings saus barbeque\n,"[\n sayap ayam\n , \n Bawang putih\...",Feriana Feriana,https://img-global.cpcdn.com/users/efde4575a8b...,https://img-global.cpcdn.com/recipes/524f4bca7...,2022-06-24 10:30:25,https://img-global.cpcdn.com/recipes/524f4bca7...,...,4 orang,"[7 potong sayap ayam, 4 siung Bawang putih, Ja...",[],24 Juni 2022 09.11,1.0,NaN,NaN,NaN,"[7 potong sayap ayam, 4 siung Bawang putih, Ja...","Lagi pengen masak ayam ,tapi bosen kalau cuman..."
3,https://cookpad.com/id/cari/ayam?event=search....,2022-06-24 10:30:16,https://cookpad.com/id/resep/16326002-ayam-gor...,\n Ayam Goreng Oat\n,"[\n Marinasi:\n , \n Ayam dada/fill...",LinaS_Cuisine,https://img-global.cpcdn.com/users/95a77d1da4d...,https://img-global.cpcdn.com/recipes/0cd304549...,2022-06-24 10:30:27,https://img-global.cpcdn.com/recipes/0cd304549...,...,None,"[Marinasi:, 400 gr Ayam dada/fillet potong cub...",[],24 Juni 2022 07.48,NaN,NaN,2.0,NaN,"[Marinasi:, 400 gr Ayam dada/fillet potong cub...",Terinspirasi dari udang goreng crispy oat (per...
4,https://cookpad.com/id/cari/ayam?event=search....,2022-06-24 10:30:16,https://cookpad.com/id/resep/16326112-ayam-gor...,\n Ayam Goreng Mentega\n,"[\n Marinasi ayam :\n , \n paha aya...",Putri Larasati,https://img-global.cpcdn.com/users/dc5af1b724d...,https://img-global.cpcdn.com/recipes/a5b99a24c...,2022-06-24 10:30:50,https://img-global.cpcdn.com/recipes/a5b99a24c...,...,None,"[Marinasi ayam :, 4 potong paha ayam, 1 buah j...",[],24 Juni 2022 08.43,NaN,NaN,NaN,NaN,"[Marinasi ayam :, 4 potong paha ayam, 1 buah j...","masak praktis dan bergizi, tentu saja gurih se..."

## GUI Ayam Selenium - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = ayam_cpd_sln.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
6     -0.206636 -0.036072       1        1  39.107383
1     -0.250333 -0.041670       2        1  34.102830
5     -0.135254  0.106983       3        1  14.591090
0      0.120914 -0.245434       4        1   5.097039
4      0.046852  0.118757       5        1   3.736746
2      0.217787  0.050384       6        1   2.145580
3      0.206668  0.047053       7        1   1.219332, topic_info=                Term        Freq       Total Category  logprob  loglift
16              buah  234.000000  234.000000  Default  30.0000  30.0000
73            tepung   66.000000   66.000000  Default  29.0000  29.0000
129          cincang   57.000000   57.000000  Default  28.0000  28.0000
102             ruas  104.000000  104.000000  Default  27.0000  27.0000
5              halus   96.000000   96.000000  Default  26.0000  26.0000
7             bawang  419.000000  419.000000  Default  25.0000  25.0000
28              daun  200.000000  200.000000  Default  24.0000  24.0000
56             kecap  103.000000  103.000000  Default  23.0000  23.0000
8              merah  172.000000  172.000000  Default  22.0000  22.0000
49              gram   63.000000   63.000000  Default  21.0000  21.0000
68              saus   90.000000   90.000000  Default  20.0000  20.0000
27            lembar   83.000000   83.000000  Default  19.0000  19.0000
42              cabe   94.000000   94.000000  Default  18.0000  18.0000
84             telur   49.000000   49.000000  Default  17.0000  17.0000
30             jeruk   97.000000   97.000000  Default  16.0000  16.0000
18            kunyit   70.000000   70.000000  Default  15.0000  15.0000
59             bubuk  174.000000  174.000000  Default  14.0000  14.0000
61             garam  198.000000  198.000000  Default  13.0000  13.0000
1             selera   37.000000   37.000000  Default  12.0000  12.0000
29             salam   60.000000   60.000000  Default  11.0000  11.0000
123           sesuai   35.000000   35.000000  Default  10.0000  10.0000
48            wortel   28.000000   28.000000  Default   9.0000   9.0000
6              butir   78.000000   78.000000  Default   8.0000   8.0000
0               ayam  281.000000  281.000000  Default   7.0000   7.0000
13              jahe   78.000000   78.000000  Default   6.0000   6.0000
66             tomat   53.000000   53.000000  Default   5.0000   5.0000
43             rawit   48.000000   48.000000  Default   4.0000   4.0000
2                air  132.000000  132.000000  Default   3.0000   3.0000
58            merica   40.000000   40.000000  Default   2.0000   2.0000
196             keju   14.000000   14.000000  Default   1.0000   1.0000
56             kecap  102.488798  103.119764   Topic1  -3.4016   0.9327
68              saus   90.219432   90.898907   Topic1  -3.5291   0.9314
55             tiram   51.136342   51.766784   Topic1  -4.0968   0.9266
47            fillet   40.008379   40.639522   Topic1  -4.3422   0.9232
54              saos   37.995999   38.626270   Topic1  -4.3938   0.9224
105           sachet   36.546380   37.177336   Topic1  -4.4327   0.9217
78              dadu   27.614290   28.246329   Topic1  -4.7130   0.9162
127              btr   25.662882   26.299083   Topic1  -4.7863   0.9144
60              asin   23.601619   24.232175   Topic1  -4.8700   0.9125
141            pakai   19.006168   19.645663   Topic1  -5.0866   0.9058
85           maizena   16.331356   16.962094   Topic1  -5.2382   0.9010
248         haluskan   12.057155   12.689868   Topic1  -5.5417   0.8877
82           inggris   11.379563   12.009869   Topic1  -5.5995   0.8849
172          mentega   10.765039   11.395431   Topic1  -5.6550   0.8820
107            pedas    9.976707   10.610127   Topic1  -5.7311   0.8773
106            saori    8.580357    9.211273   Topic1  -5.8818   0.8679
161        serbaguna    8.409101    9.040892   Topic1  -5.9020   0.8664
529           butter    8.306597    8.937532   Topic1  -5.9143   0.8656
477          tapioka    7.830649    8.462589   Topic1  -5.9733   0.8612
124              mie    6.981260    7.611556   Topic1  -6.0881   0.8524
511             biar    6.737795    7.368113   Topic1  -6.1236   0.8494
554          merebus    6.735904    7.367201   Topic1  -6.1239   0.8493
437        sesuaikan    6.565410    7.197614   Topic1  -6.1495   0.8469
237            filet    6.365343    6.996759   Topic1  -6.1805   0.8443
358          mangkok    6.357319    7.013111   Topic1  -6.1817   0.8407
718         dadapaha    5.953509    6.583506   Topic1  -6.2473   0.8383
118             madu    5.752615    6.382688   Topic1  -6.2817   0.8349
114              bbq    5.581682    6.212178   Topic1  -6.3118   0.8318
128              bwg    5.411249    6.041918   Topic1  -6.3428   0.8286
746           crispy    5.168675    5.798651   Topic1  -6.3887   0.8238
75          marinasi   20.217320   23.001181   Topic1  -5.0248   0.8099
57             manis   57.042889   66.530472   Topic1  -3.9875   0.7850
96            bombay   46.831066   56.027872   Topic1  -4.1848   0.7596
129          cincang   47.990224   57.699371   Topic1  -4.1603   0.7546
46              dada   36.286227   43.256316   Topic1  -4.4399   0.7632
38             hitam   14.101122   16.235478   Topic1  -5.3851   0.7979
146             iris   45.682258   56.780389   Topic1  -4.2096   0.7214
22              lada   77.661530   99.964814   Topic1  -3.6790   0.6864
81             pasir   41.837789   53.271371   Topic1  -4.2975   0.6973
62             wijen   28.086636   34.652753   Topic1  -4.6960   0.7288
59             bubuk  117.795953  174.622099   Topic1  -3.2624   0.5452
73            tepung   47.123492   66.905203   Topic1  -4.1785   0.5884
10             putih  138.767772  236.748776   Topic1  -3.0985   0.4047
70             kaldu   74.243379  116.994376   Topic1  -3.7240   0.4841
0               ayam  147.140451  281.816199   Topic1  -3.0399   0.2890
2                air   76.832470  132.101035   Topic1  -3.6897   0.3969
61             garam  105.769438  198.667507   Topic1  -3.3701   0.3085
7             bawang  181.874683  419.439287   Topic1  -2.8280   0.1033
52             jamur   35.114686   51.403394   Topic1  -4.4727   0.5578
9              siung  114.128482  242.227868   Topic1  -3.2940   0.1863
32              gula   65.466500  118.366226   Topic1  -3.8498   0.3466
58            merica   29.220995   40.968717   Topic1  -4.6564   0.6009
49              gram   36.222694   63.532968   Topic1  -4.4416   0.3770
16              buah   53.206226  234.916147   Topic1  -4.0571  -0.5462
4              bumbu   40.609355  131.974695   Topic1  -4.3273  -0.2398
41            goreng   34.914316   86.732505   Topic1  -4.4784   0.0289
5              halus   35.667689   96.634005   Topic1  -4.4571  -0.0578
66             tomat   29.609108   53.333816   Topic1  -4.6432   0.3504
102             ruas  103.932853  104.595233   Topic2  -3.2506   1.0694
18            kunyit   69.744729   70.407701   Topic2  -3.6495   1.0663
29             salam   59.356202   60.018621   Topic2  -3.8108   1.0647
12          lengkuas   42.168068   42.830254   Topic2  -4.1527   1.0602
208         memarkan   31.592647   32.335299   Topic2  -4.4415   1.0526
474          sangrai   27.341631   28.004029   Topic2  -4.5860   1.0519
25             sereh   26.613799   27.276398   Topic2  -4.6130   1.0512
215              lbr   21.662776   22.324663   Topic2  -4.8188   1.0457
65              jari   19.648998   20.311665   Topic2  -4.9164   1.0426
362          kampung   12.848153   13.512303   Topic2  -5.3412   1.0254
300            liter   10.836972   11.499484   Topic2  -5.5114   1.0165
214            serai   28.053591   30.212727   Topic2  -4.5603   1.0016
595           jempol    8.498741    9.161818   Topic2  -5.7545   1.0007
235             laos    8.228395    8.890308   Topic2  -5.7868   0.9984
762           irisan    8.116583    8.778610   Topic2  -5.8005   0.9974
11            kemiri   52.419426   56.736778   Topic2  -3.9351   0.9966
163             sere    6.350450    7.013417   Topic2  -6.0459   0.9765
452          genggam    5.858137    6.522320   Topic2  -6.1266   0.9684
680           padang    5.369592    6.033413   Topic2  -6.2136   0.9592
622             limo    5.370043    6.033932   Topic2  -6.2136   0.9592
611           selada    5.368552    6.032986   Topic2  -6.2138   0.9591
27            lembar   73.735325   83.985263   Topic2  -3.5939   0.9456
13              jahe   68.505994   78.101547   Topic2  -3.6675   0.9447
220              ltr    4.449626    5.111869   Topic2  -6.4016   0.9370
50             beras   11.971711   13.807240   Topic2  -5.4118   0.9331
775              ptg    4.120696    4.782211   Topic2  -6.4784   0.9269
776          ktumbar    4.120696    4.782211   Topic2  -6.4784   0.9269
777      serehgeprek    4.120696    4.782211   Topic2  -6.4784   0.9269
778             blok    4.120696    4.782211   Topic2  -6.4784   0.9269
760      kunyitbubuk    4.120516    4.782162   Topic2  -6.4784   0.9269
21          ketumbar   38.377253   45.090442   Topic2  -4.2469   0.9146
316             ekor   26.243878   30.730424   Topic2  -4.6270   0.9180
24            batang   47.904593   57.218850   Topic2  -4.0252   0.8981
30             jeruk   78.403094   97.048540   Topic2  -3.5325   0.8624
28              daun  151.703130  200.927576   Topic2  -2.8725   0.7948
304              cup    8.799776   10.524818   Topic2  -5.7197   0.8968
221           santan   21.653024   28.592262   Topic2  -4.8192   0.7978
8              merah   99.667519  172.762378   Topic2  -3.2925   0.5257
94             nipis   20.803458   28.883286   Topic2  -4.8593   0.7476
4              bumbu   73.891079  131.974695   Topic2  -3.5918   0.4958
6              butir   46.042358   78.902653   Topic2  -4.0648   0.5371
41            goreng   49.725357   86.732505   Topic2  -3.9879   0.5195
42              cabe   52.264226   94.121165   Topic2  -3.9381   0.4875
7             bawang  157.754401  419.439287   Topic2  -2.8333   0.0979
26            geprek   24.459544   37.138011   Topic2  -4.6974   0.6582
9              siung   95.792940  242.227868   Topic2  -3.3322   0.1481
61             garam   75.125706  198.667507   Topic2  -3.5752   0.1033
0               ayam   92.648590  281.816199   Topic2  -3.3656  -0.0367
5              halus   44.767278   96.634005   Topic2  -4.0929   0.3063
10             putih   76.414800  236.748776   Topic2  -3.5582  -0.0550
2                air   49.593089  132.101035   Topic2  -3.9905   0.0961
32              gula   44.544893  118.366226   Topic2  -4.0979   0.0985
59             bubuk   51.465441  174.622099   Topic2  -3.9535  -0.1459
70             kaldu   42.211188  116.994376   Topic2  -4.1517   0.0563
16              buah   43.830954  234.916147   Topic2  -4.1140  -0.6031
67             cabai   21.285126   21.931141   Topic3  -3.9874   1.8949
19            sendok    8.781899    9.426216   Topic3  -4.8727   1.8540
14             kupas    7.991505    8.640116   Topic3  -4.9670   1.8467
430           buncis    7.842353    8.486517   Topic3  -4.9859   1.8458
290           kental    7.841260    8.486507   Topic3  -4.9860   1.8457
23          cemplung    7.279991    7.924746   Topic3  -5.0603   1.8399
136             soun    7.278468    7.924789   Topic3  -5.0605   1.8397
138             beli    6.563678    7.207705   Topic3  -5.1639   1.8312
725              sop    6.158656    6.802045   Topic3  -5.2276   1.8254
539         kapulaga    6.157650    6.801868   Topic3  -5.2277   1.8253
281           lawang    6.002114    6.646129   Topic3  -5.2533   1.8228
737            bunga    5.440404    6.084546   Topic3  -5.3516   1.8129
254          kemangi    5.099935    5.745044   Topic3  -5.4162   1.8056
327            ambil    5.005816    5.651054   Topic3  -5.4348   1.8035
769          tingkat    4.723028    5.367431   Topic3  -5.4930   1.7969
756              yah    4.722769    5.367180   Topic3  -5.4930   1.7969
757             jual    4.722769    5.367180   Topic3  -5.4930   1.7969
758            sobek    4.722769    5.367180   Topic3  -5.4930   1.7969
759            magie    4.722769    5.367180   Topic3  -5.4930   1.7969
328           airnya    4.289837    4.933935   Topic3  -5.5892   1.7849
323          tangkai    4.132210    4.777708   Topic3  -5.6266   1.7796
123           sesuai   30.329002   35.407463   Topic3  -3.6333   1.7699
182            belah    3.415039    4.060419   Topic3  -5.8172   1.7517
177            isian    3.412140    4.059440   Topic3  -5.8181   1.7511
31             makan    5.101262    6.103376   Topic3  -5.4159   1.7454
97              skip   11.818843   14.183601   Topic3  -4.5757   1.7424
1             selera   31.428616   37.761613   Topic3  -3.5977   1.7412
380          kerupuk   10.030441   12.106973   Topic3  -4.7398   1.7366
260             ikan    3.725299    4.649571   Topic3  -5.7303   1.7031
142        rawitiris    2.544176    3.187813   Topic3  -6.1116   1.6992
240            suwir    7.017443    8.835356   Topic3  -5.0970   1.6944
16              buah  129.069052  234.916147   Topic3  -2.1851   1.3259
201          kentang   19.380423   29.064683   Topic3  -4.0812   1.5195
183             kuah    6.366539    8.798809   Topic3  -5.1944   1.6012
43             rawit   23.099149   48.949093   Topic3  -3.9056   1.1738
42              cabe   36.263980   94.121165   Topic3  -3.4546   0.9710
66             tomat   23.236119   53.333816   Topic3  -3.8997   1.0939
8              merah   47.343828  172.762378   Topic3  -3.1880   0.6303
7             bawang   72.166226  419.439287   Topic3  -2.7664   0.1648
253             ikat    7.210738   10.802051   Topic3  -5.0698   1.5206
111         penyedap   13.632848   32.280152   Topic3  -4.4329   1.0628
49              gram   19.152893   63.532968   Topic3  -4.0930   0.7257
79              pake    7.321115   11.777225   Topic3  -5.0547   1.4494
28              daun   31.025677  200.927576   Topic3  -3.6106   0.0566
9              siung   31.942706  242.227868   Topic3  -3.5815  -0.1012
0               ayam   27.565176  281.816199   Topic3  -3.7289  -0.3999
10             putih   21.201074  236.748776   Topic3  -3.9914  -0.4882
4              bumbu   17.110555  131.974695   Topic3  -4.2057  -0.1182
48            wortel    9.243913   28.017877   Topic3  -4.8215   0.8159
30             jeruk   12.712164   97.048540   Topic3  -4.5029  -0.1079
146             iris   10.609761   56.780389   Topic3  -4.6836   0.2473
96            bombay    8.708666   56.027872   Topic3  -4.8811   0.0632
61             garam    8.237836  198.667507   Topic3  -4.9367  -1.2581
32              gula    7.991189  118.366226   Topic3  -4.9671  -0.7707
196             keju   13.599229   14.290076   Topic4  -3.3837   2.9270
91             lihat    9.527909   10.215332   Topic4  -3.7394   2.9068
190             cair    9.518333   10.214845   Topic4  -3.7404   2.9059
343           instan    8.637472    9.326587   Topic4  -3.8376   2.8998
429           giling    7.747033    8.437891   Topic4  -3.9464   2.8911
103          chicken    6.449027    7.137992   Topic4  -4.1297   2.8750
110              bks    6.447057    7.138569   Topic4  -4.1300   2.8746
698             sisa    6.859301    7.646937   Topic4  -4.0681   2.8678
341         opsional    5.163470    5.860909   Topic4  -4.3521   2.8498
45             resep    9.412724   10.827316   Topic4  -3.7516   2.8365
739             sagu    3.783168    4.470283   Topic4  -4.6631   2.8096
337            bubur    3.672637    4.362101   Topic4  -4.6928   2.8045
338          saledri    3.672637    4.362101   Topic4  -4.6928   2.8045
765           filler    3.284701    3.971469   Topic4  -4.8044   2.7866
766             kone    3.284701    3.971469   Topic4  -4.8044   2.7866
767          special    3.284701    3.971469   Topic4  -4.8044   2.7866
770            dough    3.284545    3.971464   Topic4  -4.8044   2.7866
771            pizza    3.284545    3.971464   Topic4  -4.8044   2.7866
772            sosis    3.284545    3.971464   Topic4  -4.8044   2.7866
773       mozzarella    3.284545    3.971464   Topic4  -4.8044   2.7866
774           ceddar    3.284545    3.971464   Topic4  -4.8044   2.7866
763         kremesan    3.284337    3.971556   Topic4  -4.8045   2.7865
764           saring    3.284337    3.971556   Topic4  -4.8045   2.7865
191             roti    2.549825    3.236966   Topic4  -5.0576   2.7379
335           kuning    6.464139    8.699556   Topic4  -4.1274   2.6795
285            kanji    1.984890    2.672865   Topic4  -5.3081   2.6789
90           topping    4.019063    5.563840   Topic4  -4.6026   2.6513
505          munjung    1.595087    2.282183   Topic4  -5.5267   2.6183
296             sate    1.485402    2.174501   Topic4  -5.5980   2.5954
348      disesuaikan    1.485175    2.174794   Topic4  -5.5981   2.5951
404            sauce    3.282983    5.201198   Topic4  -4.8049   2.5164
73            tepung   19.250287   66.905203   Topic4  -3.0361   1.7308
204       menggoreng    4.690421   10.775824   Topic4  -4.4481   2.1447
460           powder    5.478362   13.833326   Topic4  -4.2929   2.0502
84             telur   10.580469   49.285820   Topic4  -3.6347   1.4379
112            parut    4.573700   11.456701   Topic4  -4.4733   2.0583
459           baking    4.467749   12.059135   Topic4  -4.4968   1.9836
6              butir    7.415288   78.902653   Topic4  -3.9901   0.6118
74            terigu    5.098291   19.811226   Topic4  -4.3648   1.6192
0               ayam    8.393429  281.816199   Topic4  -3.8662  -0.5373
94             nipis    4.921456   28.883286   Topic4  -4.4001   1.2069
30             jeruk    5.512558   97.048540   Topic4  -4.2866   0.1083
2                air    5.235322  132.101035   Topic4  -4.3382  -0.2516
199        pelengkap    3.890627   19.048977   Topic4  -4.6351   1.3881
37            sambal    3.833477   24.640272   Topic4  -4.6499   1.1159
458          oregano    3.555834   10.227962   Topic4  -4.7251   1.9200
28              daun    3.762956  200.927576   Topic4  -4.6685  -1.0012
320           matang    4.738764    5.434966   Topic5  -4.1274   3.1499
313           sambel    4.280977    4.977893   Topic5  -4.2290   3.1361
210             pala    4.263963    4.960360   Topic5  -4.2330   3.1357
527            puyuh    3.921727    4.620873   Topic5  -4.3167   3.1229
247            kukus    3.825227    4.520542   Topic5  -4.3416   3.1199
768           pokcoy    3.010441    3.705478   Topic5  -4.5811   3.0792
753            cacah    3.010322    3.705577   Topic5  -4.5812   3.0792
754             tbsp    3.010322    3.705577   Topic5  -4.5812   3.0792
755             full    3.010322    3.705577   Topic5  -4.5812   3.0792
780      sayurgoreng    3.009634    3.705719   Topic5  -4.5814   3.0789
781            pecel    3.009634    3.705719   Topic5  -4.5814   3.0789
219           ladaku    2.435880    3.131757   Topic5  -4.7929   3.0357
217              ons    1.977816    2.674692   Topic5  -5.0012   2.9851
447            panir    1.818843    2.515320   Topic5  -5.0850   2.9628
440           lumpia    3.006383    4.269389   Topic5  -4.5825   2.9362
573             suir    3.010249    4.330836   Topic5  -4.5812   2.9232
189             susu    7.049915   10.470413   Topic5  -3.7302   2.8914
185            cream    3.459644    5.141459   Topic5  -4.4421   2.8908
409           piring    1.361262    2.058793   Topic5  -5.3748   2.8732
312         putihnya    1.360895    2.058779   Topic5  -5.3751   2.8730
435            bakso    4.180491    6.448996   Topic5  -4.2528   2.8535
231             cuka    1.164110    1.859562   Topic5  -5.5313   2.8186
528            curry    1.004690    1.700209   Topic5  -5.6785   2.7609
618            tumis    1.004543    1.700409   Topic5  -5.6787   2.7606
578            takar    1.004427    1.700414   Topic5  -5.6788   2.7605
448            telor    0.905522    1.600895   Topic5  -5.7825   2.7171

Topic: 1
tepung, keju, telur, lihat, cair, resep, instan, ayam, giling, butir, sisa, kuning, chicken, bks, jeruk, powder, air, opsional, terigu, nipis, menggoreng, parut, baking, topping, pelengkap, sambal, sagu, daun, saledri, bubur

Topic: 2
bawang, daun, ruas, merah, siung, ayam, jeruk, putih, garam, bumbu, lembar, kunyit, jahe, salam, kemiri, cabe, bubuk, goreng, air, batang, butir, halus, gula, buah, kaldu, lengkuas, ketumbar, memarkan, serai, sangrai

Topic: 3
kkal, pcs, bolognese, sckupnya, digeprek, bihun, terasi, soto, rosemary, kerupuk, potongpotong, daun, garamkaldu, chillies, ingredients, leaf, khas, champignon, aslinya, herb, pepper, black, pns, seduh, segar, ulek, dipotong, ogut, makenya, pkenya

Topic: 4
pasta, mix, cheddar, spaghetti, cup, sayur, peres, tambahan, cheese, tsp, suwir, centong, lee, kum, kee, abc, uht, sejumput, dirajang, paste, alfredo, italian, penne, heavy, ubi, perasa, karbo, orak, bumtik, prona

Topic: 5
halus, cincang, buah, gram, bawang, wortel, garam, susu, ayam, nasi, matang, sayur, bombai, bubuk, kulit, sambel, pala, bakso, puyuh, lembar, kukus, merica, cream, kotak, margarin, ikat, pokcoy, full, cacah, tbsp

Topic: 6
buah, bawang, merah, cabe, siung, selera, daun, sesuai, ayam, tomat, rawit, cabai, putih, kentang, gram, bumbu, penyedap, jeruk, skip, iris, kerupuk, wortel, sendok, bombay, garam, kupas, gula, buncis, kental, pake

Topic: 7
bawang, ayam, putih, bubuk, siung, garam, kecap, saus, lada, air, kaldu, gula, manis, buah, tiram, cincang, tepung, bombay, iris, pasir, bumbu, fillet, saos, sachet, dada, gram, halus, jamur, goreng, tomat

[(0,
  '0.048*"tepung" + 0.034*"keju" + 0.026*"telur" + 0.024*"lihat" + 0.024*"cair" + 0.023*"resep" + 0.022*"instan" + 0.021*"ayam" + 0.019*"giling" + 0.018*"butir"'),
 (1,
  '0.059*"bawang" + 0.057*"daun" + 0.039*"ruas" + 0.037*"merah" + 0.036*"siung" + 0.035*"ayam" + 0.029*"jeruk" + 0.028*"putih" + 0.028*"garam" + 0.028*"bumbu"'),
 (2,
  '0.056*"kkal" + 0.032*"pcs" + 0.023*"bolognese" + 0.017*"sckupnya" + 0.012*"digeprek" + 0.012*"bihun" + 0.012*"terasi" + 0.012*"soto" + 0.010*"rosemary" + 0.009*"kerupuk"'),
 (3,
  '0.055*"pasta" + 0.034*"mix" + 0.028*"cheddar" + 0.024*"spaghetti" + 0.012*"cup" + 0.011*"sayur" + 0.011*"peres" + 0.010*"tambahan" + 0.008*"cheese" + 0.008*"tsp"'),
 (4,
  '0.033*"halus" + 0.031*"cincang" + 0.029*"buah" + 0.026*"gram" + 0.025*"bawang" + 0.025*"wortel" + 0.024*"garam" + 0.024*"susu" + 0.020*"ayam" + 0.019*"nasi"'),
 (5,
  '0.112*"buah" + 0.063*"bawang" + 0.041*"merah" + 0.032*"cabe" + 0.028*"siung" + 0.027*"selera" + 0.027*"daun" + 0.026*"sesuai" + 0.024*"ayam" + 0.020*"tomat"'),
 (6,
  '0.059*"bawang" + 0.048*"ayam" + 0.045*"putih" + 0.038*"bubuk" + 0.037*"siung" + 0.034*"garam" + 0.033*"kecap" + 0.029*"saus" + 0.025*"lada" + 0.025*"air"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
ayamSlnCpdProb = make_dictionary_terms_prob(ldamodel, id_map, d)
ayamSlnCpdProb["mee"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
ayamCpdSlnWN = dfWordnet.copy()

ayamCpdSlnWN["Synonym_clean"] = cleanWN_Synonym(ayamCpdSlnWN["Synonym"])
ayamCpdSlnWN["Hypernim_clean"] = cleanWN(ayamCpdSlnWN["Hypernim"])
ayamCpdSlnWN["Hyponim_clean"] = cleanWN(ayamCpdSlnWN["Hyponim"])
ayamCpdSlnWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/ayamSeleniumCookpad.owl")
makeOntology(ontoName, ayamCpdSlnWN)
ontoName.save(file = "ayamSeleniumCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1DgiR9ABRAki_Ut9SBfnCGwzquuhDCjEB"

In [ ]:
wiki_ayam_sln = pd.read_excel("AyamSlnCookpadFinal.xlsx").iloc[:, 1:]

# Translate
wiki_ayam_sln["Category"] = translate(wiki_ayam_sln["Category"])
wiki_ayam_sln.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_ayam_sln[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
ayamSlnTabel_new = tabel_1981.copy()
ayamSlnTabel_new["correct_category"] = all_cat
ayamSlnTabel_new["suggestion"] = all_suggestion

# Export Result to File
ayamSlnTabel_new.to_excel("ayamSlnTabel_Result.xlsx")
ayamSlnTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdSlnTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
ayamSlnTabel_new = concatListInColumn(ayamSlnTabel_new)
ayamSlnTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, ayamSlnTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_ayam_sln.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
ayamCpdSlnWiki_new = wiki_df.copy()
ayamCpdSlnWiki_new["suggest"] = all_cat

# Export Result to file
ayamCpdSlnWiki_new.to_excel("ayamCpdSlnWiki_Result.xlsx")
ayamCpdSlnWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdSlnWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
ayamCpdSlnOntoWiki = get_ontology("http://test.org/ayamCpdSln_onto_wiki.owl")
makeOntology_wiki(ayamCpdSlnOntoWiki, ayamCpdSlnWiki_new)
ayamCpdSlnOntoWiki.save(file = "ayamCpdSln_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = ayamCpdSlnWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
ayamCpdSlnWN_new = listToDataframe(changesList, tableWordnet)
ayamCpdSlnWN_new.to_excel("ayamCpdSlnWN_Result.xlsx")
ayamCpdSlnWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ayamCpdSlnWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Ikan - Cookpad

In [ ]:
!gdown --id "1xMuIl-GL3PIlXyyzhnW_SrJ35RNmlRYT"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1xMuIl-GL3PIlXyyzhnW_SrJ35RNmlRYT
To: /content/cookpad-selenium_ikan.jl
100% 406k/406k [00:00<00:00, 105MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
ikan_cpd=pd.read_json(r'/content/cookpad-selenium_ikan.jl', lines = True)
ikan_cpd = concat_bahan_langkah(ikan_cpd)

# fill NaN with empty string
ikan_cpd["page_description"] = ikan_cpd["page_description"].fillna("")

#save dalam acar biar ngebut loading ntar.
ikan_cpd.to_pickle(r'/content/raw_df.pkl')

# covnert page_description to list
ikan_cpd["temp"] = ikan_cpd["page_description"]
ikan_cpd["page_description"] = ikan_cpd["page_bahan_langkah"]

# # clean text
ikan_cpd = pre_cleaning_text(ikan_cpd, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
ikan_cpd.head()

,url_search,list_scraping_time,list_item_url,list_item_title,list_item_ingredients,list_item_author_name,list_item_author_image_url,list_item_image_url,page_scraping_time,page_image_url,...,page_serving_count,page_bahan,page_langkah,page_post_datetime,page_post_love_count,page_post_clap_count,page_post_tasty_count,page_comment_count,page_bahan_langkah,temp
0,https://cookpad.com/id/cari/ikan?event=search....,2022-06-24 21:59:20,https://cookpad.com/id/resep/16304096-steam-pa...,\n Steam Patin/Dori Saus Hongkong\n,"[fillet ikan patin/dori, jahe, iris korek, jer...",Elia Wahid,https://img-global.cpcdn.com/users/09905b79e3f...,https://img-global.cpcdn.com/recipes/19f92026f...,2022-06-24 21:59:22,https://img-global.cpcdn.com/recipes/19f92026f...,...,1-2 orang,"[Steam Ikan, 330 gram fillet ikan patin/dori, ...",[],24 Juni 2022 21.39,NaN,NaN,NaN,NaN,"[Steam Ikan, 330 gram fillet ikan patin/dori, ...",Ikan dori fillet yang saya dapati di penjual i...
1,https://cookpad.com/id/cari/ikan?event=search....,2022-06-24 21:59:20,https://cookpad.com/id/resep/16318606-salmon-m...,\n Salmon Mentai Rice\n,"[nasi putih, minyak wijen, serpihan nori, butt...",Iftitah Kurniasari,https://img-global.cpcdn.com/users/e6da63fd390...,https://img-global.cpcdn.com/recipes/8beb5f361...,2022-06-24 21:59:25,https://img-global.cpcdn.com/recipes/8beb5f361...,...,5 cup kecil,"[Nasi :, 300 gr nasi putih, 1/2 sdm minyak wij...",[],24 Juni 2022 16.48,2.0,NaN,NaN,NaN,"[Nasi :, 300 gr nasi putih, 1/2 sdm minyak wij...",Ibu ibu biasanya pusing anaknya belum makan na...
2,https://cookpad.com/id/cari/ikan?event=search....,2022-06-24 21:59:20,https://cookpad.com/id/resep/16084408-382-onig...,\n 382. 🍙 Onigiri Tuna mayo\n,"[nasi, mirin (me: Skip), minyak wijen, tuna, m...",Intan Zahra Al Arsyad (Bunda'Reycha),https://img-global.cpcdn.com/users/51213d3b636...,https://img-global.cpcdn.com/recipes/11f187f70...,2022-06-24 21:59:48,https://img-global.cpcdn.com/recipes/11f187f70...,...,None,"[3-4 piring nasi, 3 Sdm mirin (me: Skip), 1 sd...",[],24 Juni 2022 16.55,1.0,1.0,1.0,NaN,"[3-4 piring nasi, 3 Sdm mirin (me: Skip), 1 sd...",Bismillah.. \n
3,https://cookpad.com/id/cari/ikan?event=search....,2022-06-24 21:59:20,https://cookpad.com/id/resep/15881149-orak-ari...,\n Orak arik Tongkol Pedas\n,"[pindang tongkol suwir2, air, bawang merah, ba...",abuk irun,https://img-global.cpcdn.com/users/5e66d2681bd...,https://img-global.cpcdn.com/recipes/c15b57a71...,2022-06-24 21:59:56,https://img-global.cpcdn.com/recipes/c15b57a71...,...,None,"[4 ekor pindang tongkol suwir2, 100 ml air, Bu...",[],24 Juni 2022 16.03,4.0,4.0,1.0,NaN,"[4 ekor pindang tongkol suwir2, 100 ml air, Bu...",Bismillah..
4,https://cookpad.com/id/cari/ikan?event=search....,2022-06-24 21:59:20,https://cookpad.com/id/resep/16327000-pesmol-i...,\n Pesmol Ikan Nila\n,"[Ikan nila, Jeruk nipis, bawang merah, bawang ...",Rika Veronica,https://img-global.cpcdn.com/users/13a5c22dd28...,https://img-global.cpcdn.com/recipes/df50848d6...,2022-06-24 22:00:31,https://img-global.cpcdn.com/recipes/df50848d6...,...,None,"[Ikan nila, Jeruk nipis, Bumbu halus:, 8 siung...",[],24 Juni 2022 16.25,NaN,NaN,NaN,NaN,"[Ikan nila, Jeruk nipis, Bumbu halus:, 8 siung...",

## GUI Ikan - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = ikan_cpd.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
5      0.293113  0.072557       1        1  58.380772
4      0.203877 -0.060639       2        1  18.874425
6     -0.100290 -0.172096       3        1  10.324474
1      0.108877 -0.010352       4        1   5.104438
0     -0.156954  0.269474       5        1   3.121851
3     -0.175202 -0.055601       6        1   2.835980
2     -0.173422 -0.043344       7        1   1.358061, topic_info=                    Term        Freq       Total Category  logprob  loglift
8                   buah  267.000000  267.000000  Default  30.0000  30.0000
65                  cabe  138.000000  138.000000  Default  29.0000  29.0000
30                  daun  194.000000  194.000000  Default  28.0000  28.0000
1                   ikan  146.000000  146.000000  Default  27.0000  27.0000
28                 merah  245.000000  245.000000  Default  26.0000  26.0000
66                 rawit   75.000000   75.000000  Default  25.0000  25.0000
6                   iris   58.000000   58.000000  Default  24.0000  24.0000
97                selera   43.000000   43.000000  Default  23.0000  23.0000
138               tepung   51.000000   51.000000  Default  22.0000  22.0000
17                   air   99.000000   99.000000  Default  21.0000  21.0000
168                makan   34.000000   34.000000  Default  20.0000  20.0000
14                bawang  302.000000  302.000000  Default  19.0000  19.0000
507              sckpnya   33.000000   33.000000  Default  18.0000  18.0000
96                sesuai   28.000000   28.000000  Default  17.0000  17.0000
41                 bubuk   93.000000   93.000000  Default  16.0000  16.0000
150                 ikat   24.000000   24.000000  Default  15.0000  15.0000
39                 garam  164.000000  164.000000  Default  14.0000  14.0000
67              keriting   45.000000   45.000000  Default  13.0000  13.0000
118              kemangi   28.000000   28.000000  Default  12.0000  12.0000
125               merica   36.000000   36.000000  Default  11.0000  11.0000
13                 siung  182.000000  182.000000  Default  10.0000  10.0000
69                 resep   15.000000   15.000000  Default   9.0000   9.0000
88                lembar   84.000000   84.000000  Default   8.0000   8.0000
68                 lihat   15.000000   15.000000  Default   7.0000   7.0000
74                  ruas  127.000000  127.000000  Default   6.0000   6.0000
31                 tipis   24.000000   24.000000  Default   5.0000   5.0000
44                 tomat   83.000000   83.000000  Default   4.0000   4.0000
10                 nipis   51.000000   51.000000  Default   3.0000   3.0000
201               ukuran   47.000000   47.000000  Default   2.0000   2.0000
71                 halus   62.000000   62.000000  Default   1.0000   1.0000
74                  ruas  126.481357  127.072551   Topic1  -3.4386   0.5335
89                 salam   74.027128   74.615728   Topic1  -3.9742   0.5303
27                 cabai   61.613955   62.203368   Topic1  -4.1578   0.5287
92              lengkuas   60.326922   60.914607   Topic1  -4.1789   0.5285
73                kemiri   52.199856   52.787494   Topic1  -4.3236   0.5270
79                 serai   39.959188   40.547203   Topic1  -4.5908   0.5236
206               sendok   36.108407   36.705368   Topic1  -4.6921   0.5218
87                geprek   30.272591   30.860046   Topic1  -4.8684   0.5190
76                kunyit   72.008895   73.485190   Topic1  -4.0019   0.5179
313             cakalang   27.888324   28.478537   Topic1  -4.9505   0.5172
62               tongkol   25.464634   26.052503   Topic1  -5.0414   0.5154
30                  daun  189.441246  194.086153   Topic1  -3.0346   0.5140
372                 utuh   22.639564   23.227207   Topic1  -5.1590   0.5126
80                   lbr   22.293438   22.880710   Topic1  -5.1744   0.5122
116                sereh   21.079466   21.666739   Topic1  -5.2304   0.5107
28                 merah  237.326793  245.470565   Topic1  -2.8092   0.5044
527                  amp   15.104820   15.694064   Topic1  -5.5637   0.4999
70                  nila   13.496725   14.084364   Topic1  -5.6762   0.4956
48               sangrai   12.045097   12.670315   Topic1  -5.7900   0.4876
257               kencur   11.266937   11.854444   Topic1  -5.8568   0.4874
86                instan    9.681050   10.268622   Topic1  -6.0085   0.4793
81                  gula   94.580914  100.365791   Topic1  -3.7292   0.4788
75                  jari   35.203871   37.490079   Topic1  -4.7175   0.4753
570                  aja    7.897231    8.484610   Topic1  -6.2122   0.4664
552            segenggam    7.895073    8.483722   Topic1  -6.2124   0.4663
504                  cup    7.772105    8.360645   Topic1  -6.2281   0.4652
445                 uleg    7.649656    8.236881   Topic1  -6.2440   0.4642
121               santan   28.972953   31.274286   Topic1  -4.9123   0.4618
628            tulangnya    6.757989    7.344876   Topic1  -6.3679   0.4549
578                 kari    6.756527    7.344807   Topic1  -6.3682   0.4547
5                   jahe   51.358145   55.850058   Topic1  -4.3398   0.4543
66                 rawit   67.247752   75.909139   Topic1  -4.0703   0.4170
115               batang   62.777663   71.136120   Topic1  -4.1391   0.4132
13                 siung  152.863455  182.181730   Topic1  -3.2491   0.3627
72                 butir   83.780194   97.781303   Topic1  -3.8505   0.3836
64                 bumbu  102.261639  121.148454   Topic1  -3.6511   0.3687
126             ketumbar   31.573148   35.816283   Topic1  -4.8264   0.4121
8                   buah  205.967349  267.316958   Topic1  -2.9510   0.2775
14                bawang  230.535040  302.736713   Topic1  -2.8383   0.2657
88                lembar   69.921710   84.267335   Topic1  -4.0313   0.3516
9                  jeruk   92.452805  115.671869   Topic1  -3.7520   0.3141
65                  cabe  107.635520  138.461557   Topic1  -3.5999   0.2863
15                 putih  117.653689  167.431932   Topic1  -3.5109   0.1854
67              keriting   39.065844   45.606003   Topic1  -4.6134   0.3834
60                  ekor   57.946905   74.284582   Topic1  -4.2191   0.2898
39                 garam  104.070191  164.187213   Topic1  -3.6336   0.0822
1                   ikan   85.876492  146.003040   Topic1  -3.8258   0.0075
44                 tomat   56.716479   83.975720   Topic1  -4.2406   0.1457
127             penyedap   39.032963   47.652062   Topic1  -4.6143   0.3387
71                 halus   41.596479   62.559629   Topic1  -4.5507   0.1301
17                   air   41.997245   99.701421   Topic1  -4.5411  -0.3264
138               tepung   50.513822   51.106443   Topic2  -3.2272   1.6557
125               merica   35.724212   36.317285   Topic2  -3.5737   1.6509
128                 saos   21.809677   22.402915   Topic2  -4.0671   1.6405
200                pakai   18.544244   19.137909   Topic2  -4.2293   1.6359
132               adonan   17.930134   18.522304   Topic2  -4.2630   1.6349
319              maizena   15.587286   16.179782   Topic2  -4.4030   1.6301
18                 tiram   13.730016   14.329626   Topic2  -4.5299   1.6246
559         potongpotong   12.250572   12.843327   Topic2  -4.6439   1.6201
197               serong   12.645486   13.264950   Topic2  -4.6122   1.6195
777                basah   11.706899   12.299069   Topic2  -4.6893   1.6180
778               kompas   11.706899   12.299069   Topic2  -4.6893   1.6180
3                 fillet   24.442409   25.687399   Topic2  -3.9532   1.6177
134             tenggiri   10.452354   11.045335   Topic2  -4.8027   1.6122
357                pedas    9.781881   10.382763   Topic2  -4.8690   1.6077
312              tangkai    9.245112    9.838360   Topic2  -4.9254   1.6052
29             memanjang    9.008693    9.601562   Topic2  -4.9513   1.6036
674                liter    6.997605    7.590371   Topic2  -5.2039   1.5860
199               kerapu    6.879207    7.471819   Topic2  -5.2210   1.5847
779                  aga    5.909576    6.501746   Topic2  -5.3729   1.5719
776              diseduh    5.909189    6.501727   Topic2  -5.3730   1.5718
774          tongkolsure    5.909091    6.501768   Topic2  -5.3730   1.5718
775                sunti    5.909091    6.501768   Topic2  -5.3730   1.5718
139               terigu    4.962777    5.555474   Topic2  -5.5475   1.5545
174              tapioka    4.181357    4.774573   Topic2  -5.7189   1.5347
293                 lele    3.563345    4.159031   Topic2  -5.8788   1.5128
135                 sagu    3.448079    4.040996   Topic2  -5.9117   1.5087
16               cincang   17.906853   21.196486   Topic2  -4.2643   1.4987
2                   gram   12.952188   15.443554   Topic2  -4.5882   1.4914
365                  teh    2.713749    3.307459   Topic2  -6.1512   1.4695
318               giling    2.478355    3.070738   Topic2  -6.2419   1.4530
110               kering    7.208326    9.002643   Topic2  -5.1743   1.4451
11                  saus   15.255191   20.728264   Topic2  -4.4246   1.3608
17                   air   56.008900   99.701421   Topic2  -3.1240   1.0907
41                 bubuk   52.302737   93.009455   Topic2  -3.1924   1.0917
180                 asam   16.343291   25.832438   Topic2  -4.3557   1.2095
10                 nipis   25.583170   51.138558   Topic2  -3.9076   0.9748
39                 garam   51.529061  164.187213   Topic2  -3.2073   0.5085
14                bawang   67.280394  302.736713   Topic2  -2.9406   0.1634
15                 putih   43.530220  167.431932   Topic2  -3.3760   0.3202
368               matang    8.086664   10.825400   Topic2  -5.0593   1.3757
321             marinasi   10.726372   17.314784   Topic2  -4.7768   1.1885
1                   ikan   38.394236  146.003040   Topic2  -3.5016   0.3316
6                   iris   20.012179   58.412464   Topic2  -4.1531   0.5962
326             memarkan   11.018692   19.037653   Topic2  -4.7499   1.1205
8                   buah   35.339338  267.316958   Topic2  -3.5845  -0.3561
44                 tomat   20.107127   83.975720   Topic2  -4.1484   0.2379
13                 siung   23.207314  182.181730   Topic2  -4.0050  -0.3932
9                  jeruk   18.626407  115.671869   Topic2  -4.2249  -0.1588
60                  ekor   15.828565   74.284582   Topic2  -4.3877   0.1213
71                 halus   15.076500   62.559629   Topic2  -4.4364   0.2444
64                 bumbu   16.801170  121.148454   Topic2  -4.3280  -0.3082
168                makan   33.580475   34.147903   Topic3  -3.0323   2.2539
507              sckpnya   32.745557   33.309264   Topic3  -3.0574   2.2536
32                  nasi   17.283957   17.847059   Topic3  -3.6964   2.2386
402               orange   16.052857   16.616688   Topic3  -3.7703   2.2361
31                 tipis   23.447468   24.301971   Topic3  -3.3914   2.2349
224              daunnya   10.089042   10.653040   Topic3  -4.2348   2.2163
292                panas    9.918746   10.498974   Topic3  -4.2518   2.2138
406                tusuk    9.400200    9.963771   Topic3  -4.3055   2.2124
407                 gigi    8.710716    9.274305   Topic3  -4.3816   2.2080
349             singkong    8.017754    8.584086   Topic3  -4.4645   2.2024
36                salmon    6.524905    7.087747   Topic3  -4.6706   2.1879
34                  nori    5.836199    6.398584   Topic3  -4.7821   2.1787
355             sejumput    4.514890    5.079419   Topic3  -5.0388   2.1528
153             haluskan    4.365058    4.929386   Topic3  -5.0726   2.1491
385                 cuci    3.977070    4.540420   Topic3  -5.1657   2.1382
386               bersih    3.977070    4.540420   Topic3  -5.1657   2.1382
178                sayur    9.932735   11.393958   Topic3  -4.2504   2.1334
37                butter    3.826989    4.390449   Topic3  -5.2041   2.1333
193                porsi    3.826567    4.390196   Topic3  -5.2042   2.1332
183               kacang    3.676591    4.240337   Topic3  -5.2442   2.1280
352               pandan    8.236458    9.513798   Topic3  -4.4376   2.1265
494               diiris    3.438125    4.001211   Topic3  -5.3113   2.1190
291                limau    3.427165    3.996467   Topic3  -5.3145   2.1170
395                sushi    3.139151    3.701458   Topic3  -5.4022   2.1059
50                piring    3.138041    3.701215   Topic3  -5.4026   2.1056
187                  kol    3.137902    3.701167   Topic3  -5.4026   2.1056
441                bakso    3.134252    3.700199   Topic3  -5.4038   2.1047
21                 wijen    8.628103   10.204193   Topic3  -4.3912   2.1029
45                  keju    2.599094    3.161820   Topic3  -5.5910   2.0747
282             opsional    2.598724    3.161795   Topic3  -5.5912   2.0745
53                  tuna   10.436567   13.307969   Topic3  -4.2009   2.0276
225            belimbing    8.344298   10.637519   Topic3  -4.4246   2.0278
49              optional    9.963528   20.497620   Topic3  -4.2473   1.5493
102                telur    8.357245   18.235859   Topic3  -4.4231   1.4904
47                  skip   10.777016   27.745020   Topic3  -4.1688   1.3250
100               wortel    5.719267   10.184049   Topic3  -4.8024   1.6937
23                 kaldu   11.362527   45.386658   Topic3  -4.1159   0.8858
88                lembar   12.815335   84.267335   Topic3  -3.9956   0.3873
24                 jamur    7.292223   23.024769   Topic3  -4.5594   1.1209
72                 butir    9.406215   97.781303   Topic3  -4.3048  -0.0707
113               pisang    4.931510   12.113430   Topic3  -4.9506   1.3720
22                  asin    5.008529   13.402575   Topic3  -4.9351   1.2863
63                 suwir    5.463923   23.206903   Topic3  -4.8480   0.8244
41                 bubuk    6.938406   93.009455   Topic3  -4.6091  -0.3250
1                   ikan    6.852678  146.003040   Topic3  -4.6216  -0.7883
15                 putih    5.913750  167.431932   Topic3  -4.7689  -1.0726
115               batang    5.115163   71.136120   Topic3  -4.9140  -0.3617
413             irisiris   10.486731   11.094196   Topic4  -3.4917   2.9187
156              kembung    9.462574   10.071952   Topic4  -3.5944   2.9126
354                 dadu    7.255017    7.862975   Topic4  -3.8601   2.8946
369               sachet    6.311521    6.922521   Topic4  -3.9994   2.8827
785                 sate    5.107774    5.715243   Topic4  -4.2110   2.8627
248                bamer    2.244236    2.852170   Topic4  -5.0334   2.7353
249                baput    2.244236    2.852170   Topic4  -5.0334   2.7353
632                racik    1.978095    2.586238   Topic4  -5.1597   2.7070
353               seruas    1.671614    2.279334   Topic4  -5.3280   2.6650
429                  abc    1.405921    2.013495   Topic4  -5.5011   2.6159
317              kentang    1.404718    2.013868   Topic4  -5.5020   2.6148
315               sarden    4.587891    6.688846   Topic4  -4.3184   2.5980
268                  utk    7.936654   11.621500   Topic4  -3.7703   2.5937
265                kocok    1.302864    1.911265   Topic4  -5.5772   2.5919
556                tauco    1.037736    1.645367   Topic4  -5.8048   2.5141
171               dencis    0.934748    1.543176   Topic4  -5.9093   2.4737
222                kanji    0.930022    1.543905   Topic4  -5.9143   2.4682
167                 cuka    3.075762    5.222537   Topic4  -4.7182   2.4456
428              spageti    0.833092    1.440676   Topic4  -6.0244   2.4273
421                saset    0.832586    1.440831   Topic4  -6.0250   2.4266
300                telor    1.404539    2.593417   Topic4  -5.5021   2.3618
141           menggoreng    2.312672    4.544862   Topic4  -5.0034   2.2995
96                sesuai   14.610592   28.955906   Topic4  -3.1600   2.2910
711              belanak    0.567440    1.174895   Topic4  -6.4084   2.2473
712           masakgaram    0.567440    1.174895   Topic4  -6.4084   2.2473
682               mangga    0.567405    1.174902   Topic4  -6.4085   2.2472
554             nilabisa    0.567224    1.174934   Topic4  -6.4088   2.2468
555             kakapdll    0.567224    1.174934   Topic4  -6.4088   2.2468
557              tingkat    0.567224    1.174934   Topic4  -6.4088   2.2468
558             pedasnya    0.567224    1.174934   Topic4  -6.4088   2.2468
52                kaleng    3.657405    9.432667   Topic4  -4.5450   2.0276
169                 sasa    1.314872    2.997988   Topic4  -5.5681   2.1509
97                selera   13.253319   43.125656   Topic4  -3.2575   1.7952
240                lemon    2.220527    5.634398   Topic4  -5.0440   2.0439
321             marinasi    5.401894   17.314784   Topic4  -4.1550   1.8102
6                   iris   14.409436   58.412464   Topic4  -3.1739   1.5754
65                  cabe   20.882410  138.461557   Topic4  -2.8029   1.0834
8                   buah   25.357304  267.316958   Topic4  -2.6087   0.6197
1                   ikan   14.642836  146.003040   Topic4  -3.1578   0.6754
66                 rawit    8.170427   75.909139   Topic4  -3.7413   0.7460
67              keriting    6.048529   45.606003   Topic4  -4.0420   0.9548
201               ukuran    6.007218   47.783270   Topic4  -4.0488   0.9013
71                 halus    5.507565   62.559629   Topic4  -4.1357   0.5451
44                 tomat    6.083497   83.975720   Topic4  -4.0362   0.3501
10                 nipis    4.739021   51.138558   Topic4  -4.2860   0.5964
13                 siung    5.728976  182.181730   Topic4  -4.0963  -0.4844
39                 garam    5.221565  164.187213   Topic4  -4.1890  -0.4732
28                 merah    5.264153  245.470565   Topic4  -4.1809  -0.8672
9                  jeruk    4.167541  115.671869   Topic4  -4.4145  -0.3484
14                bawang    3.574112  302.736713   Topic4  -4.5681  -1.4641
381               terasi    2.331632   10.990832   Topic4  -4.9952   1.4246
69                 resep   14.747547   15.398211   Topic5  -2.6590   3.4236
68                 lihat   14.597568   15.247923   Topic5  -2.6693   3.4232
765            melintang    5.714495    6.364898   Topic5  -3.6071   3.3590
767               rajang    5.714495    6.364898   Topic5  -3.6071   3.3590
540                gelas    3.946772    4.598052   Topic5  -3.9772   3.3140
284                ambil    3.889273    4.540136   Topic5  -3.9919   3.3120
331              perasan    3.882603    4.547241   Topic5  -3.9936   3.3087
599                rebus    3.415473    4.066752   Topic5  -4.1218   3.2922
523            dagingnya    3.150223    3.800480   Topic5  -4.2026   3.2791
635                petik    3.150202    3.800560   Topic5  -4.2026   3.2791
360              genggam    4.018445    4.911086   Topic5  -3.9592   3.2661
780                serei    2.884614    3.534733   Topic5  -4.2907   3.2635
781               kosong    2.884614    3.534733   Topic5  -4.2907   3.2635
782                penuh    2.884545    3.534734   Topic5  -4.2907   3.2635
783               bimoli    2.884545    3.534734   Topic5  -4.2907   3.2635
784                  unt    2.884545    3.534734   Topic5  -4.2907   3.2635
762             bongggol    2.884464    3.534899   Topic5  -4.2908   3.2634
763           besarbuang    2.884464    3.534899   Topic5  -4.2908   3.2634
764          bijinyairis    2.884464    3.534899   Topic5  -4.2908   3.2634
766                kucai    2.884464    3.534899   Topic5  -4.2908   3.2634
768             skipbisa    2.884464    3.534899   Topic5  -4.2908   3.2634
769                  iii    2.884464    3.534899   Topic5  -4.2908   3.2634
770              segepok    2.884464    3.534899   Topic5  -4.2908   3.2634
771           membungkus    2.884464    3.534899   Topic5  -4.2908   3.2634
772                 tali    2.884464    3.534899   Topic5  -4.2908   3.2634

Topic: 1
resep, lihat, ikat, melintang, rajang, kemangi, mas, daun, genggam, gelas, ambil, perasan, rebus, memarkan, dagingnya, petik, sobek, serei, kosong, penuh, bimoli, unt, besarbuang, skipbisa, lidi, bongggol, tali, bijinyairis, segepok, membungkus

Topic: 2
buah, cabe, ikan, sesuai, iris, selera, irisiris, kembung, rawit, utk, dadu, sachet, tomat, keriting, ukuran, siung, halus, marinasi, merah, garam, sate, nipis, sarden, jeruk, kaleng, bawang, cuka, terasi, menggoreng, bamer

Topic: 3
kakap, sambal, wuluh, serbaguna, bombay, belimbing, extra, ditambahdikurangi, mas, telor, kepala, tumis, jenis, dgn, korek, wader, matahari, bunga, himalaya, seraigeprek, sisiknya, kandis, lmbr, grm, dikurangisecukupnya, gereh, talang, susai, kakdu, teriyaki

Topic: 4
serut, kecap, manis, tujuan, kaleng, bawal, margarin, sesukanya, asin, menyesuaikan, lemon, oil, merk, gram, basic, olive, madu, sambal, sarden, timun, irisan, blackpepper, bombay, ditambah, selada, kubis, ceplok, saori, bebas, spaghetti

Topic: 5
bawang, air, bubuk, garam, tepung, putih, ikan, merica, buah, nipis, fillet, siung, saos, tomat, iris, jeruk, pakai, adonan, cincang, bumbu, asam, ekor, maizena, saus, halus, tiram, gram, serong, potongpotong, basah

Topic: 6
merah, bawang, buah, daun, siung, ruas, putih, cabe, garam, bumbu, gula, jeruk, ikan, butir, salam, kunyit, lembar, rawit, batang, cabai, lengkuas, ekor, tomat, kemiri, jahe, air, halus, serai, keriting, penyedap

Topic: 7
makan, sckpnya, tipis, nasi, orange, lembar, kaldu, skip, tuna, daunnya, optional, sayur, panas, butir, tusuk, gigi, wijen, telur, belimbing, pandan, singkong, jamur, bubuk, ikan, salmon, putih, nori, wortel, suwir, batang

[(0,
  '0.070*"resep" + 0.069*"lihat" + 0.034*"ikat" + 0.027*"melintang" + 0.027*"rajang" + 0.020*"kemangi" + 0.020*"mas" + 0.019*"daun" + 0.019*"genggam" + 0.019*"gelas"'),
 (1,
  '0.074*"buah" + 0.061*"cabe" + 0.043*"ikan" + 0.042*"sesuai" + 0.042*"iris" + 0.038*"selera" + 0.030*"irisiris" + 0.027*"kembung" + 0.024*"rawit" + 0.023*"utk"'),
 (2,
  '0.065*"kakap" + 0.063*"sambal" + 0.052*"wuluh" + 0.036*"serbaguna" + 0.025*"bombay" + 0.020*"belimbing" + 0.011*"extra" + 0.008*"ditambahdikurangi" + 0.007*"mas" + 0.007*"telor"'),
 (3,
  '0.033*"serut" + 0.032*"kecap" + 0.024*"manis" + 0.018*"tujuan" + 0.015*"kaleng" + 0.014*"bawal" + 0.014*"margarin" + 0.012*"sesukanya" + 0.012*"asin" + 0.012*"menyesuaikan"'),
 (4,
  '0.053*"bawang" + 0.044*"air" + 0.041*"bubuk" + 0.040*"garam" + 0.040*"tepung" + 0.034*"putih" + 0.030*"ikan" + 0.028*"merica" + 0.028*"buah" + 0.020*"nipis"'),
 (5,
  '0.060*"merah" + 0.059*"bawang" + 0.052*"buah" + 0.048*"daun" + 0.039*"siung" + 0.032*"ruas" + 0.030*"putih" + 0.027*"cabe" + 0.026*"garam" + 0.026*"bumbu"'),
 (6,
  '0.048*"makan" + 0.047*"sckpnya" + 0.034*"tipis" + 0.025*"nasi" + 0.023*"orange" + 0.018*"lembar" + 0.016*"kaldu" + 0.015*"skip" + 0.015*"tuna" + 0.014*"daunnya"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
ikanCpdProb = make_dictionary_terms_prob(ldamodel, id_map, d)
ikanCpdProb["mee"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
ikanCpdWN = dfWordnet.copy()

ikanCpdWN["Synonym_clean"] = cleanWN_Synonym(ikanCpdWN["Synonym"])
ikanCpdWN["Hypernim_clean"] = cleanWN(ikanCpdWN["Hypernim"])
ikanCpdWN["Hyponim_clean"] = cleanWN(ikanCpdWN["Hyponim"])
ikanCpdWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/ikanCookpad.owl")
makeOntology(ontoName, ikanCpdWN)
ontoName.save(file = "ikanCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1Ar_A-vPp8TWorA1BsEQjWR8cf1RE6GI4"

In [ ]:
wiki_ikan_cpd = pd.read_excel("IkanCookpadFinal.xlsx").iloc[:, 1:]

# Translate
wiki_ikan_cpd["Category"] = translate(wiki_ikan_cpd["Category"])
wiki_ikan_cpd.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_ikan_cpd[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
ikanCpdTabel_new = tabel_1981.copy()
ikanCpdTabel_new["correct_category"] = all_cat
ikanCpdTabel_new["suggestion"] = all_suggestion

# Export Result to File
ikanCpdTabel_new.to_excel("ikanCpdTabel_Result.xlsx")
ikanCpdTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanCpdTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
ikanCpdTabel_new = concatListInColumn(ikanCpdTabel_new)
ikanCpdTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, ikanCpdTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_ikan_cpd.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
ikanCpdWiki_new = wiki_df.copy()
ikanCpdWiki_new["suggest"] = all_cat

# Export Result to file
ikanCpdWiki_new.to_excel("ikanCpdWiki_Result.xlsx")
ikanCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
ikanCpdOntoWiki = get_ontology("http://test.org/ikanCpd_onto_wiki.owl")
makeOntology_wiki(ikanCpdOntoWiki, ikanCpdWiki_new)
ikanCpdOntoWiki.save(file = "ikanCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = ikanCpdWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
ikanCpdWN_new = listToDataframe(changesList, tableWordnet)
ikanCpdWN_new.to_excel("ikanCpdWN_Result.xlsx")
ikanCpdWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "ikanCpdWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Kambing - Cookpad

In [ ]:
!gdown --id "1ccVQ68WN2fmGRvPO8_3JUhRNZ6Uy3cie"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1ccVQ68WN2fmGRvPO8_3JUhRNZ6Uy3cie
To: /content/cookpad-selenium_kambing.jl
100% 434k/434k [00:00<00:00, 50.4MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
kambing_cpd=pd.read_json(r'/content/cookpad-selenium_kambing.jl', lines = True)
kambing_cpd = concat_bahan_langkah(kambing_cpd)

# fill NaN with empty string
kambing_cpd["page_description"] = kambing_cpd["page_description"].fillna("")

#save dalam acar biar ngebut loading ntar.
kambing_cpd.to_pickle(r'/content/raw_df.pkl')

# covnert page_description to list
kambing_cpd["temp"] = kambing_cpd["page_description"]
kambing_cpd["page_description"] = kambing_cpd["page_bahan_langkah"]

# # clean text
kambing_cpd = pre_cleaning_text(kambing_cpd, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
kambing_cpd.head()

,url_search,list_scraping_time,list_item_url,list_item_title,list_item_ingredients,list_item_author_name,list_item_author_image_url,list_item_image_url,page_scraping_time,page_image_url,...,page_serving_count,page_bahan,page_langkah,page_post_datetime,page_post_love_count,page_post_clap_count,page_post_tasty_count,page_comment_count,page_bahan_langkah,temp
0,https://cookpad.com/id/cari/kambing?event=sear...,2022-06-24 22:34:41,https://cookpad.com/id/resep/16326243-nasi-bri...,\n Nasi Briyani Daging Kambing\n,"[daging kambing dg tulang, Bumbu marinasi dagi...",Um Syara,https://img-global.cpcdn.com/users/ae4b45294af...,https://img-global.cpcdn.com/recipes/f8cf1e21b...,2022-06-24 22:35:00,https://img-global.cpcdn.com/recipes/f8cf1e21b...,...,None,"[20 potong daging kambing dg tulang, Bumbu mar...",[],24 Juni 2022 12.20,3.0,3.0,2.0,NaN,"[20 potong daging kambing dg tulang, Bumbu mar...",
1,https://cookpad.com/id/cari/kambing?event=sear...,2022-06-24 22:34:41,https://cookpad.com/id/resep/16325562-sup-kaki...,\n Sup kaki kambing seger mantap\n,"[Kaki Kambing yang sudah dibakar dan bersih, W...",Ana,https://img-global.cpcdn.com/users/6d0ca1474cc...,https://img-global.cpcdn.com/recipes/2008d4583...,2022-06-24 22:35:17,https://img-global.cpcdn.com/recipes/2008d4583...,...,8 porsi,[1 kg Kaki Kambing yang sudah dibakar dan bers...,[],24 Juni 2022 02.49,6.0,5.0,5.0,NaN,[1 kg Kaki Kambing yang sudah dibakar dan bers...,Berawal dari si bocil yg sudah bosan dg ikan d...
2,https://cookpad.com/id/cari/kambing?event=sear...,2022-06-24 22:34:41,https://cookpad.com/id/resep/15311012-krengsen...,\n Krengsengan Daging Kambing🧆\n,[daging kambing (rebus dengan daun salam dan s...,Anggela Ayik,https://img-global.cpcdn.com/users/90e1df0754a...,https://img-global.cpcdn.com/recipes/5247f8800...,2022-06-24 22:35:32,https://img-global.cpcdn.com/recipes/5247f8800...,...,None,[500 gr daging kambing (rebus dengan daun sala...,[],22 Juni 2022 07.04,8.0,3.0,1.0,NaN,[500 gr daging kambing (rebus dengan daun sala...,"Ini di masak sampai bener2 air menyusut yak, k..."
3,https://cookpad.com/id/cari/kambing?event=sear...,2022-06-24 22:34:41,https://cookpad.com/id/resep/13311878-nasi-keb...,\n Nasi kebuli kambing homemade\n,"[daging kambing, Santan 700ml (saya pake fiber...",Wahida _BundaMufida&Royyan,https://img-global.cpcdn.com/users/37b18e865a6...,https://img-global.cpcdn.com/recipes/ea4a16b1d...,2022-06-24 22:35:54,https://img-global.cpcdn.com/recipes/ea4a16b1d...,...,10 porsi,"[1/2 kg daging kambing, Santan 700ml (saya pak...",[],22 Juni 2022 12.57,4.0,NaN,1.0,NaN,"[1/2 kg daging kambing, Santan 700ml (saya pak...","Anak2 paling suka yang namanya nasi kebuli, na..."
4,https://cookpad.com/id/cari/kambing?event=sear...,2022-06-24 22:34:41,https://cookpad.com/id/resep/16311977-sup-kamb...,\n Sup Kambing + Sambal Kecap\n,"[kambing (daging, tulang, hati, lemak), kentan...",Fadilla Hanum,https://img-global.cpcdn.com/users/f0323be2404...,https://img-global.cpcdn.com/recipes/e9b8a602d...,2022-06-24 22:35:58,https://img-global.cpcdn.com/recipes/e9b8a602d...,...,3-4 orang,"[1/4 kg kambing (daging, tulang, hati, lemak),...",[],18 Juni 2022 07.03,4.0,2.0,1.0,NaN,"[1/4 kg kambing (daging, tulang, hati, lemak),...",Seorang mahasiswi yg sedang belajar memasak su...

## GUI Kambing - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = kambing_cpd.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
3      0.283459 -0.024202       1        1  80.907188
4     -0.110744  0.067709       2        1   6.027193
1      0.062374  0.259563       3        1   5.369491
2      0.169723 -0.099032       4        1   4.361796
5     -0.061617 -0.181928       5        1   1.888576
6     -0.183758 -0.009935       6        1   0.767004
0     -0.159437 -0.012175       7        1   0.678753, topic_info=                     Term        Freq       Total Category  logprob  loglift
30                   daun  325.000000  325.000000  Default  30.0000  30.0000
81                   ruas  164.000000  164.000000  Default  29.0000  29.0000
34                 bawang  484.000000  484.000000  Default  28.0000  28.0000
29                 lembar  176.000000  176.000000  Default  27.0000  27.0000
27                 batang  143.000000  143.000000  Default  26.0000  26.0000
31                  salam  130.000000  130.000000  Default  25.0000  25.0000
60                   jari   69.000000   69.000000  Default  24.0000  24.0000
207                geprek   81.000000   81.000000  Default  23.0000  23.0000
1                 kambing  218.000000  218.000000  Default  22.0000  22.0000
122                 sereh   58.000000   58.000000  Default  21.0000  21.0000
25                  butir  133.000000  133.000000  Default  20.0000  20.0000
23                   biji   60.000000   60.000000  Default  19.0000  19.0000
38                  putih  219.000000  219.000000  Default  18.0000  18.0000
7                   garam  193.000000  193.000000  Default  17.0000  17.0000
78                  halus  122.000000  122.000000  Default  16.0000  16.0000
39                   jahe  125.000000  125.000000  Default  15.0000  15.0000
151              lengkuas   66.000000   66.000000  Default  14.0000  14.0000
3                   bumbu  224.000000  224.000000  Default  13.0000  13.0000
59                  manis  140.000000  140.000000  Default  12.0000  12.0000
58                   kayu   65.000000   65.000000  Default  11.0000  11.0000
24               kapulaga   55.000000   55.000000  Default  10.0000  10.0000
26                cengkeh   56.000000   56.000000  Default   9.0000   9.0000
18                 kunyit  108.000000  108.000000  Default   8.0000   8.0000
130                sendok   31.000000   31.000000  Default   7.0000   7.0000
82                 santan   67.000000   67.000000  Default   6.0000   6.0000
16                   lada   57.000000   57.000000  Default   5.0000   5.0000
32               penyedap   46.000000   46.000000  Default   4.0000   4.0000
55                   pala   60.000000   60.000000  Default   3.0000   3.0000
57                  jeruk  122.000000  122.000000  Default   2.0000   2.0000
15               ketumbar  107.000000  107.000000  Default   1.0000   1.0000
79                  siung  271.404294  271.886168   Topic1  -3.3124   0.2101
35                  merah  332.792828  333.579272   Topic1  -3.1084   0.2095
0                  daging  190.429241  190.914256   Topic1  -3.6667   0.2093
75                   gula  136.311371  136.791228   Topic1  -4.0010   0.2084
69                  kecap  103.494577  103.974637   Topic1  -4.2764   0.2072
54                 merica   81.512244   81.992672   Topic1  -4.5152   0.2060
63                  kaldu   74.060657   74.555535   Topic1  -4.6111   0.2052
80                 kemiri   69.697402   70.177471   Topic1  -4.6718   0.2050
51                   iris   65.838338   66.386539   Topic1  -4.7288   0.2036
33                   buah  302.770590  305.377739   Topic1  -3.2030   0.2033
112                 cabai   49.002955   49.482473   Topic1  -5.0241   0.2021
105                   kol   44.104160   44.583965   Topic1  -5.1294   0.2010
407              irisiris   38.900205   39.379407   Topic1  -5.2550   0.1996
124                 pasir   34.827300   35.308343   Topic1  -5.3656   0.1981
321              memarkan   33.298138   33.777789   Topic1  -5.4105   0.1976
166                   iga   30.665733   31.145420   Topic1  -5.4928   0.1963
128             pelengkap   29.072511   29.552790   Topic1  -5.5462   0.1955
71               optional   28.662041   29.147670   Topic1  -5.5604   0.1951
139                jintan   22.813485   23.300101   Topic1  -5.7886   0.1908
115              keriting   20.746496   21.226518   Topic1  -5.8836   0.1890
117                instan   20.348211   20.828245   Topic1  -5.9030   0.1886
226                   btr   20.196531   20.676531   Topic1  -5.9104   0.1884
104                   lbr   20.011532   20.491354   Topic1  -5.9197   0.1882
129                 nipis   16.736918   17.216488   Topic1  -6.0983   0.1836
14                  bubuk  203.071585  208.903944   Topic1  -3.6024   0.1836
2                  tulang   16.704470   17.185402   Topic1  -6.1003   0.1835
22                  rebus   16.583873   17.063345   Topic1  -6.1075   0.1834
64                  jamur   15.909596   16.389673   Topic1  -6.1490   0.1821
82                 santan   65.120662   67.115281   Topic1  -4.7397   0.1817
72                    air  111.097071  114.502213   Topic1  -4.2056   0.1817
57                  jeruk  118.133199  122.889783   Topic1  -4.1441   0.1724
40                   cabe  142.068169  148.617550   Topic1  -3.9597   0.1668
34                 bawang  456.557242  484.875665   Topic1  -2.7922   0.1517
38                  putih  208.633528  219.932962   Topic1  -3.5754   0.1591
15               ketumbar  102.759596  107.568479   Topic1  -4.2836   0.1661
66                  rawit  100.908641  105.620908   Topic1  -4.3017   0.1662
39                   jahe  119.422015  125.597841   Topic1  -4.1333   0.1614
18                 kunyit  102.976716  108.484916   Topic1  -4.2815   0.1598
30                   daun  298.474345  325.632058   Topic1  -3.2173   0.1248
3                   bumbu  207.080933  224.256718   Topic1  -3.5829   0.1322
7                   garam  178.611360  193.246636   Topic1  -3.7307   0.1331
78                  halus  114.995600  122.232102   Topic1  -4.1711   0.1508
1                 kambing  197.501469  218.410344   Topic1  -3.6302   0.1112
36                  tomat   92.983981   99.158362   Topic1  -4.3835   0.1476
29                 lembar  159.321008  176.018979   Topic1  -3.8450   0.1122
59                  manis  129.301032  140.982519   Topic1  -4.0538   0.1254
81                   ruas  142.083155  164.283013   Topic1  -3.9595   0.0667
27                 batang  125.978756  143.547921   Topic1  -4.0798   0.0813
31                  salam  114.830739  130.021365   Topic1  -4.1725   0.0876
25                  butir  113.069690  133.027630   Topic1  -4.1880   0.0493
207                geprek   75.804847   81.219262   Topic1  -4.5878   0.1429
130                sendok   31.440502   31.908395   Topic2  -2.8708   2.7941
62                 lawang   23.222882   23.691410   Topic2  -3.1738   2.7889
131                   teh   15.666441   16.134366   Topic2  -3.5674   2.7795
198                 royco   12.295900   12.767457   Topic2  -3.8097   2.7713
220                   nya   10.351785   10.820372   Topic2  -3.9818   2.7646
214                 makan    9.396421    9.864268   Topic2  -4.0786   2.7603
468                jempol    8.339389    8.808505   Topic2  -4.1979   2.7542
371                   tea    4.908461    5.376139   Topic2  -4.7280   2.7179
61                  bunga   22.980359   26.490377   Topic2  -3.1843   2.6667
223                  limo    2.857649    3.327372   Topic2  -5.2689   2.6567
439                 peras    2.532368    3.000118   Topic2  -5.3898   2.6394
466                   mkn    2.532171    3.000052   Topic2  -5.3899   2.6393
28              kayumanis    2.531857    2.999959   Topic2  -5.3900   2.6392
191                 pekak    3.857151    4.637524   Topic2  -4.9690   2.6246
405               paprika    2.261104    2.732565   Topic2  -5.5031   2.6195
212              dipotong    8.199633    9.960058   Topic2  -4.2148   2.6144
180               daunnya    2.102293    2.570844   Topic2  -5.5759   2.6077
357                 encer    2.100707    2.569697   Topic2  -5.5767   2.6074
438              cilantro    1.938368    2.406124   Topic2  -5.6571   2.5927
221                   sst    1.938342    2.406140   Topic2  -5.6571   2.5927
347                 limau    1.938196    2.406129   Topic2  -5.6572   2.5926
9                 briyani    1.938054    2.406004   Topic2  -5.6573   2.5926
277                  kare    1.937477    2.405820   Topic2  -5.6576   2.5924
176                campur    5.731971    7.155398   Topic2  -4.5729   2.5871
641                 ganti    1.673592    2.142076   Topic2  -5.8040   2.5621
6                  yogurt    1.509271    1.977193   Topic2  -5.9073   2.5388
194                  ikat    1.509268    1.977218   Topic2  -5.9073   2.5388
437             penyajian    1.509171    1.977162   Topic2  -5.9074   2.5388
345             evaporasi    1.509201    1.977284   Topic2  -5.9074   2.5387
216              campuran    1.508506    1.976851   Topic2  -5.9078   2.5385
48                 wortel    9.116289   14.748093   Topic2  -4.1089   2.3278
17                  hitam    8.427636   15.252596   Topic2  -4.1874   2.2157
390               tangkai    7.486236   13.276065   Topic2  -4.3059   2.2360
186                 bakar    7.902462   15.051150   Topic2  -4.2518   2.1646
92                   dadu    6.367802   12.767783   Topic2  -4.4677   2.1132
24               kapulaga   12.630702   55.785179   Topic2  -3.7828   1.3235
140                  utuh    7.786841   30.128831   Topic2  -4.2665   1.4558
25                  butir   15.302914  133.027630   Topic2  -3.5909   0.6464
26                cengkeh    8.918882   56.235271   Topic2  -4.1308   0.9675
13                 jinten    6.059375   29.984079   Topic2  -4.5173   1.2098
315                 timun    2.423635    4.006351   Topic2  -5.4337   2.3063
67                 sesuai    7.899772   65.715286   Topic2  -4.2521   0.6904
68                 selera    7.904862   70.277092   Topic2  -4.2515   0.6239
55                   pala    6.981181   60.453707   Topic2  -4.3757   0.6502
479              tambahan    3.408435    9.315824   Topic2  -5.0927   1.8034
58                   kayu    5.786886   65.374179   Topic2  -4.5633   0.3844
16                   lada    5.559863   57.864028   Topic2  -4.6034   0.4664
96                seledri    3.441536   14.688941   Topic2  -5.0830   1.3577
14                  bubuk    5.507541  208.903944   Topic2  -4.6128  -0.8269
20                  beras   17.653159   18.199707   Topic3  -3.3325   2.8939
93                  india    9.768492   10.314660   Topic3  -3.9242   2.8700
455                   bay    9.089344    9.635349   Topic3  -3.9963   2.8661
206              putihnya    8.873942    9.420146   Topic3  -4.0203   2.8647
366              mentimun    8.791409    9.337536   Topic3  -4.0296   2.8642
21                basmati    6.818829    7.367220   Topic3  -4.2837   2.8471
174          potongpotong    6.770125    7.316856   Topic3  -4.2909   2.8468
388                 nanas    6.637598    7.184232   Topic3  -4.3106   2.8453
428                 lemon    6.388325    6.936805   Topic3  -4.3489   2.8421
453               blender    5.576151    6.123787   Topic3  -4.4849   2.8308
172                  cuka    5.114122    5.660128   Topic3  -4.5714   2.8230
201                frozen    4.732712    5.279176   Topic3  -4.6489   2.8152
286               cincang   11.965890   13.365003   Topic3  -3.7213   2.8139
671                saring    4.517308    5.063485   Topic3  -4.6955   2.8103
199                 resep    4.236035    4.782796   Topic3  -4.7598   2.8030
692                hancur    4.136833    4.682724   Topic3  -4.7835   2.8005
693               dimasak    4.136833    4.682724   Topic3  -4.7835   2.8005
694               kerupuk    4.136833    4.682724   Topic3  -4.7835   2.8005
695               belinjo    4.136833    4.682724   Topic3  -4.7835   2.8005
690               mangkok    4.136495    4.682888   Topic3  -4.7835   2.8004
691                mngkok    4.136495    4.682888   Topic3  -4.7835   2.8004
202                 lihat    3.556958    4.103469   Topic3  -4.9345   2.7815
205                 ambil    9.417329   10.992955   Topic3  -3.9608   2.7697
169                  acar    6.477319    8.201733   Topic3  -4.3351   2.6884
349                   bwg    1.353604    1.899661   Topic3  -5.9006   2.5855
711                 bagus    2.991718    4.352137   Topic3  -5.1075   2.5496
712              kulitnya    2.991718    4.352137   Topic3  -5.1075   2.5496
715       karikambingsapi    2.991718    4.352137   Topic3  -5.1075   2.5496
716            kecoklatan    2.991718    4.352137   Topic3  -5.1075   2.5496
143                  koja    7.366410   11.385732   Topic3  -4.2065   2.4890
146              margarin    6.007322    9.370915   Topic3  -4.4104   2.4798
118                bombay    9.550680   16.348176   Topic3  -3.9468   2.3869
713       samingheewisman    4.709961    7.735197   Topic3  -4.6537   2.4283
714                  leaf    4.709961    7.735197   Topic3  -4.6537   2.4283
23                   biji   23.090969   60.031179   Topic3  -3.0639   1.9690
41                  hijau   11.309922   25.436158   Topic3  -3.7777   2.1139
24               kapulaga   15.802710   55.785179   Topic3  -3.4432   1.6631
26                cengkeh   13.763311   56.235271   Topic3  -3.5814   1.5169
58                   kayu   13.946781   65.374179   Topic3  -3.5681   1.3796
103                  nasi    7.263465   18.715003   Topic3  -4.2205   1.9780
16                   lada   10.041094   57.864028   Topic3  -3.8967   1.1730
1                 kambing   13.369284  218.410344   Topic3  -3.6104   0.1310
7                   garam   10.909093  193.246636   Topic3  -3.8138   0.0501
34                 bawang   13.680032  484.875665   Topic3  -3.5875  -0.6435
3                   bumbu   10.853138  224.256718   Topic3  -3.8189  -0.1039
59                  manis    9.476471  140.982519   Topic3  -3.9546   0.2246
111                  kari    5.968162   23.670113   Topic3  -4.4170   1.5467
94                 goreng    5.615447   63.145822   Topic3  -4.4779   0.5045
126               kriting    6.143924    6.692268   Topic4  -4.1801   3.0468
247                buncis    5.543697    6.089483   Topic4  -4.2829   3.0384
155               sayuran    5.541203    6.090071   Topic4  -4.2833   3.0378
467                 mrica    4.858803    5.403986   Topic4  -4.4147   3.0259
238                seruas    4.672961    5.221433   Topic4  -4.4537   3.0213
688                  asem    4.173673    4.718666   Topic4  -4.5667   3.0096
689       gulagaramtotole    4.173673    4.718666   Topic4  -4.5667   3.0096
710                jagung    4.173633    4.718639   Topic4  -4.5668   3.0096
699                  ekor    4.173485    4.718823   Topic4  -4.5668   3.0095
700               kampung    4.173485    4.718823   Topic4  -4.5668   3.0095
701                 habis    4.173485    4.718823   Topic4  -4.5668   3.0095
433                 stock    4.173491    5.312710   Topic4  -4.5668   2.8909
56                   lmbr    1.666165    2.212196   Topic4  -5.4850   2.8488
304               butiran   10.272728   14.982914   Topic4  -3.6660   2.7549
187              aromatik    1.144273    1.694785   Topic4  -5.8608   2.7395
150                keprek    1.064763    1.610749   Topic4  -5.9328   2.7183
518               brokoli    0.847248    1.393219   Topic4  -6.1613   2.6349
532                  gule    0.846608    1.393760   Topic4  -6.1621   2.6338
561              telunjuk    0.846753    1.394223   Topic4  -6.1619   2.6336
479              tambahan    5.518268    9.315824   Topic4  -4.2875   2.6086
448               topping    0.764186    1.309712   Topic4  -6.2645   2.5935
156                rajang    0.764133    1.309757   Topic4  -6.2646   2.5934
356                  arab    0.764090    1.309792   Topic4  -6.2646   2.5933
240                gulpas    0.763873    1.309575   Topic4  -6.2649   2.5932
460                kelapa    0.763333    1.310251   Topic4  -6.2656   2.5920
302                 kupas    0.762896    1.310730   Topic4  -6.2662   2.5911
303            dimemarkan    0.680647    1.226027   Topic4  -6.3803   2.5438
232           dibersihkan    0.680315    1.225944   Topic4  -6.3807   2.5434
252                halawa    0.680158    1.226183   Topic4  -6.3810   2.5430
323                   ltr    1.043447    2.224973   Topic4  -5.9530   2.3751
23                   biji   27.789833   60.031179   Topic4  -2.6709   2.3621
74                   jawa    6.196132   14.179341   Topic4  -4.1716   2.3044
96                seledri    5.207044   14.688941   Topic4  -4.3455   2.0952
547                 setan    4.567984   13.299054   Topic4  -4.4765   2.0637
185               sangrai    5.281495   21.185543   Topic4  -4.3313   1.7432
27                 batang   17.166827  143.547921   Topic4  -3.1526   1.0086
13                 jinten    5.963129   29.984079   Topic4  -4.2099   1.5172
151              lengkuas    9.555227   66.366717   Topic4  -3.7385   1.1942
60                   jari    9.575970   69.640223   Topic4  -3.7363   1.1482
29                 lembar   16.295175  176.018979   Topic4  -3.2047   0.7526
30                   daun   23.860365  325.632058   Topic4  -2.8233   0.5187
133              sejumput    4.328052   23.202343   Topic4  -4.5304   1.4532
41                  hijau    4.340837   25.436158   Topic4  -4.5275   1.3642
81                   ruas   12.134522  164.283013   Topic4  -3.4995   0.5268
31                  salam    9.295611  130.021365   Topic4  -3.7660   0.4941
34                 bawang   13.300578  484.875665   Topic4  -3.4077  -0.4638
78                  halus    6.835777  122.232102   Topic4  -4.0734   0.2485
38                  putih    7.657235  219.932962   Topic4  -3.9599  -0.2254
1                 kambing    6.562603  218.410344   Topic4  -4.1142  -0.3727
55                   pala    5.442807   60.453707   Topic4  -4.3012   0.7247
18                 kunyit    5.106098  108.484916   Topic4  -4.3651   0.0761
15               ketumbar    4.406882  107.568479   Topic4  -4.5124  -0.0627
25                  butir    4.410952  133.027630   Topic4  -4.5115  -0.2742
57                  jeruk    4.353606  122.889783   Topic4  -4.5245  -0.2080
329                   bau    3.426219    3.994740   Topic5  -3.9270   3.8158
42                  pedas    3.425638    3.995221   Topic5  -3.9272   3.8155
379           tomatpotong    3.155067    3.723790   Topic5  -4.0095   3.8036
376               yoghurt    3.154694    3.723877   Topic5  -4.0096   3.8035
706               prengus    2.943030    3.511556   Topic5  -4.0790   3.7927
707                 isian    2.943030    3.511556   Topic5  -4.0790   3.7927
708            selerairis    2.943030    3.511556   Topic5  -4.0790   3.7927
709                griris    2.943030    3.511556   Topic5  -4.0790   3.7927
375                 plain    6.291542    7.679879   Topic5  -3.3193   3.7699
193                 tumis    6.655323    9.235762   Topic5  -3.2631   3.6417
365               rebusan    5.175512    7.511697   Topic5  -3.5145   3.5968
85                  cream    1.021303    1.591237   Topic5  -5.1374   3.5259
403                 bahan    0.962709    1.532590   Topic5  -5.1965   3.5044
257               baceman    0.904299    1.472773   Topic5  -5.2591   3.4816
88                    cup    3.293849    5.419965   Topic5  -3.9664   3.4713
352           seraigeprek    2.965479    5.281878   Topic5  -4.0714   3.3921
551                 cacah    0.597841    1.166702   Topic5  -5.6729   3.3007
404                   sop    0.539004    1.107559   Topic5  -5.7765   3.2492
324                  full    0.536877    1.108643   Topic5  -5.7805   3.2442
19                 kaleng    0.638264    1.357134   Topic5  -5.6075   3.2150

Topic: 1
pack, pre, tdk, ujung, kencur, digeprek, steak, slice, grill, master, memanggang, kuping, kapri, serut, ikan, jahesecukupnya, basmatibumbu, memerk, almadina, minyakmargarin, kobis, disesuaikan, laoslengkuas, kepedasannya, halusulek, presto, kalo, gajih, jantung, pisang

Topic: 2
biji, beras, kapulaga, kayu, cengkeh, bawang, kambing, cincang, hijau, garam, bumbu, lada, india, bombay, manis, ambil, bay, putihnya, mentimun, koja, nasi, basmati, potongpotong, nanas, acar, lemon, margarin, kari, goreng, blender

Topic: 3
biji, daun, batang, lembar, bawang, ruas, butiran, jari, lengkuas, salam, putih, halus, kambing, jawa, kriting, jinten, buncis, sayuran, tambahan, pala, sangrai, seledri, kunyit, mrica, seruas, setan, butir, ketumbar, jeruk, hijau

Topic: 4
bawang, merah, buah, daun, siung, putih, bumbu, bubuk, kambing, daging, garam, lembar, ruas, cabe, gula, manis, batang, jahe, jeruk, halus, salam, butir, air, kecap, kunyit, ketumbar, rawit, tomat, merica, geprek

Topic: 5
sendok, lawang, bunga, teh, butir, kapulaga, royco, nya, makan, wortel, cengkeh, hitam, jempol, dipotong, selera, bakar, sesuai, utuh, tangkai, pala, dadu, jinten, kayu, campur, lada, bubuk, tea, pekak, seledri, tambahan

Topic: 6
jari, ruas, tumis, hitam, plain, salam, rebusan, geprek, sereh, bau, pedas, cup, dihaluskan, tomatpotong, yoghurt, seraigeprek, griris, selerairis, isian, prengus, kotak, daun, leaf, samingheewisman, penyedap, jahe, santan, cream, bahan, cincang

Topic: 7
tetelan, diganti, jgn, seasonings, jeroanrebus, dipisah, campur, baput, sct, genggam, paha, masako, bamer, serei, siapkan, pan, mengoles, plastik, btir, temu, tergantung, kencur, kunci, suwir, nasgor, curry, porsi, bputih, bmerah, maniss

[(0,
  '0.052*"pack" + 0.052*"pre" + 0.010*"ujung" + 0.010*"tdk" + 0.010*"kencur" + 0.007*"digeprek" + 0.005*"memanggang" + 0.005*"grill" + 0.005*"slice" + 0.005*"steak"'),
 (1,
  '0.047*"biji" + 0.036*"beras" + 0.032*"kapulaga" + 0.028*"kayu" + 0.028*"cengkeh" + 0.028*"bawang" + 0.027*"kambing" + 0.024*"cincang" + 0.023*"hijau" + 0.022*"garam"'),
 (2,
  '0.069*"biji" + 0.059*"daun" + 0.043*"batang" + 0.041*"lembar" + 0.033*"bawang" + 0.030*"ruas" + 0.026*"butiran" + 0.024*"jari" + 0.024*"lengkuas" + 0.023*"salam"'),
 (3,
  '0.061*"bawang" + 0.045*"merah" + 0.041*"buah" + 0.040*"daun" + 0.036*"siung" + 0.028*"putih" + 0.028*"bumbu" + 0.027*"bubuk" + 0.027*"kambing" + 0.026*"daging"'),
 (4,
  '0.057*"sendok" + 0.042*"lawang" + 0.041*"bunga" + 0.028*"teh" + 0.028*"butir" + 0.023*"kapulaga" + 0.022*"royco" + 0.019*"nya" + 0.017*"makan" + 0.016*"wortel"'),
 (5,
  '0.086*"jari" + 0.056*"ruas" + 0.038*"tumis" + 0.037*"hitam" + 0.036*"plain" + 0.032*"salam" + 0.030*"rebusan" + 0.029*"geprek" + 0.028*"sereh" + 0.020*"bau"'),
 (6,
  '0.087*"tetelan" + 0.046*"diganti" + 0.039*"jgn" + 0.039*"seasonings" + 0.039*"jeroanrebus" + 0.039*"dipisah" + 0.014*"campur" + 0.011*"baput" + 0.008*"sct" + 0.007*"genggam"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
kambingCpdProb = make_dictionary_terms_prob(ldamodel, id_map, d)
kambingCpdProb["mee"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
kambingCpdWN = dfWordnet.copy()

kambingCpdWN["Synonym_clean"] = cleanWN_Synonym(kambingCpdWN["Synonym"])
kambingCpdWN["Hypernim_clean"] = cleanWN(kambingCpdWN["Hypernim"])
kambingCpdWN["Hyponim_clean"] = cleanWN(kambingCpdWN["Hyponim"])
kambingCpdWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/kambingCookpad.owl")
makeOntology(ontoName, kambingCpdWN)
ontoName.save(file = "kambingCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1B6Cw9zU7dPMqhzyNd3CIRjLiP_ZPrQeQ"

In [ ]:
wiki_kambing_cpd = pd.read_excel("KambingCookpadFinal.xlsx").iloc[:, 1:]

# Translate
wiki_kambing_cpd["Category"] = translate(wiki_kambing_cpd["Category"])
wiki_kambing_cpd.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_kambing_cpd[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
kambingCpdTabel_new = tabel_1981.copy()
kambingCpdTabel_new["correct_category"] = all_cat
kambingCpdTabel_new["suggestion"] = all_suggestion

# Export Result to File
kambingCpdTabel_new.to_excel("kambingCpdTabel_Result.xlsx")
kambingCpdTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingCpdTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
kambingCpdTabel_new = concatListInColumn(kambingCpdTabel_new)
kambingCpdTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, kambingCpdTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_kambing_cpd.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
kambingCpdWiki_new = wiki_df.copy()
kambingCpdWiki_new["suggest"] = all_cat

# Export Result to file
kambingCpdWiki_new.to_excel("kambingCpdWiki_Result.xlsx")
kambingCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
kambingCpdOntoWiki = get_ontology("http://test.org/kambingCpd_onto_wiki.owl")
makeOntology_wiki(kambingCpdOntoWiki, kambingCpdWiki_new)
kambingCpdOntoWiki.save(file = "kambingCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = kambingCpdWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
kambingCpdWN_new = listToDataframe(changesList, tableWordnet)
kambingCpdWN_new.to_excel("kambingCpdWN_Result.xlsx")
kambingCpdWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "kambingCpdWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Sapi - Cookpad

In [ ]:
!gdown --id "1_HiEr1_J-c55HsGvRatqmWpjXQdLEt7_"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1_HiEr1_J-c55HsGvRatqmWpjXQdLEt7_
To: /content/cookpad-selenium_sapi.jl
100% 415k/415k [00:00<00:00, 97.0MB/s]

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
sapi_cpd=pd.read_json(r'/content/cookpad-selenium_sapi.jl', lines = True)
sapi_cpd = concat_bahan_langkah(sapi_cpd)

# fill NaN with empty string
sapi_cpd["page_description"] = sapi_cpd["page_description"].fillna("")

#save dalam acar biar ngebut loading ntar.
sapi_cpd.to_pickle(r'/content/raw_df.pkl')

# covnert page_description to list
sapi_cpd["temp"] = sapi_cpd["page_description"]
sapi_cpd["page_description"] = sapi_cpd["page_bahan_langkah"]

# # clean text
sapi_cpd = pre_cleaning_text(sapi_cpd, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
sapi_cpd.head()

,url_search,list_scraping_time,list_item_url,list_item_title,list_item_ingredients,list_item_author_name,list_item_author_image_url,list_item_image_url,page_scraping_time,page_image_url,...,page_serving_count,page_bahan,page_langkah,page_post_datetime,page_post_love_count,page_post_clap_count,page_post_tasty_count,page_comment_count,page_bahan_langkah,temp
0,https://cookpad.com/id/cari/sapi?event=search....,2022-06-24 23:14:28,https://cookpad.com/id/resep/16327449-us-beef-...,\n US Beef Slice Pedas Manis\n,"[US Beef Slice, Kecap Manis Daging Asap ABC, S...",Doyan Makan!,https://img-global.cpcdn.com/users/8cf96b2c882...,https://img-global.cpcdn.com/recipes/c5d03baf9...,2022-06-24 23:14:43,https://img-global.cpcdn.com/recipes/c5d03baf9...,...,"1,5 orang","[100 gr US Beef Slice, 1,5 sdt Kecap Manis Dag...",[],24 Juni 2022 22.42,NaN,NaN,NaN,NaN,"[100 gr US Beef Slice, 1,5 sdt Kecap Manis Dag...",US Beef Slice ini menu terinspirasi dari Raa C...
1,https://cookpad.com/id/cari/sapi?event=search....,2022-06-24 23:14:28,https://cookpad.com/id/resep/16321842-280-riso...,\n 280. RISOLES MAYO SMOKE BEEF\n,"[resep kulit dadar, resep adonan pencelup riso...",Ibu Endah,https://img-global.cpcdn.com/users/610bbdb12d2...,https://img-global.cpcdn.com/recipes/d6fa4e8ab...,2022-06-24 23:14:50,https://img-global.cpcdn.com/recipes/d6fa4e8ab...,...,24 biji,"[1 resep kulit dadar\n (lihat resep),...",[],24 Juni 2022 09.53,7.0,5.0,5.0,NaN,"[1 resep kulit dadar\n (lihat resep),...",Assalamualaikum wr wb\n
2,https://cookpad.com/id/cari/sapi?event=search....,2022-06-24 23:14:28,https://cookpad.com/id/resep/16325861-sop-tete...,\n Sop Tetelan Sedap Wangi\n,"[tetelan, kentang, wortel, daun bawang dan sel...",Hayati MS,https://img-global.cpcdn.com/users/fed80c02c96...,https://img-global.cpcdn.com/recipes/971c2ab7a...,2022-06-24 23:14:56,https://img-global.cpcdn.com/recipes/971c2ab7a...,...,1 panci,"[250 gram tetelan, 2 buah kentang, 2 buah wort...",[],24 Juni 2022 12.09,20.0,4.0,6.0,2.0,"[250 gram tetelan, 2 buah kentang, 2 buah wort...",Masak simpel tapi ala resto dan dilahap habis ...
3,https://cookpad.com/id/cari/sapi?event=search....,2022-06-24 23:14:28,https://cookpad.com/id/resep/16320884-gulai-da...,\n Gulai Daging Sapi Pakai Bumbu ...,"[daging sapi, potong dadu, Jeruk nipis, Bumbu ...",Tanti Mak Ibra,https://img-global.cpcdn.com/users/c58dfedf57f...,https://img-global.cpcdn.com/recipes/89474b551...,2022-06-24 23:15:02,https://img-global.cpcdn.com/recipes/89474b551...,...,2 orang,"[1/2 kg daging sapi, potong dadu, Jeruk nipis,...",[],22 Juni 2022 05.32,10.0,3.0,7.0,NaN,"[1/2 kg daging sapi, potong dadu, Jeruk nipis,...",Lusa lalu beli Ind*mie goreng di minimarket. A...
4,https://cookpad.com/id/cari/sapi?event=search....,2022-06-24 23:14:28,https://cookpad.com/id/resep/16321487-tumis-ka...,\n Tumis Kangkung Beef Slice\n,"[kangkung, beef slice, saos tiram, saos teriya...",Martha Christinawatie,https://img-global.cpcdn.com/users/9cb5007c0e4...,https://img-global.cpcdn.com/recipes/f77275b45...,2022-06-24 23:15:08,https://img-global.cpcdn.com/recipes/f77275b45...,...,2 orang,"[1 ikat kangkung, 150 gram beef slice, 1 sdt s...",[],22 Juni 2022 08.54,6.0,4.0,3.0,NaN,"[1 ikat kangkung, 150 gram beef slice, 1 sdt s...",

## GUI Sapi - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = sapi_cpd.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
4     -0.240078 -0.002265       1        1  41.167074
6     -0.103117 -0.152694       2        1  34.180843
2      0.017067  0.012328       3        1   7.268400
1     -0.065870 -0.046550       4        1   6.053477
3     -0.043193  0.248163       5        1   5.179283
5      0.201905 -0.156557       6        1   4.393116
0      0.233286  0.097575       7        1   1.757806, topic_info=              Term        Freq       Total Category  logprob  loglift
37            buah  225.000000  225.000000  Default  30.0000  30.0000
176           saus   95.000000   95.000000  Default  29.0000  29.0000
47           bumbu  146.000000  146.000000  Default  28.0000  28.0000
41            daun  158.000000  158.000000  Default  27.0000  27.0000
60            iris  136.000000  136.000000  Default  26.0000  26.0000
85           garam  160.000000  160.000000  Default  25.0000  25.0000
3            manis  120.000000  120.000000  Default  24.0000  24.0000
55           butir   98.000000   98.000000  Default  23.0000  23.0000
14           bubuk  148.000000  148.000000  Default  22.0000  22.0000
35            gram   40.000000   40.000000  Default  21.0000  21.0000
51           salam   61.000000   61.000000  Default  20.0000  20.0000
64            sapi  153.000000  153.000000  Default  19.0000  19.0000
0             beef   51.000000   51.000000  Default  18.0000  18.0000
286          sayur   25.000000   25.000000  Default  17.0000  17.0000
52           halus  108.000000  108.000000  Default  16.0000  16.0000
56          kemiri   47.000000   47.000000  Default  15.0000  15.0000
54           putih  217.000000  217.000000  Default  14.0000  14.0000
45             air  151.000000  151.000000  Default  13.0000  13.0000
61            jahe   80.000000   80.000000  Default  12.0000  12.0000
94            cabe   49.000000   49.000000  Default  11.0000  11.0000
77            ruas   67.000000   67.000000  Default  10.0000  10.0000
4           daging  149.000000  149.000000  Default   9.0000   9.0000
26             lbr   22.000000   22.000000  Default   8.0000   8.0000
70           merah  188.000000  188.000000  Default   7.0000   7.0000
92           kaldu   84.000000   84.000000  Default   6.0000   6.0000
134         santan   42.000000   42.000000  Default   5.0000   5.0000
29           telur   25.000000   25.000000  Default   4.0000   4.0000
44          goreng   52.000000   52.000000  Default   3.0000   3.0000
78        lengkuas   32.000000   32.000000  Default   2.0000   2.0000
42          bawang  443.000000  443.000000  Default   1.0000   1.0000
49          lembar   69.841049   70.479421   Topic1  -3.7893   0.8784
75          selera   66.593694   67.232284   Topic1  -3.8369   0.8780
74          sesuai   63.948534   64.587320   Topic1  -3.8774   0.8776
172         geprek   55.053437   55.692014   Topic1  -4.0272   0.8760
50           jeruk   52.317163   53.075099   Topic1  -4.0782   0.8731
103           jawa   26.031883   26.670222   Topic1  -4.7762   0.8633
315          serai   23.340182   23.977827   Topic1  -4.8854   0.8606
306           asam   18.776327   19.428511   Topic1  -5.1029   0.8534
72        keriting   11.629819   12.268482   Topic1  -5.5820   0.8341
113            amp   10.619655   11.258264   Topic1  -5.6728   0.8291
223            iga    9.947266   10.584933   Topic1  -5.7382   0.8254
58          jinten   16.750557   17.846977   Topic1  -5.2171   0.8241
236          bunga    9.514269   10.152126   Topic1  -5.7827   0.8226
607         keping    8.216781    8.853995   Topic1  -5.9293   0.8128
454          bulat    7.972523    8.612802   Topic1  -5.9595   0.8103
331         kental   22.025700   23.978106   Topic1  -4.9433   0.8026
95           rawit   20.172853   21.970499   Topic1  -5.0312   0.8022
182          tumis    6.990176    7.627478   Topic1  -6.0910   0.8003
610         salmon    6.557531    7.194714   Topic1  -6.1549   0.7948
82        kapulaga    6.027439    6.665982   Topic1  -6.2392   0.7868
771     tenderloin    6.004452    6.641637   Topic1  -6.2430   0.7867
772   besarkriting    6.004452    6.641637   Topic1  -6.2430   0.7867
773   kapulagapala    6.004452    6.641637   Topic1  -6.2430   0.7867
779          leher    6.004453    6.641641   Topic1  -6.2430   0.7867
785          kupas    6.004121    6.641550   Topic1  -6.2431   0.7866
67          instan   13.369768   14.991902   Topic1  -5.4425   0.7730
159           jari   12.827758   14.385193   Topic1  -5.4839   0.7729
40          batang   52.823468   60.176659   Topic1  -4.0686   0.7572
87            ikat    4.173037    4.814856   Topic1  -6.6069   0.7445
305        bungkus   12.645819   14.789040   Topic1  -5.4982   0.7310
77            ruas   56.989598   67.577448   Topic1  -3.9927   0.7171
51           salam   51.690142   61.502580   Topic1  -4.0903   0.7137
70           merah  150.922972  188.197613   Topic1  -3.0188   0.6668
164       penyedap   31.634036   37.363951   Topic1  -4.5813   0.7211
134         santan   35.252857   42.151714   Topic1  -4.4730   0.7088
57         sangrai   19.870109   23.550873   Topic1  -5.0463   0.7176
56          kemiri   38.056350   47.256051   Topic1  -4.3965   0.6710
41            daun  112.375954  158.076115   Topic1  -3.3137   0.5463
55           butir   72.459773   98.839116   Topic1  -3.7525   0.5771
44          goreng   40.293128   52.150973   Topic1  -4.3393   0.6296
61            jahe   59.405812   80.385939   Topic1  -3.9511   0.5851
53           siung  135.479251  216.168541   Topic1  -3.1267   0.4203
71           cabai   24.925695   31.557765   Topic1  -4.8196   0.6516
47           bumbu   88.693027  146.561113   Topic1  -3.5503   0.3853
94            cabe   35.657568   49.633390   Topic1  -4.4616   0.5568
84            gula   80.361849  137.200761   Topic1  -3.6490   0.3526
63           tomat   40.846875   60.035681   Topic1  -4.3257   0.5024
42          bawang  200.453991  443.272675   Topic1  -2.7349   0.0939
85           garam   77.448489  160.761129   Topic1  -3.6859   0.1572
64            sapi   74.295355  153.026373   Topic1  -3.7275   0.1650
54           putih   86.188834  217.484533   Topic1  -3.5790  -0.0381
37            buah   86.095988  225.207759   Topic1  -3.5801  -0.0740
4           daging   64.848640  149.368717   Topic1  -3.8635   0.0532
52           halus   52.360042  108.374440   Topic1  -4.0774   0.1601
3            manis   53.764733  120.730254   Topic1  -4.0509   0.0786
45             air   57.461332  151.541377   Topic1  -3.9844  -0.0822
2            kecap   45.591433  139.092475   Topic1  -4.2158  -0.2279
14           bubuk   46.209893  148.566338   Topic1  -4.2023  -0.2803
105           asin   34.732378   35.300048   Topic2  -4.3019   1.0573
197       tambahan   27.579521   28.147968   Topic2  -4.5325   1.0531
11           hitam   20.703454   21.270542   Topic2  -4.8193   1.0465
203       marinasi   20.587473   21.154473   Topic2  -4.8249   1.0463
290        paprika   16.584781   17.151903   Topic2  -5.0411   1.0399
469       kikkoman   13.784032   14.352075   Topic2  -5.2260   1.0331
204           madu   13.200514   13.768666   Topic2  -5.2693   1.0314
515          sosis   12.190301   12.758477   Topic2  -5.3489   1.0279
104          wijen   52.834745   55.343199   Topic2  -3.8824   1.0271
456           prei   11.296618   11.864689   Topic2  -5.4250   1.0244
91        teriyaki   10.054911   10.621905   Topic2  -5.5415   1.0186
65            dadu   20.924690   22.360456   Topic2  -4.8086   1.0071
295          saori    7.451368    8.018368   Topic2  -5.8412   1.0002
227        mentega    6.945539    7.512934   Topic2  -5.9115   0.9950
149        maizena   27.484914   30.074375   Topic2  -4.5359   0.9835
233         diiris    5.271846    5.840299   Topic2  -6.1872   0.9711
32           pakai   11.489182   12.818007   Topic2  -5.4081   0.9641
221       larutkan    4.768414    5.335982   Topic2  -6.2875   0.9610
112       margarin    7.403006    8.294994   Topic2  -5.8477   0.9597
1            slice   21.333004   23.922908   Topic2  -4.7893   0.9589
554         selada    4.653623    5.220555   Topic2  -6.3119   0.9585
102          makan    4.575235    5.142221   Topic2  -6.3289   0.9567
189           baby    4.574281    5.141756   Topic2  -6.3291   0.9566
265        bonggol    4.571889    5.140686   Topic2  -6.3296   0.9562
126        cincang   40.054288   45.091430   Topic2  -4.1593   0.9550
327         butter    4.261771    4.830114   Topic2  -6.3999   0.9483
325        saikoro    4.257847    4.828173   Topic2  -6.4008   0.9478
299        inggris    4.070335    4.637235   Topic2  -6.4458   0.9431
147        tapioka    4.070144    4.637154   Topic2  -6.4459   0.9431
15         oregano    4.069644    4.636817   Topic2  -6.4460   0.9430
97          bombay   57.627915   67.080993   Topic2  -3.7955   0.9216
0             beef   42.859976   51.377693   Topic2  -4.0916   0.8922
282         bombai    7.679969    8.870313   Topic2  -5.8109   0.9294
90           tiram   53.001178   67.151237   Topic2  -3.8792   0.8369
145          tipis   23.617508   28.830765   Topic2  -4.6876   0.8741
93           jamur   22.330282   27.806010   Topic2  -4.7436   0.8542
176           saus   68.055780   95.547112   Topic2  -3.6292   0.7342
2            kecap   93.045098  139.092475   Topic2  -3.3165   0.6715
60            iris   81.601005  136.659954   Topic2  -3.4477   0.5579
54           putih  113.951101  217.484533   Topic2  -3.1138   0.4271
42          bawang  198.430200  443.272675   Topic2  -2.5591   0.2698
45             air   72.607539  151.541377   Topic2  -3.5645   0.3377
146         tepung   22.152611   33.821526   Topic2  -4.7516   0.6504
4           daging   68.680243  149.368717   Topic2  -3.6201   0.2965
14           bubuk   66.923326  148.566338   Topic2  -3.6460   0.2760
37            buah   87.577829  225.207759   Topic2  -3.3770   0.1290
53           siung   80.082027  216.168541   Topic2  -3.4665   0.0805
13            lada   43.027459   93.299376   Topic2  -4.0877   0.2995
92           kaldu   39.325952   84.813153   Topic2  -4.1777   0.3049
85           garam   56.492943  160.761129   Topic2  -3.8154   0.0277
3            manis   44.144976  120.730254   Topic2  -4.0621   0.0674
64            sapi   49.084793  153.026373   Topic2  -3.9560  -0.0636
84            gula   39.296382  137.200761   Topic2  -4.1784  -0.1768
52           halus   34.233408  108.374440   Topic2  -4.3164  -0.0789
70           merah   36.442403  188.197613   Topic2  -4.2538  -0.5683
89            saos   23.972997   47.522593   Topic2  -4.6726   0.3892
230          rebus   15.780150   16.414558   Topic3  -3.5427   2.5822
19           resep   13.645692   14.279705   Topic3  -3.6880   2.5762
22           lihat   13.322918   13.957094   Topic3  -3.7119   2.5751
123          sauce    9.003318    9.637753   Topic3  -4.1038   2.5535
142        taburan    8.804446    9.439430   Topic3  -4.1262   2.5520
301   potongpotong    7.785861    8.421337   Topic3  -4.2491   2.5432
122            soy    7.539159    8.173111   Topic3  -4.2813   2.5409
333        butiran    7.214535    7.850628   Topic3  -4.3253   2.5371
763         diskip    6.769811    7.403777   Topic3  -4.3890   2.5321
235          liter    6.272857    6.907793   Topic3  -4.4652   2.5252
780        kurangi    6.198965    6.832870   Topic3  -4.4770   2.5243
781        takaran    6.198965    6.832870   Topic3  -4.4770   2.5243
782        madunya    6.198965    6.832870   Topic3  -4.4770   2.5243
770    sapitetelan    6.198552    6.833000   Topic3  -4.4771   2.5242
434           ikan    5.006091    5.642688   Topic3  -4.6908   2.5019
137        sayuran    3.739181    4.376575   Topic3  -4.9826   2.4642
701           sawi    2.400689    3.035361   Topic3  -5.4257   2.3871
381        sengkel    2.276619    2.910767   Topic3  -5.4787   2.3759
136      sesuaikan    2.022958    2.661872   Topic3  -5.5969   2.3472
663            sup    1.830336    2.464133   Topic3  -5.6969   2.3243
304            cup    1.869814    2.527286   Topic3  -5.6756   2.3203
118         kacang    1.706022    2.339775   Topic3  -5.7673   2.3057
289        larutan    1.452618    2.093901   Topic3  -5.9281   2.2560
29           telur   17.206268   25.431284   Topic3  -3.4562   2.2309
657   kulitnyacuci    1.259428    1.893130   Topic3  -6.0708   2.2141
658   bersihpotong    1.259428    1.893130   Topic3  -6.0708   2.2141
661       makaroni    1.259428    1.893130   Topic3  -6.0708   2.2141
584          kanji    1.258727    1.892821   Topic3  -6.0713   2.2137
690          tholo    1.258665    1.892869   Topic3  -6.0714   2.2136
396            isi    1.135350    1.768923   Topic3  -6.1745   2.1782
231        rebusan    3.218449    5.034010   Topic3  -5.1325   2.1743
125            btr    2.819458    4.558994   Topic3  -5.2649   2.1411
121         giling    5.385518   10.517723   Topic3  -4.6177   1.9523
228            utk    2.962797    5.578399   Topic3  -5.2153   1.9889
143            btg    7.921090   22.383437   Topic3  -4.2319   1.5828
244         matang    3.551154    7.668871   Topic3  -5.0342   1.8517
146         tepung   10.613445   33.821526   Topic3  -3.9393   1.4627
116           ayam    4.152273   10.322191   Topic3  -4.8778   1.7110
14           bubuk   17.901952  148.566338   Topic3  -3.4165   0.5055
86          merica    9.676369   49.135321   Topic3  -4.0317   0.9967
92           kaldu   12.691222   84.813153   Topic3  -3.7605   0.7221
45             air   16.675691  151.541377   Topic3  -3.4875   0.4147
38         kentang    6.900778   28.324591   Topic3  -4.3698   1.2095
52           halus   13.435081  108.374440   Topic3  -3.7036   0.5339
55           butir   11.941936   98.839116   Topic3  -3.8214   0.5082
60            iris   11.018945  136.659954   Topic3  -3.9018   0.1038
42          bawang   16.520900  443.272675   Topic3  -3.4968  -0.6679
41            daun    9.145897  158.076115   Topic3  -4.0881  -0.2281
64            sapi    7.715383  153.026373   Topic3  -4.2582  -0.3658
84            gula    6.575707  137.200761   Topic3  -4.4180  -0.4164
85           garam    6.372977  160.761129   Topic3  -4.4494  -0.6062
4           daging    6.330319  149.368717   Topic3  -4.4561  -0.5394
718          black    9.114675    9.786001   Topic4  -3.9086   2.7335
504          paper    9.026474    9.697850   Topic4  -3.9184   2.7328
163     dihaluskan    7.690301    8.360493   Topic4  -4.0786   2.7210
36         tetelan    7.373051    8.043476   Topic4  -4.1207   2.7175
81          lawang    6.966688    7.638792   Topic4  -4.1774   2.7124
43         seledri    6.740585    7.408872   Topic4  -4.2104   2.7100
140       aromatik    6.246051    6.915712   Topic4  -4.2866   2.7027
544          tauge    4.799798    5.471073   Topic4  -4.5499   2.6736
786       purutair    4.397458    5.066433   Topic4  -4.6375   2.6629
166        merebus    3.375525    4.045273   Topic4  -4.9020   2.6235
413         kelapa   13.169322   18.898670   Topic4  -3.5406   2.4433
485            bks    1.526498    2.195854   Topic4  -5.6955   2.4409
416          empuk    1.208170    1.879120   Topic4  -5.9294   2.3628
218           kalo    1.207425    1.881924   Topic4  -5.9300   2.3607
62       pelengkap    5.876068    9.216470   Topic4  -4.3476   2.3544
302      memanjang    2.002492    3.143484   Topic4  -5.4241   2.3536
553        kerupuk    1.249351    1.966644   Topic4  -5.8959   2.3508
672          racik    0.891998    1.562146   Topic4  -6.2328   2.2442
80         kembang    0.805390    1.473347   Topic4  -6.3349   2.2006
76        pedasnya    0.804990    1.473442   Topic4  -6.3354   2.2000
69        indofood    0.804441    1.473763   Topic4  -6.3361   2.1991
414       gongseng    0.804020    1.473411   Topic4  -6.3367   2.1988
68           gulai    0.803477    1.473380   Topic4  -6.3373   2.1982
507         coklat    0.803701    1.474309   Topic4  -6.3370   2.1978
319         kluwek    0.803395    1.473948   Topic4  -6.3374   2.1977
474        rendang    0.802860    1.474799   Topic4  -6.3381   2.1964
385        cuciwis    0.717252    1.385481   Topic4  -6.4508   2.1462
374          lemak    1.401907    2.987023   Topic4  -5.7807   2.0481
48        cemplung   10.811556   23.785473   Topic4  -3.7379   2.0161
229        menumis   10.579928   24.654131   Topic4  -3.7596   1.9586
37            buah   51.163646  225.207759   Topic4  -2.1835   1.3225
184          parut    5.398631   15.761180   Topic4  -4.4324   1.7331
174           kayu    5.805863   17.896642   Topic4  -4.3597   1.6788
569         slices    4.634963   15.189433   Topic4  -4.5849   1.6176
99          ukuran    4.807912   16.183918   Topic4  -4.5483   1.5908
60            iris   19.704105  136.659954   Topic4  -3.1377   0.8679
79         cengkeh    5.067056   20.138050   Topic4  -4.4958   1.4247
35            gram    8.071101   40.416671   Topic4  -4.0302   1.1936
3            manis   16.060682  120.730254   Topic4  -3.3421   0.7874
59            pala    4.890094   22.258985   Topic4  -4.5313   1.2890
14           bubuk   14.912624  148.566338   Topic4  -3.4163   0.5057
61            jahe   10.063318   80.385939   Topic4  -3.8096   0.7266
44          goreng    7.779318   52.150973   Topic4  -4.0671   0.9019
77            ruas    8.225636   67.577448   Topic4  -4.0113   0.6985
47           bumbu   11.315078  146.561113   Topic4  -3.6924   0.2432
42          bawang   15.280613  443.272675   Topic4  -3.3919  -0.5631
64            sapi    8.540639  153.026373   Topic4  -3.9737  -0.0812
41            daun    7.414152  158.076115   Topic4  -4.1151  -0.2551
85           garam    7.190927  160.761129   Topic4  -4.1457  -0.3026
13            lada    6.115308   93.299376   Topic4  -4.3077   0.0795
131            ijo    6.210986    6.880930   Topic5  -4.1362   2.8581
480      kayumanis    5.090708    5.759939   Topic5  -4.3351   2.8370
668           laja    4.776041    5.444470   Topic5  -4.3989   2.8295
651         airnya    4.776035    5.444472   Topic5  -4.3989   2.8295
26             lbr   19.538790   22.516084   Topic5  -2.9902   2.8187
787      garamroco    4.373293    5.041585   Topic5  -4.4870   2.8183
788      sasakecap    4.373293    5.041585   Topic5  -4.4870   2.8183
789      rawitklau    4.373293    5.041585   Topic5  -4.4870   2.8183
783     sangraidan    4.373152    5.041648   Topic5  -4.4871   2.8183
784        diambil    4.373152    5.041648   Topic5  -4.4871   2.8183
200           utuh    3.529587    4.203066   Topic5  -4.7014   2.7859
666         presto    4.584113    6.069092   Topic5  -4.4400   2.6799
155            kol    7.459389   10.131322   Topic5  -3.9531   2.6543
359        direbus    1.509910    2.187959   Topic5  -5.5505   2.5896
317          pedas    1.430333    2.100007   Topic5  -5.6046   2.5765
170         rempah    1.115712    1.784470   Topic5  -5.8531   2.4909
143            btg   13.910954   22.383437   Topic5  -3.3299   2.4849
157          fiber    1.028542    1.696774   Topic5  -5.9344   2.4599
652          encer    0.888128    1.556951   Topic5  -6.0812   2.3991
549           soto    0.887803    1.556927   Topic5  -6.0816   2.3988
605       dirajang    0.887091    1.557995   Topic5  -6.0824   2.3973
156           sere    0.800955    1.469169   Topic5  -6.1845   2.3539
479        jengkol    0.800763    1.469257   Topic5  -6.1847   2.3536
459          taoge    0.800679    1.469336   Topic5  -6.1848   2.3534
424        tingkat    0.800138    1.469947   Topic5  -6.1855   2.3523
364   buncispotong    0.798578    1.469414   Topic5  -6.1875   2.3507
481          pekak    0.798212    1.469514   Topic5  -6.1879   2.3502
363     jahegeprek    0.798196    1.469567   Topic5  -6.1880   2.3501
461          belah    0.798583    1.472044   Topic5  -6.1875   2.3489
464     pendamping    0.797384    1.470124   Topic5  -6.1890   2.3487
568           kara    8.787666   17.941790   Topic5  -3.7892   2.2467

Topic: 1
baput, bamer, iris, seruas, menyesuaikan, terasi, gelas, sirloin, haluskan, skip, tipis, sour, smua, mebeli, dipake, indomie, hijaupotong, seujung, limau, matah, kemangi, cuci, bersih, panas, cabe, steak, grain, milk, lemon, juice

Topic: 2
buah, iris, manis, bawang, bubuk, kelapa, bumbu, cemplung, menumis, jahe, black, paper, sapi, ruas, gram, goreng, dihaluskan, daun, tetelan, garam, lawang, seledri, aromatik, lada, pelengkap, kayu, parut, cengkeh, pala, ukuran

Topic: 3
bubuk, telur, air, bawang, rebus, resep, halus, lihat, kaldu, butir, iris, tepung, merica, daun, sauce, taburan, btg, potongpotong, sapi, soy, butiran, kentang, diskip, gula, garam, daging, liter, kurangi, madunya, takaran

Topic: 4
bumbu, lbr, daun, btg, sapi, salam, daging, sereh, kara, kemiri, cabe, halus, butir, ketumbar, kunyit, kol, lengkuas, gula, lada, santan, ijo, kelapa, kayumanis, bawang, laja, airnya, tomat, presto, rawitklau, sasakecap

Topic: 5
bawang, merah, siung, daun, bumbu, putih, buah, gula, garam, sapi, butir, lembar, selera, daging, sesuai, jahe, air, ruas, geprek, manis, batang, halus, jeruk, salam, bubuk, kecap, tomat, goreng, kemiri, cabe

Topic: 6
sayur, saus, gram, garam, oil, putih, sdk, beef, telur, bawang, manis, butir, sejumput, tumisan, kering, buncis, margarine, jagung, kocok, nasi, sendok, olive, irisiris, dipipil, egg, scramble, sdmolive, bubuk, slice, aja

Topic: 7
bawang, putih, kecap, buah, iris, siung, air, daging, saus, bubuk, bombay, garam, tiram, wijen, sapi, manis, lada, beef, cincang, kaldu, gula, merah, asin, halus, tambahan, maizena, saos, tipis, jamur, tepung

[(0,
  '0.053*"baput" + 0.038*"bamer" + 0.014*"iris" + 0.012*"seruas" + 0.010*"menyesuaikan" + 0.010*"terasi" + 0.010*"gelas" + 0.009*"sirloin" + 0.008*"haluskan" + 0.008*"skip"'),
 (1,
  '0.113*"buah" + 0.043*"iris" + 0.035*"manis" + 0.034*"bawang" + 0.033*"bubuk" + 0.029*"kelapa" + 0.025*"bumbu" + 0.024*"cemplung" + 0.023*"menumis" + 0.022*"jahe"'),
 (2,
  '0.033*"bubuk" + 0.032*"telur" + 0.031*"air" + 0.030*"bawang" + 0.029*"rebus" + 0.025*"resep" + 0.025*"halus" + 0.024*"lihat" + 0.023*"kaldu" + 0.022*"butir"'),
 (3,
  '0.057*"bumbu" + 0.050*"lbr" + 0.047*"daun" + 0.036*"btg" + 0.034*"sapi" + 0.024*"salam" + 0.024*"daging" + 0.024*"sereh" + 0.023*"kara" + 0.022*"kemiri"'),
 (4,
  '0.065*"bawang" + 0.049*"merah" + 0.044*"siung" + 0.036*"daun" + 0.029*"bumbu" + 0.028*"putih" + 0.028*"buah" + 0.026*"gula" + 0.025*"garam" + 0.024*"sapi"'),
 (5,
  '0.075*"sayur" + 0.063*"saus" + 0.058*"gram" + 0.040*"garam" + 0.028*"oil" + 0.028*"putih" + 0.025*"sdk" + 0.024*"beef" + 0.023*"telur" + 0.023*"bawang"'),
 (6,
  '0.077*"bawang" + 0.044*"putih" + 0.036*"kecap" + 0.034*"buah" + 0.032*"iris" + 0.031*"siung" + 0.028*"air" + 0.027*"daging" + 0.027*"saus" + 0.026*"bubuk"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sapiCpdProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sapiCpdProb["sapi"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
sapiCpdWN = dfWordnet.copy()

sapiCpdWN["Synonym_clean"] = cleanWN_Synonym(sapiCpdWN["Synonym"])
sapiCpdWN["Hypernim_clean"] = cleanWN(sapiCpdWN["Hypernim"])
sapiCpdWN["Hyponim_clean"] = cleanWN(sapiCpdWN["Hyponim"])
sapiCpdWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/sapiCookpad.owl")
makeOntology(ontoName, sapiCpdWN)
ontoName.save(file = "sapiCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown --id "1VB_hbAtT1k3woShItXm2NVOZLWB4LLhk"

In [ ]:
wiki_sapi_cpd = pd.read_excel("SapiCookpadFinal.xlsx").iloc[:, 1:]

# Translate
wiki_sapi_cpd["Category"] = translate(wiki_sapi_cpd["Category"])
wiki_sapi_cpd.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_sapi_cpd[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
sapiCpdTabel_new = tabel_1981.copy()
sapiCpdTabel_new["correct_category"] = all_cat
sapiCpdTabel_new["suggestion"] = all_suggestion

# Export Result to File
sapiCpdTabel_new.to_excel("sapiCpdTabel_Result.xlsx")
sapiCpdTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiCpdTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
sapiCpdTabel_new = concatListInColumn(sapiCpdTabel_new)
sapiCpdTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, sapiCpdTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_sapi_cpd.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

In [ ]:
sapiCpdWiki_new = wiki_df.copy()
sapiCpdWiki_new["suggest"] = all_cat

# Export Result to file
sapiCpdWiki_new.to_excel("sapiCpdWiki_Result.xlsx")
sapiCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
sapiCpdOntoWiki = get_ontology("http://test.org/sapiCpd_onto_wiki.owl")
makeOntology_wiki(sapiCpdOntoWiki, sapiCpdWiki_new)
sapiCpdOntoWiki.save(file = "sapiCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = sapiCpdWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
sapiCpdWN_new = listToDataframe(changesList, tableWordnet)
sapiCpdWN_new.to_excel("sapiCpdWN_Result.xlsx")
sapiCpdWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "sapiCpdWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Tahu - Cookpad

In [ ]:
!gdown 1H4AQrK-VnNAhhx0hevdTAPr9UFRcquoI

Downloading...
From: https://drive.google.com/uc?id=1H4AQrK-VnNAhhx0hevdTAPr9UFRcquoI
To: /content/cookpad-selenium_tahu.jl
100% 396k/396k [00:00<00:00, 78.8MB/s]

In [ ]:
cps_tahu = pd.read_json(r'/content/cookpad-selenium_tahu.jl', lines = True)
print(f'NaN page description: {len(cps_tahu.loc[cps_tahu["page_description"].isna()])}')

# fill NaN with empty string
cps_tahu["page_description"] = cps_tahu["page_description"].fillna("")

# covnert page_description to list
cps_tahu["temp"] = cps_tahu["page_description"]
cps_tahu = concat_bahan_langkah(cps_tahu)
cps_tahu["page_description"] = cps_tahu["page_bahan_langkah"]

# clean text
cps_tahu = pre_cleaning_text(cps_tahu, threshold = 20)

NaN page description: 34

## GUI Tahu - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = cps_tahu.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
3     -0.161535 -0.073724       1        1  50.938766
0     -0.123733  0.053217       2        1  22.076286
6     -0.145807 -0.018596       3        1  11.102594
2     -0.047562  0.219558       4        1   4.892865
4      0.005917 -0.193662       5        1   4.852979
1      0.226136 -0.014493       6        1   4.700520
5      0.246584  0.027699       7        1   1.435990, topic_info=                Term        Freq       Total Category  logprob  loglift
1               buah  296.000000  296.000000  Default  30.0000  30.0000
9              bubuk  156.000000  156.000000  Default  29.0000  29.0000
18            bawang  378.000000  378.000000  Default  28.0000  28.0000
8              kaldu  120.000000  120.000000  Default  27.0000  27.0000
5             tepung   75.000000   75.000000  Default  26.0000  26.0000
7              garam  191.000000  191.000000  Default  25.0000  25.0000
34             rawit   66.000000   66.000000  Default  24.0000  24.0000
2              putih  237.000000  237.000000  Default  23.0000  23.0000
41             merah  153.000000  153.000000  Default  22.0000  22.0000
56             telur   77.000000   77.000000  Default  21.0000  21.0000
123             lada   59.000000   59.000000  Default  20.0000  20.0000
33              cabe  123.000000  123.000000  Default  19.0000  19.0000
178             ikat   29.000000   29.000000  Default  18.0000  18.0000
36            selera   45.000000   45.000000  Default  17.0000  17.0000
16            batang   87.000000   87.000000  Default  16.0000  16.0000
24            wortel   58.000000   58.000000  Default  15.0000  15.0000
52            goreng   64.000000   64.000000  Default  14.0000  14.0000
146             iris   70.000000   70.000000  Default  13.0000  13.0000
22             halus   69.000000   69.000000  Default  12.0000  12.0000
20             siung  192.000000  192.000000  Default  11.0000  11.0000
15              ayam   48.000000   48.000000  Default  10.0000  10.0000
12               air   87.000000   87.000000  Default   9.0000   9.0000
30             bumbu   80.000000   80.000000  Default   8.0000   8.0000
285          genggam   17.000000   17.000000  Default   7.0000   7.0000
44            terigu   26.000000   26.000000  Default   6.0000   6.0000
187            resep   15.000000   15.000000  Default   5.0000   5.0000
105              nya   22.000000   22.000000  Default   4.0000   4.0000
325          secukup   22.000000   22.000000  Default   3.0000   3.0000
145            rebus   20.000000   20.000000  Default   2.0000   2.0000
172          cincang   30.000000   30.000000  Default   1.0000   1.0000
3              butir   77.815843   78.393323   Topic1  -3.6984   0.6672
76             salam   35.441148   36.017891   Topic1  -4.4849   0.6584
23              biji   28.444418   29.021668   Topic1  -4.7048   0.6545
166            kulit   27.648184   28.226159   Topic1  -4.7332   0.6539
70            kemiri   25.883988   26.460638   Topic1  -4.7991   0.6525
68            kunyit   25.378851   25.955477   Topic1  -4.8188   0.6521
72            geprek   25.998790   26.599899   Topic1  -4.7947   0.6517
77             jeruk   20.690019   21.267412   Topic1  -5.0231   0.6470
67              ruas   20.510538   21.087304   Topic1  -5.0318   0.6468
120           kuning   20.005222   20.582089   Topic1  -5.0568   0.6461
73          lengkuas   18.021756   18.598593   Topic1  -5.1612   0.6430
663           rolade   17.841565   18.418072   Topic1  -5.1712   0.6427
221            serai   17.409504   17.985915   Topic1  -5.1957   0.6420
81            santan   14.234954   14.811834   Topic1  -5.3970   0.6348
96             tempe   14.112180   14.701586   Topic1  -5.4057   0.6336
260          kriting   12.143337   12.720061   Topic1  -5.5560   0.6281
469              ons   11.494827   12.071283   Topic1  -5.6108   0.6256
259           pisang   11.314602   11.890863   Topic1  -5.6267   0.6249
300           lumpia   11.306866   11.887523   Topic1  -5.6273   0.6245
304           mentah   11.125662   11.706701   Topic1  -5.6435   0.6236
75               lbr   10.627971   11.205127   Topic1  -5.6893   0.6217
641       bahanbahan    9.006421    9.582641   Topic1  -5.8548   0.6125
642           orange    9.006421    9.582641   Topic1  -5.8548   0.6125
129            royco    7.741217    8.319247   Topic1  -6.0062   0.6025
74             sereh    7.563490    8.140161   Topic1  -6.0294   0.6011
361             jari    6.734117    7.310826   Topic1  -6.1456   0.5924
80            sachet    6.552068    7.129616   Topic1  -6.1730   0.5901
415            bakso    6.437908    7.018544   Topic1  -6.1905   0.5882
373              teh    5.610630    6.190774   Topic1  -6.3281   0.5761
216            kupas    5.255191    5.832100   Topic1  -6.3935   0.5704
56             telur   69.090368   77.195754   Topic1  -3.8173   0.5636
47          ketumbar   19.913937   22.484024   Topic1  -5.0613   0.5532
41             merah  130.358988  153.397883   Topic1  -3.1825   0.5118
16            batang   74.820814   87.979079   Topic1  -3.7376   0.5125
17              daun  132.802137  177.710379   Topic1  -3.1639   0.3833
22             halus   55.106010   69.621242   Topic1  -4.0435   0.4407
1               buah  205.714972  296.854153   Topic1  -2.7263   0.3078
33              cabe   89.887060  123.149100   Topic1  -3.5542   0.3597
34             rawit   50.543687   66.557810   Topic1  -4.1299   0.3993
18            bawang  223.440262  378.256702   Topic1  -2.6436   0.1481
20             siung  120.612136  192.136324   Topic1  -3.2602   0.2089
28              gula   70.249348  106.138936   Topic1  -3.8007   0.2618
2              putih  129.814746  237.749687   Topic1  -3.1866   0.0694
7              garam  106.253957  191.820641   Topic1  -3.3869   0.0838
92            lembar   38.789830   56.208105   Topic1  -4.3946   0.3036
25            ukuran   32.216931   45.246235   Topic1  -4.5803   0.3349
79             pasir   25.000638   32.570863   Topic1  -4.8338   0.4100
8              kaldu   57.409132  120.590571   Topic1  -4.0025  -0.0677
24            wortel   36.303122   58.704577   Topic1  -4.4608   0.1939
30             bumbu   44.018195   80.680856   Topic1  -4.2681   0.0686
9              bubuk   63.426566  156.273190   Topic1  -3.9029  -0.2272
15              ayam   30.026145   48.938971   Topic1  -4.6507   0.1860
27             tiram   27.289936   46.799250   Topic1  -4.7462   0.1352
12               air   31.916735   87.577130   Topic1  -4.5896  -0.3348
26             jamur   27.326468   52.480770   Topic1  -4.7449   0.0220
10            merica   26.149525   52.353900   Topic1  -4.7889  -0.0196
172          cincang   30.333573   30.937996   Topic2  -3.8044   1.4909
148             asin   29.786777   30.391155   Topic2  -3.8226   1.4906
208            tipis   20.168841   20.772970   Topic2  -4.2125   1.4812
515     potongpotong   17.799635   18.404777   Topic2  -4.3374   1.4772
179             sawi   13.251263   13.854980   Topic2  -4.6325   1.4661
199           bersih   11.855490   12.459033   Topic2  -4.7438   1.4610
198             cuci    9.913709   10.517106   Topic2  -4.9227   1.4516
133             saos    9.639936   10.244202   Topic2  -4.9507   1.4499
240           buncis    9.516613   10.123165   Topic2  -4.9636   1.4489
54            rendam    9.364786    9.969906   Topic2  -4.9797   1.4481
252         margarin    8.821344    9.424781   Topic2  -5.0395   1.4445
643          kembang    7.577500    8.180820   Topic2  -5.1914   1.4341
644  memarkancincang    7.577500    8.180820   Topic2  -5.1914   1.4341
640           sajiku    7.577299    8.180722   Topic2  -5.1915   1.4340
238           serong    6.666317    7.270892   Topic2  -5.3196   1.4239
174             ikan    5.662555    6.268309   Topic2  -5.4828   1.4090
225        serbaguna    4.966718    5.571306   Topic2  -5.6139   1.3958
94              skip    6.511356    7.542783   Topic2  -5.3431   1.3636
284       dihaluskan    3.326915    3.932849   Topic2  -6.0146   1.3433
35            sesuai   27.819229   33.544529   Topic2  -3.8909   1.3235
226           keping    2.872718    3.477979   Topic2  -6.1614   1.3195
223           jepang    2.782637    3.386769   Topic2  -6.1932   1.3142
170             sagu    2.780657    3.385868   Topic2  -6.1939   1.3137
59           taburan    2.629211    3.234353   Topic2  -6.2499   1.3035
140          maizena   10.285138   12.715972   Topic2  -4.8859   1.2985
281           baking    2.478500    3.082969   Topic2  -6.3090   1.2924
282           powder    2.478500    3.082969   Topic2  -6.3090   1.2924
249            sutra    2.084471    2.688650   Topic2  -6.4821   1.2561
190             beli    2.083494    2.688438   Topic2  -6.4826   1.2558
194        besariris    2.082952    2.688337   Topic2  -6.4828   1.2555
146             iris   50.581561   70.251610   Topic2  -3.2930   1.1822
224            wijen   14.691782   21.408779   Topic2  -4.5293   1.1342
36            selera   29.291723   45.847738   Topic2  -3.8393   1.0626
111            kotak   24.347976   38.376695   Topic2  -4.0242   1.0557
203              btg   11.734881   18.444235   Topic2  -4.7541   1.0585
200             dadu    8.650348   13.460429   Topic2  -5.0590   1.0685
42             kecap   26.853899   54.837443   Topic2  -3.9262   0.7967
321         digoreng    9.177297   14.601438   Topic2  -4.9999   1.0463
10            merica   25.771363   52.353900   Topic2  -3.9674   0.8019
26             jamur   24.721360   52.480770   Topic2  -4.0090   0.7579
135             saus   21.475190   46.599366   Topic2  -4.1497   0.7360
8              kaldu   42.765606  120.590571   Topic2  -3.4609   0.4740
28              gula   35.456571  106.138936   Topic2  -3.6483   0.4142
18            bawang   78.612597  378.256702   Topic2  -2.8521  -0.0604
12               air   29.546404   87.577130   Topic2  -3.8307   0.4241
2              putih   54.285888  237.749687   Topic2  -3.2224   0.0337
20             siung   47.206006  192.136324   Topic2  -3.3621   0.1070
9              bubuk   40.367141  156.273190   Topic2  -3.5186   0.1571
123             lada   22.852093   59.014810   Topic2  -4.0876   0.5619
7              garam   40.928190  191.820641   Topic2  -3.5048  -0.0341
27             tiram   19.075340   46.799250   Topic2  -4.2682   0.6132
33              cabe   22.576442  123.149100   Topic2  -4.0997  -0.1858
5             tepung   18.541204   75.990814   Topic2  -4.2966   0.1000
17              daun   23.218765  177.710379   Topic2  -4.0717  -0.5245
30             bumbu   17.248381   80.680856   Topic2  -4.3689  -0.0321
1               buah   20.763112  296.854153   Topic2  -4.1834  -1.1494
92            lembar   12.652046   56.208105   Topic2  -4.6788   0.0194
105              nya   21.836687   22.505531   Topic3  -3.4457   2.1678
325          secukup   21.538866   22.207709   Topic3  -3.4594   2.1674
121            tauge    6.762214    7.432620   Topic3  -4.6180   2.1035
438           adonan    5.191179    5.860203   Topic3  -4.8823   2.0768
239             kobe    4.810495    5.479731   Topic3  -4.9585   2.0677
607              kol    4.512886    5.181728   Topic3  -5.0224   2.0598
595           meggie    4.512433    5.182172   Topic3  -5.0225   2.0596
645        mengoreng    4.132298    4.801099   Topic3  -5.1105   2.0480
646          sayuran    4.132298    4.801099   Topic3  -5.1105   2.0480
647              sdk    4.132298    4.801099   Topic3  -5.1105   2.0480
648       melarutkan    4.132298    4.801099   Topic3  -5.1105   2.0480
655            jambi    4.132287    4.801104   Topic3  -5.1105   2.0480
656             lupa    4.132287    4.801104   Topic3  -5.1105   2.0480
657          purpose    4.132287    4.801104   Topic3  -5.1105   2.0480
658           gluten    4.132287    4.801104   Topic3  -5.1105   2.0480
659             free    4.132287    4.801104   Topic3  -5.1105   2.0480
664          lumayan    4.132055    4.801261   Topic3  -5.1105   2.0479
665             cube    4.132055    4.801261   Topic3  -5.1105   2.0479
666              sbg    4.132055    4.801261   Topic3  -5.1105   2.0479
168             toge    5.578066    6.740949   Topic3  -4.8105   2.0086
131          kemangi    5.559658    7.014644   Topic3  -4.8138   1.9655
184             pong    2.493881    3.163656   Topic3  -5.6155   1.9601
219          kentang   14.054906   18.160156   Topic3  -3.8863   1.9417
139            baput    6.195399    8.570322   Topic3  -4.7055   1.8735
251         haluskan    7.827268   10.883510   Topic3  -4.4717   1.8684
303             dada    5.165474    7.366694   Topic3  -4.8873   1.8430
45             beras    3.213860    4.801313   Topic3  -5.3618   1.7966
60             kubis    1.136928    1.806712   Topic3  -6.4010   1.7348
253            micin    1.136026    1.807834   Topic3  -6.4018   1.7334
353          protein    1.054394    1.723607   Topic3  -6.4763   1.7065
32              gram    9.960278   16.451019   Topic3  -4.2307   1.6962
44            terigu   15.666461   26.501284   Topic3  -3.7778   1.6723
293              amp    4.557287    7.905035   Topic3  -5.0126   1.6472
5             tepung   31.369307   75.990814   Topic3  -3.0835   1.3132
24            wortel   21.869788   58.704577   Topic3  -3.4442   1.2106
15              ayam   18.413579   48.938971   Topic3  -3.6162   1.2205
123             lada   16.245681   59.014810   Topic3  -3.7415   0.9080
18            bawang   43.563547  378.256702   Topic3  -2.7551   0.0366
1               buah   29.520410  296.854153   Topic3  -3.1442  -0.1102
2              putih   26.389639  237.749687   Topic3  -3.2563  -0.0003
20             siung   23.791771  192.136324   Topic3  -3.3600   0.1091
12               air   15.614880   87.577130   Topic3  -3.7811   0.4737
7              garam   21.161797  191.820641   Topic3  -3.4771  -0.0064
52            goreng   12.989446   64.686717   Topic3  -3.9652   0.5926
17              daun   17.252085  177.710379   Topic3  -3.6814  -0.1342
30             bumbu   11.994465   80.680856   Topic3  -4.0449   0.2919
95           menumis    8.712271   36.994831   Topic3  -4.3646   0.7519
203              btg    6.181981   18.444235   Topic3  -4.7077   1.1049
9              bubuk   10.372919  156.273190   Topic3  -4.1901  -0.5144
25            ukuran    7.501433   45.246235   Topic3  -4.5142   0.4010
29        menggoreng    6.246561   25.279558   Topic3  -4.6973   0.8000
270           daging    6.010294   23.430568   Topic3  -4.7358   0.8374
22             halus    6.611277   69.621242   Topic3  -4.6405  -0.1563
41             merah    6.682462  153.397883   Topic3  -4.6298  -0.9356
16            batang    5.755404   87.979079   Topic3  -4.7792  -0.5290
606             prei    8.694892    9.364143   Topic4  -3.5472   2.9432
237            kocok    6.562365    7.231001   Topic4  -3.8285   2.9204
278        sesuaikan    5.185274    5.853509   Topic4  -4.0641   2.8962
570         pencelup    4.967221    5.635056   Topic4  -4.1070   2.8912
660            cabut    4.194593    4.862318   Topic4  -4.2761   2.8697
661             saji    4.194593    4.862318   Topic4  -4.2761   2.8697
662       mencairkan    4.194593    4.862318   Topic4  -4.2761   2.8697
501             blok    4.967175    5.988224   Topic4  -4.1070   2.8304
499          daunnya    4.193915    5.692378   Topic4  -4.2763   2.7119
342         singkong    1.154424    1.822469   Topic4  -5.5663   2.5608
548              egg    0.852135    1.520207   Topic4  -5.8699   2.4385
549             roll    0.852135    1.520207   Topic4  -5.8699   2.4385
635          sepucuk    0.852064    1.520152   Topic4  -5.8700   2.4385
526             nori    0.852009    1.520272   Topic4  -5.8701   2.4383
409              dgn    0.768091    1.436102   Topic4  -5.9737   2.3916
21      putihcincang    0.683968    1.352298   Topic4  -6.0897   2.3357
569            kepal    0.465929    1.133739   Topic4  -6.4736   2.1281
571     kekentalanya    0.465929    1.133739   Topic4  -6.4736   2.1281
605              isi    0.465868    1.133748   Topic4  -6.4738   2.1280
568            kriuk    0.465860    1.133763   Topic4  -6.4738   2.1280
532              aci    0.465689    1.133824   Topic4  -6.4741   2.1276
533         mendidih    0.465689    1.133824   Topic4  -6.4741   2.1276
550           bombai    0.465678    1.133936   Topic4  -6.4742   2.1274
551      kecilsedang    0.465678    1.133936   Topic4  -6.4742   2.1274
611            rawon    0.465642    1.134073   Topic4  -6.4742   2.1272
612         mahmudah    0.465642    1.134073   Topic4  -6.4742   2.1272
471    putihhaluskan    0.465579    1.133968   Topic4  -6.4744   2.1272
472      wortelserut    0.465579    1.133968   Topic4  -6.4744   2.1272
473      sosispotong    0.465579    1.133968   Topic4  -6.4744   2.1272
474    seledrirajang    0.465579    1.133968   Topic4  -6.4744   2.1272
44            terigu    8.691754   26.501284   Topic4  -3.5475   1.9026
9              bubuk   41.745349  156.273190   Topic4  -1.9783   1.6974
5             tepung   20.683999   75.990814   Topic4  -2.6805   1.7161
123             lada   15.479057   59.014810   Topic4  -2.9704   1.6791
36            selera   10.288068   45.847738   Topic4  -3.3789   1.5231
8              kaldu   17.351200  120.590571   Topic4  -2.8562   1.0787
7              garam   18.232569  191.820641   Topic4  -2.8067   0.6640
56             telur    7.559621   77.195754   Topic4  -3.6871   0.6939
22             halus    6.206270   69.621242   Topic4  -3.8843   0.5999
2              putih   13.199855  237.749687   Topic4  -3.1297   0.1264
12               air    7.007837   87.577130   Topic4  -3.7629   0.4919
16            batang    6.785447   87.979079   Topic4  -3.7951   0.4551
227            sosis    1.469553    7.555497   Topic4  -5.3249   1.3801
140          maizena    1.906204   12.715972   Topic4  -5.0648   1.1196
18            bawang    8.897392  378.256702   Topic4  -3.5241  -0.7324
512            bayam    9.989064   10.652087   Topic5  -3.4002   2.9613
118             merk    7.734803    8.398231   Topic5  -3.6560   2.9433
358          pelapis    6.553228    7.215274   Topic5  -3.8218   2.9293
475          brokoli    6.314071    6.975416   Topic5  -3.8589   2.9260
87             pedas    4.945241    5.607247   Topic5  -4.1033   2.8999
649          broiler    4.614971    5.274676   Topic5  -4.1724   2.8920
650        putihtahu    4.614971    5.274676   Topic5  -4.1724   2.8920
651            china    4.614971    5.274676   Topic5  -4.1724   2.8920
652           sakset    4.614971    5.274676   Topic5  -4.1724   2.8920
653              sup    4.614971    5.274676   Topic5  -4.1724   2.8920
654            racik    4.614971    5.274676   Topic5  -4.1724   2.8920
154             tofu    2.117743    2.781067   Topic5  -4.9514   2.7531
84            terong    1.270276    1.930185   Topic5  -5.4625   2.6072
88            terasi    1.270251    1.930188   Topic5  -5.4625   2.6072
359             roti    1.269579    1.930373   Topic5  -5.4630   2.6065
155          paprika    1.269444    1.930732   Topic5  -5.4631   2.6063
91          tambahan    1.269066    1.931049   Topic5  -5.4634   2.6058
164         sejumput   10.887370   17.721488   Topic5  -3.3141   2.5384
230              kbe    0.752827    1.412514   Topic5  -5.9856   2.3963
180           sambal    2.845193    5.866670   Topic5  -4.6561   2.3019
572            gelas    0.512652    1.172425   Topic5  -6.3699   2.1983
573        kebutuhan    0.512652    1.172425   Topic5  -6.3699   2.1983
574           gongso    0.512652    1.172425   Topic5  -6.3699   2.1983
575            bahas    0.512652    1.172425   Topic5  -6.3699   2.1983
576            block    0.512652    1.172425   Topic5  -6.3699   2.1983
577             silk    0.512652    1.172425   Topic5  -6.3699   2.1983
578           krispi    0.512652    1.172425   Topic5  -6.3699   2.1983

Topic: 1
bawang, putih, iris, siung, kaldu, garam, bubuk, gula, cincang, asin, air, selera, sesuai, kecap, merica, jamur, kotak, daun, lada, cabe, saus, buah, tipis, tiram, tepung, potongpotong, bumbu, wijen, sawi, lembar

Topic: 2
genggam, resep, ikat, goreng, segenggam, cabe, lihat, rebus, kacang, rajang, rawit, irisan, makaroni, serut, aldente, asli, petis, sayur, seledri, lada, putih, lontong, kerupuk, air, kecap, ijo, manis, garam, taoge, pelengkap

Topic: 3
bubuk, tepung, garam, kaldu, lada, putih, selera, bawang, prei, terigu, telur, air, batang, kocok, halus, sesuaikan, pencelup, blok, saji, mencairkan, cabut, daunnya, maizena, sosis, singkong, roll, egg, sepucuk, nori, dgn

Topic: 4
bawang, buah, daun, merah, putih, siung, garam, cabe, butir, batang, gula, telur, bubuk, kaldu, halus, rawit, bumbu, lembar, wortel, salam, ukuran, air, ayam, biji, kulit, jamur, tiram, merica, geprek, kemiri

Topic: 5
buah, bawang, sejumput, putih, bayam, merah, rawit, merk, tomat, bumbu, pelapis, brokoli, goreng, tepung, pedas, cabai, racik, putihtahu, china, sup, broiler, sakset, daun, sambal, garam, tofu, pakai, cabe, terong, terasi

Topic: 6
homemade, mangkok, hancurkan, sdh, bentuk, nugget, lmbr, kuranglebih, dirajang, pok, skipkuranglebih, mentega, bonggol, dipotong, bebas, kurangsesuai, lalapan, tahupotong, ikanirisiris, cooking, wine, jamurtotole, ladamerica, ribuiris, garamgulabumbu, tempesaya, penyedapkecap, tahuiris, pete, airnya

Topic: 7
bawang, tepung, buah, putih, siung, wortel, nya, secukup, garam, ayam, daun, lada, terigu, air, kentang, goreng, bumbu, bubuk, gram, menumis, haluskan, ukuran, tauge, merah, halus, menggoreng, baput, btg, daging, batang

[(0,
  '0.058*"bawang" + 0.040*"putih" + 0.037*"iris" + 0.035*"siung" + 0.031*"kaldu" + 0.030*"garam" + 0.030*"bubuk" + 0.026*"gula" + 0.022*"cincang" + 0.022*"asin"'),
 (1,
  '0.057*"genggam" + 0.052*"resep" + 0.048*"ikat" + 0.031*"goreng" + 0.031*"segenggam" + 0.030*"cabe" + 0.027*"lihat" + 0.024*"rebus" + 0.024*"kacang" + 0.024*"rajang"'),
 (2,
  '0.138*"bubuk" + 0.069*"tepung" + 0.060*"garam" + 0.057*"kaldu" + 0.051*"lada" + 0.044*"putih" + 0.034*"selera" + 0.029*"bawang" + 0.029*"prei" + 0.029*"terigu"'),
 (3,
  '0.071*"bawang" + 0.065*"buah" + 0.042*"daun" + 0.041*"merah" + 0.041*"putih" + 0.038*"siung" + 0.034*"garam" + 0.029*"cabe" + 0.025*"butir" + 0.024*"batang"'),
 (4,
  '0.136*"buah" + 0.078*"bawang" + 0.036*"sejumput" + 0.034*"putih" + 0.033*"bayam" + 0.032*"merah" + 0.030*"rawit" + 0.026*"merk" + 0.025*"tomat" + 0.024*"bumbu"'),
 (5,
  '0.047*"homemade" + 0.047*"mangkok" + 0.046*"hancurkan" + 0.013*"sdh" + 0.013*"bentuk" + 0.009*"nugget" + 0.009*"lmbr" + 0.009*"kuranglebih" + 0.009*"dirajang" + 0.009*"pok"'),
 (6,
  '0.064*"bawang" + 0.046*"tepung" + 0.043*"buah" + 0.039*"putih" + 0.035*"siung" + 0.032*"wortel" + 0.032*"nya" + 0.031*"secukup" + 0.031*"garam" + 0.027*"ayam"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sTahuProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sTahuProb["bawang"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
cpsTahuWN = dfWordnet.copy()

cpsTahuWN["Synonym_clean"] = cleanWN_Synonym(cpsTahuWN["Synonym"])
cpsTahuWN["Hypernim_clean"] = cleanWN(cpsTahuWN["Hypernim"])
cpsTahuWN["Hyponim_clean"] = cleanWN(cpsTahuWN["Hyponim"])
cpsTahuWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/tahuCookpad.owl")
makeOntology(ontoName, cpsTahuWN)
ontoName.save(file = "tahuCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown 1RVnjWTvdYu4b-kDFrhfRcaKcK7RfYjoe

In [ ]:
wiki_tahu_sln = pd.read_excel("TahuCookpadFinal.xlsx").iloc[:, 1:]
wiki_tahu_sln.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_tahu_sln["Category"] = translate(wiki_tahu_sln["Category"])
wiki_tahu_sln.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_tahu_sln[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
tahuSlnTabel_new = tabel_1981.copy()
tahuSlnTabel_new["correct_category"] = all_cat
tahuSlnTabel_new["suggestion"] = all_suggestion

# Export Result to File
tahuSlnTabel_new.to_excel("tahuSlnTabel_Result.xlsx")
tahuSlnTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tahuSlnTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
tahuSlnTabel_new = concatListInColumn(tahuSlnTabel_new)
tahuSlnTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, tahuSlnTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_tahu_sln.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
tahuCpdWiki_new = wiki_df.copy()
tahuCpdWiki_new["suggest"] = all_cat

# Export Result to file
tahuCpdWiki_new.to_excel("tahuCpdWiki_Result.xlsx")
tahuCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tahuCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
tahuCpdOntoWiki = get_ontology("http://test.org/tahuCpd_onto_wiki.owl")
makeOntology_wiki(tahuCpdOntoWiki, tahuCpdWiki_new)
tahuCpdOntoWiki.save(file = "tahuCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = cpsTahuWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
cpsTahuWN_new = listToDataframe(changesList, tableWordnet)
cpsTahuWN_new.to_excel("cpsTahuWN_Result.xlsx")
cpsTahuWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cpsTahuWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Telur - Cookpad

In [ ]:
!gdown 1RizCmOSgDG9krsvBFCieRQP5hpe9aIdW

Downloading...
From: https://drive.google.com/uc?id=1RizCmOSgDG9krsvBFCieRQP5hpe9aIdW
To: /content/cookpad-selenium_telur.jl
100% 384k/384k [00:00<00:00, 112MB/s]

In [ ]:
cps_telur = pd.read_json(r'/content/cookpad-selenium_telur.jl', lines = True)
print(f'NaN page description: {len(cps_telur.loc[cps_telur["page_description"].isna()])}')

# fill NaN with empty string
cps_telur["page_description"] = cps_telur["page_description"].fillna("")

# covnert page_description to list
cps_telur["temp"] = cps_telur["page_description"]
cps_telur = concat_bahan_langkah(cps_telur)
cps_telur["page_description"] = cps_telur["page_bahan_langkah"]

# clean text
cps_telur = pre_cleaning_text(cps_telur, threshold = 20)

NaN page description: 41

## GUI Telur - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = cps_telur.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sTelurProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sTelurProb["bawang"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
cpsTelurWN = dfWordnet.copy()

cpsTelurWN["Synonym_clean"] = cleanWN_Synonym(cpsTelurWN["Synonym"])
cpsTelurWN["Hypernim_clean"] = cleanWN(cpsTelurWN["Hypernim"])
cpsTelurWN["Hyponim_clean"] = cleanWN(cpsTelurWN["Hyponim"])
cpsTelurWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/telurCookpad.owl")
makeOntology(ontoName, cpsTelurWN)
ontoName.save(file = "telurCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown 1zDnVhtmf3HGT2YagYDYFxxmGM1hDm4QV

In [ ]:
wiki_telur_sln = pd.read_excel("TelurCookpadFinal.xlsx").iloc[:, 1:]
wiki_telur_sln.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_telur_sln["Category"] = translate(wiki_telur_sln["Category"])
wiki_telur_sln.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_telur_sln[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
telurSlnTabel_new = tabel_1981.copy()
telurSlnTabel_new["correct_category"] = all_cat
telurSlnTabel_new["suggestion"] = all_suggestion

# Export Result to File
telurSlnTabel_new.to_excel("telurSlnTabel_Result.xlsx")
telurSlnTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "telurSlnTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
telurSlnTabel_new = concatListInColumn(telurSlnTabel_new)
telurSlnTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, telurSlnTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_telur_sln.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
telurCpdWiki_new = wiki_df.copy()
telurCpdWiki_new["suggest"] = all_cat

# Export Result to file
telurCpdWiki_new.to_excel("telurCpdWiki_Result.xlsx")
telurCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "telurCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
telurCpdOntoWiki = get_ontology("http://test.org/telurCpd_onto_wiki.owl")
makeOntology_wiki(telurCpdOntoWiki, telurCpdWiki_new)
telurCpdOntoWiki.save(file = "telurCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = cpsTelurWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
cpsTelurWN_new = listToDataframe(changesList, tableWordnet)
cpsTelurWN_new.to_excel("cpsTelurWN_Result.xlsx")
cpsTelurWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cpsTelurWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Tempe Cookpad

In [ ]:
!gdown 1dpqsr-WMdFtALig6js2Lc7Xk_Nc7u4q_

Downloading...
From: https://drive.google.com/uc?id=1dpqsr-WMdFtALig6js2Lc7Xk_Nc7u4q_
To: /content/cookpad-selenium_tempe.jl
100% 401k/401k [00:00<00:00, 104MB/s]

In [ ]:
cps_tempe = pd.read_json(r'/content/cookpad-selenium_tempe.jl', lines = True)
print(f'NaN page description: {len(cps_tempe.loc[cps_tempe["page_description"].isna()])}')

# fill NaN with empty string
cps_tempe["page_description"] = cps_tempe["page_description"].fillna("")

# covnert page_description to list
cps_tempe["temp"] = cps_tempe["page_description"]
cps_tempe = concat_bahan_langkah(cps_tempe)
cps_tempe["page_description"] = cps_tempe["page_bahan_langkah"]

# clean text
cps_tempe = pre_cleaning_text(cps_tempe, threshold = 20)

NaN page description: 25

## GUI Tempe - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = cps_tempe.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2      0.241870  0.095309       1        1  39.662271
6      0.232971  0.022779       2        1  32.463099
3     -0.018340 -0.317111       3        1  13.611750
0      0.015337 -0.059538       4        1   8.269289
5     -0.088787  0.155886       5        1   2.165622
1     -0.200545  0.037830       6        1   1.991393
4     -0.182507  0.064846       7        1   1.836577, topic_info=              Term        Freq       Total Category  logprob  loglift
96          tepung   67.000000   67.000000  Default  30.0000  30.0000
21            buah  170.000000  170.000000  Default  29.0000  29.0000
35           merah  177.000000  177.000000  Default  28.0000  28.0000
45           bubuk  117.000000  117.000000  Default  27.0000  27.0000
27             air  154.000000  154.000000  Default  26.0000  26.0000
28            gula   90.000000   90.000000  Default  25.0000  25.0000
95            gram   63.000000   63.000000  Default  24.0000  24.0000
104           ragi   51.000000   51.000000  Default  23.0000  23.0000
37          bawang  251.000000  251.000000  Default  22.0000  22.0000
22            cabe  105.000000  105.000000  Default  21.0000  21.0000
232         terigu   33.000000   33.000000  Default  20.0000  20.0000
99         kedelai   42.000000   42.000000  Default  19.0000  19.0000
24            iris   80.000000   80.000000  Default  18.0000  18.0000
16           tempe  232.000000  232.000000  Default  17.0000  17.0000
93          bersih   35.000000   35.000000  Default  16.0000  16.0000
12          batang   59.000000   59.000000  Default  15.0000  15.0000
44        ketumbar   57.000000   57.000000  Default  14.0000  14.0000
205        plastik   34.000000   34.000000  Default  13.0000  13.0000
60           butir   39.000000   39.000000  Default  12.0000  12.0000
87          goreng   56.000000   56.000000  Default  11.0000  11.0000
23           rawit   67.000000   67.000000  Default  10.0000  10.0000
191          liter   28.000000   28.000000  Default   9.0000   9.0000
54           telur   16.000000   16.000000  Default   8.0000   8.0000
14           garam  151.000000  151.000000  Default   7.0000   7.0000
135          pasir   19.000000   19.000000  Default   6.0000   6.0000
103        merebus   26.000000   26.000000  Default   5.0000   5.0000
36           siung  169.000000  169.000000  Default   4.0000   4.0000
140          resep   47.000000   47.000000  Default   3.0000   3.0000
102       merendam   23.000000   23.000000  Default   2.0000   2.0000
38           putih  159.000000  159.000000  Default   1.0000   1.0000
35           merah  176.772033  177.408272   Topic1  -2.5385   0.9212
22            cabe  105.317041  105.907057   Topic1  -3.0564   0.9192
23           rawit   66.690121   67.277052   Topic1  -3.5133   0.9160
20           jeruk   32.231296   32.818175   Topic1  -4.2405   0.9067
172       lengkuas   30.690653   31.277500   Topic1  -4.2894   0.9058
162          cabai   26.776548   27.368411   Topic1  -4.4259   0.9029
115       keriting   25.767975   26.354826   Topic1  -4.4643   0.9023
134         kencur   19.792950   20.379975   Topic1  -4.7281   0.8955
706            bwg   18.590956   19.177402   Topic1  -4.7907   0.8937
118          kecap   45.804383   47.287137   Topic1  -3.8890   0.8929
68             bks   15.355929   15.945027   Topic1  -4.9819   0.8871
125         sambal   21.658592   22.571519   Topic1  -4.6380   0.8835
150         geprek   13.329109   13.948105   Topic1  -5.1235   0.8794
648          gurih   11.977293   12.564099   Topic1  -5.2304   0.8769
445          racik   11.780016   12.374317   Topic1  -5.2470   0.8756
362        instant   10.920386   11.510681   Topic1  -5.3228   0.8721
19         kemangi   10.774538   11.361576   Topic1  -5.3362   0.8717
175           jawa   11.399261   12.029074   Topic1  -5.2799   0.8710
707       sejempol    9.384612    9.971058   Topic1  -5.4743   0.8642
708           limo    9.384612    9.971058   Topic1  -5.4743   0.8642
705     kepelpadat    9.384610    9.971057   Topic1  -5.4743   0.8642
59            biji   17.766622   18.892131   Topic1  -4.8361   0.8633
64            ikat    8.067070    8.655856   Topic1  -5.6256   0.8543
238           teri    7.693384    8.280177   Topic1  -5.6730   0.8513
11           sereh    7.693364    8.280250   Topic1  -5.6730   0.8513
174           asam    7.693129    8.280148   Topic1  -5.6731   0.8512
242      pelengkap    7.568654    8.163479   Topic1  -5.6894   0.8491
163         terasi    6.528510    7.115446   Topic1  -5.8372   0.8387
8           santan    6.339177    6.926866   Topic1  -5.8667   0.8361
236            lbr    5.964698    6.551426   Topic1  -5.9275   0.8309
61            ruas   20.368656   22.438812   Topic1  -4.6994   0.8280
28            gula   80.547676   90.503676   Topic1  -3.3246   0.8082
21            buah  137.682736  170.438238   Topic1  -2.7884   0.7113
55           tomat   22.065809   25.437161   Topic1  -4.6194   0.7826
39          kemiri   22.357106   26.171579   Topic1  -4.6063   0.7672
52           manis   24.176419   28.911413   Topic1  -4.5280   0.7459
67           hijau   16.361209   19.106532   Topic1  -4.9185   0.7697
38           putih  105.487123  159.592987   Topic1  -3.0548   0.5107
44        ketumbar   42.766327   57.399720   Topic1  -3.9577   0.6305
14           garam   92.309518  151.677366   Topic1  -3.1883   0.4282
36           siung   94.645399  169.328706   Topic1  -3.1633   0.3431
26          selera   23.371958   30.342900   Topic1  -4.5619   0.6637
37          bawang  119.166509  251.000064   Topic1  -2.9329   0.1798
153          salam   32.991235   47.973315   Topic1  -4.2172   0.5504
25          sesuai   21.795573   28.788801   Topic1  -4.6317   0.6465
16           tempe   76.756403  232.572346   Topic1  -3.3728  -0.1838
0             daun   50.475908  143.092143   Topic1  -3.7919  -0.1172
33           bumbu   37.445143   93.343154   Topic1  -4.0905   0.0114
34           halus   19.086488   44.443305   Topic1  -4.7644   0.0795
24            iris   79.933099   80.551151   Topic2  -3.1319   1.1174
140          resep   46.866222   47.485004   Topic2  -3.6658   1.1119
139          lihat   42.728783   43.347657   Topic2  -3.7582   1.1107
158           lada   29.043711   29.661981   Topic2  -4.1443   1.1040
88          ukuran   21.048838   21.667162   Topic2  -4.4663   1.0961
32          merica   17.250874   17.870556   Topic2  -4.6652   1.0898
420         bakwan   15.947141   16.565646   Topic2  -4.7438   1.0870
246           asin   15.419037   16.037464   Topic2  -4.7775   1.0857
189          parut   14.282002   14.908984   Topic2  -4.8541   1.0821
357       homemade   11.903730   12.522390   Topic2  -5.0363   1.0744
138           ayam   11.624521   12.242925   Topic2  -5.0600   1.0732
256           skip   11.623965   12.242729   Topic2  -5.0600   1.0732
235          baput   10.473955   11.091541   Topic2  -5.1642   1.0678
291         serong   10.442856   11.060673   Topic2  -5.1672   1.0676
419        seledri   10.161851   10.780242   Topic2  -5.1945   1.0660
230          tipis   10.037632   10.656226   Topic2  -5.2068   1.0653
234          bamer    9.758941   10.376261   Topic2  -5.2349   1.0637
462          bunga    9.198123    9.816118   Topic2  -5.2941   1.0600
463         telang    9.198123    9.816118   Topic2  -5.2941   1.0600
335        cincang    8.357863    8.976213   Topic2  -5.3899   1.0537
70            saos    7.083077    7.701443   Topic2  -5.5554   1.0414
17      menggoreng    7.081469    7.700556   Topic2  -5.5556   1.0413
65           sayur    6.989068    7.608282   Topic2  -5.5688   1.0402
181           dadu    6.926750    7.545673   Topic2  -5.5777   1.0395
133           nasi    6.119124    6.737333   Topic2  -5.7017   1.0288
60           butir   35.626895   39.954036   Topic2  -3.9400   1.0104
501          telor    9.209611   10.359330   Topic2  -5.2929   1.0074
338          korek    4.844140    5.462057   Topic2  -5.9353   1.0050
254            ijo    4.127961    4.746322   Topic2  -6.0953   0.9855
73           kukus    3.968998    4.589594   Topic2  -6.1346   0.9798
379         bombay   15.632637   18.167673   Topic2  -4.7637   0.9748
63           kaldu   54.631069   66.650986   Topic2  -3.5125   0.9262
45           bubuk   90.976765  117.393849   Topic2  -3.0025   0.8701
10          lembar   44.032230   56.868290   Topic2  -3.7282   0.8693
12          batang   44.498148   59.008671   Topic2  -3.7177   0.8428
37          bawang  129.457616  251.000064   Topic2  -2.6498   0.4630
0             daun   78.659644  143.092143   Topic2  -3.1480   0.5267
360         wortel   13.258519   16.701676   Topic2  -4.9285   0.8942
117           saus   14.177820   18.174522   Topic2  -4.8614   0.8767
33           bumbu   49.407009   93.343154   Topic2  -3.6130   0.4889
36           siung   74.243633  169.328706   Topic2  -3.2058   0.3006
16           tempe   92.106649  232.572346   Topic2  -2.9902   0.1988
87          goreng   31.828356   56.384987   Topic2  -4.0527   0.5532
27             air   62.390847  154.254022   Topic2  -3.3797   0.2199
75         bungkus   18.377637   27.027098   Topic2  -4.6020   0.7394
38           putih   53.665829  159.592987   Topic2  -3.5303   0.0352
90           jamur   18.587182   28.568520   Topic2  -4.5906   0.6952
14           garam   45.817312  151.677366   Topic2  -3.6884  -0.0720
34           halus   22.242147   44.443305   Topic2  -4.4111   0.4328
31        penyedap   15.500818   26.730141   Topic2  -4.7722   0.5802
21            buah   27.256845  170.438238   Topic2  -4.2078  -0.7080
153          salam   14.543049   47.973315   Topic2  -4.8360  -0.0685
99         kedelai   42.135203   42.790545   Topic3  -2.9031   1.9788
93          bersih   34.687467   35.344073   Topic3  -3.0976   1.9755
205        plastik   33.845352   34.498922   Topic3  -3.1221   1.9751
103        merebus   25.504210   26.158868   Topic3  -3.4051   1.9689
102       merendam   23.225836   23.880087   Topic3  -3.4987   1.9665
197          panci   17.447813   18.101395   Topic3  -3.7847   1.9575
104           ragi   49.891739   51.840605   Topic3  -2.7341   1.9559
100          kupas   15.544957   16.199129   Topic3  -3.9002   1.9530
208        cetakan   14.041890   14.695518   Topic3  -4.0019   1.9487
191          liter   27.114255   28.394255   Topic3  -3.3439   1.9481
516            lap   13.160053   13.866529   Topic3  -4.0667   1.9419
4             gigi   11.880159   12.534249   Topic3  -4.1691   1.9406
209          jarum   10.917346   11.570820   Topic3  -4.2536   1.9361
206         tampah   10.377120   11.030493   Topic3  -4.3043   1.9332
251          kulit   10.375439   11.030803   Topic3  -4.3045   1.9330
459           alat   10.189258   10.842703   Topic3  -4.3226   1.9321
199       saringan    9.719204   10.372589   Topic3  -4.3698   1.9292
351         baskom    8.872617    9.526628   Topic3  -4.4610   1.9231
355           wrap    8.333228    8.986601   Topic3  -4.5237   1.9188
415     pembungkus    7.370018    8.023413   Topic3  -4.6465   1.9093
448           cuka    6.829372    7.483337   Topic3  -4.7227   1.9028
710          tabur    5.866678    6.519951   Topic3  -4.8746   1.8887
711          aneka    5.866678    6.519951   Topic3  -4.8746   1.8887
709      pendukung    5.866466    6.519875   Topic3  -4.8747   1.8886
3            tusuk   12.412601   14.156123   Topic3  -4.1252   1.8628
298          jelly    3.658705    4.312080   Topic3  -5.3468   1.8299
196      peralatan    3.540493    4.194342   Topic3  -5.3797   1.8248
207           klip    2.578052    3.231391   Topic3  -5.6969   1.7684
101       mendidih    2.460483    3.113848   Topic3  -5.7436   1.7587
374     membungkus    2.155268    2.808607   Topic3  -5.8760   1.7295
192            utk    7.661602   10.044558   Topic3  -4.6077   1.7234
110         kacang   16.468693   30.562739   Topic3  -3.8425   1.3759
27             air   62.102857  154.254022   Topic3  -2.5151   1.0844
95            gram   24.684163   63.291507   Topic3  -3.4378   1.0526
16           tempe   40.346270  232.572346   Topic3  -2.9464   0.2425
0             daun   13.628072  143.092143   Topic3  -4.0318  -0.3571
1           pisang    7.597868   18.463832   Topic3  -4.6161   1.1063
75         bungkus    8.141649   27.027098   Topic3  -4.5469   0.7944
96          tepung   66.852274   67.493964   Topic4  -1.9431   2.4831
281        brokoli    7.054910    7.696011   Topic4  -4.1918   2.4056
396         coklat    5.448436    6.088528   Topic4  -4.4502   2.3815
86          adonan    4.315030    4.955121   Topic4  -4.6834   2.3543
97           kriuk    3.919641    4.559557   Topic4  -4.7795   2.3414
265        protein    3.629820    4.269960   Topic4  -4.8564   2.3302
443         powder    3.019798    3.662319   Topic4  -5.0404   2.2997
105           kobe    2.970948    3.610864   Topic4  -5.0567   2.2976
532           susu    3.540285    4.312316   Topic4  -4.8813   2.2954
128            bon    2.759677    3.400109   Topic4  -5.1304   2.2839
442         baking    2.417774    3.057711   Topic4  -5.2627   2.2578
232         terigu   26.736287   33.934460   Topic4  -2.8595   2.2542
451           sapi    2.407624    3.056663   Topic4  -5.2669   2.2539
109           sate    2.285122    2.925744   Topic4  -5.3191   2.2455
504         vanili    1.943220    2.583355   Topic4  -5.4812   2.2079
441        maizena    1.811359    2.451431   Topic4  -5.5515   2.1900
229        mendoan    1.811435    2.451567   Topic4  -5.5514   2.1900
398         butter    1.810490    2.450930   Topic4  -5.5520   2.1898
228            pcs    1.808564    2.450394   Topic4  -5.5530   2.1889
268           bola    1.808543    2.450789   Topic4  -5.5530   2.1887
399        mentega    1.807639    2.450385   Topic4  -5.5535   2.1884
6            beras   10.644117   14.451901   Topic4  -3.7805   2.1868
455          petis    1.337137    1.977191   Topic4  -5.8550   2.1015
533            uht    1.336748    1.976892   Topic4  -5.8553   2.1013
502        teriaki    1.336926    1.977263   Topic4  -5.8552   2.1013
689           mini    1.333557    1.976388   Topic4  -5.8577   2.0992
400         toping    1.205455    1.845262   Topic4  -5.9587   2.0669
226        potong²    1.204828    1.845418   Topic4  -5.9592   2.0663
227      seasoning    1.204828    1.845418   Topic4  -5.9592   2.0663
266          cakra    1.204397    1.844770   Topic4  -5.9596   2.0662
95            gram   36.505371   63.291507   Topic4  -2.5481   1.9423
80          sachet    3.704108    7.317170   Topic4  -4.8361   1.8118
87          goreng   15.338411   56.384987   Topic4  -3.4152   1.1908
45           bubuk   25.923110  117.393849   Topic4  -2.8904   0.9822
44        ketumbar   14.112448   57.399720   Topic4  -3.4985   1.0896
12          batang   14.017832   59.008671   Topic4  -3.5052   1.0553
148         kunyit    9.036119   36.565205   Topic4  -3.9443   1.0948
16           tempe   23.159989  232.572346   Topic4  -3.0031   0.1858
27             air   17.432591  154.254022   Topic4  -3.2872   0.3124
14           garam   13.224487  151.677366   Topic4  -3.5635   0.0529
190        tapioka    3.081548    8.193759   Topic4  -5.0201   1.5147
28            gula    3.229929   90.503676   Topic4  -4.9731  -0.8403
34           halus    2.800364   44.443305   Topic4  -5.1158  -0.2718
699          bahan    8.799980    9.508513   Topic5  -2.6310   3.7550
403         kering    4.005530    4.715218   Topic5  -3.4180   3.6693
248        tangkai    3.458105    4.167722   Topic5  -3.5650   3.6458
700         nugget    2.970845    3.679391   Topic5  -3.7169   3.6186
701        muncung    2.970845    3.679391   Topic5  -3.7169   3.6186
702        diparut    2.970845    3.679391   Topic5  -3.7169   3.6186
703       irisiris    2.970845    3.679391   Topic5  -3.7169   3.6186
704     breadcrumb    2.970845    3.679391   Topic5  -3.7169   3.6186
119          rebus    2.648860    3.359291   Topic5  -3.8316   3.5949
107          basah    3.392916    5.064062   Topic5  -3.5840   3.4320
510        himsalt    0.876729    1.586245   Topic5  -4.9373   3.2395
365         kental    0.778792    1.588369   Topic5  -5.0557   3.1197
600          kocok    0.602229    1.314162   Topic5  -5.3128   3.0521
253         lombok    0.543928    1.253050   Topic5  -5.4146   2.9979
405         olesan    0.543580    1.252885   Topic5  -5.4153   2.9974
404          panir    0.543460    1.253479   Topic5  -5.4155   2.9967
402        baluran    0.484539    1.193150   Topic5  -5.5303   2.9313
507         kerang    0.329644    1.039178   Topic5  -5.9155   2.6843
508         cengek    0.329644    1.039178   Topic5  -5.9155   2.6843
509          domba    0.329644    1.039178   Topic5  -5.9155   2.6843
685     memanggang    0.329582    1.039175   Topic5  -5.9156   2.6841
686        sayuran    0.329582    1.039175   Topic5  -5.9156   2.6841
687            pre    0.329582    1.039175   Topic5  -5.9156   2.6841
609       potongan    0.329503    1.039418   Topic5  -5.9159   2.6836
610       julienne    0.329503    1.039418   Topic5  -5.9159   2.6836
611      hilangkan    0.329503    1.039418   Topic5  -5.9159   2.6836
612          tumis    0.329503    1.039418   Topic5  -5.9159   2.6836
54           telur    5.179232   16.351241   Topic5  -3.1611   2.6828
488           ikan    0.328836    1.040543   Topic5  -5.9179   2.6805
620       seblmnya    0.328477    1.041487   Topic5  -5.9190   2.6785
505          menit    0.595128    1.928984   Topic5  -5.3247   2.6565
232         terigu    6.614052   33.934460   Topic5  -2.9165   2.1972
135          pasir    3.485891   19.391528   Topic5  -3.5570   2.1164
360         wortel    2.881166   16.701676   Topic5  -3.7475   2.0751
123       sejumput    0.710766    2.972405   Topic5  -5.1471   2.4017
379         bombay    1.973161   18.167673   Topic5  -4.1261   1.6125
21            buah    5.115351  170.438238   Topic5  -3.1735   0.3263
60           butir    2.346984   39.954036   Topic5  -3.9526   0.9979
28            gula    3.602013   90.503676   Topic5  -3.5242   0.6086
9           instan    0.601121    6.121680   Topic5  -5.3147   1.5117
116         totole    0.363728    1.389354   Topic5  -5.8171   2.4923
37          bawang    1.963591  251.000064   Topic5  -4.1309  -1.0182
125         sambal    0.381499   22.571519   Topic5  -5.7694  -0.2479
515         nampan    8.841023    9.535974   Topic6  -2.5424   3.8407
514          wadah    8.148478    8.842276   Topic6  -2.6240   3.8346
674          tutup    7.800957    8.496123   Topic6  -2.6676   3.8310
712          datar    3.763192    4.456935   Topic6  -3.3966   3.7471
452            ltr    1.803920    2.498440   Topic6  -4.1319   3.5906
583           ayak    1.110959    1.804779   Topic6  -4.6166   3.4311
473         bening    1.109952    1.805463   Topic6  -4.6175   3.4298
490        munjung    0.764591    1.458181   Topic6  -4.9902   3.2707
497           soto    0.764570    1.458190   Topic6  -4.9903   3.2707
644         kripik    0.764559    1.458193   Topic6  -4.9903   3.2707
492       charcoal    0.764433    1.458136   Topic6  -4.9905   3.2706
588           krim    0.764260    1.458152   Topic6  -4.9907   3.2703
493          kelor    0.764211    1.458345   Topic6  -4.9907   3.2701
471         kedele    0.764180    1.458369   Topic6  -4.9908   3.2701
472          peres    0.764032    1.458416   Topic6  -4.9910   3.2698
489           utuh    0.417892    1.111523   Topic6  -5.5944   2.9381
491         angkak    0.417892    1.111523   Topic6  -5.5944   2.9381
517        indomie    0.417834    1.111549   Topic6  -5.5945   2.9379
518        special    0.417834    1.111549   Topic6  -5.5945   2.9379
494         pepaya    0.417862    1.111691   Topic6  -5.5944   2.9378
495        diserut    0.417862    1.111691   Topic6  -5.5944   2.9378
496         rupiah    0.417862    1.111691   Topic6  -5.5944   2.9378

Topic: 1
tepung, gram, terigu, bubuk, tempe, air, goreng, ketumbar, batang, garam, beras, kunyit, brokoli, coklat, adonan, kriuk, sachet, protein, susu, gula, tapioka, powder, kobe, halus, bon, baking, sapi, sate, vanili, mendoan

Topic: 2
nampan, wadah, tutup, datar, ltr, ragi, ayak, bening, munjung, soto, kripik, charcoal, krim, kelor, kedele, peres, liter, celupan, angkak, utuh, diserut, rupiah, pepaya, campuran, kating, indomie, special, dilubangi, tunggak, sdh

Topic: 3
merah, buah, bawang, putih, cabe, siung, garam, gula, tempe, rawit, daun, kecap, ketumbar, bumbu, salam, jeruk, lengkuas, cabai, keriting, manis, selera, kemiri, tomat, sesuai, sambal, ruas, kencur, halus, bwg, biji

Topic: 4
air, ragi, kedelai, tempe, bersih, plastik, liter, merebus, gram, merendam, panci, kacang, kupas, cetakan, daun, lap, tusuk, gigi, jarum, tampah, kulit, alat, saringan, baskom, wrap, bungkus, utk, pisang, pembungkus, cuka

Topic: 5
pelapis, keju, cheddar, onion, cacah, kismis, strawberry, flour, gorengfried, roti, asli, oregano, rajang, cair, skm, dingin, hitam, pasta, bosé, cubit, daunplastik, meragi, wadahcetakan, seed, umerebus, awur, chia, pastikan, mix, aktif

Topic: 6
bahan, terigu, telur, buah, kering, gula, pasir, tangkai, basah, breadcrumb, irisiris, diparut, nugget, muncung, wortel, rebus, butir, bombay, bawang, himsalt, kental, sejumput, kocok, instan, menit, lombok, olesan, panir, baluran, sambal

Topic: 7
bawang, tempe, bubuk, iris, daun, siung, air, kaldu, putih, bumbu, resep, garam, batang, lembar, lihat, butir, goreng, lada, buah, halus, ukuran, jamur, bungkus, merica, bakwan, bombay, penyedap, asin, salam, parut

[(0,
  '0.143*"tepung" + 0.078*"gram" + 0.057*"terigu" + 0.056*"bubuk" + 0.050*"tempe" + 0.037*"air" + 0.033*"goreng" + 0.030*"ketumbar" + 0.030*"batang" + 0.028*"garam"'),
 (1,
  '0.079*"nampan" + 0.073*"wadah" + 0.069*"tutup" + 0.033*"datar" + 0.016*"ltr" + 0.012*"ragi" + 0.010*"ayak" + 0.010*"bening" + 0.007*"munjung" + 0.007*"soto"'),
 (2,
  '0.079*"merah" + 0.062*"buah" + 0.053*"bawang" + 0.047*"putih" + 0.047*"cabe" + 0.042*"siung" + 0.041*"garam" + 0.036*"gula" + 0.034*"tempe" + 0.030*"rawit"'),
 (3,
  '0.081*"air" + 0.065*"ragi" + 0.055*"kedelai" + 0.053*"tempe" + 0.045*"bersih" + 0.044*"plastik" + 0.035*"liter" + 0.033*"merebus" + 0.032*"gram" + 0.030*"merendam"'),
 (4,
  '0.078*"pelapis" + 0.055*"keju" + 0.041*"cheddar" + 0.011*"onion" + 0.011*"cacah" + 0.008*"kismis" + 0.008*"strawberry" + 0.008*"flour" + 0.008*"gorengfried" + 0.008*"roti"'),
 (5,
  '0.072*"bahan" + 0.054*"terigu" + 0.042*"telur" + 0.042*"buah" + 0.033*"kering" + 0.029*"gula" + 0.029*"pasir" + 0.028*"tangkai" + 0.028*"basah" + 0.024*"muncung"'),
 (6,
  '0.071*"bawang" + 0.050*"tempe" + 0.050*"bubuk" + 0.044*"iris" + 0.043*"daun" + 0.041*"siung" + 0.034*"air" + 0.030*"kaldu" + 0.029*"putih" + 0.027*"bumbu"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sTempeProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sTempeProb["bawang"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
cpsTempeWN = dfWordnet.copy()

cpsTempeWN["Synonym_clean"] = cleanWN_Synonym(cpsTempeWN["Synonym"])
cpsTempeWN["Hypernim_clean"] = cleanWN(cpsTempeWN["Hypernim"])
cpsTempeWN["Hyponim_clean"] = cleanWN(cpsTempeWN["Hyponim"])
cpsTempeWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/tempeCookpad.owl")
makeOntology(ontoName, cpsTempeWN)
ontoName.save(file = "tempeCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown 1Ca3lXQKYevxhdo-BQkWRw3zVGoFIdPGF

In [ ]:
wiki_tempe_sln = pd.read_excel("TempeCookpadFinal.xlsx").iloc[:, 1:]
wiki_tempe_sln.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_tempe_sln["Category"] = translate(wiki_tempe_sln["Category"])
wiki_tempe_sln.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_tempe_sln[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
tempeSlnTabel_new = tabel_1981.copy()
tempeSlnTabel_new["correct_category"] = all_cat
tempeSlnTabel_new["suggestion"] = all_suggestion

# Export Result to File
tempeSlnTabel_new.to_excel("tempeSlnTabel_Result.xlsx")
tempeSlnTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tempeSlnTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
tempeSlnTabel_new = concatListInColumn(tempeSlnTabel_new)
tempeSlnTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, tempeSlnTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_tempe_sln.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
tempeCpdWiki_new = wiki_df.copy()
tempeCpdWiki_new["suggest"] = all_cat

# Export Result to file
tempeCpdWiki_new.to_excel("tempeCpdWiki_Result.xlsx")
tempeCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "tempeCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
tempeCpdOntoWiki = get_ontology("http://test.org/tempeCpd_onto_wiki.owl")
makeOntology_wiki(tempeCpdOntoWiki, tempeCpdWiki_new)
tempeCpdOntoWiki.save(file = "tempeCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = cpsTempeWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
cpsTempeWN_new = listToDataframe(changesList, tableWordnet)
cpsTempeWN_new.to_excel("cpsTempeWN_Result.xlsx")
cpsTempeWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cpsTempeWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Udang - Cookpad

In [ ]:
!gdown 1zV22F5HEqQiRMukMWx7rkWAs7JNtMEmF

Downloading...
From: https://drive.google.com/uc?id=1zV22F5HEqQiRMukMWx7rkWAs7JNtMEmF
To: /content/cookpad-selenium_udang.jl
100% 403k/403k [00:00<00:00, 97.3MB/s]

In [ ]:
cps_udang = pd.read_json(r'/content/cookpad-selenium_udang.jl', lines = True)
print(f'NaN page description: {len(cps_udang.loc[cps_udang["page_description"].isna()])}')

# fill NaN with empty string
cps_udang["page_description"] = cps_udang["page_description"].fillna("")

# covnert page_description to list
cps_udang["temp"] = cps_udang["page_description"]
cps_udang = concat_bahan_langkah(cps_udang)
cps_udang["page_description"] = cps_udang["page_bahan_langkah"]

# clean text
cps_udang = pre_cleaning_text(cps_udang, threshold = 20)

NaN page description: 41

## GUI Udang - Cookpad

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = cps_udang.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(run_button_clicked)
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
2      0.217062 -0.078868       1        1  52.268626
0      0.201345  0.148554       2        1  19.986747
1      0.131884 -0.131859       3        1  13.522870
3     -0.044559  0.189196       4        1   8.266531
5     -0.187083  0.019997       5        1   2.707614
6     -0.118521 -0.155045       6        1   2.162112
4     -0.200129  0.008024       7        1   1.085501, topic_info=                  Term        Freq       Total Category  logprob  loglift
37                buah  196.000000  196.000000  Default  30.0000  30.0000
114               iris   92.000000   92.000000  Default  29.0000  29.0000
27               merah  188.000000  188.000000  Default  28.0000  28.0000
131              cabai   30.000000   30.000000  Default  27.0000  27.0000
29               rawit   60.000000   60.000000  Default  26.0000  26.0000
28                cabe  110.000000  110.000000  Default  25.0000  25.0000
47               jeruk   54.000000   54.000000  Default  24.0000  24.0000
207              manis   57.000000   57.000000  Default  23.0000  23.0000
11               telur   63.000000   63.000000  Default  22.0000  22.0000
43                daun  130.000000  130.000000  Default  21.0000  21.0000
197               saos   69.000000   69.000000  Default  20.0000  20.0000
12              tepung   76.000000   76.000000  Default  19.0000  19.0000
4                udang  218.000000  218.000000  Default  18.0000  18.0000
32                 air  126.000000  126.000000  Default  17.0000  17.0000
39               bumbu   94.000000   94.000000  Default  16.0000  16.0000
30              sambal   24.000000   24.000000  Default  15.0000  15.0000
147               ruas   33.000000   33.000000  Default  14.0000  14.0000
34              goreng   55.000000   55.000000  Default  13.0000  13.0000
49               kupas   41.000000   41.000000  Default  12.0000  12.0000
78                jahe   41.000000   41.000000  Default  11.0000  11.0000
83              lembar   36.000000   36.000000  Default  10.0000  10.0000
51              bersih   23.000000   23.000000  Default   9.0000   9.0000
8               bawang  417.000000  417.000000  Default   8.0000   8.0000
0                 ayam   48.000000   48.000000  Default   7.0000   7.0000
7                siung  185.000000  185.000000  Default   6.0000   6.0000
172              lemon   13.000000   13.000000  Default   5.0000   5.0000
177               ikat   14.000000   14.000000  Default   4.0000   4.0000
38               bubuk   92.000000   92.000000  Default   3.0000   3.0000
232               cuci   18.000000   18.000000  Default   2.0000   2.0000
10               butir   58.000000   58.000000  Default   1.0000   1.0000
58              selera   68.395333   69.004140   Topic1  -3.9269   0.6399
175             bombay   63.175639   63.776651   Topic1  -4.0063   0.6393
3              cincang   38.512518   39.114100   Topic1  -4.5013   0.6333
110             ukuran   31.181981   31.782920   Topic1  -4.7124   0.6297
57              sesuai   43.364054   44.271833   Topic1  -4.3826   0.6281
98              geprek   24.492795   25.094432   Topic1  -4.9539   0.6245
123            maizena   19.637873   20.238839   Topic1  -5.1748   0.6186
105             sendok   19.188138   19.789086   Topic1  -5.1980   0.6179
205             jagung   14.943191   15.544241   Topic1  -5.4480   0.6093
86             menumis   14.814793   15.415798   Topic1  -5.4566   0.6090
85                skip   14.350474   14.959672   Topic1  -5.4885   0.6072
197               saos   66.484838   69.526353   Topic1  -3.9553   0.6040
182              makan   12.435407   13.036065   Topic1  -5.6317   0.6016
319               utuh   12.123274   12.738135   Topic1  -5.6571   0.5993
437           larutkan   11.566790   12.167619   Topic1  -5.7041   0.5981
183               dadu   11.431076   12.038488   Topic1  -5.7159   0.5970
510            bonggol   10.988130   11.588906   Topic1  -5.7554   0.5955
432            tangkai   10.827827   11.428117   Topic1  -5.7701   0.5948
207              manis   54.217484   57.313429   Topic1  -4.1592   0.5932
55                 grm   10.504863   11.105988   Topic1  -5.8004   0.5931
315             airnya   10.344626   10.945204   Topic1  -5.8158   0.5923
223            taburan    9.927086   10.527479   Topic1  -5.8570   0.5901
19                saus   99.955900  106.184581   Topic1  -3.5475   0.5883
227              saori    8.382659    8.983998   Topic1  -6.0261   0.5795
711           pedasnya    8.024150    8.629619   Topic1  -6.0698   0.5760
712            diambil    8.024150    8.629619   Topic1  -6.0698   0.5760
126           margarin    7.065748    7.666308   Topic1  -6.1970   0.5672
285            mentega    6.904675    7.505085   Topic1  -6.2200   0.5654
20               tiram   87.025096   94.666757   Topic1  -3.6860   0.5646
93             kentang    6.743234    7.344258   Topic1  -6.2437   0.5634
22               kecap   79.029042   86.114573   Topic1  -3.7824   0.5629
111              tomat   67.572464   74.083023   Topic1  -3.9390   0.5568
533             diiris    9.884826   10.805228   Topic1  -5.8612   0.5597
8               bawang  338.846827  417.127370   Topic1  -2.3267   0.4409
7                siung  149.023218  185.441920   Topic1  -3.1481   0.4301
137               ekor   13.950877   15.445436   Topic1  -5.5167   0.5470
37                buah  144.894571  196.392686   Topic1  -3.1762   0.3447
61            penyedap   32.946329   39.530173   Topic1  -4.6574   0.4666
27               merah  135.935068  188.722937   Topic1  -3.2401   0.3207
9                putih  154.339261  222.273937   Topic1  -3.1131   0.2840
4                udang  148.768424  218.172351   Topic1  -3.1499   0.2659
14               garam  108.077250  174.891851   Topic1  -3.4694   0.1675
29               rawit   43.542674   60.463899   Topic1  -4.3785   0.3205
28                cabe   67.634371  110.132005   Topic1  -3.9381   0.1612
32                 air   71.420862  126.944254   Topic1  -3.8837   0.0736
15                gula   65.656227  115.329390   Topic1  -3.9678   0.0854
114               iris   54.249369   92.563002   Topic1  -4.1587   0.1145
40               halus   44.909712   73.786577   Topic1  -4.3476   0.1523
39               bumbu   51.249127   94.488906   Topic1  -4.2155   0.0370
68              batang   30.534176   45.349168   Topic1  -4.7334   0.2532
43                daun   55.730417  130.044152   Topic1  -4.1317  -0.1986
38               bubuk   42.584316   92.704341   Topic1  -4.4008  -0.1292
70                lada   29.512463   47.127372   Topic1  -4.7674   0.1807
185            tapioka   14.799127   15.452205   Topic2  -4.4963   1.5669
13                sagu   14.566941   15.220014   Topic2  -4.5122   1.5662
196         menggoreng   12.903059   13.556197   Topic2  -4.6335   1.5607
559            rebusan   11.386964   12.039851   Topic2  -4.7584   1.5543
551             rendam   11.386586   12.039794   Topic2  -4.7585   1.5543
452              liter   11.281688   11.934544   Topic2  -4.7677   1.5538
586              bahan   10.902431   11.555470   Topic2  -4.8019   1.5519
89               beras   10.818134   11.471489   Topic2  -4.8097   1.5515
215             daging   10.544789   11.197895   Topic2  -4.8353   1.5500
11               telur   59.962220   63.699134   Topic2  -3.0972   1.5496
376             fillet   10.271167   10.924315   Topic2  -4.8616   1.5485
194              kocok    9.785030   10.441114   Topic2  -4.9101   1.5452
88              terigu   21.316389   22.953247   Topic2  -4.1314   1.5361
216               paha    7.849151    8.502189   Topic2  -5.1305   1.5302
238                utk    7.575307    8.228577   Topic2  -5.1660   1.5274
152            merebus    7.259507    7.912457   Topic2  -5.2086   1.5240
474             giling    7.195653    7.849483   Topic2  -5.2174   1.5231
401              isian    7.091217    7.744052   Topic2  -5.2321   1.5220
410             kuping    6.985455    7.638777   Topic2  -5.2471   1.5207
534              bunga    6.710070    7.365478   Topic2  -5.2873   1.5169
189            pangsit    6.122548    6.775314   Topic2  -5.3789   1.5088
451               kuah    6.122227    6.775221   Topic2  -5.3790   1.5088
135                bks    6.121557    6.775453   Topic2  -5.3791   1.5086
482               soun    5.743160    6.396162   Topic2  -5.4429   1.5024
402               cuko    5.638110    6.290839   Topic2  -5.4614   1.5006
187              timun    5.637702    6.290817   Topic2  -5.4614   1.5005
713          tulangnya    5.259203    5.911835   Topic2  -5.5309   1.4931
706              biang    5.259124    5.911814   Topic2  -5.5310   1.4931
714              model    5.258658    5.911741   Topic2  -5.5310   1.4930
715           tenggiri    5.258658    5.911741   Topic2  -5.5310   1.4930
2                kulit   23.288321   26.944307   Topic2  -4.0430   1.4643
53           pelengkap   12.302759   14.451405   Topic2  -4.6811   1.4491
0                 ayam   38.777188   48.639800   Topic2  -3.5331   1.3835
12              tepung   51.955098   76.472533   Topic2  -3.2405   1.2235
21               wijen   18.824977   25.839882   Topic2  -4.2557   1.2934
134                btr   10.464212   12.976552   Topic2  -4.8430   1.3949
72                gram   34.716576   58.495350   Topic2  -3.6437   1.0884
25               parut   10.892776   14.392711   Topic2  -4.8028   1.3315
38               bubuk   43.320238   92.704341   Topic2  -3.4223   0.8493
201              pasir   23.426779   41.292395   Topic2  -4.0370   1.0433
34              goreng   28.592585   55.280348   Topic2  -3.8378   0.9508
32                 air   42.447096  126.944254   Topic2  -3.4427   0.5146
10               butir   25.360066   58.649482   Topic2  -3.9577   0.7717
14               garam   49.130792  174.891851   Topic2  -3.2964   0.3404
15                gula   36.599937  115.329390   Topic2  -3.5909   0.4624
17               kaldu   25.364946   65.192066   Topic2  -3.9575   0.6661
9                putih   49.537515  222.273937   Topic2  -3.2882   0.1089
138               ikan   13.253737   21.589935   Topic2  -4.6066   1.1222
4                udang   35.785340  218.172351   Topic2  -3.6134  -0.1976
8               bawang   46.377046  417.127370   Topic2  -3.3541  -0.5865
18               jamur   15.193378   31.593502   Topic2  -4.4701   0.8780
70                lada   17.113158   47.127372   Topic2  -4.3511   0.5971
43                daun   17.550149  130.044152   Topic2  -4.3259  -0.3927
49               kupas   12.799559   41.180965   Topic2  -4.6415   0.4415
16              merica   12.174536   27.924780   Topic2  -4.6916   0.7799
24              wortel   12.281505   38.964766   Topic2  -4.6828   0.4555
47               jeruk   11.964097   54.116212   Topic2  -4.7090   0.1009
108             kunyit   21.746450   22.310689   Topic3  -3.7208   1.9752
166               biji   16.845342   17.409455   Topic3  -3.9762   1.9678
97                jari   14.693651   15.257823   Topic3  -4.1128   1.9631
213                ijo   13.934551   14.499575   Topic3  -4.1659   1.9610
688                sct   10.866482   11.431660   Topic3  -4.4145   1.9501
271             santan    9.991378   10.555484   Topic3  -4.4985   1.9459
267              serai    9.792392   10.356221   Topic3  -4.5186   1.9448
163             kelapa    5.607987    6.171883   Topic3  -5.0760   1.9050
234           lengkuas   12.733377   14.171701   Topic3  -4.2560   1.8938
147               ruas   30.420373   33.953934   Topic3  -3.3851   1.8909
83              lembar   32.525733   36.415050   Topic3  -3.3182   1.8878
346           digeprek    4.572043    5.136082   Topic3  -5.2803   1.8845
170             kencur    4.173923    4.737493   Topic3  -5.3714   1.8741
84               salam   20.264690   23.246010   Topic3  -3.7913   1.8635
461            kemangi    3.655685    4.219475   Topic3  -5.5039   1.8574
165             pisang    3.257298    3.820861   Topic3  -5.6193   1.8412
629               srut    2.937885    3.502218   Topic3  -5.7225   1.8251
345               laos    2.540092    3.103619   Topic3  -5.8680   1.8004
79                 aja    2.538709    3.102858   Topic3  -5.8686   1.8001
159              kotak    3.243619    4.106632   Topic3  -5.6235   1.7649
616              purut    2.021800    2.585612   Topic3  -6.0962   1.7548
686            botolan    2.021728    2.585649   Topic3  -6.0963   1.7548
549             tulang    2.019757    2.584341   Topic3  -6.0973   1.7543
99          dihaluskan    3.439291    4.496528   Topic3  -5.5650   1.7327
344            diparut    1.822821    2.386371   Topic3  -6.1998   1.7314
171           selembar    1.820637    2.385082   Topic3  -6.2010   1.7307
456              fresh    1.820342    2.385742   Topic3  -6.2012   1.7303
463              micin    1.810944    2.380049   Topic3  -6.2064   1.7275
254            sejuput    1.623338    2.186939   Topic3  -6.3157   1.7028
364             instan    1.623221    2.186928   Topic3  -6.3158   1.7027
148             kemiri   14.421360   22.239057   Topic3  -4.1315   1.5676
240               lmbr    3.124701    4.373326   Topic3  -5.6609   1.6646
107           ketumbar   10.509013   17.096477   Topic3  -4.4480   1.5141
47               jeruk   24.772394   54.116212   Topic3  -3.5905   1.2194
43                daun   50.098557  130.044152   Topic3  -2.8862   1.0469
28                cabe   42.085992  110.132005   Topic3  -3.0605   1.0388
39               bumbu   32.878166   94.488906   Topic3  -3.3074   0.9451
212           keriting   10.738773   23.239779   Topic3  -4.4264   1.2288
27               merah   49.711519  188.722937   Topic3  -2.8940   0.6667
10               butir   19.999822   58.649482   Topic3  -3.8045   0.9249
40               halus   22.282041   73.786577   Topic3  -3.6964   0.8034
68              batang   12.752515   45.349168   Topic3  -4.2545   0.7321
7                siung   26.351114  185.441920   Topic3  -3.5287   0.0496
78                jahe   11.534148   41.373775   Topic3  -4.3549   0.7235
17               kaldu   14.223624   65.192066   Topic3  -4.1453   0.4784
8               bawang   31.559576  417.127370   Topic3  -3.3484  -0.5807
37                buah   20.138852  196.392686   Topic3  -3.7976  -0.2767
76               hijau    7.441591   21.124147   Topic3  -4.7931   0.9575
9                putih   18.077211  222.273937   Topic3  -3.9056  -0.5085
15                gula   12.755316  115.329390   Topic3  -4.2543  -0.2011
4                udang   14.487114  218.172351   Topic3  -4.1270  -0.7112
14               garam   10.520206  174.891851   Topic3  -4.4469  -0.8101
51              bersih   22.933531   23.554315   Topic4  -3.1755   2.4662
232               cuci   17.829785   18.449626   Topic4  -3.4272   2.4588
118              tipis   12.136162   12.757009   Topic4  -3.8119   2.4431
155          kepalanya   10.453103   11.073418   Topic4  -3.9612   2.4353
426                kol   10.088635   10.709096   Topic4  -3.9967   2.4333
296          memanjang    8.798258    9.419043   Topic4  -4.1335   2.4248
181            brokoli    8.657849    9.278753   Topic4  -4.1496   2.4237
707            spesial    7.004253    7.623776   Topic4  -4.3615   2.4082
708         tergantung    7.004253    7.623776   Topic4  -4.3615   2.4082
709         kekentalan    7.004253    7.623776   Topic4  -4.3615   2.4082
192             serong    5.881102    6.502492   Topic4  -4.5363   2.3925
65             genggam    5.236943    5.857248   Topic4  -4.6523   2.3810
233           memarkan    3.805378    4.426809   Topic4  -4.9716   2.3417
214              sosis    2.431522    3.052316   Topic4  -5.4195   2.2656
200           putihnya    2.431298    3.052152   Topic4  -5.4196   2.2655
265              tauco    2.291535    2.912447   Topic4  -5.4788   2.2532
116            sisakan    2.291063    2.912431   Topic4  -5.4790   2.2530
251               kari    2.290829    2.912493   Topic4  -5.4791   2.2529
418             bakwan    6.431436    8.286337   Topic4  -4.4469   2.2395
117             buntut    2.150818    2.772128   Topic4  -5.5422   2.2392
576               mili    2.067619    2.688157   Topic4  -5.5817   2.2305
588            kembang    2.066805    2.687825   Topic4  -5.5821   2.2302
178              kucai    1.926469    2.547343   Topic4  -5.6524   2.2136
449               madu    1.926229    2.547433   Topic4  -5.6525   2.2134
67             daunnya    1.925385    2.547542   Topic4  -5.6529   2.2130
360              pakis    1.925799    2.548274   Topic4  -5.6527   2.2129
180             buncis    2.791137    3.707415   Topic4  -5.2816   2.2091
288              helai    1.786583    2.407633   Topic4  -5.7278   2.1946
119             miring    1.647125    2.267068   Topic4  -5.8090   2.1735
69        potongpotong    1.646758    2.266900   Topic4  -5.8093   2.1734
112              belah    4.265481    5.997070   Topic4  -4.8575   2.1522
156              lihat   11.616809   18.692081   Topic4  -3.8556   2.0173
157              resep   11.576446   19.061054   Topic4  -3.8591   1.9943
49               kupas   19.703730   41.180965   Topic4  -3.3273   1.7558
114               iris   37.845184   92.563002   Topic4  -2.6746   1.5986
5                ambil    2.906009    4.461848   Topic4  -5.2413   2.0642
325                btg    3.942837    6.882791   Topic4  -4.9362   1.9358
24              wortel   12.215535   38.964766   Topic4  -3.8054   1.3330
146              sereh    3.571376    6.100074   Topic4  -5.0351   1.9576
34              goreng   14.253825   55.280348   Topic4  -3.6510   1.1376
268                lbr    5.114217   12.502004   Topic4  -4.6760   1.5991
37                buah   16.504688  196.392686   Topic4  -3.5044   0.0165
18               jamur    6.838939   31.593502   Topic4  -4.3854   0.9626
32                 air   12.696531  126.944254   Topic4  -3.7667   0.1905
12              tepung    9.506824   76.472533   Topic4  -4.0561   0.4080
4                udang   12.960200  218.172351   Topic4  -3.7462  -0.3304
177               ikat    4.226910   14.522373   Topic4  -4.8666   1.2587
43                daun    6.486770  130.044152   Topic4  -4.4383  -0.5052
47               jeruk    5.103610   54.116212   Topic4  -4.6781   0.1318
14               garam    5.157533  174.891851   Topic4  -4.6676  -1.0308
72                gram    4.261396   58.495350   Topic4  -4.8585  -0.1264
191          serbaguna   10.121034   10.801350   Topic5  -2.8773   3.5440
210            perasan    9.666338   10.345003   Topic5  -2.9233   3.5412
512                soy    4.805368    5.482850   Topic5  -3.6222   3.4772
513              sauce    4.805368    5.482850   Topic5  -3.6222   3.4772
520              kunci    4.433689    5.110257   Topic5  -3.7027   3.4671
279           kangkung    4.352987    5.028815   Topic5  -3.7211   3.4648
400             pempek    4.352273    5.028910   Topic5  -3.7212   3.4646
699               blok    4.060326    4.736186   Topic5  -3.7907   3.4551
323               sawi    4.026908    4.704856   Topic5  -3.7989   3.4535
77              terasi    5.349852    6.422334   Topic5  -3.5148   3.4264
322            blender    1.784257    2.459947   Topic5  -4.6129   3.2880
177               ikat    9.750744   14.522373   Topic5  -2.9146   3.2108
330              bulat    1.033922    1.713672   Topic5  -5.1586   3.1038
632  digilingdicincang    0.824784    1.500700   Topic5  -5.3845   3.0105
633           potongan    0.824784    1.500700   Topic5  -5.3845   3.0105
498               merk    0.824496    1.500651   Topic5  -5.3849   3.0102
524              cacah    0.824440    1.501179   Topic5  -5.3850   3.0098
518            cocolan    0.824243    1.500952   Topic5  -5.3852   3.0097
531              korek    3.815975    7.193112   Topic5  -3.8527   2.9752

Topic: 1
telur, tepung, putih, garam, bawang, bubuk, air, ayam, gula, udang, gram, goreng, kaldu, butir, pasir, kulit, terigu, wijen, daun, lada, jamur, tapioka, sagu, ikan, menggoreng, kupas, pelengkap, wortel, merica, jeruk

Topic: 2
daun, merah, cabe, bumbu, lembar, bawang, ruas, siung, jeruk, halus, kunyit, salam, buah, butir, putih, biji, jari, udang, kemiri, kaldu, ijo, gula, batang, lengkuas, jahe, sct, keriting, garam, ketumbar, santan

Topic: 3
bawang, putih, siung, udang, buah, merah, garam, saus, tiram, kecap, air, selera, cabe, tomat, saos, gula, bombay, daun, iris, manis, bumbu, halus, rawit, sesuai, bubuk, cincang, penyedap, ukuran, batang, lada

Topic: 4
iris, bersih, kupas, cuci, buah, goreng, udang, air, wortel, tipis, lihat, resep, kepalanya, kol, tepung, memanjang, brokoli, tergantung, spesial, kekentalan, jamur, daun, bakwan, serong, genggam, garam, lbr, jeruk, belah, gram

Topic: 5
jeruk, garlic, mince, honey, water, black, vinegar, sriracha, rice, pepper, powder, lemon, cemplung, digiling, ghee, cengkeh, kapulaga, seukuran, jempol, btng, pete, dipotong, garamgulakaldu, kecapsaus, tiramsaus, jamjur, adas, basmati, mede, mint

Topic: 6
serbaguna, ikat, perasan, terasi, sauce, soy, kunci, sambal, kangkung, pempek, rawit, blok, kuning, sawi, korek, udang, saos, tepung, kepala, blender, kulit, pedas, bungkus, terigu, bulat, kering, ons, amp, potongan, digilingdicincang

Topic: 7
cabai, buah, irisan, rawit, rebon, asam, pedas, jeruk, crispy, baby, serut, kailan, ladaku, nenas, ketimun, tumbuk, tambahkan, udang, bungkus, merah, manis, jahe, garam, pake, pare, kecap, secukup, nya, gak, cemplung

[(0,
  '0.045*"telur" + 0.039*"tepung" + 0.037*"putih" + 0.037*"garam" + 0.035*"bawang" + 0.033*"bubuk" + 0.032*"air" + 0.029*"ayam" + 0.028*"gula" + 0.027*"udang"'),
 (1,
  '0.056*"daun" + 0.055*"merah" + 0.047*"cabe" + 0.037*"bumbu" + 0.036*"lembar" + 0.035*"bawang" + 0.034*"ruas" + 0.029*"siung" + 0.028*"jeruk" + 0.025*"halus"'),
 (2,
  '0.098*"bawang" + 0.044*"putih" + 0.043*"siung" + 0.043*"udang" + 0.042*"buah" + 0.039*"merah" + 0.031*"garam" + 0.029*"saus" + 0.025*"tiram" + 0.023*"kecap"'),
 (3,
  '0.069*"iris" + 0.042*"bersih" + 0.036*"kupas" + 0.032*"cuci" + 0.030*"buah" + 0.026*"goreng" + 0.024*"udang" + 0.023*"air" + 0.022*"wortel" + 0.022*"tipis"'),
 (4,
  '0.038*"jeruk" + 0.035*"garlic" + 0.033*"sriracha" + 0.033*"rice" + 0.033*"pepper" + 0.033*"honey" + 0.033*"water" + 0.033*"mince" + 0.033*"vinegar" + 0.033*"black"'),
 (5,
  '0.056*"serbaguna" + 0.054*"ikat" + 0.054*"perasan" + 0.030*"terasi" + 0.027*"sauce" + 0.027*"soy" + 0.025*"kunci" + 0.025*"sambal" + 0.024*"kangkung" + 0.024*"pempek"'),
 (6,
  '0.114*"cabai" + 0.053*"buah" + 0.040*"irisan" + 0.030*"rawit" + 0.029*"rebon" + 0.025*"asam" + 0.024*"pedas" + 0.022*"jeruk" + 0.022*"crispy" + 0.022*"baby"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
sUdangProb = make_dictionary_terms_prob(ldamodel, id_map, d)
sUdangProb["bawang"] #probabilitas kata mee pada setiap topik

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
cpsUdangWN = dfWordnet.copy()

cpsUdangWN["Synonym_clean"] = cleanWN_Synonym(cpsUdangWN["Synonym"])
cpsUdangWN["Hypernim_clean"] = cleanWN(cpsUdangWN["Hypernim"])
cpsUdangWN["Hyponim_clean"] = cleanWN(cpsUdangWN["Hyponim"])
cpsUdangWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/udangCookpad.owl")
makeOntology(ontoName, cpsUdangWN)
ontoName.save(file = "udangCookpad.owl")

## Wikipedia & Category

In [ ]:
!gdown 1rQqb216082yJiR5TJqOHELNHpu9STyOj

In [ ]:
wiki_udang_sln = pd.read_excel("UdangCookpadFinal.xlsx").iloc[:, 1:]
wiki_udang_sln.rename(columns={"category": "Category"}, inplace = True)

# Translate
wiki_udang_sln["Category"] = translate(wiki_udang_sln["Category"])
wiki_udang_sln.head()

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_udang_sln[["Title", "Category"]].copy()

# idx_nan, percent = check_nan_cat(tabel_1981)
# tabel_1981.iloc[idx_nan]

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

In [ ]:
udangSlnTabel_new = tabel_1981.copy()
udangSlnTabel_new["correct_category"] = all_cat
udangSlnTabel_new["suggestion"] = all_suggestion

# Export Result to File
udangSlnTabel_new.to_excel("udangSlnTabel_Result.xlsx")
udangSlnTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "udangSlnTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
udangSlnTabel_new = concatListInColumn(udangSlnTabel_new)
udangSlnTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, udangSlnTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_udang_sln.iloc[:, :-1].copy()

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check'
)

asyncio.ensure_future(f_wiki())

In [ ]:
udangCpdWiki_new = wiki_df.copy()
udangCpdWiki_new["suggest"] = all_cat

# Export Result to file
udangCpdWiki_new.to_excel("udangCpdWiki_Result.xlsx")
udangCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "udangCpdWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
udangCpdOntoWiki = get_ontology("http://test.org/udangCpd_onto_wiki.owl")
makeOntology_wiki(udangCpdOntoWiki, udangCpdWiki_new)
udangCpdOntoWiki.save(file = "udangCpd_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = cpsUdangWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(fWordnet())

In [ ]:
# Export Result to File
cpsUdangWN_new = listToDataframe(changesList, tableWordnet)
cpsUdangWN_new.to_excel("cpsUdangWN_Result.xlsx")
cpsUdangWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cpsUdangWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

# Malaysian Cooking PDF

In [ ]:
!gdown --id "1XZojUfe1couf7XUkNP54I2E_D4v4uPuZ"

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1XZojUfe1couf7XUkNP54I2E_D4v4uPuZ
To: /content/Malaysian_cooking.jl
100% 78.2k/78.2k [00:00<00:00, 48.7MB/s]

In [ ]:
cookPdf=pd.read_json(r'/content/Malaysian_cooking.jl', lines = True)

In [ ]:
cookPdf

,Title,page_bahan,page_langkah,page_description
0,Coffee Beef Ribs,"[1 kg Beef ribs, 3 tbsp Cooking oil, Marinade,...",[Put the beef ribs into a large bowl and add t...,"[1 kg Beef ribs, 3 tbsp Cooking oil, Marinade,..."
1,Beef Curry,"[1 kg Beef cubed, 1/2 tsp Fenugreek, 2 cm Cinn...",[Put the ingredients of Paste 1 into a blender...,"[1 kg Beef cubed, 1/2 tsp Fenugreek, 2 cm Cinn..."
2,Pepper Beef,"[350g Beef sliced, 3 cloves Garlic chopped fin...",[Place the beef in a bowl with the marinade in...,"[350g Beef sliced, 3 cloves Garlic chopped fin..."
3,Tangy Beef,"[350g Beef sliced, 2/3 tsp Sugar, 1/2 cube Bee...",[Mix the coconut powder and water and set asid...,"[350g Beef sliced, 2/3 tsp Sugar, 1/2 cube Bee..."
4,Beef Rendang,"[900g Beef cubed, 1/2 tin Coconut cream, 1/2 t...",[We have been tryin g to perfect this recipe f...,"[900g Beef cubed, 1/2 tin Coconut cream, 1/2 t..."
5,Beef with Red Curry Paste,"[Beef with Red Curry Paste, Ingredients, 400g ...",[Thinly slice the beef and then rub in the bic...,"[Beef with Red Curry Paste, Ingredients, 400g ..."
6,Szechuan Beef,"[1/2 tsp Light soya sauce, 250 g Beef sliced i...",[Put the beef in a bowl and add some salt (a s...,"[1/2 tsp Light soya sauce, 250 g Beef sliced i..."
7,Fennel Beef,"[400g Beef cubed, Hand full Raw peanuts, 1 tbs...",[Add the marinade ingredients to the beef in a...,"[400g Beef cubed, Hand full Raw peanuts, 1 tbs..."
8,Serunding Lembu,"[400g Beef sliced, 1/2 tsp Aniseed powder, 1 t...","[Blend the lemon grass, 1 onion, and ginger in...","[400g Beef sliced, 1/2 tsp Aniseed powder, 1 t..."
9,Beef Tomchi,"[300g Steak diced, 1/4 tsp Bi-Carb of Soda, 1 ...","[Put the diced beef into a bowl, Add the bi-ca...","[300g Steak diced, 1/4 tsp Bi-Carb of Soda, 1 ..."
10,Beef Satay,"[600g Rump steak diced, Beef marinade, 1/2 cup...",[Combine the ingredients in a blender and mix ...,"[600g Rump steak diced, Beef marinade, 1/2 cup..."
11,Peking Beef,"[1 Onion sliced thinly, 1 in Ginger sliced fin...",[Mix the beef and marinade ingre dients in a b...,"[1 Onion sliced thinly, 1 in Ginger sliced fin..."
12,Red wine and rosemary beef,"[1 1/2 cups Red wine, 6 small Potatoes peeled ...",[Remove any fat from the beef and cut it into ...,"[1 1/2 cups Red wine, 6 small Potatoes peeled ..."
13,Ma-Po,"[2 blocks Firm Tofu, 120g Beef, 120g Pork, 1 t...","[Mix the beef and pork with 1/2 tsp of sugar, ...","[2 blocks Firm Tofu, 120g Beef, 120g Pork, 1 t..."

In [ ]:
#data = pd.read_csv('G:\Github\Recipe_reco\data\RAW_recipes.csv')
cookPdf=pd.read_json(r'/content/Malaysian_cooking.jl', lines = True)

#save dalam acar biar ngebut loading ntar.
cookPdf.to_pickle(r'/content/raw_df.pkl')

# # clean text
cookPdf = pre_cleaning_text(cookPdf, threshold = 20)

#data["cleaned_description"] = cleaning_text(data["page_description"])
#data["cleaned_description"].head()

# ingredients_all = data["cleaned_description"].apply(lambda x: treat_ingredients(x))
# ingredients_all

In [ ]:
cookPdf.head()

,Title,page_bahan,page_langkah,page_description
0,Coffee Beef Ribs,"[1 kg Beef ribs, 3 tbsp Cooking oil, Marinade,...",[Put the beef ribs into a large bowl and add t...,"[1 kg Beef ribs, 3 tbsp Cooking oil, Marinade,..."
1,Beef Curry,"[1 kg Beef cubed, 1/2 tsp Fenugreek, 2 cm Cinn...",[Put the ingredients of Paste 1 into a blender...,"[1 kg Beef cubed, 1/2 tsp Fenugreek, 2 cm Cinn..."
2,Pepper Beef,"[350g Beef sliced, 3 cloves Garlic chopped fin...",[Place the beef in a bowl with the marinade in...,"[350g Beef sliced, 3 cloves Garlic chopped fin..."
3,Tangy Beef,"[350g Beef sliced, 2/3 tsp Sugar, 1/2 cube Bee...",[Mix the coconut powder and water and set asid...,"[350g Beef sliced, 2/3 tsp Sugar, 1/2 cube Bee..."
4,Beef Rendang,"[900g Beef cubed, 1/2 tin Coconut cream, 1/2 t...",[We have been tryin g to perfect this recipe f...,"[900g Beef cubed, 1/2 tin Coconut cream, 1/2 t..."

## GUI Malaysian Cooking PDF

In [ ]:
# Run lagi jika sehabis running dataset lain
listSW = listStopword
print("Harap tekan tombol \"Add words and clean\" setiap runtime baru")

data = cookPdf.copy()

button = widgets.Button(description="Add words and clean")
run_button = widgets.Button(description = "Run Model")
output_run = widgets.Output()
output = widgets.Output()

teks = widgets.Text(
    value='',
    placeholder='Type something',
    description='String:',
    disabled=False
)

n_topics = widgets.IntSlider(
    value=7,
    min=5,
    max=10,
    step=1,
    description='n_topics:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
iteration = widgets.IntText(
    value=20,
    description='Number of Iteration:',
    disabled=False,
    layout = widgets.Layout(width='250px'),
    style = {'description_width': 'initial'}
)

display(teks)
display(n_topics)
display(iteration)
run_button.on_click(functools.partial(run_button_clicked, lang="eng"))
button.on_click(on_button_clicked)
display(button, output)
display(run_button, output_run)

Text(value='', description='String:', placeholder='Type something')

IntSlider(value=7, continuous_update=False, description='n_topics:', max=10, min=5)

IntText(value=20, description='Number of Iteration:', layout=Layout(width='250px'), style=DescriptionStyle(des…

Button(description='Add words and clean', style=ButtonStyle())

Output()

Button(description='Run Model', style=ButtonStyle())

Output()

Running..

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic
0     -0.124472 -0.093419       1        1  53.785848
4     -0.112408 -0.095194       2        1  19.983216
3     -0.136839  0.155385       3        1  13.304130
6      0.041944  0.069057       4        1  12.909775
1      0.110524 -0.011896       5        1   0.005931
2      0.110891 -0.011829       6        1   0.005700
5      0.110360 -0.012105       7        1   0.005399, topic_info=               Term        Freq       Total Category  logprob  loglift
96          coconut   31.000000   31.000000  Default  30.0000  30.0000
97           powder   46.000000   46.000000  Default  29.0000  29.0000
100           paste   60.000000   60.000000  Default  28.0000  28.0000
15            sauce   62.000000   62.000000  Default  27.0000  27.0000
32              add  280.000000  280.000000  Default  26.0000  26.0000
109             set   39.000000   39.000000  Default  25.0000  25.0000
140             fry   55.000000   55.000000  Default  24.0000  24.0000
1              ribs   23.000000   23.000000  Default  23.0000  23.0000
62              pan   45.000000   45.000000  Default  22.0000  22.0000
13             salt   33.000000   33.000000  Default  21.0000  21.0000
93           leaves   15.000000   15.000000  Default  20.0000  20.0000
0              beef   79.000000   79.000000  Default  19.0000  19.0000
142            stir   39.000000   39.000000  Default  18.0000  18.0000
112        fragrant   17.000000   17.000000  Default  17.0000  17.0000
45            aside   42.000000   42.000000  Default  16.0000  16.0000
12              tsp   82.000000   82.000000  Default  15.0000  15.0000
47          minutes   46.000000   46.000000  Default  14.0000  14.0000
141            high   17.000000   17.000000  Default  13.0000  13.0000
42              mix   86.000000   86.000000  Default  12.0000  12.0000
44             well   53.000000   53.000000  Default  11.0000  11.0000
188          bicarb   16.000000   16.000000  Default  10.0000  10.0000
87         cinnamon   11.000000   11.000000  Default   9.0000   9.0000
33      ingredients   36.000000   36.000000  Default   8.0000   8.0000
23              msg   22.000000   22.000000  Default   7.0000   7.0000
24         optional   22.000000   22.000000  Default   6.0000   6.0000
29              put   56.000000   56.000000  Default   5.0000   5.0000
73             heat   59.000000   59.000000  Default   4.0000   4.0000
19             soya   24.000000   24.000000  Default   3.0000   3.0000
28            water   58.000000   58.000000  Default   2.0000   2.0000
4               oil   59.000000   59.000000  Default   1.0000   1.0000
96          coconut   31.134114   31.555136   Topic1  -4.1241   0.6067
93           leaves   14.625991   15.069214   Topic1  -4.8796   0.5903
87         cinnamon   10.802925   11.196493   Topic1  -5.1826   0.5844
306        potatoes    9.833580   10.227244   Topic1  -5.2766   0.5809
89             star    7.894572    8.287675   Topic1  -5.4962   0.5716
90            anise    7.894336    8.287570   Topic1  -5.4963   0.5715
115          reduce    7.894281    8.287637   Topic1  -5.4963   0.5715
149           basil    7.894085    8.287787   Topic1  -5.4963   0.5715
139           hours    7.893617    8.287629   Topic1  -5.4963   0.5715
143            cube    7.892293    8.287579   Topic1  -5.4965   0.5713
151          kaffir    8.741997    9.244911   Topic1  -5.3943   0.5642
92            curry    5.955519    6.348530   Topic1  -5.7781   0.5563
101            part    5.955145    6.348340   Topic1  -5.7781   0.5562
94         cardamom    5.955114    6.348337   Topic1  -5.7781   0.5562
86        fenugreek    5.955053    6.348313   Topic1  -5.7782   0.5562
117           rinse    5.955031    6.348388   Topic1  -5.7782   0.5562
106        turmeric    7.735492    8.271616   Topic1  -5.5166   0.5531
98             ghee    4.985835    5.378777   Topic1  -5.9558   0.5443
227        shredded    4.985678    5.378963   Topic1  -5.9558   0.5442
155           grass    6.711156    7.296824   Topic1  -5.6586   0.5365
154           lemon    6.710451    7.296751   Topic1  -5.6587   0.5364
119             cho    4.016414    4.409178   Topic1  -6.1720   0.5269
113            past    4.016384    4.409193   Topic1  -6.1720   0.5269
114             int    4.016326    4.409176   Topic1  -6.1720   0.5268
108           forms    4.016272    4.409153   Topic1  -6.1720   0.5268
120             ice    4.016277    4.409171   Topic1  -6.1720   0.5268
118           bowls    4.016261    4.409158   Topic1  -6.1720   0.5268
110           glass    4.016256    4.409163   Topic1  -6.1720   0.5268
121      vegetables    4.016225    4.409226   Topic1  -6.1721   0.5268
136       overnight    4.016239    4.409336   Topic1  -6.1721   0.5268
100           paste   52.996477   60.184188   Topic1  -3.5922   0.4930
97           powder   40.713543   46.481036   Topic1  -3.8558   0.4877
112        fragrant   15.518701   17.960992   Topic1  -4.8204   0.4740
13             salt   27.641964   33.304919   Topic1  -4.2431   0.4338
32              add  195.945609  280.708620   Topic1  -2.2846   0.2607
140             fry   40.224892   55.292099   Topic1  -3.8679   0.3020
111             pot   11.481918   14.082372   Topic1  -5.1216   0.4160
138           least    9.833055   11.974103   Topic1  -5.2766   0.4232
142            stir   28.046681   39.006809   Topic1  -4.2285   0.2903
73             heat   40.647457   59.731186   Topic1  -3.8575   0.2352
42              mix   55.140401   86.218743   Topic1  -3.5525   0.1732
109             set   27.916292   39.199862   Topic1  -4.2332   0.2807
47          minutes   32.089466   46.227139   Topic1  -4.0939   0.2551
0              beef   49.736279   79.237494   Topic1  -3.6557   0.1544
12              tsp   49.345516   82.380767   Topic1  -3.6636   0.1077
28            water   37.214919   58.468212   Topic1  -3.9457   0.1684
4               oil   37.705666   59.729091   Topic1  -3.9326   0.1602
45            aside   27.895222   42.804501   Topic1  -4.2339   0.1920
11           garlic   16.706547   22.583677   Topic1  -4.7466   0.3187
20           chilli   15.962712   21.525989   Topic1  -4.7921   0.3212
27              cup   17.898684   25.292519   Topic1  -4.6777   0.2744
67             cook   27.896609   45.962770   Topic1  -4.2339   0.1208
3           cooking   25.493735   43.349172   Topic1  -4.3240   0.0893
84           serves   21.279821   34.732538   Topic1  -4.5046   0.1302
62              pan   25.502064   45.817747   Topic1  -4.3236   0.0342
188          bicarb   12.421897   16.011029   Topic1  -5.0429   0.3663
44             well   27.463531   53.054696   Topic1  -4.2495  -0.0383
29              put   27.445787   56.898706   Topic1  -4.2502  -0.1089
17            sugar   23.730458   45.222589   Topic1  -4.3956  -0.0247
80            serve   19.209583   32.783079   Topic1  -4.6070   0.0857
6              rice   19.212544   33.685077   Topic1  -4.6068   0.0587
72           medium   19.077142   33.822432   Topic1  -4.6139   0.0475
8             onion   17.386241   29.980349   Topic1  -4.7067   0.0753
33      ingredients   16.130153   36.696305   Topic1  -4.7817  -0.2018
334            tofu    6.853098    7.248193   Topic2  -4.6476   1.5542
335            pork    6.853060    7.248191   Topic2  -4.6476   1.5542
295           seeds    6.851423    7.248733   Topic2  -4.6478   1.5539
342           squid    3.015419    3.409767   Topic2  -5.4685   1.4874
350            bean    3.015347    3.409732   Topic2  -5.4686   1.4874
337          prawns    3.015361    3.409751   Topic2  -5.4686   1.4874
297          oyster    3.014420    3.409977   Topic2  -5.4689   1.4870
302         browned    7.222693    8.214488   Topic2  -4.5951   1.4816
198        szechuan    3.672264    4.342482   Topic2  -5.2715   1.4426
364         seafood    2.056074    2.450201   Topic2  -5.8515   1.4349
361            hard    2.055950    2.450092   Topic2  -5.8515   1.4349
357        mushroom    2.055938    2.450082   Topic2  -5.8515   1.4349
354           block    2.055932    2.450087   Topic2  -5.8516   1.4349
362      categorise    2.055971    2.450143   Topic2  -5.8515   1.4349
353          hopped    2.055919    2.450082   Topic2  -5.8516   1.4349
355          golden    2.055930    2.450097   Topic2  -5.8516   1.4349
363        contains    2.055920    2.450092   Topic2  -5.8516   1.4349
358            plus    2.055920    2.450094   Topic2  -5.8516   1.4349
352            carb    2.055962    2.450149   Topic2  -5.8515   1.4349
341        coarsely    2.055946    2.450131   Topic2  -5.8515   1.4349
360          lastly    2.055933    2.450121   Topic2  -5.8516   1.4349
359           prawn    2.055959    2.450165   Topic2  -5.8515   1.4349
356           chick    2.055936    2.450143   Topic2  -5.8516   1.4349
298          shakes    2.055786    2.450184   Topic2  -5.8516   1.4348
296         chinese    2.055642    2.450218   Topic2  -5.8517   1.4347
304     tablespoons    2.055485    2.450274   Topic2  -5.8518   1.4346
301          dients    2.055353    2.450296   Topic2  -5.8518   1.4345
300           ingre    2.055298    2.450278   Topic2  -5.8519   1.4345
204           steps    2.055203    2.450198   Topic2  -5.8519   1.4345
303         leaving    2.055154    2.450281   Topic2  -5.8519   1.4344
211          sesame    7.166012    9.024841   Topic2  -4.6029   1.3796
19             soya   17.976907   24.421674   Topic2  -3.6832   1.3039
131            corn   12.188728   18.827884   Topic2  -4.0718   1.1755
243             wok    5.891995    8.228204   Topic2  -4.7987   1.2763
326          carrot    3.931788    5.339550   Topic2  -5.2032   1.3042
7             flour   12.191484   23.336046   Topic2  -4.0715   0.9610
318          enough    2.670659    3.413381   Topic2  -5.5900   1.3649
254           dried    5.191344    8.139082   Topic2  -4.9253   1.1606
126          pepper    7.945860   14.993204   Topic2  -4.4996   0.9753
16           ginger    9.415293   20.716806   Topic2  -4.3299   0.8217
32              add   56.198225  280.708620   Topic2  -2.5434   0.0018
0              beef   22.663344   79.237494   Topic2  -3.4515   0.3586
219          remove    7.363769   15.695268   Topic2  -4.5757   0.8535
15            sauce   18.002463   62.023632   Topic2  -3.6818   0.3733
12              tsp   19.817051   82.380767   Topic2  -3.5857   0.1855
17            sugar   12.725024   45.222589   Topic2  -4.0287   0.3423
109             set   11.004079   39.199862   Topic2  -4.1740   0.3399
2              tbsp   10.762086   40.549463   Topic2  -4.1963   0.2838
156          needed    6.646523   17.914251   Topic2  -4.6782   0.6188
45            aside   11.005540   42.804501   Topic2  -4.1739   0.2520
4               oil   13.250479   59.729091   Topic2  -3.9882   0.1045
23              msg    7.458099   22.687090   Topic2  -4.5630   0.4978
42              mix   14.434594   86.218743   Topic2  -3.9027  -0.1770
24         optional    7.457031   22.687038   Topic2  -4.5631   0.4976
140             fry   11.263193   55.292099   Topic2  -4.1507   0.0192
3           cooking    9.680383   43.349172   Topic2  -4.3022   0.1111
29              put   10.305918   56.898706   Topic2  -4.2396  -0.0983
73             heat   10.328819   59.731186   Topic2  -4.2373  -0.1446
142            stir    8.702823   39.006809   Topic2  -4.4086   0.1102
72           medium    8.260474   33.822432   Topic2  -4.4608   0.2006
28            water    8.228641   58.468212   Topic2  -4.4647  -0.3506
8             onion    7.184708   29.980349   Topic2  -4.6003   0.1817
1              ribs   22.660797   23.072219   Topic3  -3.0448   1.9991
59              hot    7.339101    7.744124   Topic3  -4.1722   1.9634
60            plate    7.339067    7.744180   Topic3  -4.1723   1.9634
61           frying    7.338913    7.744102   Topic3  -4.1723   1.9634
36             sure    7.338687    7.744069   Topic3  -4.1723   1.9633
64             nice    3.733999    4.137486   Topic3  -4.8480   1.9145
70            swill    3.733852    4.137469   Topic3  -4.8480   1.9145
34             last    3.733875    4.137531   Topic3  -4.8480   1.9144
65            smoky    3.733839    4.137523   Topic3  -4.8480   1.9144
63             help    3.733820    4.137521   Topic3  -4.8480   1.9144
39           coated    3.733829    4.137532   Topic3  -4.8480   1.9144
35             make    3.733824    4.137542   Topic3  -4.8480   1.9144
57        otherwise    3.733730    4.137509   Topic3  -4.8481   1.9144
46             abou    3.733770    4.137557   Topic3  -4.8480   1.9144
52           making    3.733707    4.137497   Topic3  -4.8481   1.9144
41            hands    3.733647    4.137530   Topic3  -4.8481   1.9144
66          flavour    3.733579    4.137532   Topic3  -4.8481   1.9144
53        dissolves    3.733345    4.137532   Topic3  -4.8482   1.9143
14   worcestershire    1.930990    2.334204   Topic3  -5.5074   1.8275
54              bbq    7.338791    9.491310   Topic3  -4.1723   1.7599
58              use    7.338191    9.491348   Topic3  -4.1724   1.7598
74            spare    3.733678    5.011237   Topic3  -4.8481   1.7228
37              rib    3.733515    5.011185   Topic3  -4.8481   1.7228
26           coffee    1.029997    1.432557   Topic3  -6.1359   1.6872
25          instant    1.029951    1.432564   Topic3  -6.1360   1.6871
48          prepare    7.338629   11.238562   Topic3  -4.1723   1.5909
40            using    3.733959    5.884692   Topic3  -4.8480   1.5622
55            grill    3.733844    5.884781   Topic3  -4.8480   1.5622
76          serving    3.733709    5.884662   Topic3  -4.8481   1.5621
43         together    3.733325    5.884286   Topic3  -4.8482   1.5621
51           except    3.733961    6.056702   Topic3  -4.8480   1.5334
38          lightly    3.733950    6.056867   Topic3  -4.8480   1.5334
15            sauce   26.266923   62.023632   Topic3  -2.8972   1.1579
49          mixture    7.338905   15.478879   Topic3  -4.1723   1.2708
62              pan   14.547803   45.817747   Topic3  -3.4880   0.8699
31             bowl   10.943583   34.313707   Topic3  -3.7727   0.8743
33      ingredients   10.943355   36.696305   Topic3  -3.7727   0.8072
69            place    7.338228   18.803437   Topic3  -4.1724   1.0762
44             well   10.942547   53.054696   Topic3  -3.7728   0.4384
29              put   10.942626   56.898706   Topic3  -3.7728   0.3685
32              add   21.757707  280.708620   Topic3  -3.0855  -0.5403
42              mix   10.943524   86.218743   Topic3  -3.7727  -0.0470
77             dish    7.339016   28.576132   Topic3  -4.1723   0.6577
2              tbsp    8.239913   40.549463   Topic3  -4.0565   0.4236
28            water    8.239978   58.468212   Topic3  -4.0565   0.0576
67             cook    7.338109   45.962770   Topic3  -4.1724   0.1823
47          minutes    7.338044   46.227139   Topic3  -4.1724   0.1766
17            sugar    5.536578   45.222589   Topic3  -4.4541  -0.0831
7             flour    4.634677   23.336046   Topic3  -4.6319   0.4007
5          marinade    4.634923   25.724675   Topic3  -4.6318   0.3033
6              rice    4.634866   33.685077   Topic3  -4.6319   0.0336
3           cooking    4.634865   43.349172   Topic3  -4.6319  -0.2186
4               oil    4.635035   59.729091   Topic3  -4.6318  -0.5391
0              beef    4.635027   79.237494   Topic3  -4.6318  -0.8217
208         peanuts    9.723266   10.141927   Topic4  -3.8609   2.0050
274        charcoal    7.111796    7.519889   Topic4  -4.1736   1.9914
248          peanut    5.365349    5.772570   Topic4  -4.4554   1.9740
285         skewers    5.365031    5.772515   Topic4  -4.4555   1.9740
170         rendang    4.489119    4.896160   Topic4  -4.6337   1.9604
282            hour    3.618349    4.025246   Topic4  -4.8494   1.9406
275          burner    3.618323    4.025308   Topic4  -4.8494   1.9406
284         glowing    3.618238    4.025295   Topic4  -4.8494   1.9406
207             raw    2.743824    3.151897   Topic4  -5.1260   1.9085
263             day    1.871635    2.278137   Topic4  -5.5086   1.8506
277       retailers    1.871596    2.278098   Topic4  -5.5086   1.8506
283            want    1.871614    2.278131   Topic4  -5.5086   1.8506
179          begins    1.871232    2.277667   Topic4  -5.5088   1.8506
273            need    1.871586    2.278102   Topic4  -5.5086   1.8506
268            even    1.871559    2.278081   Topic4  -5.5086   1.8506
171            like    1.871266    2.277724   Topic4  -5.5088   1.8506
247           sweet    1.871581    2.278110   Topic4  -5.5086   1.8506
264          intend    1.871561    2.278099   Topic4  -5.5086   1.8506
266        saucepan    1.871597    2.278147   Topic4  -5.5086   1.8506
267            soft    1.871566    2.278116   Topic4  -5.5086   1.8506
272        properly    1.871543    2.278091   Topic4  -5.5086   1.8506
260         plastic    1.871587    2.278147   Topic4  -5.5086   1.8506
288            wate    1.871528    2.278084   Topic4  -5.5086   1.8506
292           every    1.871495    2.278044   Topic4  -5.5086   1.8506
269     consistency    1.871567    2.278132   Topic4  -5.5086   1.8506
261       container    1.871548    2.278113   Topic4  -5.5086   1.8506
262           night    1.871562    2.278133   Topic4  -5.5086   1.8506
278          priced    1.871562    2.278135   Topic4  -5.5086   1.8506
265           satay    1.871548    2.278119   Topic4  -5.5086   1.8506
279          upward    1.871574    2.278161   Topic4  -5.5086   1.8506
289           first    1.871551    2.278138   Topic4  -5.5086   1.8506
105            meat   12.041539   21.499848   Topic4  -3.6470   1.4675
177           brown    5.308135    9.636858   Topic4  -4.4661   1.4508
15            sauce   12.095856   62.023632   Topic4  -3.6425   0.4125
78             pour    3.619872    7.631968   Topic4  -4.8489   1.3013
2              tbsp    8.793169   40.549463   Topic4  -3.9614   0.5186
183          little    3.156984    6.014946   Topic4  -4.9858   1.4026
137          fridge    3.618512    7.903722   Topic4  -4.8493   1.2659
33      ingredients    7.514736   36.696305   Topic4  -4.1185   0.4614
69            place    5.368729   18.803437   Topic4  -4.4548   0.7937
12              tsp   10.384232   82.380767   Topic4  -3.7951  -0.0239
44             well    8.264201   53.054696   Topic4  -4.0234   0.1878
29              put    8.202691   56.898706   Topic4  -4.0309   0.1104
5          marinade    5.698730   25.724675   Topic4  -4.3951   0.5400
201           allow    3.178663    7.930617   Topic4  -4.9789   1.1329
163            turn    3.430176    9.843361   Topic4  -4.9028   0.9930
48          prepare    3.620508   11.238562   Topic4  -4.8488   0.9144
83        vegetable    4.266323   21.093387   Topic4  -4.6846   0.4490
127             red    3.618667   13.710510   Topic4  -4.8493   0.7151
97           powder    5.494408   46.481036   Topic4  -4.4316  -0.0881
82           choice    4.105063   23.048390   Topic4  -4.7232   0.3218
8             onion    4.377416   29.980349   Topic4  -4.6589   0.1231
42              mix    5.698532   86.218743   Topic4  -4.3952  -0.6695
73             heat    5.018886   59.731186   Topic4  -4.5222  -0.4295
32              add    6.805336  280.708620   Topic4  -4.2177  -1.6724
67             cook    4.712190   45.962770   Topic4  -4.5852  -0.2305
28            water    4.782987   58.468212   Topic4  -4.5703  -0.4562
77             dish    4.066648   28.576132   Topic4  -4.7326   0.0974
4               oil    4.136225   59.729091   Topic4  -4.7156  -0.6229
81           boiled    3.843909   25.038552   Topic4  -4.7889   0.1733
100           paste    4.015835   60.184188   Topic4  -4.7451  -0.6600
140             fry    3.672084   55.292099   Topic4  -4.8346  -0.6647
164             tin    0.000582    1.404093   Topic5  -5.8981   1.9450

Topic: 1
add, mix, paste, beef, tsp, powder, heat, fry, oil, water, minutes, coconut, stir, set, cook, aside, salt, well, put, pan, cooking, sugar, serves, rice, serve, medium, cup, onion, garlic, ingredients

Topic: 2
add, paste, rendang, tsp, mix, ingredients, water, cook, put, powder, oil, low, cover, heat, cup, sugar, coconut, minutes, boiled, sauce, tbsp, get, serves, pan, dry, dish, well, cooking, set, malaysian

Topic: 3
add, mix, sauce, water, tsp, pan, put, oil, beef, fry, sugar, marinade, well, ribs, heat, paste, tbsp, dish, ingredients, aside, peanuts, minutes, serves, set, boiled, choice, bowl, vegetable, cooking, cook

Topic: 4
sauce, ribs, add, pan, bowl, mix, ingredients, put, well, water, tbsp, hot, plate, dish, frying, mixture, bbq, sure, prepare, place, use, cook, minutes, sugar, oil, beef, marinade, rice, cooking, flour

Topic: 5
add, beef, tsp, sauce, soya, mix, oil, sugar, flour, corn, fry, aside, set, tbsp, heat, put, cooking, ginger, stir, medium, water, pepper, msg, optional, remove, browned, onion, sesame, tofu, pork

Topic: 6
add, beef, fry, tsp, oil, sauce, mix, water, heat, powder, well, cooking, paste, minutes, sugar, tbsp, medium, meat, put, stir, soya, serves, cook, garlic, dish, aside, pan, onion, boiled, rice

Topic: 7
sauce, meat, tsp, peanuts, tbsp, well, put, ingredients, charcoal, add, marinade, mix, powder, place, peanut, skewers, brown, heat, water, cook, rendang, onion, vegetable, oil, choice, dish, paste, boiled, fry, prepare

[(0,
  '0.102*"add" + 0.029*"mix" + 0.028*"paste" + 0.026*"beef" + 0.026*"tsp" + 0.021*"powder" + 0.021*"heat" + 0.021*"fry" + 0.020*"oil" + 0.019*"water"'),
 (1,
  '0.003*"add" + 0.003*"paste" + 0.003*"rendang" + 0.003*"tsp" + 0.003*"mix" + 0.003*"ingredients" + 0.003*"water" + 0.003*"cook" + 0.003*"put" + 0.003*"powder"'),
 (2,
  '0.003*"add" + 0.003*"mix" + 0.003*"sauce" + 0.003*"water" + 0.003*"tsp" + 0.003*"pan" + 0.003*"put" + 0.003*"oil" + 0.003*"beef" + 0.003*"fry"'),
 (3,
  '0.055*"sauce" + 0.048*"ribs" + 0.046*"add" + 0.031*"pan" + 0.023*"bowl" + 0.023*"mix" + 0.023*"ingredients" + 0.023*"put" + 0.023*"well" + 0.017*"water"'),
 (4,
  '0.079*"add" + 0.032*"beef" + 0.028*"tsp" + 0.025*"sauce" + 0.025*"soya" + 0.020*"mix" + 0.019*"oil" + 0.018*"sugar" + 0.017*"flour" + 0.017*"corn"'),
 (5,
  '0.003*"add" + 0.003*"beef" + 0.003*"fry" + 0.003*"tsp" + 0.003*"oil" + 0.003*"sauce" + 0.003*"mix" + 0.003*"water" + 0.003*"heat" + 0.003*"powder"'),
 (6,
  '0.026*"sauce" + 0.026*"meat" + 0.022*"tsp" + 0.021*"peanuts" + 0.019*"tbsp" + 0.018*"well" + 0.018*"put" + 0.016*"ingredients" + 0.015*"charcoal" + 0.015*"add"')]

### Inspect Probability

In [ ]:
# Jika mau cek probabilitas per kata di topik dataset
cookPdfProb = make_dictionary_terms_prob(ldamodel, id_map, d)
cookPdfProb["beef"] #probabilitas kata beef pada setiap topik

[(0, 0.08954082),
 (1, 0.012025514),
 (2, 0.011557357),
 (3, 0.016079266),
 (4, 0.83193976),
 (5, 0.010947535),
 (6, 0.027909735)]

## Wordnet

In [ ]:
# Harus running modelnya dulu jangan lupa
cookPdfWN = dfWordnet.copy()

cookPdfWN["Synonym_clean"] = cleanWN_Synonym(cookPdfWN["Synonym"])
cookPdfWN["Hypernim_clean"] = cleanWN(cookPdfWN["Hypernim"])
cookPdfWN["Hyponim_clean"] = cleanWN(cookPdfWN["Hyponim"])
cookPdfWN

### Make Ontology

In [ ]:
# Make Ontology
ontoName = get_ontology("http://test.org/malaysianCook.owl")
makeOntology(ontoName, cookPdfWN)
ontoName.save(file = "malaysianCook.owl")

## Wikipedia & Category

In [ ]:
!gdown "1Be4Xi9t6ulzOfIXxZ2SYHo7v_ZTi9zRX"

Downloading...
From: https://drive.google.com/uc?id=1Be4Xi9t6ulzOfIXxZ2SYHo7v_ZTi9zRX
To: /content/MalayCookPdfFinal.xlsx
100% 6.42k/6.42k [00:00<00:00, 9.61MB/s]

In [ ]:
wiki_cook_pdf = pd.read_excel("MalayCookPdfFinal.xlsx").iloc[:, 1:]

# Translate
wiki_cook_pdf["Category"] = translate(wiki_cook_pdf["Category"])
wiki_cook_pdf.head()

,Title,Cleaned,Def_IND,Def_MS,Def_ENG,Category
0,Coffee Beef Ribs,coffee beef ribs,Not Found,Not Found,dark them in a variety of strengths,['daging']
1,Beef Curry,beef curry,Not Found,Not Found,Not Found,['daging']
2,Pepper Beef,pepper beef,perusahaan waralaba (franchise) lokal yang ber...,Not Found,French-inspired Vietnamese dish that consists ...,['daging']
3,Tangy Beef,tangy beef,Not Found,Not Found,Not Found,['daging']
4,Beef Rendang,beef rendang,Not Found,hidangan asli bangsa Minangkabau yang menduduk...,Minang dish originating from the Minangkabau r...,['daging']
5,Beef with Red Curry Paste,beef red curry paste,seorang sutradara film film hasil adaptasi The...,makanan tradisonal resepi Perancis,French beef stew braised in red wine with whol...,['daging']
6,Szechuan Beef,szechuan beef,Not Found,Not Found,Not Found,['daging']
7,Fennel Beef,fennel beef,Not Found,Not Found,Not Found,['daging']
8,Serunding Lembu,serunding lembu,Not Found,sejenis masakan yang dibuat dengan rempah dan ...,Not Found,[]
9,Beef Tomchi,beef tomchi,Not Found,Not Found,Not Found,['daging']
10,Beef Satay,beef satay,Not Found,Not Found,Southeast Asian dish of seasoned from peanut b...,['daging']
11,Peking Beef,peking beef,Not Found,Not Found,style of Chinese cuisine developed by Chinese ...,['daging']
12,Red wine and rosemary beef,red wine rosemary beef,minuman beralkohol yang terbuat dari fermentas...,satu minuman beralkohol dibuat daripada penapa...,type of wine made from dark-colored grape vari...,['daging']
13,Ma-Po,mapo,satu dari 25 distrik (gu) di Seoul,Not Found,symbolic depiction emphasizing relationships b...,[]

## Counter Category Tabel 1981

In [ ]:
tabel_1981 = wiki_cook_pdf[["Title", "Category"]].copy()

benar = 0
salah = 0
all_cat = []
all_suggestion = []
lanjut = False
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

asyncio.ensure_future(f())

ToggleButton(value=False, button_style='success', description='Next row', icon='check', tooltip='Description')

Row: 1/14
 Coffee Beef Ribs

SelectMultiple(description='category', options=('daging',), value=())

In [ ]:
cookPdfTabel_new = tabel_1981.copy()
cookPdfTabel_new["correct_category"] = all_cat
cookPdfTabel_new["suggestion"] = all_suggestion

# Export Result to File
cookPdfTabel_new.to_excel("cookPdfTabel_Result.xlsx")
cookPdfTabel_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cookPdfTabel_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Update Ontology NFO

In [ ]:
# NFO Ontology

# If runtime expired, put updated file in colab or gdrive and run commented code below
# !gdown "<insert-id-here>"
# table1981_Onto = get_ontology(r'/content/NFO_Updated.owl').load()

In [ ]:
# Concat List in Column "suggestion" & "correct_category"
cookPdfTabel_new = concatListInColumn(cookPdfTabel_new)
cookPdfTabel_new

In [ ]:
# Update Ontology
makeOntologyTable1981(table1981_Onto, cookPdfTabel_new)
table1981_Onto.save(file = "NFO_Updated.owl")

Downloading...
From: https://drive.google.com/uc?id=1T8NVqHoq4BMzNUFuTdWT9z1oaMrFZ7Ru
To: /content/NFOversion2April22.owl
100% 14.8k/14.8k [00:00<00:00, 12.7MB/s]

## Counter Wikipedia

In [ ]:
wiki_df = wiki_cook_pdf.iloc[:, :-1].copy().iloc[:]

all_cat = []
idx = []
button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success',
  tooltip='Description',
  icon='check' 
)

# kategori --> usulan class dari juri, textbox
asyncio.ensure_future(f_wiki())

ToggleButton(value=False, button_style='success', description='Next row', icon='check', tooltip='Description')

Row: 1/14
 Coffee Beef Ribs

======Definition========

Indonesia: Not Found
Malaysia: Not Found
English: dark them in a variety of strengths

Text(value='', description='Usulan Class', layout=Layout(height='40px', width='600px'), placeholder='input cla…

In [ ]:
cookCpdWiki_new = wiki_df.copy()
cookCpdWiki_new["suggest"] = all_cat

# Export Result to file
cookCpdWiki_new.to_excel("cookPdfWiki_Result.xlsx")
cookCpdWiki_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cookPdfWiki_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.

### Make Ontology Wikipedia

In [ ]:
# Make Ontology
cookCpdOntoWiki = get_ontology("http://test.org/malaysianCook_onto_wiki.owl")
makeOntology_wiki(cookCpdOntoWiki, cookCpdWiki_new)
cookCpdOntoWiki.save(file = "malaysianCook_onto_wiki.owl")

## Counter Wordnet Hypo, Syno, Hyper

In [ ]:
tableWordnet = cookPdfWN[["Word", "Synonym_clean", "Hypernim_clean", "Hyponim_clean"]].copy()

benarWordnet = 0
salahWordnet = 0
lanjut = False

button = widgets.ToggleButton(
  value=False,
  description='Next row',
  disabled=False,
  button_style='success', # 'success', 'info', 'warning', 'danger' or ''
  tooltip='Description',
  icon='check' # (FontAwesome names without the `fa-` prefix)
)

# status --> usulan class, kasih dua pilihan apakah setuju jika tidak judge kasih input sendiri (hipernim saja)
# jika hipernim kosong, maka judge input manual dan wordnet auto salah
asyncio.ensure_future(fWordnet())

ToggleButton(value=False, button_style='success', description='Next row', icon='check', tooltip='Description')

Row: 1/210

Word: add
Synonym: attention_deficit_disorder
Hypernim: ['syndrome']
Hyponim: None

RadioButtons(description='Hypernym (True/False?)', options=('True', 'False'), value='True')

Button(description='Submit', style=ButtonStyle())

In [ ]:
# Export Result to File
cookPdfWN_new = listToDataframe(changesList, tableWordnet)
cookPdfWN_new.to_excel("cookPdfWN_Result.xlsx")
cookPdfWN_new

In [ ]:
# Upload file to drive
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

upload_file = "cookPdfWN_Result.xlsx"

# setelah code dijalankan maka file akan ada di https://drive.google.com/drive/folders/1EorSiyj_0figmlI3aVIdobFtTIQZRuZF?usp=sharing
gfile = drive.CreateFile({'parents': [{'id': '1EorSiyj_0figmlI3aVIdobFtTIQZRuZF'}]})
# Read file and set it as the content of this instance.
gfile.SetContentFile(upload_file)
gfile.Upload() # Upload the file.